mbta/skate

- README.md
- assets/package-lock.json
- assets/package.json
- assets/webpack.config.js
add `asdf` to the readme
upgrade some packages according to `npm audit`
> updates after first install

- lib/gtfs.ex
- lib/gtfs/route_pattern.ex
- lib/gtfs/stop_time.ex
- lib/gtfs/timepoint.ex
- lib/skate_web/controllers/ladder_controller.ex
- lib/skate_web/controllers/route_controller.ex
- lib/skate_web/router.ex
- lib/skate_web/templates/ladder/index.html.eex
- lib/skate_web/templates/ladder/route.html.eex
- lib/skate_web/views/ladder_view.ex
- test/gtfs_test.exs
Asana Task:
- [Calculate a static route ladder for a single route/direction from GTFS - Part 1 - Unsorted time points](https://app.asana.com/0/1112935048846093/1114820119722039)
- [Calculate list of bus routes (and whatever other information is needed for UI)](https://app.asana.com/0/1112935048846093/1114820119722037)
3 new endpoints:
- `/api/routes/:route_id` (List of checkpoints on the route)
- `/ladder` (List of routes)
- `/ladder/:route_id` (List of checkpoints on the route)
I still don't have controller tests because I think of these as kind of throwaway endpoints.
> unsorted list of checkpoints

- CODE_OF_CONDUCT.md
- LICENSE
> Add an open source license and code of conduct

- lib/gtfs.ex
- test/gtfs_test.exs
> bugfix don't crash if a trip doesn't have timepoints

- lib/gtfs.ex
- lib/gtfs/csv.ex
- lib/gtfs/route.ex
- lib/gtfs/route_pattern.ex
- lib/gtfs/stop.ex
- lib/gtfs/timepoint.ex
- lib/gtfs/trip.ex
- test/gtfs/csv_test.exs
- test/gtfs_test.exs
This includes:
• routes
• route patterns
• trips
• timepoints
Time gtfs loading.
Asana ticket: [Filter routes to only include buses](https://app.asana.com/0/1112935048846093/1117662445344605)
> Filter data imports to only save bus-related data

- assets/css/_route_ladder.scss
- assets/src/components/routeLadder.tsx
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
Deselects the route.
Asana ticket: [Add X button to route ladder header](https://app.asana.com/0/1112935048846093/1118437179466238)
> Add close button to route ladder header

- lib/realtime/server.ex
- lib/realtime/vehicle.ex
- lib/skate_web/channels/user_socket.ex
- lib/skate_web/channels/vehicles_channel.ex
- test/channels/vehicles_channel_test.exs
- test/realtime/server_test.exs
This is purely the server-side work pulled out from the work on [build UI for displaying/updating a table of vehicles and their locations](https://app.asana.com/0/1112935048846093/1114820119722045)
> Set up a channel for sending vehicles to client

- lib/skate_web/templates/layout/app.html.eex
This will let us launch it from the desktop without a tab bar.
> Declare that this site is "app capable"

- assets/css/_inter_ui.scss
- assets/css/_route_ladder.scss
- assets/css/_route_ladders.scss
- assets/css/_route_picker.scss
- assets/css/app.scss
- assets/src/components/routePicker.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/routePicker.test.tsx.snap
- assets/tests/components/routePicker.test.tsx
- lib/skate_web/templates/layout/app.html.eex
Asana ticket: [Prettify the route picker](https://app.asana.com/0/1112935048846093/1118883223380541)
> Style the route picker section

- config/prod.exs
- lib/skate_web/endpoint.ex
Fixes a problem opening websocket connections from prod (the dev server).
> Define domains for websocket to check and use the system host value

- config/config.exs
- config/prod.exs
- lib/skate_web/router.ex
Asana ticket: [Set up a redirect from http to https](https://app.asana.com/0/1112935048846093/709916117691678)
> Configure prod site to redirect from http to https

- assets/css/_close_button.scss
- assets/css/_colors.scss
- assets/css/_route_ladder.scss
- assets/css/_vehicle_properties_panel.scss
- assets/css/app.scss
- assets/src/components/app.tsx
- assets/src/components/closeButton.tsx
- assets/src/components/routeLadder.tsx
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/helpers/detectSwipe.ts
- assets/src/skate.d.ts
- assets/src/state.ts
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- assets/tests/helpers/detectSwipe.test.tsx
- assets/tests/state.test.ts
- assets/tests/testHelpers/touchEventHelpers.ts
Asana ticket: [Add an initial Vehicle Properties Panel](https://app.asana.com/0/1112935048846093/1120388911202260)
> Add an initial Vehicle Properties Panel

- assets/css/_ladder.scss
- assets/css/_vehicle_properties_panel.scss
- assets/src/components/app.tsx
- assets/src/components/ladder.tsx
- assets/src/components/routeLadder.tsx
- assets/src/components/routeLadders.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/routeLadders.test.tsx
Asana ticket: [The selected vehicle for should be highlighted on the route ladder](https://app.asana.com/0/1112935048846093/1121935738144311)
Move the selection action to the new triangle icons.
> Highlight the selected vehicle icon

- assets/package-lock.json
- assets/package.json
I accidentally merged https://github.com/mbta/skate/pull/52 before pushing this commit.
> Add webpack-bundle-analyzer as a dev dependency

- assets/src/helpers/detectSwipe.ts
This was blocking clicks on buttons and links.
Asana ticket: [🐞 Clicking links or buttons in the Vehicle Properties Panel does not work on the tablets](https://app.asana.com/0/1112935048846093/1123561348606748)
> Don't preventDefault on events in detectSwipe

- assets/css/_ladder.scss
- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
Asana ticket: [Use correct vehicle triangle icon](https://app.asana.com/0/1112935048846093/1123604338536305)
This also addresses: [Add a gray stroke to the triangle icon and a gray background behind the run number](https://app.asana.com/0/1112935048846093/1123838037403439)
> Use a custom path for the vehicle triangles

- assets/css/_colors.scss
- assets/css/_incoming_box.scss
- assets/css/_ladder.scss
- assets/css/_route_ladder.scss
- assets/css/_vehicle_icon.scss
- assets/css/app.scss
- assets/src/components/incomingBox.tsx
- assets/src/components/ladder.tsx
- assets/src/components/routeLadder.tsx
- assets/src/components/vehicleIcon.tsx
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
- assets/tests/components/__snapshots__/vehicleIcon.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehicleIcon.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- lib/realtime/vehicle.ex
- test/channels/vehicles_channel_test.exs
- test/realtime/server_test.exs
- test/realtime/vehicle_test.exs
Asana ticket: [Add “INCOMING” box to bottom of route ladders](https://app.asana.com/0/1112935048846093/1118437179466250)
> Add an incoming box and display incoming vehicles there

- assets/css/_vehicle_properties_panel.scss
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- lib/gtfs.ex
- lib/gtfs/data.ex
- lib/gtfs/stop.ex
- lib/realtime/vehicle.ex
- test/channels/vehicles_channel_test.exs
- test/concentrate/stop_time_update_test.exs
- test/gtfs/cache_file_test.exs
- test/gtfs/data_test.exs
- test/gtfs/stop_test.exs
- test/gtfs_test.exs
- test/realtime/vehicle_test.exs
Asana Task: [Add "Next Stop" to the Vehicle Properties Panel](https://app.asana.com/0/1112935048846093/1120900265272096)
> Add "Next Stop" to the Vehicle Properties Panel

- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
Asana ticket: [Add the Run to the Vehicle Properties Panel](https://app.asana.com/0/1112935048846093/1120980093841753)
> Add the Run number to the Vehicle Properties Panel

- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
Last name and badge number.
Asana ticket: [Add the Operator Badge Number and Last Name to the Vehicle Properties Panel](https://app.asana.com/0/1112935048846093/1120980093841757)
> Add Operator info to the Vehicle Properties Panel

- lib/skate_web/templates/layout/app.html.eex
Asana ticket: [Scale the viewport smaller](https://app.asana.com/0/1112935048846093/1125366821749133)
> Scale the viewport smaller for the tablets

- assets/src/components/app.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/app.test.tsx
Asana Task: [Open route ladders in the order they're selected.](https://app.asana.com/0/1112935048846093/1125374606719903)
> open ladders in the order they're selected

- assets/src/api.ts
- assets/tests/api.test.ts
- lib/gtfs/data.ex
- lib/gtfs/route.ex
- test/gtfs/cache_file_test.exs
- test/gtfs/data_test.exs
- test/gtfs/route_test.exs
- test/gtfs_test.exs
Asana ticket: [Refactor Route directions data structure](https://app.asana.com/0/1112935048846093/1125751680948291)
> Limit route direction data to only the names

- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
Asana ticket: [Draw all schedule lines below all triangles](https://app.asana.com/0/1112935048846093/1126085679577924)
Dependent on https://github.com/mbta/skate/pull/74
> Draw all schedule lines below all triangles

- config/config.exs
- config/prod.exs
- lib/skate_web/templates/layout/_fullstory.html.eex
- lib/skate_web/templates/layout/app.html.eex
- lib/skate_web/views/layout_view.ex
- test/skate_web/views/layout_view_test.exs
Only enable FullStory recording in production.
Asana ticket: [Add FullStory session recording](https://app.asana.com/0/1112935048846093/1125337183434468)
> Add a FullStory recording snippet

- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
Asana ticket: [When you select a vehicle, bring it to the top](https://app.asana.com/0/1112935048846093/1123838037403441)
Unselected:
Selected:
> Display a selected vehicle on top of all others

- assets/css/_vehicle_properties_panel.scss
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/hooks/useVehicles.ts
- assets/src/skate.d.ts
- assets/tests/components/app.test.tsx
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- assets/tests/hooks/useVehicles.test.ts
- lib/concentrate/data_discrepancy.ex
- lib/realtime/vehicle.ex
- test/channels/vehicles_channel_test.exs
- test/realtime/server_test.exs
- test/realtime/vehicle_test.exs
At the bottom of the Vehicle Properties panel.
View this by adding `?debug=1` to the URL.
Asana ticket: [Debug mode for data discrepancies](https://app.asana.com/0/1112935048846093/1128997245638196)
> Show data discrepancies when in debug mode

- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/ladder.test.tsx
Asana Task: [🐞Reversing a route ladder seems to disrupt late/early display](https://app.asana.com/0/1112935048846093/1129015100963251)
> bugfix: show reversed ladder correctly

- assets/src/skate.d.ts
- assets/tests/hooks/useVehicles.test.ts
- test/realtime/vehicle_test.exs
No Asana ticket, I noticed this in the course of other work.
> Data discrepancy values might be null

- assets/css/_inter_ui.scss
Asana Task: [🐞UI font files don't load on MBTA network because font file paths don't have "www"](https://app.asana.com/0/1112935048846093/1130435043779645)
> load fonts through cdn

- assets/src/components/appStateWrapper.tsx
- assets/src/hooks/usePersistedStateReducer.ts
- assets/src/localStorage.ts
- assets/src/state.ts
- assets/tests/hooks/usePersistedStateReducer.test.ts
- assets/tests/localStorage.test.ts
Asana ticket: [Save selected routes interface state in local browser storage](https://app.asana.com/0/1112935048846093/1124828852046158)
> Save selected routes state in local browser storage

- lib/realtime/vehicle.ex
- lib/util/time.ex
In order to draw a scheduled line, we need to compare the current time to the trip times.
The trip times are in time_of_day format, so we need to know what the current time_of_day is.
But since times can wrap around after midnight, we calculate the times relative to the block to make sure we get the right day.
Previously, we did it by choosing the time of day that was closest to the start of the block, within 12 hours before and 12 hours after.
The bug was if a block started more than 12 hours ago, we'd round the wrong direction.
E.g. if a block started at 05:45, and it's 18:00, we'd assume it's really negative -06:00 (18:00 on the previous date) because that's closer to 05:45 than today's 18:00 is.
Since -06:00 is before (11 hours before) any trips on the block, the lines were fixed to …
> bugfix when calculating service dates to determine the scheduled trip

- assets/css/_ui_kit.scss
- assets/css/_vehicle_icon.scss
- assets/css/_vehicle_properties_panel.scss
- assets/src/components/incomingBox.tsx
- assets/src/components/ladder.tsx
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/models/ladderVehicle.ts
- assets/src/models/vehicleStatus.ts
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/ladder.test.tsx
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- assets/tests/models/ladderVehicle.test.ts
- assets/tests/models/vehicleStatus.test.ts
Asana ticket: [Vehicle states: invalid, vehicle is off course](https://app.asana.com/0/1112935048846093/1128793574082090)
(MTSTY is where both of these are scheduled to be at this moment)
> Add an off course vehicle state

- assets/static/robots.txt
Asana ticket: [Populate robots.txt](https://app.asana.com/0/1112935048846093/1131082799871086)
> Use robots.txt to ban all spiders from the entire site

- lib/skate_web/controllers/page_controller.ex
Asana ticket: [Track logged in usernames in Splunk](https://app.asana.com/0/1112935048846093/1130673090389398)
> log uid on page visit

- assets/package-lock.json
- assets/package.json
- assets/src/api.ts
Asana ticket: [🐞 Error making API requests in Edge](https://app.asana.com/0/1112935048846093/1131699365398877)
> Add a polyfill for fetch

- assets/css/_vehicle_map.scss
- assets/css/_vehicle_properties_panel.scss
- assets/css/app.scss
- assets/package-lock.json
- assets/package.json
- assets/src/components/map.tsx
- assets/src/components/vehicleIcon.tsx
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/tests/components/__snapshots__/map.test.tsx.snap
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/map.test.tsx
- lib/skate_web/templates/layout/app.html.eex
**Asana Ticket**: [Render a map component given a lat-long by fetching tiles from our tile server](https://app.asana.com/0/1112935048846093/1127990888669976)
> Add map to vehicle properties panel

- assets/css/_ladder.scss
- assets/src/components/headwayLines.tsx
- assets/src/components/ladder.tsx
- assets/src/models/ladderVehicle.ts
- assets/src/skate.d.ts
- assets/tests/components/__snapshots__/headwayLines.test.tsx.snap
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
- assets/tests/components/headwayLines.test.tsx
- assets/tests/models/ladderVehicle.test.ts
- lib/realtime/headway.ex
Asana ticket: [Use the vehicle bunched/gapped property to draw colored lines on the ladder](https://app.asana.com/0/1112935048846093/1130519303015343)
>  show bunched/gapped colors on route ladders

- assets/src/appData.ts
- assets/src/components/ladder.tsx
- assets/src/hooks/useSocket.ts
- assets/src/laboratoryFeatures.ts
- assets/tests/components/ladder.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/routeLadders.test.tsx
- assets/tests/laboratoryFeatures.test.ts
- config/config.exs
- lib/skate_web/controllers/page_controller.ex
- lib/skate_web/router.ex
- lib/skate_web/templates/page/index.html.eex
- mix.exs
- mix.lock
- test/skate_web/router_test.exs
Go to /_flags to enable or disable active flags.
Asana ticket: [Feature flags](https://app.asana.com/0/1112935048846093/1132105244340199)
> Use laboratory to allow us to control feature flags

- config/config.exs
- lib/skate/application.ex
- lib/skate_web/controllers/page_controller.ex
Ian has requested that we only read secrets at runtime for security.
> read secrets at runtime

- assets/src/components/map.tsx
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/helpers/detectSwipe.ts
- assets/tests/components/__snapshots__/map.test.tsx.snap
- assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/vehiclePropertiesPanel.test.tsx
- assets/tests/helpers/detectSwipe.test.tsx
Asana ticket: [🐞 Right swipe on map should not close the vehicle properties panel](https://app.asana.com/0/1112935048846093/1131945338037530)
This also uncovered a small bug in our detectSwipe module which I fixed.
> right swipe on map should not close panel

- assets/src/components/app.tsx
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/ladderPage.test.tsx
> Fix LadderPage name inconsistencies

- lib/gtfs/route.ex
- lib/skate_web/controllers/route_controller.ex
- test/gtfs/cache_file_test.exs
- test/gtfs/data_test.exs
- test/gtfs/route_test.exs
- test/gtfs_test.exs
Asana ticket: [Remove shuttle routes from route picker in route ladder view](https://app.asana.com/0/1112935048846093/1131078147057200)
> Filter shuttles from route list

- LICENSE
Asana ticket: [Convert to GNU AGPLv3 license](https://app.asana.com/0/1112935048846093/1133313349847315)
> Convert to GNU AGPLv3 license

- assets/src/components/ladder.tsx
- assets/src/components/map.tsx
- assets/src/components/vehiclePropertiesPanel.tsx
- assets/src/helpers/statusClass.tsx
- assets/src/helpers/vehicleAdherenceDisplayClass.tsx
- assets/tests/components/map.test.tsx
(asana is down at the moment, i'll update with the ticket link when it's back up)
> don't color VPP vehicle icons for headway routes

- assets/src/hooks/usePersistedStateReducer.ts
Asana Task: [Save selected vehicle. Keep VPP open through refresh](https://app.asana.com/0/1148853526253426/1157713971731881)
> persist selectedVehicleId. keep VPP open.

- assets/css/_disconnected_modal.scss
- assets/css/_properties_panel.scss
- assets/css/_ui_kit.scss
- assets/css/app.scss
- assets/src/components/app.tsx
- assets/src/components/appStateWrapper.tsx
- assets/src/components/disconnectedModal.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/searchPage.tsx
- assets/src/components/shuttleMapPage.tsx
- assets/src/contexts/socketContext.tsx
- assets/src/hooks/useSocket.ts
- assets/tests/components/__snapshots__/disconnectedModal.test.tsx.snap
- assets/tests/components/app.test.tsx
- assets/tests/components/disconnectedModal.test.tsx
- assets/tests/hooks/useSocket.test.ts
> show disconnected modal when socket disconnects

- assets/src/state/searchPageState.ts
- assets/tests/state/searchPageState.test.ts
Asana ticket: [Increase recent searches stored in Search  to 10 (current limit is 5)](https://app.asana.com/0/1148853526253426/1158831919513737)
> Increase saved recent searches cap to 10

- config/config.exs
- config/prod.exs
- lib/skate_web/templates/layout/app.html.eex
`static_url` was saying assets were at `localhost`, which means they weren't loading when connecting over wifi from a mobile device.
> use static_path on dev for easier mobile testing

- assets/src/app.tsx
- lib/skate_web/templates/layout/app.html.eex
Asana Task: [Only set scaling for Samsung Galaxy A tablets](https://app.asana.com/0/1148853526253426/1134672421440310)
The small tablets are 601x962
The large tablets are 640x1024
This is pretty hard to test, so we should put this on dev and poke around on several devices.
> Only set the scale smaller for small devices.

- README.md
> Add a "Community" section to the Readme

- assets/css/properties_panel/_vehicle_properties_panel.scss
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana ticket: [Invalid vehicle banner](https://app.asana.com/0/1148853526253426/1162089955688349)
Depends on https://github.com/mbta/skate/pull/457
> Add a banner describing an invalid vehicle

- lib/skate_web/templates/layout/_fullstory.html.eex
Link to new, CDN-hosted version.
Asana ticket: [Update FullStory snippet to link to new CDN-hosted version](https://app.asana.com/0/1148853526253426/1164222313401921)
> Update FullStory snippet

- assets/src/components/searchResults.tsx
- assets/tests/components/__snapshots__/searchResults.test.tsx.snap
- assets/tests/components/searchResults.test.tsx
Asana ticket: [Sort search results by most recent vehicle login time](https://app.asana.com/0/1148853526253426/1160813278503793)
> Sort search results by most recent logon time

- lib/realtime/ghost.ex
- lib/realtime/vehicle_or_ghost.ex
- test/realtime/vehicle_or_ghost_test.exs
Asana ticket: [🐞 Vehicles or ghosts with nil run_id properties break trying to subscribe to search results](https://app.asana.com/0/1148853526253426/1166724967888593)
> Handle nil values in vehicle/ghost property matching

- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/models/blockWaiver.ts
- assets/tests/components/__snapshots__/incomingBox.test.tsx.snap
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/layoverBox.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
- assets/tests/components/app.test.tsx
- assets/tests/components/incomingBox.test.tsx
- assets/tests/components/ladder.test.tsx
- assets/tests/components/layoverBox.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/ghostPropertiesPanel.test.tsx
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/components/routeLadders.test.tsx
- assets/tests/models/blockWaiver.test.ts
- config/config.exs
Remove the feature flag.
Waiting until we want this to go live in production before making a full PR.
~~Depends on https://github.com/mbta/skate/pull/502 (just the last commit is new).~~
> Enable block waivers for all users

- lib/gtfs/data.ex
> Revert "fix trips with missing timepoints"

- lib/concentrate/consumer/stop_time_updates.ex
- test/concentrate/consumer/stop_time_updates_test.exs
No ticket, just spotted this happening.
> Handle missing trips when processing stop time updates

- assets/src/components/routeLadder.tsx
- assets/tests/components/routeLadder.test.tsx
Asana ticket: [🐞 Showing both a ghost and a regular bus on the route](https://app.asana.com/0/1148853526253426/1161461620801441)
> Don't make a ghost indicator if another vehicle is on the run

- assets/css/_vehicle_map.scss
- assets/src/components/map.tsx
- assets/tests/components/__snapshots__/map.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana ticket: [Disable map recenter button if autoCenter is on](https://app.asana.com/0/1148853526253426/1145445573523887)
> Disable map recenter button when auto centering is on

- assets/src/components/propertiesList.tsx
- assets/src/helpers/vehicleLabel.ts
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesList.test.tsx.snap
- assets/tests/components/propertiesList.test.tsx
- assets/tests/helpers/vehicleLabel.test.ts
Asana ticket: [Treatment for overloaded vehicles (route ladder, Search, VPP, maps)](https://app.asana.com/0/1148853526253426/1169592928381123)
> Show "ADDED" for overloaded vehicles

- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
quick cleanup before I add more snapshots using this tag.
(view with whitespace changes hidden)
> remove redundant svg tag

- assets/src/components/STABLE/propertiesPanel.tsx
- assets/src/components/STABLE/propertiesPanel/blockWaiverBanner.tsx
- assets/src/components/STABLE/propertiesPanel/blockWaiverList.tsx
- assets/src/components/STABLE/propertiesPanel/closeButton.tsx
- assets/src/components/STABLE/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/components/STABLE/propertiesPanel/header.tsx
- assets/src/components/STABLE/propertiesPanel/headwayDiagram.tsx
- assets/src/components/STABLE/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/searchPage.tsx
- assets/src/components/shuttleMapPage.tsx
- assets/tests/components/STABLE/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel.test.tsx
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/blockWaiverBanner.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/blockWaiverList.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/header.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/headwayDiagram.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/blockWaiverBanner.test.tsx
- assets/tests/components/STABLE/propertiesPanel/blockWaiverList.test.tsx
- assets/tests/components/STABLE/propertiesPanel/ghostPropertiesPanel.test.tsx
- assets/tests/components/STABLE/propertiesPanel/header.test.tsx
- assets/tests/components/STABLE/propertiesPanel/headwayDiagram.test.tsx
- assets/tests/components/STABLE/propertiesPanel/vehiclePropertiesPanel.test.tsx
- config/config.exs
Add a new mini-schedule laboratory feature flag.
Copy all properties panel-related files into a "STABLE" folder.
The files in the stable folder will remain unchanged as we develop mini-
schedule in the "non-stable" files. When we are ready to launch mini-
schedule, we will be able to delete the "stable" folder without having
to make any changes to the "non-stable" files.
> Set up project for work on mini-schedules

- test/schedule_test.exs
No Asana ticket, just something I noticed.
> Update Schedule test name to match module

- lib/schedule/data.ex
- lib/schedule/gtfs/stop_time.ex
- lib/schedule/gtfs/trip.ex
- lib/schedule/helpers.ex
- lib/schedule/minischedule/load.ex
- lib/schedule/trip.ex
- test/schedule/data_test.exs
- test/schedule/gtfs/trip_test.exs
- test/schedule/trip_test.exs
Asana Task: [Mini-schedule | Store nonrevenue trips and trip schedule_ids](https://app.asana.com/0/1148853526253426/1171782113097825)
> Save nonrevenue trips

- lib/schedule.ex
- lib/schedule/data.ex
- lib/schedule/gtfs/feed_info.ex
- test/schedule/gtfs/feed_info_test.exs
Asana ticket: [Log GTFS version during import](https://app.asana.com/0/1148853526253426/1171057756326225)
> Log GTFS version during import

- .tool-versions
- Dockerfile
- semaphore/setup.sh
- test/concentrate/merge/table_test.exs
- test/concentrate/merge_test.exs
elixir v1.9.4-otp-22
erlang 22.3.2
No Asana ticket. Erlang 22.3.1+ is required for Catalina.
> Upgrade Elixir and Erlang

- lib/schedule/data.ex
- lib/schedule/minischedule/break.ex
- lib/schedule/minischedule/piece.ex
- lib/schedule/trip.ex
> by_id type and time types

- lib/schedule.ex
No asana task.
Deduplicates some code, fixes a couple typos, and should make problems like https://github.com/mbta/skate/pull/612#issuecomment-620577322 less likely to happen in the future.
> deduplicate timeout handling in Schedule

- assets/src/api.ts
- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/components/propertiesPanel/status_run_block_tabs.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/hooks/useMinischedule.ts
- assets/src/minischedule.d.ts
- assets/src/models/minischeduleData.ts
- assets/src/schedule.d.ts
- assets/tests/api.test.ts
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- assets/tests/components/propertiesPanel/status_run_block_tabs.test.tsx
- assets/tests/hooks/useMinischedule.test.ts
- assets/tests/testHelpers/mockHelpers.ts
Asana Task: [Mini-schedule | Frontend | Fetch data](https://app.asana.com/0/1148853526253426/1170680075334329)
> Fetch minischedules data in frontend 

- assets/css/properties_panel/_header.scss
- assets/src/components/STABLE/propertiesPanel/header.tsx
- assets/src/components/propertiesPanel/header.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/tests/components/STABLE/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/header.test.tsx.snap
- assets/tests/components/STABLE/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/header.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/header.test.tsx
Only for mini-schedule version. The stable version remains unchanged.
Asana ticket: [Mini-schedule | Frontend | Move the "last GPS ping" status into the header](https://app.asana.com/0/1148853526253426/1153848861993994)
Without flag:
With flag:
> Move the "last GPS ping" status into the header

- assets/src/components/map.tsx
- assets/tests/components/map.test.tsx
Followup from https://github.com/mbta/skate/pull/632#discussion_r420206636
> pull out useAutoCenter hook

- assets/css/_minischedule.scss
- assets/css/app.scss
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
Asana Task: [Mini-schedule | Trip List Component | Base component](https://app.asana.com/0/1148853526253426/1153870789408601)
> Minischedules trip list

- lib/train_vehicles/supervisor.ex
See https://app.asana.com/0/1148853526253426/1174706772540009
> Fetch only trains in TrainVehicles

- test/realtime/train_vehicles_pub_sub_test.exs
Asana Task: [Intermittent test failure on master](https://app.asana.com/0/1148853526253426/1176521535630973)
> remove async: true from test

- assets/css/_minischedule.scss
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/helpers/dom.ts
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
Card: https://app.asana.com/0/1148853526253426/1153870789408619
We now calculate and show layovers between trips in the minischedule.
> Layovers in minischedules

- lib/helpers.ex
- lib/realtime/data_status.ex
- lib/realtime/vehicle.ex
- lib/schedule/block.ex
- lib/schedule/trip.ex
- lib/skate_web/controllers/shuttle_controller.ex
No Asana task
@ingridpierre was having trouble compiling, getting this warning:
```
warning: type bool() is now called boolean(); please use the new name instead
```
This isn't blocking compiling for anyone else, so I'm not sure why it became a problem, but it's easy enough to try just fixing it.
> replace bool() with boolean()

- assets/css/_minischedule.scss
- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/components/propertiesPanel/status_run_block_tabs.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/helpers/dom.ts
- assets/src/minischedule.d.ts
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- assets/tests/components/propertiesPanel/status_run_block_tabs.test.tsx
Card: https://app.asana.com/0/1148853526253426/1153870789408614
The current trip or layover is highlighted in the minischedule with a
background color corresponding to its on-time adherence.
> Highlight current trip/layover in minischedule

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
Asana Task: [Mini-schedule | No icons for start/done, only for swings](https://app.asana.com/0/1148853526253426/1176968901192790)
I recommend doing the code review with whitespace changes hidden, since I had to change the indentation of the whole `Piece` component.
> No icons for start/done, only for swings

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
Asana Task: [Mini-schedule | Show if breaks are paid](https://app.asana.com/0/1148853526253426/1170732391370740)
> show whether breaks are paid or not

- assets/css/_properties_panel.scss
Card: https://app.asana.com/0/1148853526253426/1179728644442403
This makes the header of the VPP sticky, both with and without minischedules enabled.
> Make header of VPP sticky

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/minischedule.d.ts
- assets/src/models/minischeduleData.ts
- assets/tests/api.test.ts
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- lib/schedule/minischedule/load.ex
- lib/schedule/minischedule/piece.ex
- test/schedule/minischedule/block_test.exs
- test/schedule/minischedule/load_test.exs
- test/schedule/minischedule/piece_test.exs
- test/schedule/minischedule/run_test.exs
- test/schedule_test.exs
and other small fixes and refactors in preparation for [Mid-Route Swings](https://app.asana.com/0/1148853526253426/1170698291365289)
No behavior or interface changes.
> Flatten Piece type

- assets/css/_minischedule.scss
Card: https://app.asana.com/0/1148853526253426/1181088597711177
> Correct a few font sizes

- assets/css/_properties_panel.scss
- assets/package-lock.json
- assets/package.json
- assets/src/components/map.tsx
- assets/tests/setup.tsx
- assets/tests/testHelpers/cssStubber.js
Card: https://app.asana.com/0/1148853526253426/1173065850148378
...pretty much what it says on the label.
> Fullscreen button on VPP map

- assets/css/_crowding_diagram.scss
- assets/src/components/propertiesPanel.tsx
- assets/src/components/propertiesPanel/crowdingDiagram.tsx
- assets/tests/components/propertiesPanel.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/crowdingDiagram.test.tsx.snap
Card: https://app.asana.com/0/1148853526253426/1182434887083497
Tooltip activated by clicking on the "?" icon
> Add tooltip to crowding diagram

- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- config/config.exs
Card: https://app.asana.com/0/1148853526253426/1182591064768049
> Remove crowding-in-VPP feature flag

- assets/src/components/map.tsx
Card: https://app.asana.com/0/1148853526253426/1179942155819579
> Fix positioning of train vehicles on shuttle map

- assets/css/properties_panel/_vehicle_properties_panel.scss
- assets/src/api.ts
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/hooks/useNearestIntersection.ts
- assets/tests/api.test.ts
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
- assets/tests/hooks/useNearestIntersection.test.ts
- lib/geonames.ex
- lib/skate_web/controllers/intersection_controller.ex
- lib/skate_web/router.ex
- test/geonames_test.exs
- test/skate_web/controllers/intersection_controller_test.exs
Asana Task: [Add nearest intersection to VPP](https://app.asana.com/0/1148853526253426/1120980093841759)
If it's still loading / failed to load:
Old:
It still needs some QA for edge cases (bridges, tunnels, etc).
We're waiting for a response from geonames to see if we can add a token to the request. Right now it's completely open, all you need is the username to make the request.
Codecov is failing because we don't (and shouldn't) test the call to Geonames. Everything else is covered.
> Show nearest intersection

- lib/realtime/vehicles.ex
- test/realtime/vehicles_test.exs
Card: https://app.asana.com/0/1148853526253426/1173324653606105
We now sort vehicles in the incoming box, according to the departure time of their first trip on the new route.
> Sort incoming vehicles by departure time

- lib/notifications/notification_server.ex
- lib/realtime/block_waiver.ex
- test/notifications/notification_server_test.exs
Card: https://app.asana.com/0/1148853526253426/1189835249457881
Got the list in question from Dan.
> Use cause ID instead of cause description

- assets/src/components/app.tsx
- assets/src/components/notifications.tsx
- assets/src/components/routeLadders.tsx
- assets/src/hooks/useNotifications.ts
- assets/src/models/notificationData.ts
- assets/src/realtime.d.ts
- assets/tests/components/notifications.test.tsx
- assets/tests/hooks/useNotifications.test.tsx
- lib/notifications/notification_server.ex
- lib/skate_web/channels/notifications_channel.ex
- test/channels/notifications_channel_test.exs
- test/notifications/notification_server_test.exs
Asana Task: [Create front end socket](https://app.asana.com/0/1148853526253426/1187690663845805)
There's nothing to demo or screenshot here. It logs the data to the client's console in basically the same way as it did before this PR.
> Parse and log notifications on the frontend

- assets/src/components/notifications.tsx
- assets/tests/components/notifications.test.tsx
- config/config.exs
Card: https://app.asana.com/0/1148853526253426/1191003352789111
> Add feature flag for notifications

- assets/src/realtime.d.ts
- lib/notifications/notification_server.ex
- test/notifications/notification_server_test.exs
Card: https://app.asana.com/0/1148853526253426/1188888192128019
This adds four more block waiver types as triggers for notifications.
> Add more block waiver types to notifications

- assets/css/_notifications.scss
- assets/css/_ui_kit.scss
- assets/css/app.scss
- assets/src/components/app.tsx
- assets/src/components/notifications.tsx
- assets/src/components/propertiesList.tsx
- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/components/searchResults.tsx
- assets/src/realtime.d.ts
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/notifications.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesList.test.tsx.snap
- assets/tests/components/notifications.test.tsx
- assets/tests/components/propertiesList.test.tsx
Asana Task: [Notifications cards](https://app.asana.com/0/1148853526253426/1187690663845807)
And here it is behind the VPP:
The hover states work. The close button removes the notification, but clicking the body of the notification does nothing.
Opening the VPP, showing the specific route that an accident happened on, and showing the operator will depend on getting that information out of Transit Master
Animation, showing the modal if we can't find the vehicle, and fullstory tracking are all separate tickets and not part of this.
> Notification Cards

- assets/css/_notifications.scss
- assets/src/components/notifications.tsx
- assets/tests/components/__snapshots__/notifications.test.tsx.snap
- assets/tests/components/notifications.test.tsx
Asana Task: [Notification animation](https://app.asana.com/0/1148853526253426/1191003352789117)
Animating closing the notifications would be a little harder, so I skipped that. (You'd have to keep the component around until the animation finishes, and you might also want to animate the other notifications sliding into position.)
~Built on top of #828~ Ready for review. There was an indentation change, so view it with whitespace turned off.
> Notification Animation

- assets/src/models/notificationData.ts
- assets/src/realtime.d.ts
Card: https://app.asana.com/0/1148853526253426/1193945478472273
> Send vehicle data fields to frontend

- assets/src/contexts/notificationsContext.tsx
- config/config.exs
https://app.asana.com/0/1148853526253426/1192226947985430
> Remove notifications feature flag

- assets/src/api.ts
- assets/src/components/appStateWrapper.tsx
- assets/src/components/settingsPage.tsx
- assets/src/hooks/usePersistedStateReducer.ts
- assets/src/settings.ts
- assets/src/skate.d.ts
- assets/src/state.ts
- assets/tests/api.test.ts
- assets/tests/components/settingsPage.test.tsx
- assets/tests/hooks/useAppcues.test.ts
- assets/tests/hooks/usePersistedStateReducer.test.ts
- assets/tests/state.test.ts
- config/test.exs
- lib/skate/application.ex
- lib/skate/migrate.ex
- lib/skate/settings.ex
- lib/skate/settings/user.ex
- lib/skate/settings/user_settings.ex
- lib/skate/settings/vehicle_label.ex
- lib/skate_web/controllers/page_controller.ex
- lib/skate_web/controllers/settings_controller.ex
- lib/skate_web/router.ex
- lib/skate_web/templates/page/index.html.eex
- priv/repo/migrations/20200928172840_create_user_settings.exs
- test/skate/settings_test.exs
- test/skate_web/controllers/page_controller_test.exs
- test/skate_web/controllers/settings_controller_test.exs
- test/skate_web/router_test.exs
- test/support/data_case.ex
- test/test_helper.exs
Asana Task: [Store general user settings (run vs vehicle number) ](https://app.asana.com/0/1148853526253426/1184959932880361)
Sorry, this got pretty big. The commits are meaningfully separated and labeled if that helps you go through it.
> Store user settings in database

- config/config.exs
Asana Task: [Set up notifications v2 feature flag](https://app.asana.com/0/1148853526253426/1192202587402571)
> Notifications drawer feature flag

- assets/src/components/tabBar.tsx
Fixes https://sentry.io/organizations/mbtace/issues/1982425160 (no asana task)
> don't try to call drift api if fetching it failed

- assets/css/_tab_bar.scss
- assets/css/_ui_kit.scss
- assets/src/components/tabBar.tsx
- assets/src/components/vehicleIcon.tsx
- assets/src/helpers/date.ts
- assets/tests/helpers/date.test.ts
Asana Task: [Halloween icons on route ladders](https://app.asana.com/0/1148853526253426/1196841841006813)
Last year's PR: #267 
(Only off course buses will be bats. I made them all off course for the screenshot because there weren't any off course buses right now.)
I didn't bother with writing complete tests, so tests will fail all day on Saturday, but since it's the weekend and that only affects development, I assumed that'd be fine. (Tests pass on other days)
> Halloween decorations

- assets/src/components/inactiveNotificationModal.tsx
- assets/src/components/notifications.tsx
- assets/src/contexts/notificationsContext.tsx
- assets/src/hooks/useNotifications.ts
- assets/src/models/notificationData.ts
- assets/src/realtime.d.ts
- assets/tests/components/inactiveStateModal.test.tsx
- assets/tests/components/modal.test.tsx
- assets/tests/components/notifications.test.tsx
- assets/tests/contexts/notificationsContext.test.tsx
- assets/tests/hooks/useNotifications.test.tsx
- assets/tests/hooks/useVehicleForNotification.test.tsx
- assets/tests/state.test.ts
- lib/notifications/notification_server.ex
- lib/skate/settings/user.ex
- lib/skate_web/auth_manager.ex
- lib/skate_web/channels/notifications_channel.ex
- test/notifications/notification_server_test.exs
- test/skate_web/auth_manager_test.exs
- test/skate_web/channels/notifications_channel_test.exs
Card: https://app.asana.com/0/1148853526253426/1192202587402603
> Filter notifications on backend rather than frontend

- assets/css/_notification_content.scss
- assets/css/_notification_drawer.scss
- assets/css/_notifications.scss
- assets/css/app.scss
- assets/src/components/inactiveNotificationModal.tsx
- assets/src/components/notificationContent.tsx
- assets/src/components/notificationDrawer.tsx
- assets/src/components/notifications.tsx
- assets/src/components/propertiesPanel/header.tsx
- assets/src/hooks/useCurrentTime.ts
- assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap
- assets/tests/components/__snapshots__/notifications.test.tsx.snap
- assets/tests/components/notificationDrawer.test.tsx
Asana Task: [Show cards already in memory in the notification drawer](https://app.asana.com/0/1148853526253426/1192202587402577)
> Show cards in the notification drawer

- assets/src/contexts/notificationsContext.tsx
- assets/tests/contexts/notificationsContext.test.tsx
Card: https://app.asana.com/0/1148853526253426/1192202587402585
> Expire notifications in frontend after 8 hours

- assets/package-lock.json
- assets/package.json
- assets/src/app.tsx
- assets/src/components/ladderPage.tsx
Card: https://app.asana.com/0/1148853526253426/1196917567568801
> Username in Sentry (frontend)

- lib/notifications/db/notification_user.ex
- lib/notifications/notification.ex
- lib/notifications/notification_state.ex
- lib/skate/settings/user.ex
- priv/repo/migrations/20201130200537_create_notifications_users.exs
- test/notifications/db/notification_user_test.exs
- test/notifications/notification_state_test.exs
- test/notifications/notification_test.exs
Card: https://app.asana.com/0/1148853526253426/1192202587402601
When a notification is created, it's now linked via a new join table to users who are subscribed to any affected routes.
> Join notifications to users on notification create

- assets/src/components/notificationBellIcon.tsx
- assets/src/contexts/notificationsContext.tsx
- assets/tests/components/__snapshots__/notificationBellIcon.test.tsx.snap
- assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap
- assets/tests/components/notificationBellIcon.test.tsx
Card: https://app.asana.com/0/1148853526253426/1192231025751539
> Show badge on bell if new notifications

- assets/css/_notification_drawer.scss
- assets/src/components/notificationDrawer.tsx
- assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap
- assets/tests/components/notificationDrawer.test.tsx
Card: https://app.asana.com/0/1148853526253426/1199674046684106
> Merge read and unread notifications into one list

- assets/src/components/notificationDrawer.tsx
- assets/src/components/notifications.tsx
- assets/src/contexts/stateDispatchContext.tsx
- assets/tests/components/notificationDrawer.test.tsx
- assets/tests/components/notifications.test.tsx
Card: https://app.asana.com/0/1148853526253426/1192202587402595
Note: this is based on https://github.com/mbta/skate/pull/966
> Mark notifications as read when opening

- assets/src/components/notificationDrawer.tsx
- assets/src/contexts/notificationsContext.tsx
- assets/tests/components/notificationBellIcon.test.tsx
- assets/tests/components/notificationDrawer.test.tsx
- assets/tests/components/notifications.test.tsx
Card: https://app.asana.com/0/1148853526253426/1199643681548665
> Save scroll position of notifications when closing

- assets/src/components/rightPanel.tsx
- assets/src/components/tabBar.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- config/config.exs
Card: [Remove the feature flag and launch](https://app.asana.com/0/1148853526253426/1192231025751537/f)
🚀
> chore: remove notifications drawer feature flag

- assets/src/components/notificationDrawer.tsx
- assets/src/contexts/notificationsContext.tsx
- assets/tests/components/notificationBellIcon.test.tsx
- assets/tests/components/notificationDrawer.test.tsx
- assets/tests/components/notifications.test.tsx
Card: https://app.asana.com/0/1148853526253426/1199706567539372
> Opening one card submenu closes other submenus

- assets/css/_notification_drawer.scss
Card: [Increase click target of ellipsis menu](https://app.asana.com/0/1148853526253426/1199706567539368/f)
> feat: expand the clickable area of the ellipsis icon

- assets/src/components/notificationDrawer.tsx
- assets/tests/components/notificationDrawer.test.tsx
Card: https://app.asana.com/0/1148853526253426/1199706567539370
> Close ellipsis submenu on click away

- assets/css/_notification_drawer.scss
Card: https://app.asana.com/0/1148853526253426/1185722272692314
> Make notification title bar sticky

- assets/src/components/notificationContent.tsx
- assets/src/hooks/useTimepoints.ts
- assets/src/util/dateTime.ts
- assets/tests/util/dateTime.test.ts
https://app.asana.com/0/812686650013698/1199671366117688/f
> Dispatcher Note timestamps absolute if >60m

- assets/src/components/notifications.tsx
- assets/tests/components/notifications.test.tsx
Card: https://app.asana.com/0/1148853526253426/1199581932380738
> Hide latest notification on clickthrough

- priv/repo/migrations/20210201201440_add_trip_label_to_user_settings.exs
Card: https://app.asana.com/0/1148853526253426/1199712930898342
> Add migration for minischedules trip label

- lib/notifications/notification.ex
- test/notifications/notification_test.exs
> Don't copy block waiver attributes from block_waivers table to notifications

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/components/settingsPage.tsx
- assets/src/state.ts
- assets/src/userSettings.ts
- assets/tests/components/__snapshots__/settingsPage.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- assets/tests/components/settingsPage.test.tsx
- assets/tests/state.test.ts
- assets/tests/userSettings.test.ts
- config/config.exs
- lib/schedule/data.ex
- lib/skate/settings/db/user_settings.ex
- lib/skate/settings/trip_label.ex
- lib/skate/settings/user_settings.ex
- lib/skate_web/controllers/user_settings_controller.ex
- test/notifications/notification_test.exs
- test/skate/settings/user_settings_test.exs
- test/skate_web/controllers/user_settings_controller_test.exs
Card: https://app.asana.com/0/1148853526253426/1199683601247945
We've had a number of requests to make this configurable, this is an MVP behind a feature flag until the design is finalized.
> (MVP) User can choose origin or destination for minischedule trip labels

- lib/realtime/data_status.ex
- test/realtime/data_status_test.exs
Ticket: [Richer logging around data outages](https://app.asana.com/0/1148853526253426/1199901396231627/f)
I've briefly put this up on skate-dev and verified that the logs look good.
> feat: more detailed logging of data status calculations

- lib/notifications/bridge.ex
- lib/notifications/bridge_status.ex
- lib/notifications/db/bridge_movement.ex
- lib/notifications/db/notification.ex
- lib/notifications/notification.ex
- lib/notifications/notification_server.ex
- test/notifications/bridge_test.exs
- test/notifications/db/notification_user_test.exs
- test/notifications/notification_server_test.exs
- test/notifications/notification_test.exs
- test/skate_web/controllers/notification_read_states_controller_test.exs
Card: https://app.asana.com/0/1148853526253426/1199624386814205
> Chelsea bridge notifications

- lib/skate_web/controllers/route_settings_controller.ex
- test/skate_web/controllers/route_settings_controller_test.exs
Card: https://app.asana.com/0/1148853526253426/1199632230017271
> Make route setings controller tolerate missing values

- README.md
- config/config.exs
- config/dev.exs
Card: https://app.asana.com/0/1148853526253426/1200093555008845
> Set swings beta users via env var

- lib/schedule/hastus/activity.ex
- lib/schedule/hastus/place.ex
- lib/schedule/hastus/trip.ex
- test/schedule/hastus/activity_test.exs
- test/schedule/hastus/place_test.exs
- test/schedule/hastus/trip_test.exs
Ticket: [Skate should replace 'dudly' with 'nubn' ](https://app.asana.com/0/1148853526253426/1200093555008857/f)
> fix: handle "dudly" place name in HASTUS import

- assets/src/components/crowdingIcon.tsx
- assets/src/components/iconAlertCircle.tsx
- assets/src/components/incomingBox.tsx
- assets/src/components/ladder.tsx
- assets/src/components/propertiesPanel/header.tsx
- assets/src/components/propertiesPanel/headwayDiagram.tsx
- assets/src/components/vehicleIcon.tsx
- assets/tests/components/vehicleIcon.test.tsx
Card: https://app.asana.com/0/1200180014510248/1200166345135753
> Memoize several frontend components

- assets/css/_swings_view.scss
- assets/src/components/swingsView.tsx
- assets/tests/components/__snapshots__/swingsView.test.tsx.snap
Asana ticket: [⚙️ Implement mobile design for swings beta](https://app.asana.com/0/1200109164313812/1200255331565835/f)
> feat: mobile styling of swings view

- lib/schedule/swing.ex
- test/schedule/swing_test.exs
Asana ticket: [⚙️ Account for mid-route swings ](https://app.asana.com/0/1200180014510248/1200296680655481/f)
> fix: account for mid-route swings in swings view

- assets/src/components/swingsView.tsx
- assets/tests/components/__snapshots__/swingsView.test.tsx.snap
- assets/tests/components/swingsView.test.tsx
- assets/tests/factories/vehicle.ts
Card: https://app.asana.com/0/1200180014510248/1200319026485112
> Underline active swing(s) in each row of swings view

- README.md
Asana ticket: [Document skate prod deploy process](https://app.asana.com/0/1152340551558956/1200169823272443/f)
> docs: document production deploy process

- lib/realtime/server.ex
- lib/schedule/swing.ex
- lib/skate_web/channels/vehicles_channel.ex
- test/realtime/server_test.exs
- test/schedule/swing_test.exs
- test/schedule_test.exs
- test/skate_web/channels/vehicles_channel_test.exs
Asana ticket: [Back-end changes to allow subscribing to vehicles by block ID](https://app.asana.com/0/0/1200347448522880/f)
These are just the back-end changes so that we can merge and deploy those first. I'll open another PR with the front-end changes shortly.
> Allow subscribing to vehicles channel by block IDs

- assets/src/components/swingsView.tsx
- assets/src/hooks/useVehiclesForBlockIds.ts
- assets/src/models/swingsData.ts
- assets/src/schedule.d.ts
- assets/tests/components/__snapshots__/swingsView.test.tsx.snap
- assets/tests/components/swingsView.test.tsx
- assets/tests/factories/swing.ts
- assets/tests/factories/vehicle_data.ts
- assets/tests/hooks/useVehiclesForBlockIds.test.ts
- assets/tests/models/swingsData.test.ts
Asana ticket: [Make Swings View more block-oriented for determining vehicle number ](https://app.asana.com/0/1200109164313812/1200341164386661/f)
Once you review #1115 I can merge it and then TypeScript changes will be all that's left on this PR.
> Block-based swings view vehicle numbers

- assets/src/components/propertiesPanel/crowdingDiagram.tsx
- assets/tests/components/propertiesPanel/__snapshots__/crowdingDiagram.test.tsx.snap
Asana ticket: [Change crowding copy from "maximum" to "seats" ](https://app.asana.com/0/1200180014510248/1200381936995684/f)
> fix: change copy for crowding from "maximum" to "seats"

- lib/notifications/notification_server.ex
- lib/realtime/server.ex
- lib/skate_web/channels/vehicle_channel.ex
- test/notifications/notification_server_test.exs
- test/realtime/server_test.exs
- test/skate_web/channels/vehicle_channel_test.exs
@lemald once this is merged, I'll do the rebase/force-push dance on the other PR.
> Refactor VPP open--backend only

- assets/css/_swings_view.scss
- assets/src/components/swingsView.tsx
- assets/tests/components/__snapshots__/swingsView.test.tsx.snap
Asana ticket: [⚙️ Implement Swings View type size refactor](https://app.asana.com/0/1200109164313812/1200341164386746/f)
> Swings type size changes

- assets/css/_swings_view.scss
- assets/src/components/swingsView.tsx
- assets/tests/components/__snapshots__/swingsView.test.tsx.snap
- assets/tests/components/swingsView.test.tsx
Asana ticket: [⚙️ Implement past swings in Swings View ](https://app.asana.com/0/1200109164313812/1200341164386665/f)
> feat: allow showing past swings

- assets/package-lock.json
- assets/package.json
Asana ticket: [⚙️ Clean out Skate dependabot PRs](https://app.asana.com/0/1152340551558956/1200365468573553/f)
> NPM upgrades

- assets/__mocks__/leaflet.js
- assets/package-lock.json
- assets/package.json
Asana ticket: [⚙️ Clean out Skate dependabot PRs](https://app.asana.com/0/1152340551558956/1200365468573553/f)
> chore: update Jest to 26

- assets/src/components/lateView.tsx
- assets/tests/components/__snapshots__/lateView.test.tsx.snap
https://app.asana.com/0/1200180014510248/1200565967622361
> Add late ghosts to late view

- assets/src/components/app.tsx
- assets/src/components/rightPanel.tsx
- assets/src/components/tabBar.tsx
- assets/src/state.ts
- assets/tests/components/rightPanel.test.tsx
- assets/tests/components/tabBar.test.tsx
- assets/tests/state.test.ts
Asana ticket: [⚙️ Make Swings and Late View mutually exclusive](https://app.asana.com/0/1148853526253420/1200610597179066/f)
> fix: make swings view and late view mutually exclusive

- lib/realtime/ghost.ex
- lib/realtime/vehicles.ex
- lib/schedule.ex
- lib/schedule/data.ex
- lib/schedule/minischedule/load.ex
- lib/schedule/minischedule/run.ex
- test/realtime/ghost_test.exs
- test/realtime/vehicles_test.exs
- test/schedule/data_test.exs
- test/schedule/minischedule/load_test.exs
- test/schedule/minischedule/run_test.exs
- test/skate_web/controllers/minischedule_controller_test.exs
- test/support/factory.ex
Asana ticket: [⚙️ Switch to run-based ghosts](https://app.asana.com/0/1187728323414541/1200568590873231/f)
> Run-based ghosts

- lib/realtime/ghost.ex
- lib/schedule/as_directed.ex
- lib/schedule/break.ex
- lib/schedule/minischedule/block.ex
- lib/schedule/minischedule/load.ex
- lib/schedule/minischedule/run.ex
- lib/schedule/piece.ex
- lib/schedule/swing.ex
- test/realtime/ghost_test.exs
- test/realtime/vehicles_test.exs
- test/schedule/minischedule/block_test.exs
- test/schedule/minischedule/load_test.exs
- test/schedule/minischedule/piece_test.exs
- test/schedule/minischedule/run_test.exs
- test/schedule/swing_test.exs
- test/schedule_test.exs
- test/support/factory.ex
https://app.asana.com/0/1200180014510248/1200611799543196
> Move Piece and friends up a level

- assets/src/components/lateView.tsx
- assets/src/components/tabBar.tsx
- assets/tests/components/lateView.test.tsx
- assets/tests/components/tabBar.test.tsx
Asana ticket: [⚙️ Custom FullStory tracking for Late View ](https://app.asana.com/0/1200180014510248/1200599650648951/f)
> Late view Fullstory tracking

- assets/src/components/app.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/lateView.tsx
- assets/tests/components/app.test.tsx
- assets/tests/components/lateView.test.tsx
Asana ticket: [⚙️ Investigate why route ladders in Skate-dev and Skate-dev-blue don't update in real-time when Late View is open](https://app.asana.com/0/1200180014510248/1200636403340835/f)
> fix: provide vehicles to late view via context

- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
Asana ticket: [⚙️ Change unknown dispatcher note copy](https://app.asana.com/0/1187728323414541/1200631101767179/f)
> feat: update unknown ghost copy

- assets/css/_late_view.scss
- assets/src/components/lateView.tsx
- assets/tests/components/__snapshots__/lateView.test.tsx.snap
https://app.asana.com/0/1200180014510248/1200599650648974
> Adjust some spacing in late view

- assets/css/_pigeon.scss
- assets/css/_vehicle_map.scss
- assets/css/app.scss
- assets/package-lock.json
- assets/package.json
- assets/src/components/map.tsx
- assets/tests/components/map.test.tsx
- config/config.exs
Asana ticket: [⚙️ Pigeon replacement: Draw map, icons, and labels (1/3)](https://app.asana.com/0/1200180014510248/1200542106910651/f)
> Pigeon maps: draw map and vehicle markers

- assets/css/_late_view.scss
Asana ticket: [⚙️  Implement visual design polishes to Late View](https://app.asana.com/0/1187728323414541/1200777010749406/f)
> feat: Late View style polish

- lib/realtime/block_waiver_store.ex
- lib/realtime/ghost.ex
- lib/realtime/vehicle.ex
- test/realtime/block_waiver_store_test.exs
Asana ticket: [🐞 Block waivers not showing up in Skate ](https://app.asana.com/0/1148853526253437/1200899029361209/f)
Also reverts #1259 because that debugging logging is no longer needed.
> fix waivers on vehicles / ghosts

- lib/schedule/data.ex
- lib/schedule/garage.ex
- lib/schedule/gtfs/route.ex
- test/schedule/garage_test.exs
- test/skate_web/controllers/route_controller_test.exs
- test/support/factory.ex
Asana ticket: [Add garages data to routes](https://app.asana.com/0/0/1201189412881318/f)
> feat: add garage data to routes

- assets/src/api.ts
- assets/src/components/ladderPage.tsx
- assets/src/hooks/usePersistedStateReducer.ts
- assets/src/models/routeTab.ts
- assets/src/state.ts
- assets/tests/api.test.ts
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/ladderPage.test.tsx
- assets/tests/factories/routeTab.ts
- assets/tests/hooks/usePersistedStateReducer.test.ts
- assets/tests/state.test.ts
- lib/skate/settings/db/route_tab.ex
- lib/skate/settings/db/user.ex
- lib/skate/settings/route_tab.ex
- lib/skate_web/controllers/route_tabs_controller.ex
- lib/skate_web/router.ex
- test/skate/settings/route_tab_test.exs
- test/skate_web/controllers/page_controller_test.exs
- test/skate_web/controllers/route_tabs_controller_test.exs
- test/support/factory.ex
Asana ticket: [⚙️ Live prototype: Implement logic + interactions for Presets tab ](https://app.asana.com/0/1200180014510248/1201087271304728/f)
I probably need to add a couple more tests to get coverage up to 100% but figured I would open a PR for review.
> Persist tabs

- assets/css/_drawer_tab.scss
- assets/css/_garage_filter.scss
- assets/css/_route_filter.scss
- assets/css/app.scss
- assets/src/helpers/icon.tsx
- assets/src/hooks/useGarageFilter.tsx
- assets/src/hooks/useRouteFilter.tsx
- assets/static/images/icon-toggle-off.svg
- assets/static/images/icon-toggle-on.svg
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/routePicker.test.tsx.snap
- assets/tests/hooks/useGarageFilter.test.tsx
- assets/tests/hooks/useRouteFilter.test.tsx
Asana ticket: [⚙️ Implement styling to route picker](https://app.asana.com/0/1200180014510248/1201148067873468/f)
This should be largely feature-complete but note that I still haven't quite figured out how to test the focus-dependent clear route filter button, so there's still a failing test in there. Everything else should be ready for review though and I'll revisit that test tomorrow.
> Style route picker

- assets/src/api.ts
- assets/src/hooks/usePersistedStateReducer.ts
- assets/src/models/routeTab.ts
- assets/tests/hooks/usePersistedStateReducer.test.ts
Asana ticket: [⚙️Initialize route tabs on page load](https://app.asana.com/0/1200180014510248/1201433374717642/f)
> feat: load route tabs from data-route-tabs attribute into app state

- assets/css/_incoming_box.scss
- assets/css/_ladder_page.scss
Asana ticket: [⚙️ Implement styling changes to ladder page to accommodate tabs and presets](https://app.asana.com/0/1200180014510248/1201262012057890/f)
See Asana comment about which parts of the task are and are not going to be included in this PR (it ended up being pretty small).
> chore: color and border changes

- lib/schedule/fetcher.ex
- test/schedule/fetcher_test.exs
Asana ticket: [turn off automatic ingestion of schedule data](https://app.asana.com/0/1200180014510248/1201516749504966/f)
> fix: temporarily only poll schedule data on app start

- .tool-versions
- Dockerfile
- upload_assets.sh
Asana ticket: [⚙️ Update node.js](https://app.asana.com/0/1152340551558956/1200415301013517/f)
I ended up also largely redoing the Dockerfile as part of this ticket. This makes the build process much nicer and hopefully reduces the size of the resulting container as well.
> Update Node and Dockerfile

- config/prod.exs
- lib/skate_web/endpoint.ex
- mix.exs
- mix.lock
To aid in [⚙️Benchmark tabs / presets API performance](https://app.asana.com/0/1200180014510248/1201651613270218/f)
> feat: use Logster for better request logging

- assets/src/components/ladderPage.tsx
- assets/tests/components/ladderPage.test.tsx
Asana ticket: [⚙️ Behavior when no tabs are open](https://app.asana.com/0/1200180014510248/1201699907939378/f)
> fix: open blank tab when none are present

- assets/css/_ladder_page.scss
- assets/css/_route_picker.scss
- assets/src/components/ladderPage.tsx
- assets/src/components/routePicker.tsx
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/routePicker.test.tsx.snap
- assets/tests/components/routePicker.test.tsx
Asana ticket: [⚙️ Style route picker toggle between routes and presets view](https://app.asana.com/0/1200180014510248/1201403136252736/f)
> feat: style toggle between routes and presets in picker

- assets/css/_ladder_page.scss
- assets/src/components/app.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/presets.tsx
- assets/src/models/routeTab.ts
- assets/src/state.ts
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/ladderPage.test.tsx
- assets/tests/components/presets.test.tsx
- assets/tests/models/routeTab.test.ts
- assets/tests/state.test.ts
- lib/skate/settings/db/route_tab.ex
- lib/skate/settings/route_tab.ex
- lib/skate_web/controllers/route_tabs_controller.ex
- test/skate/settings/route_tab_test.exs
- test/support/factory.ex
Asana ticket: [⚙️ Ability to update an existing preset](https://app.asana.com/0/1200180014510248/1201367915520955/f)
> Edit presets

- assets/css/_presets.scss
- assets/css/app.scss
- assets/src/components/presets.tsx
- assets/tests/components/__snapshots__/presets.test.tsx.snap
- assets/tests/components/presets.test.tsx
Asana ticket: [⚙️ Implement styling to presets panel ](https://app.asana.com/0/1200180014510248/1201262012057883/f)
Here's the resulting styling (once I do the next ticket to actually provide a modal where the user can enter a real name when saving presets I'll be able to get some even better screenshots):
> Style presets panel

- assets/css/_input_modal.scss
- assets/css/app.scss
- assets/src/components/inputModals/createPresetModal.tsx
- assets/src/components/inputModals/deletePresetModal.tsx
- assets/src/components/inputModals/savePresetModal.tsx
- assets/tests/components/__snapshots__/modal.test.tsx.snap
Asana ticket: [⚙️ Implement styling to preset modals](https://app.asana.com/0/1200180014510248/1201448223729785/f)
A few screenshots:
> Styling of presets modals

- .github/workflows/deploy-dev-ecs.yml
Asana ticket: [⚙️ Migrate Skate to ECS](https://app.asana.com/0/1199703668163620/1199929177825017/f)
The actual ECS environment hasn't been created yet, but there's a PR open to do so and I'm putting together this action to be ready for it.
> build: GitHub Action to deploy to dev on ECS

- .github/workflows/deploy-prod-ecs.yml
Asana ticket: [⚙️ Migrate Skate to ECS](https://app.asana.com/0/1199703668163620/1199929177825017/f)
> build: workflow to deploy prod to ECS

- assets/src/components/inputModals/deletePresetModal.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/presets.tsx
- assets/tests/components/inputModals/deletePresetModal.test.tsx
- assets/tests/components/ladderPage.test.tsx
- assets/tests/components/presets.test.tsx
Asana ticket: [⚙️ Implement FullStory custom events ](https://app.asana.com/0/1200180014510248/1201827209067899/f)
> feat: FullStory tracking for tabs and presets

- assets/css/_input_modal.scss
- assets/src/components/inputModals/createPresetModal.tsx
- assets/src/components/inputModals/overwritePresetModal.tsx
- assets/src/components/modal.tsx
- assets/src/models/routeTab.ts
- assets/src/state.ts
- assets/tests/components/__snapshots__/modal.test.tsx.snap
- assets/tests/components/inputModals/createPresetModal.test.tsx
- assets/tests/components/inputModals/overwritePresetModal.test.tsx
- assets/tests/components/modal.test.tsx
- assets/tests/models/routeTab.test.ts
- assets/tests/state.test.ts
Asana ticket: [⚙️ Handle case when user tries to create preset under existing name](https://app.asana.com/0/1200180014510248/1201756457873983/f)
> Prevent duplicate preset names

- lib/skate/settings/route_tab.ex
- lib/skate_web/controllers/swings_controller.ex
- test/skate/settings/route_tab_test.exs
- test/skate_web/controllers/swing_controller_test.exs
Asana ticket: [⚙️ Swings view - base swings to show on open tabs](https://app.asana.com/0/1200180014510248/1201880022483800/f)
> fix: base routes in swings view off of route_tabs table

- assets/src/models/routeTab.ts
- assets/src/state.ts
- assets/tests/models/routeTab.test.ts
- assets/tests/state.test.ts
Asana ticket: [⚙️ Switch to appropriate tab when opening vehicle from notification](https://app.asana.com/0/1200180014510248/1201862941782388/f)
> feat: go to tab with route when opening VPP from notification

- assets/src/hooks/useNotifications.ts
- assets/tests/hooks/useNotifications.test.tsx
Asana ticket: [⚙️ [extra] Fix infinite useEffect loop](https://app.asana.com/0/1200180014510248/1201957254872274/f)
I also tested this out locally with some `console.log` statements and made sure that I was able to reproduce the original issue and that the fix then actually resolved it.
> fix: JSON.stringify useEffect hook dependency

- lib/schedule/health/checkers/routes_checker.ex
- lib/schedule/health/checkers/timepoints_checker.ex
- lib/schedule/health/checkers/trip_stop_times_checker.ex
- test/schedule/health/checkers/routes_checker_test.exs
- test/schedule/health/checkers/timepoints_checker_test.exs
- test/schedule/health/checkers/trip_stop_times_checker_test.exs
Asana: [Better Logging of Schedule Health Check Failures](https://app.asana.com/0/1152340551558956/1201994849078241/f)
Adds warning-level logging when schedule health checks fail: routes checker, timepoint checker, and trip stop times checker. Adds CaptureLog testing to associated tests.
> chore: logging when schedule health checks fail

- lib/schedule/gtfs/timepoint.ex
- test/schedule/data_test.exs
Asana ticket: [⚙️ Human-readable names for all garages](https://app.asana.com/0/1200180014510248/1201983930266769/f)
> chore: human-readable names for all garages in schedule

- assets/css/_notification_drawer.scss
- assets/css/properties_panel/_tab_panels.scss
- assets/src/components/notificationDrawer.tsx
- assets/src/components/propertiesPanel/tabList.tsx
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/header.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana ticket: [⚙️ [extra] Clean up ignored jsx-a11y errors](https://app.asana.com/0/1152340551558956/1202375393472375/f)
A few of the errors ended up being more complicated in question, so I have created followup tickets to discuss approaches with design and product. This still cleans out a couple of issues, though.
> jsx-a11y fixes

- assets/src/hooks/useDeviceType.ts
Asana: https://app.asana.com/0/1200180014510248/1202556284152408/f
Update tablet breakpoint to 1340 so nav will appear in tablet mode on landscape tablets
> update tablet breakpoint for landscape maximum of updated tablets

- assets/css/nav/_bottom_nav_mobile.scss
- assets/css/nav/_left_nav.scss
Asana ticket: [⚙️ Implement color and tap target size changes](https://app.asana.com/0/1200180014510248/1202801429560543/f)
> Expand tap targets and other nav styling changes

- assets/src/components/nav.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/app.test.tsx
- assets/tests/components/nav.test.tsx
Asana ticket: [⚙️ Remove beta group and ship to GA](https://app.asana.com/0/1200180014510248/1202140732775596/f)
This does a fairly minimal set of changes to display the new navigation to everyone, without going through and cleaning up all of the code related to the old navigation. This way it will be relatively quick and easy to switch back to the old navigation in case of issues once we release it. Once it has run for a few days, we have [a ticket to go in and thoroughly clean up the old navigation code](https://app.asana.com/0/1200180014510248/1202131476892177/f).
> chore: display new nav to all

- assets/css/_pigeon.scss
- assets/css/app.scss
- assets/package-lock.json
- assets/package.json
- assets/src/components/map.tsx
- assets/tests/components/map.test.tsx
- config/config.exs
Asana ticket: [⚙️[extra] remove Pigeon code](https://app.asana.com/0/1200180014510248/1202801429560548/f)
We had experimented a bit with the pigeon-maps library a while back, which initially looked promising but ended up not being quite full-featured enough for our needs. This PR just removes some code from when we thought we were adopting Pigeon to clear things up before doing other map work.
> chore(deps): remove pigeon

- assets/css/_late_view.scss
Asana ticket: [🎨⚙️ Make tables responsive](https://app.asana.com/0/1200180014510248/1202729338901503/f)
This incorporates a variety of changes discussed between dev and design that add up to a more responsive table. Adjustments include:
1. Using percentage widths for `<th>` column header elements, making the table shrink / grow more gracefully.
2. Reducing the width of the "Scheduled Logon" column so that the title wraps by default.
3. The container has fixed-width on larger screens, but on smaller screens now has `width: 100%`.
4. The table container panels can scroll horizontally if your screen is _really_ small.
> feat: more responsive layout for Late View table

- assets/tests/components/__snapshots__/propertiesList.test.tsx.snap
- assets/tests/components/app.test.tsx
- assets/tests/components/disconnectedModal.test.tsx
- assets/tests/components/drawerTab.test.tsx
- assets/tests/components/incomingBox.test.tsx
- assets/tests/components/notificationDrawer.test.tsx
- assets/tests/components/propertiesList.test.tsx
- assets/tests/components/propertiesPanel/blockWaiverBanner.test.tsx
- assets/tests/components/propertiesPanel/minischedule.test.tsx
A subset of files from https://app.asana.com/0/1152340551558956/1201708616021563/f.
> refactor(tests): convert a subset of enzyme tests to use react testing library

- assets/css/_swings_view.scss
- assets/css/_view_header.scss
- assets/css/app.scss
ticket: https://app.asana.com/0/1200180014510248/1202832778108727/f
> feat(views): sticky navigation headers on scroll

- priv/repo/migrations/20220927170631_add_user_email.exs
ticket: https://app.asana.com/0/1152340551558956/1201189412881312/f
Subsequent PR will write to this new column
> chore: add email to users table

- assets/css/_crowding.scss
---
asana ticket: https://app.asana.com/0/1203014709808707/1195589034084553/f
> feat(css/crowding): Make crowding information colors more accessible

- lib/skate_web/channels/notifications_channel.ex
- test/skate_web/channels/notifications_channel_test.exs
Follows deployment of https://github.com/mbta/skate/pull/1765
> feat: Notification channel cleanup

- lib/skate/settings/db/test_group.ex
- lib/skate/settings/db/test_group_user.ex
- lib/skate/settings/test_group.ex
- test/skate/settings/test_group_test.exs
Asana tickets: [⚙️ Database work for user test groups](https://app.asana.com/0/1200180014510248/1202519045249746/f)
This adds functions to allow for the easy creating and updating of test groups. I paid particular attention to make it possible to update the users associated with a test group in a way that doesn't require the caller to deal with the underlying schema much, so the controller modules for the admin pages will be able to implement functionality to add / remove people without much difficulty. That said, followup ticket may add functionality or slightly modify these utility functions as appropriate.
Currently based on top of the branch with the migration but I'll rebase on master once that's merged.
> Test group DB utils

- config/dev.exs
- lib/skate/settings/test_group.ex
- lib/skate/settings/user.ex
- lib/skate_web/controllers/test_group_controller.ex
- lib/skate_web/router.ex
- lib/skate_web/templates/layout/test_groups.html.eex
- lib/skate_web/templates/test_group/add_user.html.eex
- lib/skate_web/templates/test_group/index.html.eex
- lib/skate_web/templates/test_group/test_group.html.eex
- lib/skate_web/views/test_group_view.ex
- test/skate/settings/test_group_test.exs
- test/skate/settings/user_test.exs
- test/skate_web/controllers/test_group_controller_test.exs
Asana ticket: [⚙️ Admin pages for test groups](https://app.asana.com/0/1200180014510248/1202459690955957/f)
I ended up deviating slightly from the exact acceptance criteria in terms of paths for things and how various requests worked, but it all follows the general spirit. I also realized that removing users from a test group was important so made sure to include that. I'm open in particular to feedback on how the various form flows work (including which things are included in the URL vs. in the body of POST requests).
> Test group admin page

- lib/notifications/notification.ex
- lib/notifications/notification_server.ex
- lib/skate/settings/db/user.ex
- lib/skate/settings/route_tab.ex
- lib/skate/settings/user.ex
- lib/skate/settings/user_settings.ex
- lib/skate_web/channels/notifications_channel.ex
- lib/skate_web/controllers/notification_read_states_controller.ex
- lib/skate_web/controllers/page_controller.ex
- lib/skate_web/controllers/route_tabs_controller.ex
- lib/skate_web/controllers/user_settings_controller.ex
- test/notifications/notification_server_test.exs
- test/notifications/notification_test.exs
- test/skate/settings/route_tab_test.exs
- test/skate/settings/user_settings_test.exs
- test/skate/settings/user_test.exs
- test/skate_web/channels/notifications_channel_test.exs
- test/skate_web/controllers/auth_controller_test.exs
- test/skate_web/controllers/notification_read_states_controller_test.exs
- test/skate_web/controllers/page_controller_test.exs
- test/skate_web/controllers/route_tabs_controller_test.exs
- test/skate_web/controllers/user_settings_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1203331355829273/f
This must be deployed after https://github.com/mbta/skate/pull/1797.
> feat: Query by user id instead of username in all queries

- lib/skate/settings/user.ex
- test/skate/settings/user_test.exs
ticket: https://app.asana.com/0/1152340551558956/1201646081199380/f
> feat(User): only use email for associating user on login

- config/prod.exs
ticket: https://app.asana.com/0/1200180014510248/1203412139193191/f
> fix(Config): Filter out token info from logs

- config/prod.exs
- lib/skate_web/auth_manager.ex
ticket: https://app.asana.com/0/1200180014510248/1203414429135939/f
> fix(AuthManager): Simplify username_from_socket!/1

- assets/css/_map_page.scss
- assets/css/_street_view_button.scss
- assets/css/_vehicle_card.scss
- assets/css/_vehicle_map.scss
- assets/src/components/map.tsx
- assets/src/components/streetViewButton.tsx
- assets/tests/components/map.test.tsx
I'm opening this for technical review, it's very simple, given this is lowfi designs. I opted to avoid styling for now to address technical feedback first, and given this [asana task about tool tip styling](https://app.asana.com/0/1200180014510248/1203473969013271), I figure it's not in scope for this PR?
Some of the main things I'm looking for feedback on are
- BEM names, should the button component be made into something not apart of `m-vehical-map`?
- Should the street view button be it's own function to simplify the test group conditional?
I'm a little stuck writing tests, specifically trying to get the popup to appear. I'll either reach out with questions or have tests up later today hopefully.
---
Asana Ticket: https://app.asana.com/0/1203014709808707/1203329634351683/f
> feat(ts/components/map): add street view link to stops popup

- assets/src/components/shuttleMapPage.tsx
- assets/tests/components/shuttleMapPage.test.tsx
ticket: https://app.asana.com/0/1200180014510248/1203517070532957
resolves issue introduced by https://github.com/mbta/skate/pull/1802, identified in [this](https://mbta.slack.com/archives/C024N3SKX33/p1670533970162099) slack thread
> fix(ShuttleMapPage): Dispatch selectVehicle on vehicle click

- lib/geonames.ex
- test/geonames_test.exs
Asana ticket: [⚙️ Investigate intermittent external API request errors](https://app.asana.com/0/1148853526253437/1203468822722733/f)
This will give us a denominator to determine what portion of the requests are failing.
> feat: log successful geonames requests

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- assets/tests/factories/piece.ts
- assets/tests/factories/run.ts
- assets/tests/factories/trip.ts
- lib/schedule/swing.ex
- test/schedule/swing_test.exs
ticket: https://app.asana.com/0/1148853526253437/1203278600620513/f
> fix: Resolve mid-route swing => deadhead issues in minischedule & swing view

- lib/schedule/data.ex
- lib/schedule/gtfs/stop.ex
- lib/schedule/shape_with_stops.ex
- test/schedule/gtfs/stop_test.exs
- test/schedule_test.exs
- test/skate_web/controllers/shape_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1203520428951853/f
This builds on https://github.com/mbta/skate/pull/1863 to surface route connections for all stops to comply with the data contract specified in https://www.notion.so/mbta-downtown-crossing/Stop-Connections-Implementation-b08dce1922704a95ad892af9e9535d18
> feat(ShapeController): Add stop connections

- assets/css/_map_page.scss
- assets/css/app.scss
- assets/src/components/map.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/searchForm.tsx
- assets/src/components/searchPage.tsx
- assets/src/models/vehicle.ts
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/searchForm.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/map.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/rightPanel.test.tsx
- assets/tests/factories/geoCoordinate.ts
- assets/tests/factories/route.ts
- assets/tests/factories/run.ts
- assets/tests/factories/searchPageState.ts
- assets/tests/factories/searchQuery.ts
- assets/tests/factories/vehicle.ts
- assets/tests/testHelpers/leafletMapWidth.ts
- assets/tests/testHelpers/wrappers.tsx
I split out the autocenterer for this so that the offset for the mapPage can be configured independently of the other maps in skate. 
---
Asana Ticket: https://app.asana.com/0/1203014709808707/1203641439240315/f
> feat(mapPage): selection logic for map page

- assets/src/components/map.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/map.test.tsx
ticket: https://app.asana.com/0/1200180014510248/1203839162225010/f
> feat(Map): Show garage icons for all users

- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
Addresses the failing tests on master from merging https://github.com/mbta/skate/pull/1898 https://github.com/mbta/skate/actions/runs/4018524217/jobs/6904335362
Sorry for the extra review - I should have merged in master!
> fix(test): Address merge conflicts from snapshot tests with garages

- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/hooks/useNearestIntersection.ts
- assets/src/util/fetchResult.ts
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
- assets/tests/hooks/useNearestIntersection.test.ts
Asana ticket: [⚙️🐛 Show Loading state for current location when VPC changes selected vehicle](https://app.asana.com/0/1200180014510248/1203674636294153/f)
I opted to create some fairly generic types for representing various states in the lifecycle of fetching data from an external source. After some initial attempts at making the result more composable (h/t to @firestack for the initial template I started with), I opted for an approach that doesn't result in as many composable / generically useful types, but is at least fairly readable in my opinion as the overall type is a sum type of each of the various possible states.
> Loading state for current intersection in VPC

- lib/realtime/block_waiver.ex
- lib/realtime/server.ex
- test/realtime/block_waiver_test.exs
- test/realtime/server_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204005660133255/f
> feat(Realtime.Server): periodically log ghost stats

- lib/schedule/hastus/trip.ex
- test/schedule/hastus/trip_test.exs
ticket: https://app.asana.com/0/1148853526253437/1203976763779491/f
> fix(Hastus.Trip): expand_through_routed_trips/2 returns trips in order

- lib/skate_web/controllers/route_pattern_controller.ex
- test/skate_web/controllers/route_pattern_controller_test.exs
ticket: https://app.asana.com/0/1148853526253437/1203948983628890/f
New headsign field used in RPC in https://github.com/mbta/skate/pull/1954
> feat(RoutePatternController): Include headsign of representative trip

- assets/src/components/mapPage/routePropertiesCard.tsx
- assets/src/models/routePatternData.ts
- assets/src/schedule.d.ts
- assets/tests/api.test.ts
- assets/tests/components/mapPage/routePropertiesCard.test.tsx
- assets/tests/factories/routePattern.ts
- lib/skate_web/controllers/route_pattern_controller.ex
- test/skate_web/controllers/route_pattern_controller_test.exs
ticket: https://app.asana.com/0/1148853526253437/1203948983628890/f
To deploy after https://github.com/mbta/skate/pull/1955
> feat(RoutePropertiesCard): Display headsign of selected route pattern

- assets/css/_close_button.scss
- assets/css/_route_pill.scss
- assets/css/_route_properties_card.scss
Asana ticket: [⚙️ Better Maps | Design Tweaks to RPC](https://app.asana.com/0/1200180014510248/1203952044422330/f)
Note that the issue from the ticket about centering the close button is apparently no longer present, though I made other improvements to the close button.
> Route Properties Card styling fixes

- assets/css/_demo_mode.scss
- assets/css/app.scss
- assets/src/app.tsx
- assets/src/components/app.tsx
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
I wanted to try implementing the demo mode quickly. I was able to get it working with just this, but wasn't sure how to test it or if there should be a better way to toggle the demo mode than using the test groups feature.
---
Asana Ticket: https://app.asana.com/0/1152340551558956/1203938664653490/f
Related: https://github.com/mbta/skate/pull/1958#issuecomment-1458315134
> init(ts/app/demo-mode): demo mode 

- assets/src/components/map.tsx
- assets/src/components/map/controls/StreetViewSwitch.tsx
- assets/src/components/streetViewButton.tsx
- assets/tests/components/map.test.tsx
- assets/tests/components/streetViewButton.test.tsx
- assets/tests/testHelpers/selectors/components/mapPage/map.ts
I decided to also add this to the street view buttons, just in case we get any other weirdness with street view.
---
Asana Ticket: https://app.asana.com/0/1200180014510248/1204139772279191/f
> feat(ts/components/StreetViewSwitch): add FS event with source data

- assets/package-lock.json
- assets/package.json
- assets/src/components/map.tsx
- assets/tests/setup.tsx
ticket: https://app.asana.com/0/1152340551558956/1203458460363782/f
See examples of what the failing test output will look like [here](https://github.com/mbta/skate/actions/runs/4441085829/jobs/7795718019).
> Fail tests on unexpected console warning / error

- assets/css/map/controls/_street_view_switch.scss
- assets/src/components/map/controls/StreetViewSwitch.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
This removes the `lc` prefix added in https://github.com/mbta/skate/pull/1921#discussion_r1109849003
---
Asana Ticket: https://app.asana.com/0/1152340551558956/1203760641228313/f
Asana Ticket: https://app.asana.com/0/0/1204274354448022/f
> fix(ts/components/StreetViewSwitch): fix lc prefix

- assets/css/_vehicle_properties_card.scss
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1203014709808707/1203760641228313
Asana Ticket: https://app.asana.com/0/1203014709808707/1204265742473560
> fix: update `m-current-location` to `c-current-location`

- assets/css/_search_page.scss
- assets/css/_vehicle_properties_card.scss
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
Asana Ticket: https://app.asana.com/0/0/1204265743414890/f
> fix(css/vehiclePropertiesCard): update vpc css prefix to `c-`

- assets/css/_route_pill.scss
- assets/src/components/routePill.tsx
- assets/tests/components/routePill.test.tsx
I checked on my local dev env that the bus stop card still renders okay and it seemed fine.
---
Asana Ticket: https://app.asana.com/0/0/1204265743414868/f
> fix(css/route-pill): convert `m-route-pill` to `c-` component prefix

- assets/css/_card.scss
- assets/css/_page.scss
- assets/css/_search_results.scss
- assets/css/_settings_page.scss
- assets/css/app.scss
- assets/css/nav/_bottom_nav_mobile.scss
- assets/css/properties_panel/_block_waiver_banner.scss
- assets/css/properties_panel/_stale_data_properties_panel.scss
- assets/src/components/app.tsx
- assets/src/components/card.tsx
- assets/src/components/nav/bottomNavMobile.tsx
- assets/src/components/propertiesPanel/blockWaiverBanner.tsx
- assets/src/components/searchPage.tsx
- assets/src/components/settingsPage.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/searchResults.test.tsx.snap
- assets/tests/components/__snapshots__/settingsPage.test.tsx.snap
- assets/tests/components/card.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/blockWaiverBanner.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/blockWaiverList.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
ticket: https://app.asana.com/0/1152340551558956/1203760641228313/f
5 class renames split by commit.
> refactor: css prefix cleanup chunk

- assets/css/_data_status_banner.scss
- assets/css/_disconnected_modal.scss
- assets/css/_garage_filter.scss
- assets/css/_vehicle_map.scss
- assets/css/properties_panel/_ghost_properties_panel.scss
- assets/src/components/dataStatusBanner.tsx
- assets/src/components/disconnectedModal.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx
- assets/src/hooks/useGarageFilter.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/dataStatusBanner.test.tsx.snap
- assets/tests/components/__snapshots__/disconnectedModal.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/routePicker.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/map.test.tsx
- assets/tests/components/mapMarkers.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap
Part of Asana ticket: [⚙️ Standardize BEM Class Name Prefix](https://app.asana.com/0/1152340551558956/1203760641228313/f)
Just another quick round of changes before I head off to do station research for the rest of the afternoon.
> CSS classname cleanup 2

- assets/css/_ladder.scss
- assets/src/components/ladder.tsx
- assets/tests/components/__snapshots__/ladder.test.tsx.snap
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
https://github.com/mbta/skate/pull/2001#discussion_r1153586312
> fix(ts/components/ladder): convert `.selected` into BEM format

- assets/css/_late_view.scss
- assets/css/_map_page.scss
- assets/css/_minischedule.scss
- assets/css/nav/_left_nav.scss
- assets/src/components/lateView.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/nav/leftNav.tsx
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/lateView.test.tsx.snap
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/nav/leftNav.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
ticket: https://app.asana.com/0/1152340551558956/1203760641228313/f
> CSS Classname cleanup

- assets/css/_crowding.scss
- assets/css/_ladder_page.scss
- assets/css/_old_close_button.scss
- assets/css/_picker_container.scss
- assets/css/_presets.scss
- assets/css/_shuttle_map.scss
- assets/css/_shuttle_picker_container.scss
- assets/css/_swings_view.scss
- assets/css/_view_header.scss
- assets/src/components/oldCloseButton.tsx
- assets/src/components/pickerContainer.tsx
- assets/src/components/presets.tsx
- assets/src/components/propertiesPanel.tsx
- assets/src/components/propertiesPanel/crowdingDiagram.tsx
- assets/src/components/shuttlePickerContainer.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/presets.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttlePicker.test.tsx.snap
- assets/tests/components/propertiesPanel/__snapshots__/crowdingDiagram.test.tsx.snap
Similar to #2006 and #2008 
---
- https://app.asana.com/0/0/1204265743414857
- https://app.asana.com/0/0/1204265743414858
- https://app.asana.com/0/0/1204265743414860
- https://app.asana.com/0/0/1204265742473559
> fix(css-prefix): kf/chunk/4

- assets/.eslintignore
- assets/cypress.config.ts
- assets/cypress/e2e/spec.cy.ts
- assets/cypress/support/commands.ts
- assets/cypress/support/e2e.ts
- assets/cypress/tsconfig.json
- assets/package-lock.json
- assets/package.json
- assets/tsconfig.json
- assets/tsconfig.test.json
Asana ticket: part of [⚙️ Dev Innovation Sprint | Automated visual tests](https://app.asana.com/0/1152340551558956/1203152611716214/f), although this doesn't complete it.
This mainly takes care of Cypress and getting everything related to types and the build to work properly. Additionally, `@testing-library/cypress` is installed (so we can query the document just like in our React Testing Library tests) along with `cypress-visual-regression` for the visual tests themselves.
> Basic setup of Cypress

- assets/css/_drawer_tab.scss
- assets/css/_inactive_notification_modal.scss
- assets/css/_late_view.scss
- assets/css/_map_page.scss
- assets/css/_minischedule.scss
- assets/css/_presets.scss
- assets/css/_route_ladder.scss
- assets/css/_route_picker.scss
- assets/css/_settings_page.scss
- assets/css/_shuttle_picker.scss
- assets/css/_swings_view.scss
- assets/css/_ui_kit.scss
- assets/css/_vehicle_map.scss
- assets/src/components/drawerTab.tsx
- assets/tests/components/__snapshots__/app.test.tsx.snap
- assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
- assets/tests/components/__snapshots__/drawerTab.test.tsx.snap
- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttlePicker.test.tsx.snap
ticket: https://app.asana.com/0/1200180014510248/1204505872151578/f
> feat(SearchMap): Primary styling for search drawer tab

- assets/css/_map_page.scss
- assets/src/components/mapPage.tsx
- assets/src/components/vehicleRouteSummary.tsx
- assets/src/components/visualSeparator.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
> fix(ts/components/mapPage): fix `hr` style cascading into RPC

- assets/src/components/mapPage.tsx
- assets/src/components/propertiesPanel/miniMap.tsx
- assets/src/state/searchPageState.ts
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/propertiesPanel/miniMap.test.tsx
- assets/tests/components/recentSearches.test.tsx
- assets/tests/components/searchForm.test.tsx
- assets/tests/components/searchPage.test.tsx
- assets/tests/components/searchResults.test.tsx
- assets/tests/factories/searchPageState.ts
- assets/tests/state/searchPageState.test.ts
ticket: https://app.asana.com/0/1200180014510248/1204762161648730/f
> feat(MapPage): Back button navigates through selection history

- assets/css/_vehicle_icon.scss
- assets/css/_vehicle_map.scss
- assets/css/_vehicle_route_summary.scss
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/propertiesList.tsx
- assets/src/components/propertiesPanel.tsx
- assets/src/components/routeVariantName.tsx
- assets/src/components/searchResults.tsx
- assets/src/components/vehicleRouteSummary.tsx
- assets/src/models/vehicle.ts
- assets/src/models/vehicleData.ts
- assets/src/models/vehicleStatus.ts
- assets/src/realtime.d.ts
- assets/src/util/dateTime.ts
- assets/tests/components/__snapshots__/searchResults.test.tsx.snap
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/propertiesList.test.tsx
- assets/tests/components/propertiesPanel.test.tsx
- assets/tests/components/routeVariantName.test.tsx
- assets/tests/components/searchResults.test.tsx
- assets/tests/components/vehicleRouteSummary.test.tsx
- assets/tests/models/vehicle.test.ts
- assets/tests/models/vehicleStatus.test.ts
- assets/tests/util/dateTime.test.ts
- lib/realtime/server.ex
- lib/skate_web/channels/vehicle_channel.ex
- test/realtime/server_test.exs
- test/skate_web/channels/vehicle_channel_test.exs
Asana ticket: [⚙️ Better Maps | MVE | Logged out vehicles front end changes](https://app.asana.com/0/1200180014510248/1204807139228453/f)
The individual commits should be fairly self-contained if you prefer reviewing them one-at-a-time.
> Display logged out vehicles

- assets/css/_map_page.scss
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/searchResultsByProperty.tsx
- assets/src/components/oldSearchForm.tsx
- assets/src/components/searchForm.tsx
- assets/src/hooks/useChannel.ts
- assets/src/hooks/useSearchResults.ts
- assets/src/models/searchQuery.ts
- assets/src/state/searchPageState.ts
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/searchResultsByProperty.test.tsx
- assets/tests/components/oldSearchForm.test.tsx
- assets/tests/components/searchForm.test.tsx
- assets/tests/factories/searchQuery.ts
- assets/tests/hooks/useChannel.test.ts
- assets/tests/hooks/useSearchResults.test.ts
- assets/tests/models/searchQuery.test.ts
- assets/tests/state/searchPageState.test.ts
- assets/tests/testHelpers/socketHelpers.ts
- lib/skate_web/channels/vehicles_search_channel.ex
- test/skate_web/channels/vehicles_search_channel_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204956501632025/f
also dependent on https://github.com/mbta/skate/pull/2124
To limit the scope of this PR & more quickly unblock the dependent work, I've broken the following out into separate subtask tickets that will be addressed by separate PRs
* Getting filter functionality to work
* Showing a single "No results" message when no results for any property
> feat(MapPage): Limited search results grouped by property

- assets/src/components/filterAccordion.tsx
- assets/src/components/mapPage/searchResultsByProperty.tsx
- assets/src/components/searchForm.tsx
- assets/src/models/searchQuery.ts
- assets/src/state/searchPageState.ts
- assets/tests/components/__snapshots__/searchForm.test.tsx.snap
- assets/tests/components/mapPage/searchResultsByProperty.test.tsx
- assets/tests/components/searchForm.test.tsx
- assets/tests/factories/searchQuery.ts
- assets/tests/state/searchPageState.test.ts
- assets/tests/testHelpers/selectors/components/searchForm.tsx
ticket: https://app.asana.com/0/1200180014510248/1205130484527139/f
> feat(SearchForm): Filter toggle functionality

- assets/src/api.ts
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/searchResultsByProperty.tsx
- assets/src/hooks/useLocationSearchResults.ts
- assets/src/models/locationSearchResult.ts
- assets/src/models/locationSearchResultData.ts
- assets/src/state/searchPageState.ts
- assets/tests/api.test.ts
- assets/tests/components/mapPage/searchResultsByProperty.test.tsx
- assets/tests/factories/locationSearchResult.ts
- assets/tests/factories/locationSearchResultData.ts
- assets/tests/hooks/useLocationSearchResults.test.ts
- assets/tests/models/locationSearchResultData.test.ts
- assets/tests/state/searchPageState.test.ts
- lib/skate/location_search/aws_location_request.ex
- test/skate/location_search/aws_location_request_test.exs
Asana ticket: [⚙️ Better Maps | Search | Users can search by location](https://app.asana.com/0/1200180014510248/1204971421569464/f)
This is getting big so to keep the review manageable and avoid too many merge conflicts down the line I'm going to open a PR for the first part of the work on this feature. It's still all behind the feature flag so we can merge whenever it's ready. Reviewing commit-by-commit is probably going to be easier than looking at it as one big change.
This PR covers the basic functionality up through making a location the selected entity, but not actually showing the selected location on that map (I have something that basically works for that but it lacks polish). Other things that need to be done are design polish of the location cards and integration with …
> Groundwork for search by location

- lib/realtime/vehicle_or_ghost.ex
- test/realtime/vehicle_or_ghost_test.exs
- test/skate_web/channels/vehicles_search_channel_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204956501632025/f
> fix(VehicleOrGhost): Return matching search vehicles in descending logon time

- assets/css/_map_page.scss
- assets/css/_street_view_button.scss
- assets/src/api.ts
- assets/src/components/groupedAutocomplete.tsx
- assets/src/components/highlightedMatch.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/searchForm.tsx
- assets/src/state/searchPageState.ts
- assets/tests/components/groupedAutocomplete.test.tsx
- assets/tests/components/highlightedMatch.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/searchForm.test.tsx
- lib/realtime/vehicle_or_ghost.ex
- test/realtime/vehicle_or_ghost_test.exs
Asana ticket: [⚙️ Better Maps | Search | Users can search by location](https://app.asana.com/0/1200180014510248/1204971421569464/f)
This includes at least a first pass at writing some tests, but because there are changes sprinkled across various components with prop drilling between them I'm going to do a further pass of looking through and making sure we have as much coverage as possible. That said the code as-is should be ready for review (and suggestions for specific tests to add are welcome).
> Autocomplete for location search

- assets/src/hooks/useVehicles.ts
- assets/tests/hooks/useVehicles.test.ts
Asana Ticket: https://app.asana.com/0/1200180014510248/1204956277851229/f
> cleanup(ts/hooks/useVehicles): turn Superstruct problems in `useVehicles` into errors

- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
Asana Ticket: https://app.asana.com/0/1200180014510248/1205062422795409
> feat(ts/components/VehiclePropertiesPanel): fire FS event when VPP Tab is clicked

- assets/src/components/map.tsx
- assets/src/components/map/markers/stopMarker.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/stopCard.tsx
- assets/tests/components/mapMarkers.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/stopCard.test.tsx
- assets/tests/factories/stop.ts
ticket: https://app.asana.com/0/1200180014510248/1204906972532767/f
> feat: Show all nearby stops

- assets/src/components/map.tsx
- assets/src/components/map/markers/stopMarker.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/stopCard.tsx
- assets/tests/components/mapMarkers.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/stopCard.test.tsx
- assets/tests/factories/stop.ts
Reverts mbta/skate#2201 in case needed for hotfix
> Revert "feat: Show all nearby stops"

- assets/src/components/map.tsx
- assets/src/components/map/markers/stopMarker.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/stopCard.tsx
- assets/tests/components/mapMarkers.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/stopCard.test.tsx
- assets/tests/factories/stop.ts
Reverts mbta/skate#2207
Restore showing nearby stops - to be deployed after the weekend
> Revert "Revert "feat: Show all nearby stops""

- lib/api/stream.ex
- test/api/stream_test.exs
I'm not sold on the testing method, and would like input on if I should consider separating it out into it's own test.
The annoying part about that is it'd basically look the same as the test does now.
---
Asana Ticket: https://app.asana.com/0/1148853526253420/1205367064394200/f
> fix(ex/Api.Stream): handle unknown message types

- assets/css/_vehicle_map.scss
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/routeVariantName.tsx
- assets/src/components/scheduleAdherence.tsx
- assets/src/components/vehicleRouteSummary.tsx
- assets/src/helpers/vehicleLabel.ts
- assets/src/models/vehicle.ts
- assets/src/models/vehicleData.ts
- assets/src/models/vehicleStatus.ts
- assets/src/realtime.d.ts
- assets/tests/components/__snapshots__/vehicleIcon.test.tsx.snap
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/vehicleIcon.test.tsx
- assets/tests/components/vehicleRouteSummary.test.tsx
- assets/tests/factories/vehicle.ts
- assets/tests/factories/vehicle_data.ts
- assets/tests/helpers/vehicleLabel.test.ts
- assets/tests/models/vehicleData.test.ts
- assets/tests/models/vehicleStatus.test.ts
- lib/schedule/gtfs/timepoint.ex
- test/schedule/data_test.exs
Asana ticket: [⚙️ Better Maps | Show pull-backs](https://app.asana.com/0/1200180014510248/1204946801340572/f)
For now I'm basing this off of the other pull-backs branch, will change the base to `master` once that one is merged.
> Pullback layer VPC changes

- upload_assets.sh
Asana ticket: [⚙️ Fix intermittent deploy failures on "Upload static assets to S3" step](https://app.asana.com/0/1148853526253420/1205398036394618/f)
> build: improve means of extracting static assets from Docker image

- lib/skate/application.ex
- lib/skate/remove_users_without_email.ex
- lib/skate/settings/user.ex
- test/skate/remove_users_without_email_test.exs
- test/skate/settings/user_test.exs
- test/support/factory.ex
Asana ticket: [⚙️ Remove user records without email address](https://app.asana.com/0/1148853526253420/1203392965628668/f)
This is just a `cherry-pick` of the changes from #2025 after resolving some merge conflicts.
> cleanup(ex/skate/database): remove users without email

- assets/src/components/mapPage.tsx
- assets/src/userInTestGroup.ts
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/mapPage.test.tsx
Merges the LocationSearch test group into the map-beta test group
---
Asana Ticket: [⚙️ Merge search-location with map-beta](https://app.asana.com/0/1148853526253420/1205466712902305/f)
> feat(ts/components/mapPage): remove Location Search test group

- assets/css/app.scss
- assets/css/map/markers/_user_location_marker.scss
- assets/src/components/map/markers/userLocationMarker.tsx
- assets/src/hooks/useGeolocation.ts
- assets/stories/skate-components/map/markers/userLocationMarker.stories.tsx
- assets/tests/components/map/markers/userLocationMarker.test.tsx
- assets/tests/factories/geolocationCoordinates.ts
- assets/tests/hooks/useGeolocation.test.ts
- assets/tests/testHelpers/mockHelpers.ts
Asana ticket: [Implement location dot](https://app.asana.com/0/1148853526253420/1205411312261325/f)
> User location dot

- assets/src/components/map.tsx
- assets/src/components/map/controls/userLocationControl.tsx
- assets/src/components/map/follower.tsx
- assets/src/components/map/markers/userLocationMarker.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/shuttleMapPage.tsx
- assets/stories/skate-components/shuttleMapPage.stories.tsx
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/shuttleMapPage.test.tsx
- assets/tests/testHelpers/selectors/components/map/controls/currentLocationControl.ts
- assets/tests/testHelpers/selectors/components/map/markers/currentLocationMarker.ts
---
- https://app.asana.com/0/0/1205336270685222
> feat(ts/components/ShuttleMapPage): add `UserLocationControl` and `UserLocationMarker`

- lib/skate_web/router.ex
Asana Ticket: https://app.asana.com/0/1148853526253420/1205492553568017/f
> doc:feat(ex/router): document reason that we're keeping the SSL plug

- assets/src/components/map/controls/layersControl.tsx
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/searchResults.tsx
- assets/src/userInTestGroup.ts
- assets/tests/components/map/controls/layersControl.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/searchResults.test.tsx
- lib/skate_web/channels/vehicle_channel.ex
- lib/skate_web/channels/vehicles_channel.ex
- lib/skate_web/channels/vehicles_search_channel.ex
- test/skate_web/channels/vehicle_channel_test.exs
- test/skate_web/channels/vehicles_channel_test.exs
Asana ticket: [⚙️ Roll logged out buses and pullbacks to map-beta test group](https://app.asana.com/0/1148853526253420/1205615331791882/f)
> Merge pull-back layer and logged off vehicle search feature flags into map beta

- assets/.storybook/argsUpdater.ts
- assets/.storybook/inMapDecorator.tsx
- assets/css/map/controls/_layers_control.scss
- assets/src/components/map/controls/customControl.tsx
- assets/src/components/map/controls/layersControl.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/searchPage.tsx
- assets/src/components/shuttleMapPage.tsx
- assets/stories/skate-components/map/controls/layersControl.stories.tsx
- assets/stories/skate-components/map/controls/userLocationControl.stories.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/map/controls/layersControl.test.tsx
Asana Ticket: [⚙️ 🐛 Fix radio buttons in map layers menu to no longer look "stretched"](https://app.asana.com/0/0/1205630737578629/f)
> feat(storybook): add `LayersControl` stories

- .envrc.template
- assets/package-lock.json
- assets/package.json
- assets/src/app.tsx
- assets/src/helpers/sentryInit.ts
- assets/src/skate.d.ts
- assets/tests/helpers/sentryInit.test.ts
- config/config.exs
- lib/skate/application.ex
- lib/skate_web/controllers/page_controller.ex
- lib/skate_web/templates/layout/_sentry.html.eex
- test/skate_web/controllers/page_controller_test.exs
Asana ticket: [⚙️ Integrate Fullstory and Sentry](https://app.asana.com/0/1148853526253420/1205560495149255/f)
I'll do another followup to remove the old `window.sentry` stuff.
> feat: Sentry - FullStory integration

- assets/css/_vehicle_map.scss
- assets/css/app.scss
- assets/css/map/controls/_recenter_control.scss
- assets/src/components/map.tsx
- assets/src/components/map/controls/recenterControl.tsx
- assets/src/components/map/follower.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/shuttleMapPage.tsx
- assets/stories/skate-components/map/controls/recenterControl.stories.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/__snapshots__/searchPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/map.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
- assets/tests/components/shuttleMapPage.test.tsx
- assets/tests/testHelpers/selectors/components/map/controls/recenterControl.ts
---
- https://app.asana.com/0/0/1205709399517280
> feat(ts/components/RecenterControl): localize `RecenterControl` state and styling

- assets/src/components/map/follower.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
Asana Ticket: [⚙️ [Prototype] When clicking on RPC from VPC, maintain zoom level](https://app.asana.com/0/1148853526253420/1205511565935708/f)
> [PROTOTYPE] feat(ts/mapPage): respect user's current zoom in follower and initially disable follower on route _selection_

- assets/css/_settings_page.scss
- assets/src/components/settingsPage.tsx
- assets/tests/components/__snapshots__/settingsPage.test.tsx.snap
---
- https://app.asana.com/0/0/1205651022494294
> style: Update text and styling on settings page

- lib/report.ex
- lib/report/authentication_timeout.ex
- lib/report/max_connections.ex
- lib/skate/repo.ex
- test/report_test.exs
Asana ticket: related to [⚙️ Investigate various DB connection issue leads](https://app.asana.com/0/1205385723132845/1205865005764892/f)
In addition to the token-related logging, this gives us a couple of reports for `max_connections` and `authentication_timeout` as a bonus.
> DB connection details logging

- assets/css/_directions_button.scss
- assets/css/app.scss
- assets/css/properties_panel/_vehicle_properties_panel.scss
- assets/src/components/directionsButton.tsx
- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana ticket: [⚙️ Switch Street View button in VPC to Get directions to bus](https://app.asana.com/0/1148853526253420/1205762196567449/f)
Note that per the ticket this doesn't need to be gated behind the test group.
> Replace street view with directions in VPC

- assets/src/components/app.tsx
- assets/src/components/propertiesPanel.tsx
- assets/src/components/propertiesPanel/miniMap.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/tests/components/propertiesPanel.test.tsx
- assets/tests/components/propertiesPanel/miniMap.test.tsx
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
Asana ticket: [⚙️ Don't show open maps button in VPP on Search Maps](https://app.asana.com/0/1148853526253420/1205718173592000/f)
> feat: hide open map button when already on map page

- assets/css/app.scss
- assets/css/bootstrap.scss
- assets/css/bootstrap/_variable_overrides.scss
---
Asana Ticket: https://app.asana.com/0/1148853526253420/1205836854144692/f
> feat:refactor(css/bootstrap): factor bootstrap imports into own file

- assets/css/_map_page.scss
- assets/src/components/mapPage.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
Asana Ticket: https://app.asana.com/0/1148853526253420/1205703270277847/f
> feat(frontend/MapPage):  fit drawer on screen for all viewport sizes

- assets/src/components/map/follower.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/components/stopCard.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
---
- https://app.asana.com/0/0/1205730670134122
- https://app.asana.com/0/0/1204330988641900
> fix: Center selected entity correctly based on whether the drawer is open

- lib/skate/settings/db/test_group.ex
- lib/skate/settings/test_group.ex
- lib/skate_web/controllers/test_group_controller.ex
- lib/skate_web/router.ex
- lib/skate_web/templates/layout/barebones.html.eex
- lib/skate_web/templates/test_group/index.html.eex
- lib/skate_web/templates/test_group/test_group.html.eex
- lib/skate_web/views/error_helpers.ex
- test/skate/settings/test_group_test.exs
- test/skate/settings/user_test.exs
- test/skate_web/channels/vehicle_channel_test.exs
- test/skate_web/channels/vehicles_channel_test.exs
- test/skate_web/controllers/page_controller_test.exs
- test/skate_web/controllers/test_group_controller_test.exs
---
- https://app.asana.com/0/0/1203373689404088
> fix: Improve error handling on the test-groups page

- assets/src/components/mapPage.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/testHelpers/mockHelpers.ts
---
- https://app.asana.com/0/0/1205703270277843
> feat: Don't open the drawer on mobile when a search result is visible

- .github/workflows/chromatic.yml
Asana Ticket: [⚙️ Integrating Chromatic with CI](https://app.asana.com/0/1148853526253420/1205631004420370/f)
> feat(gh/actions/chromatic): add chromatic CI

- README.md
No Ticket
I'd like critical feedback on the second commit if you have any!
> doc:fix(README): update directions on deploying tags to production

- lib/skate_web.ex
- lib/skate_web/auth_manager/error_handler.ex
- lib/skate_web/controllers/auth_controller.ex
- lib/skate_web/controllers/test_group_controller.ex
- lib/skate_web/endpoint.ex
- lib/skate_web/ensure_admin_group.ex
- lib/skate_web/ensure_environment_access.ex
- lib/skate_web/templates/admin/index.html.eex
- lib/skate_web/templates/report/index.html.eex
- lib/skate_web/templates/test_group/add_user.html.eex
- lib/skate_web/templates/test_group/index.html.eex
- lib/skate_web/templates/test_group/test_group.html.eex
- test/api/stream_test.exs
- test/skate_web/controllers/admin_controller_test.exs
- test/skate_web/controllers/health_controller_test.exs
- test/skate_web/controllers/report_controller_test.exs
- test/skate_web/controllers/stop_controller_test.exs
- test/skate_web/controllers/test_group_controller_test.exs
- test/skate_web/controllers/unauthorized_controller_test.exs
- test/support/conn_case.ex
---
- https://app.asana.com/0/0/1206113388125708
> feat(ex/phoenix): Use verified routes

- lib/skate_web/components/core_components.ex
- lib/skate_web/components/layouts/app.html.heex
- lib/skate_web/controllers/admin_controller.ex
- lib/skate_web/controllers/report_controller.ex
- lib/skate_web/controllers/test_group_controller.ex
- lib/skate_web/controllers/test_group_html/index.html.heex
- lib/skate_web/controllers/unauthorized_controller.ex
- test/skate_web/controllers/page_controller_test.exs
While reviewing #2323 there were a few updates I wanted made, but it was a little outside the scope of #2323. 
This converts us to using more components in phoenix as well as follows conventions for `render`ing HTML.
> refactor(ex/skate_web): misc improvments using Phoenix 1.7

- assets/css/_dropdown.scss
- assets/css/app.scss
- assets/css/bootstrap.scss
- assets/src/components/map/dropdown.tsx
- assets/src/components/mapMarkers.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/userInTestGroup.ts
- assets/stories/skate-components/map/dropdown.stories.tsx
- assets/tests/components/map.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
---
- https://app.asana.com/0/0/1206038961362412
> feat: Add dropdown when right-clicking on a vehicle marker

- assets/css/_nav.scss
- assets/src/components/nav.tsx
- assets/tests/components/nav.test.tsx
Asana ticket: [⚙️ Finish up layout/breakpoint changes](https://app.asana.com/0/1148853526253420/1206526459943482/f)
> Breakpoint simplification

- lib/skate_web/controllers/auth_controller.ex
- lib/skate_web/router.ex
- test/skate_web/controllers/auth_controller_test.exs
- test/support/factory.ex
Depends on: #2358 
References:
- https://github.com/mbta/arrow/pull/950/files#diff-94eca8259513c68e11b1b5d47d9c571dd7c0d8233a813ca95626507bffd65399R7-R75
- https://github.com/mbta/my_charlie/blob/main/lib/my_charlie_web/router.ex#L159-L163
- https://github.com/mbta/my_charlie/blob/main/lib/my_charlie_web/controllers/auth_controller.ex#L112-L154
---
Asana Ticket: https://app.asana.com/0/1148853526253420/1206509056963769/f
> feat: add logout for keycloak

- assets/src/userEmailAddress.ts
- assets/tests/userEmailAddress.test.ts
- lib/skate_web/controllers/page_controller.ex
- lib/skate_web/controllers/page_html/index.html.heex
- test/skate_web/controllers/page_controller_test.exs
---
- https://app.asana.com/0/0/1206526459943539
> feat: Convey logged-in email address to the frontend

- assets/package-lock.json
This just updates a few npm deps that have security warnings.
> Ad-hoc update of some npm deps

- assets/css/_circle_button.scss
- assets/css/_user_avatar.scss
- assets/css/app.scss
- assets/src/components/circleButton.tsx
- assets/src/components/userAvatar.tsx
- assets/stories/skate-components/circleButton.stories.tsx
- assets/stories/skate-components/userAvatar.stories.tsx
- assets/tests/components/circleButton.test.tsx
- assets/tests/components/circleIcon.test.tsx
- assets/tests/components/userAvatar.test.tsx
Asana ticket: [⚙️ Create component for email address initial icon](https://app.asana.com/0/1148853526253420/1206526457565579/f)
> CircleButton and UserAvatar components

- assets/css/_logged_in_as.scss
- assets/css/app.scss
- assets/src/components/loggedInAs.tsx
- assets/stories/skate-components/identity/loggedInAs.stories.tsx
---
- https://app.asana.com/0/0/1206526459943484
> feat: Add <LoggedInAs /> component

- assets/css/bootstrap.scss
- assets/src/components/nav/navMenu.tsx
- assets/src/helpers/bsIcons.tsx
- assets/stories/skate-components/navMenu.stories.tsx
- assets/tests/components/nav/navMenu.test.tsx
---
- https://app.asana.com/0/0/1206526459943486
> feat(ts/components/navMenu): upgrade mobile nav to use bootstrap components

- assets/src/components/loggedInAs.tsx
- assets/src/components/nav/navMenu.tsx
- assets/tests/components/nav/navMenu.test.tsx
Supersedes: #2384 
---
- https://app.asana.com/0/0/1206526459943489
>  feat(ts/compmonents/navMenu): add `<LoggedInAs/>` to Mobile `<NavMenu/>`

- assets/css/bootstrap.scss
- assets/css/bootstrap/_polyfills.scss
- assets/css/nav/_top_nav.scss
- assets/src/components/nav/topNav.tsx
- assets/tests/components/nav/topNav.test.tsx
Asana ticket: [⚙️ Add log out button to desktop top nav](https://app.asana.com/0/1148853526253420/1206526459943495/f)
> Desktop logout link

- lib/skate_web/controllers/auth_controller.ex
Per Paul, the client application can decide how long to log the user in if using its own token, so we're going to customize it a bit to make the token valid for an hour.
> feat: use custom validity period for Guardian token

- assets/css/_diversion_page.scss
- assets/css/_modal.scss
- assets/css/app.scss
- assets/css/bootstrap.scss
- assets/css/detours/_detour_modal.scss
- assets/src/components/detours/detourDropdown.tsx
- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/detourModal.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/detours/diversionPanel.tsx
- assets/src/components/dummyDetourPage.tsx
- assets/src/components/map.tsx
- assets/src/components/mapPage.tsx
- assets/src/components/mapPage/mapDisplay.tsx
- assets/src/detour.ts
- assets/stories/skate-components/detours/diversionPage.stories.tsx
- assets/stories/skate-components/detours/diversionPanel.stories.tsx
- assets/tests/components/detours/detourMap.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/factories/latLngLiteralFactory.ts
---
- https://app.asana.com/0/0/1206260856814696
> feat: Add a detour-editing modal when a user selects that option on the dropdown menu

- config/config.exs
- lib/skate_web/controllers/redirect_controller.ex
- lib/skate_web/router.ex
---
- https://app.asana.com/0/0/1206673444071866
>  feat: add user-guide vanity URL

- lib/skate_web/controllers/detour_missed_stops_controller.ex
- lib/skate_web/router.ex
- test/skate_web/controllers/detour_missed_stops_controller_test.exs
- test/support/factory.ex
Asana ticket: [Missed stops API endpoint](https://app.asana.com/0/1148853526253420/1206680523793247/f)
> feat: missed stops endpoint

- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.tsx
- assets/tests/components/detours/detourMap.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/hooks/useDetour.test.ts
---
- https://app.asana.com/0/0/1206660467722363
- Parent Task: https://app.asana.com/0/home/1205718271156544/1206412398464686
> feat: allow undoing start and end points

- assets/css/nav/_left_nav.scss
- assets/src/components/nav/leftNav.tsx
- assets/tests/components/nav.test.tsx
- assets/tests/components/nav/leftNav.test.tsx
Not a huge deal either way, but this has been bugging me a bit.
https://github.com/mbta/skate/assets/912020/de61b5f6-edb1-4f3d-905d-50540407cc90
https://github.com/mbta/skate/assets/912020/06788c3e-ecf0-4e8c-820a-df667d6af285
> feat: Animate expanding and collapsing the left nav on Desktop

- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.tsx
- assets/tests/components/detours/detourMap.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/hooks/useDetour.test.ts
---
- https://app.asana.com/0/0/1206660467722364
- Parent Ticket: https://app.asana.com/0/home/1205718271156544/1206412398464686
> feat: Add ability to clear entire detour in one go

- assets/css/_diversion_page.scss
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/detours/diversionPanel.tsx
- assets/tests/components/detours/diversionPage.test.tsx
This adds the finish button and sets up a stable area for the button "footer" and scroll area. This does not add tests or any functionality yet, because that depends on the creation of the share detours panel which requires the #2421 refactor.
---
- https://app.asana.com/0/0/1206694541310031
>  feat(ts/ui): add finish detour button 

- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/hooks/useDetour.test.ts
No ticket, just followup on #2419 based on some feedback and pairing with @firestack.
> Remove instantPromise from tests

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
https://github.com/mbta/skate/assets/912020/819e8756-37d0-4685-91aa-35a544a7a381
---
- https://app.asana.com/0/0/1206698934433015
- https://app.asana.com/0/0/1206423114607620
> feat: Highlight and widen clickable area on original route shape for detour map

- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.ts
- assets/tests/hooks/useDetour.test.ts
---
- https://app.asana.com/0/0/1206710026837334
>  feat(ts/hooks/useDetour): move detour finished state into useDetour hook

- lib/skate/detours/route_segments.ex
- lib/skate_web/controllers/detours_controller.ex
- test/skate_web/controllers/detours_controller_test.exs
---
- https://app.asana.com/0/0/1206709678202207
> feat: Add route segment info to /finished_detour endpoint

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.ts
- assets/tests/components/detours/detourMap.test.tsx
- assets/tests/hooks/useDetour.test.ts
---
- https://app.asana.com/0/0/1206733203010774
> feat: Draw original and diverted route segments on the map

- assets/stories/skate-components/detours/detourMap.stories.tsx
In the wonderful world of atomic design, I think this would be a "page"?
---
- https://app.asana.com/0/0/1206741046767440
> feat(storybook): Add stories for DetourMap

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
---
- https://app.asana.com/0/0/1206741046767439
> feat: Update detour-shape weight and color to match hi-fi design

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
---
- https://app.asana.com/0/0/1206759503438417
> feat: Style cursor for placing the end-point of a detour

- assets/src/components/detours/detourMap.tsx
- assets/src/helpers/bsIcons.tsx
- assets/tests/components/map/controls/mapButton.test.tsx
Asana ticket: [Implement undo and clear buttons](https://app.asana.com/0/1148853526253420/1206753759080075/f)
Also adding tests for the button functionality itself from #2469.
> feat: hifi undo / clear buttons

- assets/css/color/_tokens_2024.scss
- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
- assets/stories/skate-components/detours/markers/endIcon.stories.tsx
- assets/stories/skate-components/detours/markers/startIcon.stories.tsx
- assets/stories/skate-components/detours/markers/waypointIcon.stories.tsx
---
- https://app.asana.com/0/0/1206759503438415
> feat: Update start, end, and way- point markers on the detour map

- assets/css/detours/_detour_map.scss
[Review in Chromatic](https://www.chromatic.com/review?appId=65047eaabeb50e4310dc692b&number=9&type=unlinked)
> fix: Fix detour shape color

- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.ts
- assets/src/models/detour.ts
- assets/src/models/finishedDetour.ts
- assets/src/models/stopData.ts
- assets/tests/api.test.ts
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/factories/finishedDetourFactory.ts
- assets/tests/hooks/useDetour.test.ts
- lib/skate/detours/missed_stops.ex
- lib/skate_web/controllers/detours_controller.ex
- test/skate/detours/missed_stops_test.exs
- test/skate_web/controllers/detours_controller_test.exs
This is a little on the larger size. I can break this up into separate frontend and backend PR's if that'd help but this should be reviewable by commit to help with that.
---
- https://app.asana.com/0/0/1206694541310034
> feat: add connection points to finished detour panel

- assets/css/_z_indexes.scss
- assets/css/detours/_detour_modal.scss
- assets/package-lock.json
- assets/package.json
- assets/src/components/detours/detourModal.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/mapPage.test.tsx
Asana ticket: [⚙️ Have the detour modal grab focus when it renders](https://app.asana.com/0/1148853526253420/1206648035312400/f)
> feat: make detour modal receive focus on opening

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.ts
- assets/stories/skate-components/detours/detourMap.stories.tsx
- assets/tests/hooks/useDetour.test.ts
Cursor in action:
---
- https://app.asana.com/0/0/1206759503438416
> feat: Add cursor for placing a waypoint

- assets/src/components/detours/detourMap.tsx
- assets/src/components/map/controls/layersControl.tsx
- assets/src/state/mapLayersState.ts
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/detours/detourMap.test.tsx
Asana ticket: [⚙️ 🚧 User can change map tile layers on Detour Map](https://app.asana.com/0/1148853526253420/1206436289420242/f)
> feat: detour map layers control

- assets/src/components/detours/detourMap.tsx
- assets/src/components/map/markers/stopMarker.tsx
- assets/src/hooks/useDetour.ts
- assets/stories/skate-components/detours/detourMap.stories.tsx
- assets/tests/components/detours/detourMap.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/hooks/useDetour.test.ts
- assets/tests/testHelpers/selectors/components/map/markers/stopIcon.ts
---
- https://app.asana.com/0/0/1206770478865875
> feat: Draw missed stops on the detour map

- lib/skate/detours/route_segments.ex
- lib/skate_web/controllers/detours_controller.ex
- test/skate/detours/route_segments_test.exs
- test/skate_web/controllers/detours_controller_test.exs
---
- https://app.asana.com/0/0/1206823255274991
> feat: Update route segments to connect closer to given start and end points

- assets/css/_diversion_page.scss
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/detours/diversionPanel.tsx
- assets/tests/components/detours/diversionPage.test.tsx
[Asana task](https://app.asana.com/0/1205385723132845/1206754739214649)
Just a lil phrase addition, to round off the turn-by-turn directions.
> feat: (tiny) Add "return to route" message after turn-by-turn directions

- config/runtime.exs
- lib/skate/open_route_service_api/client.ex
---
- https://app.asana.com/0/0/1206910009181796
> feat: Add more flexible OpenRouteService configuration to support self-hosting

- .github/workflows/deploy-prod-ecs.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
Asana Ticket: None
> feat(gh/ci/deploy-prod): run `deploy-to-prod` when new releases are made

- .github/workflows/deploy-prod-ecs.yml
One tiny change because I got the `type` event wrong
> fix: set deploy to only happen on full releases (not pre-releases)

- assets/tests/components/app.test.tsx
Misc thing I found while working on #2534
> cleanup:test(ts/components/app): remove commented `<App/>` component

- README.md
- lib/mix/tasks/deploy.prod.ex
---
- https://app.asana.com/0/0/1206972823536564
> feat: Add deploy script and updated deploy instructions to the README

- config/config.exs
- lib/skate_web/controllers/redirect_controller.ex
- lib/skate_web/router.ex
---
- https://app.asana.com/0/0/1205569412502727
> feat: Add training vanity URL

- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/detours/diversionPage.test.tsx
---
- https://app.asana.com/0/0/1206801929217813
> feat: Change "Detour is not editable" to "Detour shape is not editable"

- assets/css/detours/_detour_map.scss
- assets/src/components/detours/detourMap.tsx
---
- https://app.asana.com/0/0/1207103959249126
> fix: Drop waypoints in the right place

- asana.yml
I don't really have a way to experiment or test this till this file exists on main, I could strip this back so I can do more testing in a PR first.
This workflow is used on a few of our projects: https://github.com/search?q=org%3Ambta+asana.yml&type=code
---
Asana Ticket: https://app.asana.com/0/0/1207185409019452/f
> feat: add mbta asana workflow

- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1207103683979738/f
Asana Ticket: https://app.asana.com/0/1148853526253420/1207152763000093/f
---
I opened this as a test for [⚙️ Integrate Github and Asana](https://app.asana.com/0/1148853526253420/1207152763000093/f)
This is ready for review, but I'm waiting on #2565 and fixing Asana access before merging this
> feat(ts/diversionPage): change copy details heading format

- assets/src/components/mapPage/vehiclePropertiesCard.tsx
- assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx
- assets/src/hooks/useDetour.ts
- assets/src/hooks/useNearestIntersection.ts
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/components/mapPage.test.tsx
- assets/tests/components/mapPage/mapDisplay.test.tsx
- assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx
- assets/tests/components/propertiesPanel.test.tsx
- assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx
- assets/tests/components/settingsPage.test.tsx
- assets/tests/hooks/useDetour.test.ts
- assets/tests/hooks/useNearestIntersection.test.ts
Related:
- #2533 
- #2534 
- #2556 
---
Asana Ticket: https://app.asana.com/0/1205526445275136/1207210827029012/f
Asana Ticket: https://app.asana.com/0/1205526445275136/1207210827029005/f
> refactor(ts/hooks): convert `useNearestIntersection` to `useApiCall`

- assets/src/components/app.tsx
This is in preparation for some additional changes to add a minimalist page that doesn't have a nav page
Asana Ticket: https://app.asana.com/0/0/1207224914942644
> refactor: Make `<Nav />` an element in `<Routes />`

- assets/src/hooks/useNearestIntersection.ts
I think `jj` caused this in that I'm re-learning some merge habits with 3+ side merges
> fix: remove emoji in comment

- assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
- assets/tests/components/ladderPage.test.tsx
New test to check where alerts appear on Ladder Page, inspired by Josh's request [here](https://github.com/mbta/skate/pull/2583#pullrequestreview-2041766787)
> chore: New test to verify where alerts appear on ladder page

- assets/tests/components/modal.test.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207237357903286
> chore: Pressing escape closes the inputModal

- .github/workflows/ci.yml
Small cleanup for readability.
> cleanup(gh/actions/ci): use `--prefix=assets` instead of `pushd` & `popd`

- config/config.exs
- config/runtime.exs
- lib/skate_web/components/core_components.ex
- lib/skate_web/components/layouts/barebones.html.heex
- test/skate_web/controllers/admin_controller_test.exs
Asana Ticket: https://app.asana.com/0/1148853526253420/1206593159272689/f
> feat: Add a banner on the admin pages indicating what environment you're in

- assets/src/components/detours/detourRouteSelectionPanel.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207363543546281/f
> feat: Have RoutePropertiesCard on DetourRouteSelectionPanel open to "variants"

- assets/css/_route_ladder.scss
- assets/src/components/routeLadder.tsx
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207260183650049
Just adds the dropdown. Will need to be hooked up to the detour workflow once it's done.
> feat: New route ladder action dropdown

- assets/css/_route_ladder.scss
- assets/src/components/routeLadder.tsx
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
Agh sorry, I wasn't paying attention and merged into a PR still in review.
> Revert "feat: New route ladder action dropdown"

- assets/stories/skate-components/detours/diversionPanel.stories.tsx
> storybook: Remove `Change route or direction` button from `<DiversionPanel />` stories

- assets/src/components/detours/detourRouteSelectionPanel.tsx
- assets/stories/skate-components/detours/detourRouteSelectionPanel.stories.tsx
Asana Ticket: https://app.asana.com/0/0/1207428503805261/f
> feat(ts/detours/detourRouteSelectionPanel): add events to panel

- assets/src/components/detours/detourRouteSelectionPanel.tsx
This enables test code such as 
```ts
await userEvent.selectOptions(
screen.getByRole("combobox", { name: "Choose route" }),
route2.name
)
```
> fix(ts/components/detourSelect): Allow selecting form select via role

- assets/src/components/routeLadder.tsx
- assets/src/userInTestGroup.ts
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1207498509118781/f
> feat: Gate route ladder detour dropdown behind a new test group

- assets/src/helpers/bsIcons.tsx
Small fraction of the combobox work. New icon was needed.
> feat: New icon for combobox dropdown button

- assets/src/components/detours/detourRouteSelectionPanel.tsx
- assets/src/components/groupedAutocomplete.tsx
New generic component to handle ungrouped selectable options in the "autocomplete" dropdown. It's not exactly an autocomplete anymore, but I think the naming is still close enough to what it does.
> feat: New "autocomplete" component for the combobox dropdown

- assets/css/bootstrap.scss
- assets/css/bootstrap/_map_overrides.scss
- assets/src/components/detours/detourRouteSelectionPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/hooks/useDetour.ts
- assets/src/models/createDetourMachine.ts
- assets/src/userInTestGroup.ts
- assets/stories/skate-components/detours/detourRouteSelectionPanel.stories.tsx
- assets/tests/components/detours/diversionPage.test.tsx
Depends On:
- #2645
- #2648 
- #2649 
- #2650 
- #2651 
Asana Ticket: https://app.asana.com/0/1203014709808707/1207372095414476/f
> feat: add route selection panel

- assets/src/components/detours/detourMap.tsx
- assets/src/components/detours/detourRouteSelectionPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/ladderPage.tsx
- assets/src/components/routeLadder.tsx
- assets/src/components/routeLadders.tsx
- assets/src/models/detour.ts
- assets/stories/skate-components/detours/detourRouteSelectionPanel.stories.tsx
- assets/tests/components/ladderPage.test.tsx
https://github.com/mbta/skate/assets/912020/89b2a491-7030-43dc-ae4e-7d331e8b0a1c
Depends on:
- https://github.com/mbta/skate/pull/2645
- https://github.com/mbta/skate/pull/2652
Asana Ticket: https://app.asana.com/0/1205385723132845/1207260183650060/f
> feat: Open the detour modal from a route ladder

- assets/src/components/detours/detourRouteSelectionPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/models/createDetourMachine.ts
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1203014709808707/1207402376744565/f 
Superceeds #2632
> feat: ⚙️🚧 Clicking "start" with no route selected shows an error

- lib/skate/detours/missed_stops.ex
- test/skate/detours/missed_stops_test.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1207328357694128/f
Depends On:
- https://github.com/mbta/skate/pull/2664
> fix: Missed stops bug when stop is close to start point

- lib/realtime/trip_modification.ex
- test/realtime/trip_modification_test.exs
Asana Ticket: https://app.asana.com/0/1205718271156548/1207635746210190/f
> feat: Add shape_id for the original route shape to GTFS-TripModification message

- assets/src/components/detours/diversionPanel.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207582955025090/f
> feat: Change 'Finish Detour' to 'Review Detour'

- assets/src/hooks/useDetour.ts
- assets/src/models/createDetourMachine.ts
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/0/1207659713660474/f
> refactor: Move fetchFinishedDetour into the state machine

- assets/src/hooks/useApiCall.ts
- assets/src/hooks/useDetour.ts
- assets/src/models/createDetourMachine.ts
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1205526445275136/1207707249234239/f
Depends On:
- https://github.com/mbta/skate/pull/2675
> refactor: Move fetchDetourDirections calls into state machine

- assets/src/components/detours/diversionPage.tsx
Blocking:
- https://github.com/mbta/skate/pull/2680
> refactor: Only update text area when necessary

- assets/src/api.ts
- assets/src/models/createDetourMachine.ts
- assets/src/models/detour.ts
- assets/src/models/finishedDetour.ts
- assets/tests/api.test.ts
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/factories/finishedDetourFactory.ts
- lib/skate_web/controllers/detours_controller.ex
- test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1207657169700544/f
Depends on:
- https://github.com/mbta/skate/pull/2678
- https://github.com/mbta/skate/pull/2681
> refactor: Consolidate /detours/finished_detour and /detours/directions endpoints

- documentation/adr/0003-use-mqtt-to-publish-trip-modifications.md
We've somewhat already made this decision, but in trying to record this, I've created this ADR to record our decision to use MQTT in Skate for Trip Modifications communications.
---
Rendered: https://github.com/mbta/skate/blob/kf/doc/mqtt-adr/documentation/adr/0003-use-mqtt-to-publish-trip-modifications.md
Asana Ticket: https://app.asana.com/0/1205385723132845/1207716595296862/f
> doc: create ADR 0003 for Skate MQTT

- lib/realtime/shape.ex
- lib/skate/detours/trip_modification_publisher.ex
- test/skate/detours/trip_modification_publisher_test.exs
Asana Ticket: https://app.asana.com/0/1205718271156548/1207790645006778/f
> feat: Add `Shape` as an argument for `TripModificationPublisher.publish_modification/3`

- lib/skate/detours/trip_modification_publisher.ex
- lib/skate_web/controllers/detours_controller.ex
- test/skate_web/controllers/detours_controller_test.exs
- test/test_helper.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1207383192300475/f
Depends on:
- https://github.com/mbta/skate/pull/2693
- https://github.com/mbta/skate/pull/2694
> feat: send trip modification when finished detour api is called

- lib/skate_web/controllers/detours_controller.ex
Comment thread where I mentioned this _could_ be an Issue 😅 https://github.com/mbta/skate/pull/2679#discussion_r1664602128
Asana Ticket: https://app.asana.com/0/1148853526253420/1207922117949236/f
Sentry-Issue: https://mbtace.sentry.io/issues/5650418762/?referrer=slack&notification_uuid=1945fa24-a0fb-4a27-8d87-2a6b23611c3d&alert_rule_id=15157549&alert_type=issue
> fix: ignore no process error when sending modification

- assets/src/components/routeLadder.tsx
- assets/stories/skate-components/routeLadderHeader.stories.tsx
Asana Ticket: https://app.asana.com/0/1205526445275136/1207827639549180/f
Follow-up-from:
- https://github.com/mbta/skate/pull/2697
> refactor: Rename NewHeader to Header

- assets/css/_route_ladder.scss
Follow-up to:
- https://github.com/mbta/skate/pull/2697
Blocks:
- https://github.com/mbta/skate/pull/2711
> cleanup: Remove old route ladder header CSS

- assets/src/components/app.tsx
- assets/src/navLinkData.ts
- assets/src/userInTestGroup.ts
- assets/tests/components/nav/bottomNavMobile.test.tsx
- assets/tests/components/nav/leftNav.test.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207890779629102/f
> feat: Gate dummy detour page behind detours-list test group

- assets/src/components/detours/activeDetourPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/stories/skate-components/detours/activeDetourPanel.stories.tsx
- assets/tests/components/detours/diversionPageActivate.test.tsx
https://github.com/user-attachments/assets/748b3abf-29cf-4927-b3b1-6680e4598b39
https://github.com/user-attachments/assets/4fe9cbaf-9729-4c6b-9e1d-ad2a7e2a4803
Asana Ticket: https://app.asana.com/0/1205718271156548/1207937160828910/f
Depends on:
- https://github.com/mbta/skate/pull/2713
- https://github.com/mbta/skate/pull/2714
> feat: Add stubbed "Active Detour" detour panel

- assets/src/components/detours/activeDetourPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/detours/pastDetourPanel.tsx
- assets/src/models/createDetourMachine.ts
- assets/tests/components/detours/diversionPageActivate.test.tsx
https://github.com/user-attachments/assets/de51f86a-4cdc-461a-8ce6-341bc9e19d12
Asana Ticket: https://app.asana.com/0/1205385723132845/1206554755512191/f
Depends on:
- https://github.com/mbta/skate/pull/2713
- https://github.com/mbta/skate/pull/2714
- https://github.com/mbta/skate/pull/2715
> feat: Add ability to deactivate an active detour

- assets/src/components/nav/navMenu.tsx
- assets/src/components/nav/topNav.tsx
- assets/src/userInTestGroup.ts
- assets/tests/components/app.test.tsx
- assets/tests/components/appStateWrapper.test.tsx
- assets/tests/components/nav/navMenu.test.tsx
- assets/tests/components/nav/topNav.test.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207967466069594/f
> cleanup: Remove checks for KeycloakSso test group in frontend code

- lib/concentrate/merge.ex
- lib/concentrate/producer/http/state_machine.ex
- lib/geonames.ex
- lib/notifications/bridge.ex
- lib/realtime/alerts_fetcher.ex
- lib/schedule.ex
- lib/schedule/fetcher.ex
- lib/schedule/garage.ex
- lib/schedule/health/checkers/routes_checker.ex
- lib/schedule/health/checkers/timepoints_checker.ex
- lib/schedule/health/checkers/trip_stop_times_checker.ex
- lib/skate/migrate.ex
- lib/skate/oban/clean_up_notifications.ex
- lib/skate/repo.ex
- lib/skate/warm_up.ex
- lib/skate_web/channels/user_socket.ex
- lib/skate_web/channels/vehicles_search_channel.ex
- lib/skate_web/controllers/auth_controller.ex
- lib/train_vehicles/stream.ex
- test/schedule/health/checkers/routes_checker_test.exs
- test/schedule/health/checkers/timepoints_checker_test.exs
- test/schedule/health/checkers/trip_stop_times_checker_test.exs
- test/skate/migrate_test.exs
- test/skate/oban/clean_up_notifications_test.exs
- test/skate/warm_up_test.exs
Asana Ticket: https://app.asana.com/0/0/1207978932098577/f
Follows: #2726
> cleanup: remove __MODULE__ in logger calls

- config/config.exs
- config/prod.exs
- test/skate/warm_up_test.exs
Asana Ticket: https://app.asana.com/0/0/1207978932098578/f
Depends On:
- #2733
> cleanup: move $metadata to front of $level

- lib/skate_web/router.ex
Asana Ticket: https://app.asana.com/0/1205385723132845/1207798099018343/f
Depends on:
- https://github.com/mbta/skate/pull/2725
Somehow I thought this would be more work.
> fix: Remove configurable auth `:provider` in router, forcing keycloak

- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/minischedule.d.ts
- assets/src/models/minischeduleData.ts
- assets/tests/api.test.ts
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- lib/schedule/as_directed.ex
- lib/schedule/hastus/activity.ex
- test/schedule/block_test.exs
- test/schedule/data_test.exs
- test/support/factory.ex
Asana Ticket: https://app.asana.com/0/1205718271156548/1208002136498399/f
> fix: Allow Hastus import to work when a block has as-directeds and regular trips

- lib/schedule/hastus/activity.ex
- test/schedule/data_test.exs
Asana Ticket: https://app.asana.com/0/1148853526253420/1208002136498399/f
> fix: Make as-directed parsing not-crash and default to regular trips

- assets/src/components/detourListPage.tsx
- assets/src/models/createDetourMachine.ts
- assets/src/models/detour.ts
- assets/tests/components/detours/detoursPage.addDetour.test.tsx
Asana Ticket: https://app.asana.com/0/1205526445275136/1207890779629107/f
Depends on:
- #2742
> feat: add detour button to list page

- Dockerfile
```curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem | shasum -a 256```
Past PRs:
- https://github.com/mbta/skate/pull/2332
- https://github.com/mbta/skate/pull/2161
- https://github.com/mbta/skate/pull/1893
- https://github.com/mbta/skate/pull/1810
> chore: update aws cert bundle

- assets/tests/api.test.ts
- assets/tests/factories/shape_data.ts
- assets/tests/factories/stopData.ts
- assets/tests/models/shapeData.test.ts
- assets/tests/models/stopData.test.ts
One of many steps associated with https://github.com/mbta/skate/pull/2603
Part of:
- https://github.com/mbta/skate/pull/2603
> refactor: Explicitly export stopDataFactory

- assets/tests/factories/shape_data.ts
- assets/tests/models/shapeData.test.ts
One of many steps associated with https://github.com/mbta/skate/pull/2603
Part of:
- https://github.com/mbta/skate/pull/2603
> refactor: Explicitly export shapeDataFactory

- assets/css/detours/_detour_table.scss
I also snuck a few other changes in, like fixing the font and background colors, since it looked annoyingly bad without those changes.
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1208155044119310/f
> feat: Update borders on the draft detours table

- assets/css/_detour_list_page.scss
- assets/src/components/detourListPage.tsx
---
Asana Ticket: https://app.asana.com/0/1205718271156548/1208226797938042/f
Depends on:
- https://github.com/mbta/skate/pull/2763
- https://github.com/mbta/skate/pull/2762
> feat: Update text size on "Add detour" button

- assets/src/components/detours/activeDetourPanel.tsx
- assets/src/components/detours/detourPanelComponents.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/components/detours/drawDetourPanel.tsx
- assets/stories/skate-components/detours/activeDetourPanel.stories.tsx
- assets/tests/components/detours/diversionPage.saveDetour.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
- assets/tests/components/detours/diversionPageActivate.test.tsx
Asana ticket: https://app.asana.com/0/1205385723132845/1208153509160250
My last commit is optional! If this rearrangement is not valuable, I'm happy to revert. I just wanted to make a few pieces of the detour panels reusable.
Another idea for another PR: putting all detour panels in a subfolder together
> feat: Adds content to active detour panel

- assets/static/images/icon-ladder.svg
- assets/stories/skate-components/icons/ladderNavIcon.stories.tsx
No Asana Ticket.
I did this to experiment with storybooking https://github.com/mbta/skate/pull/2771, and figured that it could also be useful on its own.
> storybook: Story for route ladder nav icon

- Dockerfile
> fix: update aws cert bundle hash

- assets/src/models/notificationData.ts
Fixes incorrect comment in #2773
> fix:doc: `$type` was changed to `__struct__`

- assets/src/components/detoursTable.tsx
changes: https://github.com/mbta/skate/pull/2787 (and it's dependants)
> feat: create detour status enum and "Timestamp Name"

- assets/src/components/detourListPage.tsx
- assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
Asana Ticket: https://app.asana.com/0/1205718271156548/1208284759957882/f
> feat: Suppress draft and closed detour tables on mobile

- assets/src/components/detours/detourModal.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/stories/skate-components/detours/diversionPage.stories.tsx
- assets/tests/components/detours/detoursListPage.addDetour.test.tsx
- assets/tests/components/detours/diversionPage.activate.test.tsx
- assets/tests/components/detours/diversionPage.deactivate.test.tsx
- assets/tests/components/detours/diversionPage.saveDetour.test.tsx
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1208403460973167/f
> feat: Remove the "Are you sure?" modal on closing DiversionPanel

- assets/src/components/detourListPage.tsx
- assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
- assets/tests/components/detours/detourListPage.test.tsx
- assets/tests/components/detours/detoursListPage.openDetour.test.tsx
Asana Ticket: https://app.asana.com/0/1205718271156548/1208383654888527/f
Depends on:
- https://github.com/mbta/skate/pull/2807
- Mostly a git conflict dependency - it was easier to do these tasks in sequence rather than in parallel.
> feat: Suppress draft and closed detour tables for non-dispatchers

- .github/workflows/ci.yml
https://www.notion.so/mbta-downtown-crossing/The-GitHub-code-coverage-comments-suck-dfa2d07f8b734a95a10b6e08b3a9bc6b?pvs=4
> fix: disable code coverage until theres a better solution

- assets/src/components/detours/activateDetourModal.tsx
---
Asana Ticket: https://app.asana.com/0/1148853526253420/1208390832296805/f
> feat: Update activate detour modal to match hi-fi designs

- assets/src/components/map/utilities/reactDivIcon.tsx
- assets/tests/components/__snapshots__/mapPage.test.tsx.snap
- assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
- assets/tests/components/map/utilities/reactMarker.test.tsx
This implements the changes required to remove the diffs on the `VehicleIcon` if we need it for #2847.
> feat(ts/components/reactDivIcon): create custom `DivIcon` for React portals [optional]

- config/runtime.exs
Asana Ticket: https://app.asana.com/0/1205526445275136/1208551144486217/f
Skate instances started talking to eachother in unexpected ways and started creating data issues on channels. This disables the ability for instances to find eachother so that they don't connect to eachother.
> fix: disable distributed elixir connections in production

- assets/css/map/markers/_vehicle_marker.scss
Asana Ticket: https://app.asana.com/0/0/1208590373203727/f
Turns out I wrote the wrong color in #2860. Simple fix.
> fix(css/vehicle-marker): fix commuter rail color

- assets/src/components/detours/detourPanelComponents.tsx
- assets/src/components/detours/detourPanels/activeDetourPanel.tsx
- assets/src/components/detours/detourPanels/drawDetourPanel.tsx
- assets/src/components/detours/detourPanels/pastDetourPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/stories/skate-components/detours/drawDetourPanel.stories.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160214
> feat: Add connection points to draft detour in progress

- assets/src/models/createDetourMachine.ts
Asana Ticket: https://app.asana.com/0/0/1208610656881563/f
These are implemented as Fullstory custom events because we can be _certain_ that these events happen when they're fired in the state machine.
---
Superceeds: #2870
> feat(ts/detourMachine): add fs-events for waypoints

- assets/src/components/detours/detourPanels/detourFinishedPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160217
> feat: Add connectionPoints and missedStops to the “Review Detour” panel

- assets/src/components/detours/detourPanels/detourFinishedPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
> Revert "Revert "feat: Add connectionPoints and missedStops to the “Review Det…"

- assets/src/components/detourListPage.tsx
- assets/src/components/detours/detourDropdown.tsx
- assets/src/components/routeLadder.tsx
- assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap
- assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
---
- https://app.asana.com/0/0/1208610656881548
- https://app.asana.com/0/0/1208610656881549
> feat(ts/detour-entrypoints): add entrypoints for add detour

- lib/skate/detours/snapshot_serde.ex
Asana Ticket: https://app.asana.com/0/0/1208676455644766/f
Creates the module&file for us to work out of for the "API Adapter".
> chore(ex/detours): create ser-de module

- assets/src/components/detours/diversionPage.tsx
- assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1208675874294246/f
> fix: Copy details reflects edited detour directions

- assets/src/app.tsx
- assets/src/util/userUuid.ts
This becomes useful in the detours channel frontend hook
> tweak: (tiny) Reorganization. User UUID available in a utility

- assets/src/components/routeLadder.tsx
- assets/src/models/detoursList.ts
- assets/tests/components/detours/detourListPage.test.tsx
- assets/tests/components/ladderPage.test.tsx
- assets/tests/components/routeLadder.test.tsx
- assets/tests/factories/detourListFactory.ts
- lib/skate/detours/detour.ex
- test/skate_web/controllers/detours_controller_test.exs
- test/support/factories/detour_factory.ex
> tweak: Add routepattern signifier in detour dropdown

- assets/src/components/detours/detourPanels/activeDetourPanel.tsx
- assets/src/components/detours/diversionPage.tsx
- assets/src/helpers/bsIcons.tsx
- assets/src/userInTestGroup.ts
- assets/stories/skate-components/detours/activeDetourPanel.stories.tsx
Small PR to kick off the work for [this task](https://app.asana.com/0/1205385723132845/1208845212421705)
> feat: Add change duration button, icon, and user group

- assets/src/components/detours/detourPanels/detourFinishedPanel.tsx
> tweak: tiny styling fix for delete draft button

- assets/src/components/detours/detourPanels/activeDetourPanel.tsx
- assets/src/components/detours/detourPanels/pastDetourPanel.tsx
- assets/src/userInTestGroup.ts
`copy-button` feature flag is in override mode on prod, so we can remove the conditionals and delete the group
> tweak: remove copy-button feature flag

- assets/src/components/routeLadder.tsx
- assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
- assets/tests/components/routeLadder.test.tsx
So that we can toggle on the flag for all users when ready
> tweak: The detours dropdown should totally be behind DetoursOnLadder flag

- lib/skate/detours/db/detour.ex
- lib/skate/detours/detours.ex
- test/skate/detours/db_test.exs
- test/skate_web/controllers/detours_controller_test.exs
- test/support/factories/detour_factory.ex
Context: https://github.com/mbta/skate/pull/2965#pullrequestreview-2630847942
> refactor(ex/skate/detours): use `status` and move `categorize_detour` logic into changeset

- .env.1p.skate
- config/runtime.exs
Asana Ticket: https://app.asana.com/0/0/1209654531318891
I just lightly setup variables to use for an imaginary module. Happy to change any names. Getting this setup so we can open a Devops PR.
> feat: add API key configuration for Swiftly Service Adjustments API

- Dockerfile
Previous https://github.com/mbta/skate/pull/2922
https://github.com/mbta/skate/actions/runs/14178818166/job/39720003467
> fix: update AWS cert bundle checksum

- assets/src/minischedule.d.ts
- assets/src/models/minischeduleData.ts
- assets/tests/api.test.ts
- assets/tests/components/notificationModals/inactiveStateModal.test.tsx
- assets/tests/components/propertiesPanel/minischedule.test.tsx
- assets/tests/factories/stopTimeFactory.ts
- assets/tests/factories/trip.ts
Asana Ticket: https://app.asana.com/0/1203014709808707/1209871468833666/f
> feat: add `stop_times` to `Trip` info

- assets/css/_minischedule.scss
- assets/src/components/propertiesPanel/minischedule.tsx
- assets/src/userInTestGroup.ts
- assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
- assets/tests/components/propertiesPanel/minischedule.test.tsx
Getting this PR up so we can discuss the implementation, while I work out the style still.
---
Asana Ticket: https://app.asana.com/1/15492006741476/project/1205385723132845/task/1208502301998476
TODO:
---
- https://app.asana.com/0/0/1210002892244198
> feat(ts/components/minischedule): add timepoint stop information to run and block schedules

- lib/schedule.ex
- lib/schedule/block.ex
- lib/schedule/piece.ex
- lib/schedule/trip.ex
- test/schedule_test.exs
Asana Ticket: [Handle AsDirected activities](https://app.asana.com/1/15492006741476/project/1148853526253420/task/1210114300058018?focus=true)
> fix(timepoints): filter schedule pieces to scheduled trips with stop times

- documentation/adr/0005-detour-reminder-toasts-architecture.md
Asana Ticket: [Define data contracts](https://app.asana.com/1/15492006741476/project/1203014709808707/task/1209798706213152)
Rendered: https://github.com/mbta/skate/blob/kf/asn/detour-reminder-toasts-adr/documentation/adr/0005-detour-reminder-toasts-architecture.md
> init(adr/5): Detour Reminder Toasts Data Contracts and Notifications Architecture

- assets/src/components/notificationCard.tsx
- assets/src/components/notificationCards/blockWaiverNotificationCard.tsx
- assets/src/components/notificationCards/bridgeMovementNotificationCard.tsx
- assets/src/components/notificationCards/detourNotificationCard.tsx
- assets/src/components/notificationDrawer.tsx
- assets/src/components/notificationModals/inactiveNotificationModal.tsx
- assets/src/components/notifications.tsx
- assets/src/realtime.ts
- assets/tests/components/__snapshots__/notificationCard.test.tsx.snap
- assets/tests/components/notificationCard.openDetour.test.tsx
- assets/tests/components/notificationCard.test.tsx
Asana Ticket: [Open Detour Modal when Notification is Clicked](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1209653841420232?focus=true)
See comments below. 
This makes understanding the NotificationCard component easier by separating out the business logic by domain and resolves the read state bug with detour notifications.
> Open Detour Modal when Notification is Clicked

- lib/skate/detours/detours.ex
- test/skate_web/controllers/detours_controller_test.exs
- test/support/factories/detour_factory.ex
Asana Ticket: [Notify Scheduler when Detour is Deactivated](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1209777337394437?focus=true)
> Notify Scheduler when Detour is Deactivated

- assets/src/components/notificationCards/detourNotificationCard.tsx
Asana Ticket: [Detour reminder toast spacing](https://app.asana.com/1/15492006741476/project/1148853526253420/task/1210674129599753?focus=true)
> feat(ts/detourNotificationCard): add vertical spacing between clauses

- assets/src/components/notificationCards/detourNotificationCard.tsx
Asana Ticket: [Detour reminder toast spacing](https://app.asana.com/1/15492006741476/project/1148853526253420/task/1210674129599753?focus=true)
> feat(ts/detourNotificationCard): prevent wrapping in the middle of duration and expiration times

- test/notifications/notification_server_test.exs
Asana Ticket: [Add Detour Expiration Notification Creation Interface](https://app.asana.com/1/15492006741476/task/1210594450484912)
Following on from #3016 
> it makes sense to get this merged and add any tests for `create_detour_expiration_notification/2` thereafter.
---
- https://app.asana.com/0/0/1210594450484912
> test(ex/notification_server): assert that `create_detour_expiration_notification` broadcasts notifications to users

- lib/notifications/db/detour_expiration.ex
- lib/notifications/notification.ex
- lib/skate/detours/notification_scheduler.ex
- lib/skate/detours/notification_scheduler/server.ex
- test/skate/detours/notification_scheduler/server_test.exs
- test/skate/detours/notification_scheduler_test.exs
Asana Ticket: [Notification Creation Job](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1210329527498513?focus=true)
> feat(detours): backdate expiration notification created_at from expires_at

- Dockerfile
- lib/skate/detours/detours.ex
- lib/skate_web/controllers/admin_html/index.html.heex
- lib/skate_web/controllers/detours_admin_controller.ex
- lib/skate_web/controllers/detours_admin_html/index.html.heex
- lib/skate_web/controllers/detours_admin_html/show.html.heex
- lib/skate_web/controllers/detours_admin_html/swiftly_adjustments.html.heex
- lib/skate_web/router.ex
> feat: add admin swiftly management page

- lib/swiftly/api/service_adjustments.ex
> tweak: log all status codes for swiftly requests as a field
