mbta/skate

lib/gtfs.ex, lib/gtfs/health_server.ex, lib/skate/application.ex, lib/skate_web/controllers/health_controller.ex, lib/skate_web/router.ex, test/gtfs/health_server_test.exs, test/gtfs_test.exs, test/skate_web/controllers/health_controller_test.exs
Asana Task: [/_health endpoint](https://app.asana.com/0/1112935048846093/1117444455227122)
Makes a `/_health` endpoint
Returns 200 if healthy
Returns 503 if the gtfs genserver hasn't loaded yet.
It's a little weird since the genserver will timeout if it's not loaded, rather than returning false, and I don't know the best way to express that.
Another issue: if you catch a genserver timeout, the reply will still happen later, and can clog up the clients mailbox, as mentioned here https://cultivatehq.com/posts/genserver-call-timeouts/ . Unfortunately, I couldn't find much information on this, how to fix it, or whether it's actually a problem, so I haven't tried to do anything about it.
Perhaps a way to avoid the timeout issues would be to have a separate genserver whose only job is to keep …
=> /_health endpoint

assets/.prettierrc
Prettier was occasionally inserting commas that tslint said shouldn't be there.
=> Fix prettier trailing comma configuration

assets/package.json, assets/src/components/app.tsx, assets/src/components/routeLadder.tsx, assets/src/hooks/useFetchRoutes.ts, assets/src/hooks/useFetchTimepoints.ts, assets/tests/components/app.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/hooks/useFetchRoutes.test.ts, assets/tests/hooks/useFetchTimepoints.test.ts, assets/tests/testHelpers/testHook.tsx
We finally have a way of testing effects that I feel
* tests everything we have adequately
* keeps tests isolated enough that future new tests won't trip over existing tests
* provides a structure that we can copy when testing future effects
This PR
* Moves the fetchTimepoints effect into App, so we can consolidate all effects at the top level.
* Tests for all the effects in App so far.
It doesn't add [the sockets task](https://app.asana.com/0/1112935048846093/1114820119722045) yet, but by providing a good testing framework, the socket tests will be easy enough to build on top of this PR.
---
Each effect is given its own custom hook, so we can test it independently from the App component.  That testing uses the `testHook` component from #26, which will need to be rebased on top of this. …
=> move fetchTimepoints to App. test effects.

assets/.prettierignore, assets/.prettierrc, assets/package.json, assets/tests/api.test.ts, assets/tests/testHelpers/svgStubber.js, assets/tsconfig.json, assets/tslint.json, assets/webpack.config.js
* move formatting rules out of tslint and into prettier.
- The list of rules that should be handled by prettier are defined in `tslint-prettier-config` (and [listed here](https://unpkg.com/tslint-config-prettier@1.18.0/lib/index.json))
* fix npm run check and tweak npm scripts
* tsconfig.json nicer manual formatting
* quiet the noisy api tests that call console.error
=> Improve dev scripts

test/mix/tasks/cache.clean_test.exs
No longer prints to the terminal, plus tests that it prints.
=> Capture the Cache.Clean.run/1 output while testing

lib/gtfs/data.ex, lib/gtfs/stop_time.ex, test/gtfs/stop_time_test.exs
Asana ticket: [[Investigate] Improve timepoint ordering](https://app.asana.com/0/1112935048846093/1120792726911308)
Fixes a sorting bug once you hit double digits.
Merge lists instead of using flat_map.
=> Use integer stop sequence for sorting

lib/realtime/server.ex, test/realtime/server_test.exs
Asana ticket: [🐞 Fix dev server](https://app.asana.com/0/1112935048846093/709916117691679)
Fixes errors we were getting after requests timed out while the gtfs data was still loading.
=> Ignore replies that come after a timeout

assets/src/components/ladder.tsx, assets/src/components/routeLadder.tsx, assets/src/skate.d.ts, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/ladder.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/components/vehiclePropertiesPanel.test.tsx, lib/gtfs/stop_time.ex, lib/realtime/vehicle.ex, test/channels/vehicles_channel_test.exs, test/realtime/vehicle_test.exs
Asana Task: none
#43 didn't end up using the `timepoint_status.status` field (the `fraction_until_timepoint` field was enough), and a couple inspectors have recently said that a "Next Timepoint" feature wouldn't be useful, so I don't think we're likely to end up needing it for anything else, and we can take it out.
#43 also didn't end up using the `fraction_until_timepoint` field if the `timepoint_id` was `null`, so we can make `timepoint_id` always present, which makes a couple of things simpler.
=> simplify timepoint_status format

assets/css/_vehicle_properties_panel.scss, assets/src/components/routeLadder.tsx, assets/src/components/vehiclePropertiesPanel.tsx, assets/src/skate.d.ts, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/components/ladder.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/components/vehiclePropertiesPanel.test.tsx, lib/gtfs.ex, lib/gtfs/data.ex, lib/gtfs/route_pattern.ex, lib/gtfs/stop_time.ex, lib/gtfs/trip.ex, lib/realtime/vehicle.ex, test/channels/vehicles_channel_test.exs, test/gtfs/cache_file_test.exs, test/gtfs/data_test.exs, test/gtfs/route_pattern_test.exs, test/gtfs/trip_test.exs, test/gtfs_test.exs, test/realtime/server_test.exs, test/realtime/vehicle_test.exs
Asana Task: [Add the (adjusted) Route Pattern ID and Headsign to the Vehicle Properties Panel](https://app.asana.com/0/1112935048846093/1120980093841755)
This takes the via variant from the middle of the route pattern id, which is approximately the value ops uses. There are some differences and adjustments that we don't take into account. Getting it to match better seems complicated, so I pulled it out into a separate ticket: [Bring via_variant more in line with the numbers ops uses](https://app.asana.com/0/1112935048846093/1123452464647596)
Stop times have been moved into the `Trip` object and the `trips` field of `Gtfs.Data` so that both it and the headsign/route_pattern_id can be looked up at once.
=> Show route, variant, and headsign in vehicle properties

semaphore/test.sh
Add a bash shebang.
Asana ticket: [🐞 Semaphore builds aren't failing when tests fail](https://app.asana.com/0/1112935048846093/1124224601646246)
A successful failure can be seen here: https://semaphoreci.com/mbta/skate/branches/mss-semaphore-test-failures/builds/2
=> Make semaphore test script fail when any step fails

test/concentrate/producer/http_test.exs
I was getting errors when running `mix test` locally:
```
13:36:51.163 [error] GenServer Gtfs terminating
** (ArgumentError) argument error
(stdlib) :ets.lookup_element(:hackney_config, :mod_metrics, 2)
(hackney) /Users/sky/code/skate/deps/hackney/src/hackney_metrics.erl:27: :hackney_metrics.get_engine/0
(hackney) /Users/sky/code/skate/deps/hackney/src/hackney_connect.erl:78: :hackney_connect.create_connection/5
(hackney) /Users/sky/code/skate/deps/hackney/src/hackney_connect.erl:47: :hackney_connect.connect/5
(hackney) /Users/sky/code/skate/deps/hackney/src/hackney.erl:330: :hackney.request/5
(httpoison) lib/httpoison/base.ex:787: HTTPoison.Base.request/6
(skate) lib/gtfs.ex:175: Gtfs.fetch_remote_files/1
(skate) lib/gtfs.ex:164: Gtfs.gtfs_from_url/1
(skate) lib/gtfs.ex:147: …
```
=> don't disable hackney in tests

lib/gtfs/data.ex, test/gtfs/data_test.exs
Asana Task: [🐞 Route 70 timepoints differ from TransitMaster](https://app.asana.com/0/1112935048846093/1124514350579975)
I indented an existing test. Try viewing the diff with whitespace ignored for a better view.
=> bugfix: group timepoints with same id but different stop_id

assets/css/_ladder.scss, assets/src/components/ladder.tsx, assets/src/skate.d.ts, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/ladder.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/components/vehiclePropertiesPanel.test.tsx, lib/gtfs/csv.ex, lib/gtfs/stop_time.ex, lib/realtime/helpers.ex, lib/realtime/vehicle.ex, lib/util/time.ex, mix.exs, mix.lock, test/gtfs/data_test.exs, test/gtfs/stop_time_test.exs, test/gtfs_test.exs, test/realtime/helpers_test.exs, test/realtime/vehicle_test.exs, test/util/time_test.exs
Asana Task: [Draw a line to where the bus should be at the moment](https://app.asana.com/0/1112935048846093/1122642346801329)
Times are stored in GTFS as e.g. "17:02:00". In the `stop_time` they're stored as a `Util.Time.time_of_day()`, which is seconds after midnight.
Calculates the scheduled location by:
* Getting the stop_times on the current trip. (This limits the scheduled location to being in the same direction as the bus. [Followup task to improve this](https://app.asana.com/0/1112935048846093/1125606672346265)
* Convert the current system time to a `time_of_day`, using the time of the first stop_time as a reference to make sure we correctly handle the transition from late-night to early-morning.
* Find the timepoint just before the scheduled time and the timepoint just after, and …
=> draw line to scheduled point on ladder. add time to stop_time

assets/css/_incoming_box.scss, assets/css/_ladder.scss, assets/css/_ui_kit.scss, assets/css/_vehicle_icon.scss, assets/css/_vehicle_properties_panel.scss, assets/src/components/incomingBox.tsx, assets/src/components/ladder.tsx, assets/src/components/vehicleIcon.tsx, assets/src/components/vehiclePropertiesPanel.tsx, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/vehicleIcon.test.tsx.snap, assets/tests/components/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/components/vehicleIcon.test.tsx
Asana Tasks:
[Put variant number in the triangle](https://app.asana.com/0/1112935048846093/1123217669646641)
[🐛vehicle triangle in incoming box is cut off](https://app.asana.com/0/1112935048846093/1125794829210438)
[Add triangle to the Vehicle Properties Panel header](https://app.asana.com/0/1112935048846093/1124847099574986)
This PR changes a lot about how we make vehicle icons.
* Pulls the label and (new) variant into the VehicleIcon component.
* Handles up, down, left, and right-facing vehicles. We don't have any horizontal vehicles yet, but the label/variant placement rules are pretty different for them so I wanted to make sure I didn't make that future work more difficult.
* Has separate interfaces for returning an svg node (for the ladder) vs an html node (for the incoming box and …
=> Triangles: variant, bugfix, vehicle properties panel

lib/concentrate/data_discrepancy.ex, lib/concentrate/parser/gtfs_realtime_enhanced.ex, lib/concentrate/parser/swiftly_realtime_vehicles.ex, lib/concentrate/vehicle_position.ex, test/concentrate/parser/gtfs_realtime_enhanced_test.exs, test/concentrate/parser/swiftly_realtime_vehicles_test.exs, test/concentrate/vehicle_position_test.exs
Asana ticket: [Prioritize Swiftly vehicle trip assignment in concentrate merge](https://app.asana.com/0/1112935048846093/1126289135392019)
Save data discrepancies any time swiftly and busloc provide differing
trip_id or route_id.
=> Prioritize Swiftly vehicle trip and route assignments

lib/realtime/vehicle.ex, test/realtime/vehicle_test.exs
This was causing us to lose data about vehicles that were laying over.
Asana ticket: [🐞 Laying over, non-revenue buses in Swiftly not showing up in pending box](https://app.asana.com/0/1112935048846093/1127995824503319)
Demonstration (1836 wasn't being displayed before this change):
=> Retain vehicle positions even without a trip update

assets/src/components/vehiclePropertiesPanel.tsx, lib/concentrate/vehicle_position.ex, test/concentrate/vehicle_position_test.exs
These are never set by Busloc so they were always showing up.
Ensure that discrepancy check returns a boolean value.
=> Don't include route id and headway in discrepancies

assets/src/hooks/useTimepoints.ts
Asana Task: None
I tried to open a whole bunch of routes at once, and got into an infinite refetching loop because making a whole bunch of `setState` calls at once would overwrite previous state.
By passing a function instead of a value into the `setState` calls, React will be able to handle multiple updates that are close to each other.
=> be resilient to loading lots of routes at once

lib/skate_web/controllers/auth_controller.ex, test/skate_web/controllers/auth_controller_test.exs
Asana ticket: [🐞Unauthorized screen sometimes appears after Cognito login](https://app.asana.com/0/1112935048846093/1129718872336334)
Users are sometimes seeing unexpected Ueberauth failures of unknown
provenance. Instead of sending a 403 unauthenticated response, we are
signing them out and sending them to the home page to start the auth
path over again.
We should be on the lookout for users getting trapped in a loop because
of this. If we observe that happening we should rethink this remedy.
=> Sign the user out and redirect home on auth failure

assets/src/components/map.tsx, assets/tests/components/map.test.tsx
Asana ticket: [🐞 Map tiles only shows up on the first vehicle you click, not on following ones](https://app.asana.com/0/1112935048846093/1132059249417762)
Turns out, the tile layer needs to be re-initialized every time a new map is drawn, otherwise the tiles will only show up on the first render.
=> initialize tile layer when map is initialized

assets/package-lock.json, assets/package.json, assets/src/app.tsx, assets/src/components/map.tsx, assets/webpack.config.js, lib/skate_web/templates/layout/app.html.eex
There is a bug when using leaflet with webpack that prevents leaflet from being able to find its icon images. Someone wrote an npm package that fixes this bug, so we can load leaflet's CSS assets into our build instead of downloading them from an external source.
=> load leaflet css in webpack

assets/src/components/propertiesPanel/header.tsx, assets/src/components/propertiesPanel/headwayDiagram.tsx, assets/src/realtime.d.ts, assets/tests/components/propertiesPanel/header.test.tsx
Asana Task: [Orient triangle in VPP to match the ladder](https://app.asana.com/0/1148853526253426/1126875696911113)
=> rotate VPP icon to match orientation on ladder

assets/src/api.ts, assets/tests/api.test.ts
Deduplicates a lot of work writing and testing api calls.
Followup to https://github.com/mbta/skate/pull/415#discussion_r367615946
It's built on top of the branch for that PR, so until it merges, this PR will be a bit messy. The only new changes are in `api.ts` and `api.test.ts`.
=> return default for failed api calls instead of crashing

lib/realtime/server.ex, lib/skate_web/channels/channel_auth.ex, lib/skate_web/channels/vehicles_channel.ex, test/channels/vehicles_channel_test.exs, test/realtime/server_test.exs, test/skate_web/channels/channel_auth_test.exs
In prep for [Let users know when Skate data is stale/we have lost live data connection](https://app.asana.com/0/1148853526253426/1156122231748753)
That task will make a new `_channel.ex` file. To make that easier, this PR pulls a `ChannelAuth.valid_token?()` function out of `vehicles_channel.ex`.
Also a bit of other cleanup:
* Removes a couple `reassign_env(:realtime, :trip_fn/:block_fn)` calls that I don't think were doing anything.
* When vehicles_channel starts a new subscription, does the lookup in the channel process instead of the Server process, to avoid passing the data between processes. (The duration logging is still there.)
=> Pull out channel valid_token?

lib/gtfs/stop.ex, lib/realtime/timepoint_status.ex, lib/realtime/vehicle.ex, test/gtfs/stop_test.exs, test/gtfs_test.exs, test/realtime/timepoint_status_test.exs
Asana Task: [Increase the precision of where vehicles are drawn on the ladder by interpolating the lat/lng between the stop in front and the stop behind.](https://app.asana.com/0/1148853526253426/1133314986995053)
Buses in that screenshot where this is useful:
- 9063 (the late run), which is still crossing the Tobin, not on the other side.
- 9060 , which is not quite at BELSQ yet.
- 1440 / 1044, which are much closer to THCHE than BWYBC.
=> More precise vehicle locations on the ladder

assets/src/components/map.tsx
No asana task. It was quicker to just do this task than to file it in inbound.
Before: The labels on the map were a bit oversized, so that they would have room for the long "SW-OFF" label, but it leaves lots of extra space for run numbers.
After: The label shrinks for short run numbers.
After: And stays wide for long labels.
This is the same strategy that we do for the label backgrounds on the ladder.
=> adjust map marker label background to length of label

assets/src/api.ts, assets/src/components/disconnectedModal.tsx, assets/src/components/tabBar.tsx, assets/src/hooks/useSearchResults.ts, assets/src/hooks/useShuttleVehicles.ts, assets/src/hooks/useVehicles.ts, assets/src/models/browser.ts, assets/tests/api.test.ts, assets/tests/components/disconnectedModal.test.tsx, assets/tests/components/tabBar.test.tsx, assets/tests/hooks/useSearchResults.test.ts, assets/tests/hooks/useShuttleVehicles.test.ts, assets/tests/hooks/useVehicles.test.ts, assets/tests/models/browser.test.ts
No Asana ticket, this is required (but not sufficient) for https://github.com/mbta/skate/pull/428 to pass.
This allows us to add mock implementation on a function we control.
This is required in order to upgrade to Jest version 25.1.0.
=> Encapsulate window.location.reload call

assets/package-lock.json, assets/package.json, assets/src/components/headwayLines.tsx, assets/src/helpers/array.ts
Make formatting changes required by the new version.
Combines the version bump from https://github.com/mbta/skate/pull/454 with formatting changes required to pass our checks.
=> Upgrade tslint from 5.20.1 to 6.0.0

test/support/helpers.ex
when the :active_blocks_fn was unassigned, it got the value nil
which means Application.get_env returns nil instead of the default
this caused intermittent test failures depending on the order of tests
example of a failing seed beforehand: commit ceb6330, mix test --seed 145576
deleting the value instead of assigning nil means that future calls to
get_env will use their default values
Fixes the failing build in #475 and others.
=> fix intermittent test failure

assets/css/properties_panel/_block_waiver_banner.scss, assets/static/images/icon-alert-circle.svg
Asana ticket: [Future & Past block waiver banner treatment](https://app.asana.com/0/1148853526253426/1162089955688355)
Make the background and border gray.
Make the start time bold for future waivers.
Depends on https://github.com/mbta/skate/pull/457
=> Style past and future block waivers

assets/src/components/searchPage.tsx, assets/src/hooks/useChannel.ts, assets/src/hooks/useDataStatus.ts, assets/src/hooks/useSearchResults.ts, assets/src/hooks/useShuttleVehicles.ts, assets/tests/components/searchPage.test.tsx, assets/tests/hooks/useChannel.test.ts, assets/tests/hooks/useDataStatus.test.ts, assets/tests/hooks/useSearchResults.test.ts, assets/tests/hooks/useShuttleVehicles.test.ts, assets/tests/hooks/useVehicles.test.ts, assets/tests/testHelpers/socketHelpers.ts
Follow up to #472 
While doing that PR, I noticed some inconsistencies and problems with how we do channels from the frontend. We have 3 places that use data from a single channel now. This PR unifies and polishes those implementations.
This PR:
* Removes a ton of duplication
* Fixes how we close channels. In particular, the useShuttleVehicles channel wasn’t getting closed properly, so we were still loading shuttle vehicles after clicking away from the shuttle map.
* Adds a missing test for the data returned from the initial channel join.
* Lets the channel users focus on the parts that are special for that channel instead of the channel lifecycle.
It doesn’t change the useVehicles channel, since that needs to handle and remember multiple channels, and is significantly different from the …
=> useChannel

lib/concentrate/consumer/stop_time_updates.ex, lib/concentrate/consumer/vehicle_positions.ex, lib/realtime/block_waiver.ex, lib/realtime/server.ex, lib/realtime/stop_time_update_store.ex, lib/realtime/supervisor.ex, test/channels/vehicles_channel_test.exs, test/realtime/server_test.exs, test/realtime/stop_time_update_store_test.exs
Asana ticket: [Refactor: Move StopTimeUpdates storage into a new GenServer](https://app.asana.com/0/1148853526253426/1163344518291743)
=> Refactor: Move StopTimeUpdates storage into a new GenServer

assets/src/components/headwayLines.tsx, assets/src/components/ladder.tsx, assets/src/models/ladderVehicle.ts, assets/tests/components/headwayLines.test.tsx, assets/tests/models/ladderVehicle.test.ts
[Display block waiver markers on ghost bus ladder icons](https://app.asana.com/0/1148853526253426/1163145000751641) will require `ladder.tsx` to check the block waivers to decide what kind of icon to draw. Rather than adding all the block waivers to the `LadderVehicle`, or checking the styling when creating the `LadderVehicle`, it's probably easier pass the whole vehicle through.
Old `LadderVehicle`:
```ts
export interface LadderVehicle {
vehicleId: VehicleId
label: string
viaVariant: ViaVariant | null
status: DrawnStatus
hasBlockWaivers: boolean
headwaySpacing: HeadwaySpacing | null
x: number
y: number
vehicleDirection: VehicleDirection
scheduledY?: number
scheduledVehicleDirection?: VehicleDirection
lane: number
} 
```
new `LadderVehicle`:
```ts
export interface LadderVehicle {
vehicle: …
```
=> LadderVehicle uses whole vehicle instead of taking a few fields

assets/package-lock.json, assets/package.json, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
This incorporates https://github.com/mbta/skate/pull/487 and updates our snapshots to account for class name changes in the tooltip library.
=> Bump react-tooltip from 4.0.3 to 4.1.0

assets/css/properties_panel/_block_waiver_banner.scss, assets/src/components/iconAlertCircle.tsx, assets/src/components/propertiesPanel/blockWaiverBanner.tsx, assets/src/helpers/icon.tsx, assets/static/images/icon-alert-circle.svg, assets/tests/components/__snapshots__/iconAlertCircle.test.tsx.snap, assets/tests/components/iconAlertCircle.test.tsx, assets/tests/components/propertiesPanel/__snapshots__/blockWaiverBanner.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/blockWaiverList.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/helpers/icon.test.tsx
The big ladder svg can't use an svg from a file, so in order to do [Display block waiver markers on ghost bus ladder icons](https://app.asana.com/0/1148853526253426/1163145000751641) I moved the icon into its own component.
I figured this was a big enough piece to be worth breaking out before the main PR.
Other svg changes:
* Remove the `fill-rule` from the svg. (There's no complex shapes, so it didn't do anything.)
* `<circle class="c-icon-alert-circle__circle"/>` and `<path class="c-icon-alert-circle__circle-fill"/>` were the same shape, so I consolidated them into `__fill`.
* Changed the outline to a circle instead of a path.
User-visible changes:
* Made the outline thicker (radius 24->27).
* Fixed the outline of the grey icon from white (accidentally inherited from the black icon) to …
=> move iconAlertCircle to a component so it can be used inside an SVG

assets/css/_ladder.scss, assets/css/_ui_kit.scss, assets/src/components/ladder.tsx, assets/src/components/propertiesPanel/blockWaiverBanner.tsx, assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx, assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx, assets/src/components/vehicleIcon.tsx, assets/src/models/blockWaiver.ts, assets/src/models/vehicle.ts, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/__snapshots__/vehicleIcon.test.tsx.snap, assets/tests/components/ladder.test.tsx, assets/tests/components/vehicleIcon.test.tsx, assets/tests/models/blockWaiver.test.ts, assets/tests/models/vehicle.test.ts
~Built on top of #489 . Once that merges, this PR will be smaller.~
Asana Tasks:
* [Display markers on ghost bus ladder icons for "has waiver" and "does not have waiver"](https://app.asana.com/0/1148853526253426/1163145000751641)
* ~[Display markers on ghost bus laying over icons for "has waiver" and "does not have waiver"](https://app.asana.com/0/1148853526253426/1163145000751643)~
* [Display markers on vehicle ladder icons for "has current waiver" and "has future or past waiver"](https://app.asana.com/0/1148853526253426/1163145000751647)
* ~[Display markers on vehicle laying over icons for "has current waiver" and "has future or past waiver"](https://app.asana.com/0/1148853526253426/1163145000751649)~
It made more sense to do all of the on-ladder icons at once. To keep the size down, I …
=> Block waiver icon on ladder

assets/css/_ladder_page.scss, assets/css/_page.scss, assets/css/_route_ladders.scss, assets/css/_shuttle_map.scss, assets/css/app.scss
Asana Task: [🐞 Layout issues in Safari](https://app.asana.com/0/1148853526253426/1164221537676417)
`height: 100%` didn't work on children with `flex-basis: auto` in safari
also:
* remove width: 100% that caused the page to be slightly too wide (because of margins)
* hide route ladders scroll bar if the page is narrow (overflow-x: auto)
=> fix map on safari

assets/css/app.scss
No Asana Task. Fixes an issue raised in #492 
on iphone, 100vh includes height for the address bar,
which causes a small vertical scroll.
using height: 100% instead gives the behavior we want,
where we the address bar doesn't overlap the app,
but it has to be specified all the way up the heirarchy.
Before:
After:
This was a pre-existing issue, even before the safari bug that #492 addresses was introduced in #472. It's currently visible on prod: The route ladder in this screenshot has that small amount of scroll (though before #472, including what's on prod now, the tab bar and route picker avoided the problem by being `fixed`, which is why it became more noticable in #472.)
=> fix iphone height bug

assets/src/models/blockWaiver.ts, assets/src/models/vehicle.ts, assets/tests/models/blockWaiver.test.ts, assets/tests/models/vehicle.test.ts
Asana Task: [Only show waiver icons on virtual ghosts when a waiver exists](https://app.asana.com/0/1148853526253426/1165660305468153)
virtual ghosts indicating a late vehicle show block waivers alerts like their vehicle, not like a ghost
9028 and 9042 are virtual and don't have the icon anymore. 1181 and 1516 are dropped trips and do get an icon:
=> fix virtual ghost block waiver alert icon

lib/gtfs/data.ex
when loading the data,
any trips with missing timepoints copy their timepoints from another
trip on the same route_pattern
It's not working for everything (I'm not sure why), but most route patterns are working.
=> fix trips with missing timepoints

assets/css/_properties_list.scss, assets/css/_search_results.scss, assets/src/components/searchResults.tsx, assets/src/components/vehicleIcon.tsx, assets/src/helpers/dom.ts, assets/src/models/vehicle.ts, assets/tests/components/__snapshots__/searchResults.test.tsx.snap, assets/tests/components/searchResults.test.tsx, assets/tests/helpers/dom.test.ts, assets/tests/models/vehicle.test.ts
For buses that have logged in within the last 30 minutes.
Asana ticket: [Add "New" indicator to search result cards for buses that have logged in within last 30 min](https://app.asana.com/0/1148853526253426/1160813278503797)
=> Add "New" indicator to search result cards

hastus_oig/skate.id
Asana Task: [Adapt the HASTUS export to include all our new mini-schedule-related data](https://app.asana.com/0/1148853526253426/1166438708199676)
Old:
```
trips.csv
schedule_id;area;run_id;route_id;trip_id;block_id
aba20021;123;    1501;;   43858890; 57 - 11
aba20021;123;    1501;  193;   43857919; 57 - 11
```
New:
```
trips.csv
schedule_id;area;run_id;block_id;start_time;end_time;start_place;end_place;route_id;trip_id
aba20021;123;    1501; 57 - 11;04:15;04:30;albny;wtryd;;   43858890
aba20021;123;    1501; 57 - 11;04:30;05:05;wtryd;hayms;  193;   43857919
```
```
activities.csv
schedule_id;area;run_id;start_time;end_time;start_place;end_place;activity_name;activity_type
aba20021;123;    1501;04:05;04:15;albny;albny;Sign-on;Sign-on
aba20021;123;    1501;04:15;09:29;albny;albny; 57 - …
```
=> HASTUS export script for minischedules

lib/gtfs/trip.ex, lib/realtime/vehicle.ex, test/gtfs/trip_test.exs
Asana ticket: [Handle overloaded trip IDs](https://app.asana.com/0/1148853526253420/1168499414230753)
=> Strip the overload suffix from trip IDs

assets/src/models/vehicleData.ts, assets/src/realtime.d.ts, lib/realtime/block_waiver.ex, test/realtime/block_waiver_test.exs
This field indicates a block waiver, as opposed to a prediction or other
types of stop time update.
Require block waivers to include a remark.
Asana ticket: [Only create block waivers for stop time updates with a “remark”](https://app.asana.com/0/1148853526253426/1168716458967945)
=> Only create block waivers for stop time updates with a “remark”

README.md
No ticket. Not sure how I missed this one in the first place.
=> Add a description of the GTFS_URL env var to the readme

assets/src/components/ladder.tsx, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/ladder.test.tsx
Asana ticket: [Don't show a schedule line on route ladders for overloaded buses](https://app.asana.com/0/1148853526253426/1169592928381121)
=> Don't show a schedule line on route ladders for overloaded buses

test/concentrate/consumer/stop_time_updates_test.exs, test/concentrate/consumer/vehicle_positions_test.exs, test/concentrate/pipeline/stop_time_updates_pipeline_test.exs, test/concentrate/pipeline/vehicle_positions_pipeline_test.exs, test/concentrate/stop_time_update_test.exs, test/realtime/headway_test.exs, test/realtime/time_period_test.exs, test/realtime/vehicle_or_ghost_test.exs, test/realtime/vehicles_test.exs, test/schedule/hastus/activity_test.exs, test/schedule/hastus/trip_test.exs, test/schedule_test.exs, test/skate_web/views/layout_view_test.exs
... and add `async: true` to tests that are async safe.
Asana Task: [Intermittent Test Failure in VehiclePositionsTest](https://app.asana.com/0/1148853526253420/1170653240610633)
=> Remove async: true from tests that aren't async safe

assets/css/layover_box.scss, assets/src/components/layoverBox.tsx, assets/src/components/vehicleIcon.tsx, assets/tests/components/__snapshots__/layoverBox.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/layoverBox.test.tsx
Asana Task: [Move laying over areas into the route ladder SVG - (1) Turn each laying over sections into a single SVG](https://app.asana.com/0/1148853526253426/1166474874729001)
The space above/below the layover box might have changed by a couple pixels, but otherwise no user facing changes.
It'll be a lot easier to see how the snapshot changes if you turn off whitespace changes.
=> turn layover box into svg

lib/schedule/data.ex, lib/schedule/hastus/activity.ex, lib/schedule/hastus/run.ex, lib/schedule/hastus/trip.ex, lib/schedule/helpers.ex, lib/schedule/minischedule/block.ex, lib/schedule/minischedule/break.ex, lib/schedule/minischedule/load.ex, lib/schedule/minischedule/piece.ex, lib/schedule/minischedule/run.ex, test/schedule/minischedule/load_test.exs
Asana Task: [Import the new mini-schedule-related HASTUS data into Skate](https://app.asana.com/0/1148853526253426/1166438708199679)
Preprocesses hastus data into the format we'll need for minischedules, and stores it in Schedule.Data
This does not include a way to get it out of Data yet.
Has a placeholder implementation for the details of turning trips into pieces and understanding Operator and Sign-on activities.
The big picture of separating trips and activities into their blocks and runs is done, and will let us start working on fetching this data into the frontend, though the placeholder means the data won't be quite right.
=> Make Minischedules data from HASTUS data

assets/css/_leaflet.scss, assets/css/_vehicle_map.scss, assets/src/components/map.tsx, assets/tests/components/__snapshots__/map.test.tsx.snap, assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana ticket: [Disable map recenter button if autoCenter is on](https://app.asana.com/0/1148853526253426/1145445573523887)
New version of https://github.com/mbta/skate/pull/585 that was reverted by https://github.com/mbta/skate/pull/589. This version fixes the bug where our tab bar would disappear that was discovered here: https://github.com/mbta/skate/pull/587#issuecomment-614684877.
Background: Leaflet doesn't want its div changing, that caused the bug. I moved the class name that represents the current state of things to an adjacent div.
=> Disable map recenter button when auto centering is on

lib/concentrate/consumer/stop_time_updates.ex, lib/realtime/vehicle.ex, lib/schedule/data.ex, lib/schedule/trip.ex, test/concentrate/consumer/stop_time_updates_test.exs, test/realtime/block_waiver_test.exs, test/realtime/ghost_test.exs, test/realtime/timepoint_status_test.exs, test/realtime/vehicle_test.exs, test/realtime/vehicles_test.exs, test/schedule/block_test.exs, test/schedule/data_test.exs, test/schedule/health/checkers/trip_stop_times_checker_test.exs, test/schedule/trip_test.exs, test/schedule_test.exs
Preparing for [Mini-schedule | Store nonrevenue trips and trip schedule_ids](https://app.asana.com/0/1148853526253426/1171782113097825)
Allowing nonrevenue trips means some trips will exist in our data that don't have GTFS data. This makes that possible and makes sure everywhere that expects GTFS data can handle nonrevenue data gracefully.
=> allow missing fields in Schedule.Trip

lib/schedule/trip.ex, test/concentrate/consumer/stop_time_updates_test.exs, test/realtime/block_waiver_test.exs, test/realtime/ghost_test.exs, test/realtime/timepoint_status_test.exs, test/realtime/vehicle_test.exs, test/realtime/vehicles_test.exs, test/schedule/block_test.exs, test/schedule/data_test.exs, test/schedule/trip_test.exs, test/schedule_test.exs
No asana ticket. I realized I missed this as part of #597 because route_id is in both gtfs and hastus. But it might be nil in hastus.
=> allow nonrevenue trips with nil route_id in trip type

lib/schedule.ex, lib/schedule/data.ex, lib/schedule/minischedule/block.ex, lib/schedule/minischedule/break.ex, lib/schedule/minischedule/piece.ex, lib/schedule/minischedule/run.ex, lib/skate_web/controllers/minischedule_controller.ex, lib/skate_web/router.ex, test/schedule/data_test.exs, test/schedule_test.exs, test/skate_web/controllers/minischedule_controller_test.exs
Asana Task: [Mini-schedule | Make API endpoints](https://app.asana.com/0/1148853526253426/1170680075334326)
Also splits `Schedule.minischedule` into two functions, a followup from #612 
Example:
http://localhost:4000/api/minischedule/block/43773724
```json
{
"data": {
"id": "A502-95",
"pieces": [
{
"block_id": "A502-95",
"end": {
"mid_route?": false,
"place": "albny",
"time": 70620
},
"run_id": "123-9039",
"schedule_id": "aba20011",
"start": {
"mid_route?": false,
"place": "albny",
"time": 57300
},
"trips": ["...trips..."]
}
],
"schedule_id": "aba20011"
}
}
```
=> Minischedules Api Endpoints

lib/schedule.ex
Oops, this is important. Without this, we weren't actually loading any activities.
=> bugfix: read hastus activities

assets/src/components/map.tsx, assets/tests/components/map.test.tsx
Asana Task: [🐞 Vehicle doesn't stay centered in the properties panel map](https://app.asana.com/0/1148853526253426/1171784929698249)
Built on top of #632 
This was the result of two overlapping problems:
1. `useEffect` dependencies use a shallow `===` comparison, and `[] !== []`, so it thought that the list of vehicles was moving every render, and it called `autoCenter()` every render.
That should be fine, autoCentering should be idempotent, but
2. If `autoCenter()` is called twice in quick succession, there's a chance that events will happen in this order:
- 1st `autoCenter` starts, setting `isAutoCentering` to `true`
- 1st `movestart` triggers. `isAutoCentering` is `true`.
- 2nd `autoCenter` call happens. `isAutoCentering` is set to `true` again.
- 1st `moveend` triggers. …
=> Bugfix: Autocentering loses focus

assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/ladderPage.test.tsx, assets/tests/components/shuttleMapPage.test.tsx
Asana Task: [Intermittent test failure](https://app.asana.com/0/1152340551558956/1173051855704249)
This was continuing to get in my way, but it turned out to be a pretty quick fix. The intermittent test failures+warnings were because a couple of tests were making real api calls.
Also adds a test because we weren't testing that one of the api calls was used.
=> add missing api mocks. fix intermittent test failures

lib/schedule/minischedule/load.ex, test/schedule/minischedule/load_test.exs, test/schedule_test.exs
Asana Task: [Mini-schedule | Data | Make Pieces Correctly](https://app.asana.com/0/1148853526253426/1170680075334323)
Replaces the existing placeholder implementation.
Matches trips to their `"Operator"` activity, so trips and breaks can be shown in the right order. (Explanation is in the Asana Task.) `"Operator"` activities and their matching `"Sign-on"` activities won't be shown as `Break`s anymore.
Lynn garage also has pulls as separate activities instead of trips. In this PR, the piece's time extends to take those into account. But since they don't have a `Trip`, the pull row won't show in the frontend. [Task to fix that.](https://app.asana.com/0/1148863597048545/1170698291365294)
This doesn't handle wad/rad activities. They still show up as `Break`s for now. [Task to fix …
=> Merge trips and activities into a run.

assets/src/minischedule.d.ts, assets/src/models/minischeduleData.ts, assets/tests/api.test.ts, lib/realtime/ghost.ex, lib/realtime/timepoint_status.ex, lib/schedule/block.ex, lib/schedule/trip.ex, test/realtime/ghost_test.exs, test/realtime/timepoint_status_test.exs, test/realtime/vehicle_test.exs, test/realtime/vehicles_test.exs, test/schedule/block_test.exs, test/schedule/data_test.exs, test/schedule/trip_test.exs, test/schedule_test.exs
Minischedules trips now contain a start_time and an end_time. If a GTFS
trip is present the minischedule uses the times of the first and last
stops. Otherwise the start_time and end_time from the HASTUS trip are
used.
=> Add start_time and end_time to minischedules trip

assets/css/_minischedule.scss, assets/src/components/propertiesPanel/minischedule.tsx, assets/src/minischedule.d.ts, assets/src/util/dateTime.ts, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx, assets/tests/util/dateTime.test.ts
Asana Task: [Mini-schedule | Style Revenue Trips](https://app.asana.com/0/1148853526253426/1170698291365302)
And with long multi-line headsigns:
I don't have svg icons yet, so I'm using the ❓ as a placeholder for now. I'll replace them later.
Depends on #653 . Wait until that merges to review this.
=> Style minischedule trips

assets/src/components/propertiesPanel/minischedule.tsx, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx, lib/schedule/hastus/trip.ex, test/schedule/hastus/trip_test.exs
Asana Task: [Mini-schedule | Trip List Component | Pulls+Deadheads](https://app.asana.com/0/1148853526253426/1170698291365287)
Depends on #656 . Wait til that merges to review this.
A couple rows in HASTUS's trips.csv have route_id `pull`. Since we detect deadheads by them not having a route_id, this PR also had to detect and fix those rows.
[Later task to add the icons](https://app.asana.com/0/1148863597048545/1175607249486042)
[Later task to add the details about which garage/place the deadhead is to/from](https://app.asana.com/0/1148863597048545/1172768650171943)
=> Minischedule label pull and deadhead rows

assets/src/components/propertiesPanel/minischedule.tsx, assets/src/minischedule.d.ts, assets/src/util/dateTime.ts, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx
Card: https://app.asana.com/0/1148853526253426/1170698291365291
Breaks are now shown in the minischedule in a formatted fashion, rather than a blob of JSON.
=> Show breaks in minischedule

assets/tests/setup.tsx
No Asana Task
I don't know how a typechecker could have intermittent failures, but here we are. There's a function in `tests/setup.tsx` that adds a missing function so that Leaflet can work in tests. (It was introduced in #632 ). But typescript has failed a couple times on it.
Example failure: https://semaphoreci.com/mbta/skate/branches/dependabot-npm_and_yarn-assets-typescript-3-9-2/builds/2
```
> @ check /home/runner/skate/assets
> tsc --noEmit && npm run lint:check && npm run format:check
tests/setup.tsx:28:13 - error TS2339: Property 'createSVGRect' does not exist on type 'Element'.
28     element.createSVGRect = () => {}
~~~~~~~~~~~~~
Found 1 error.
```
I know that function doesn't exist, that's why I'm adding it!
Rather than add even more `@ts-ignore` lines, I figured it'd be easier …
=> fix intermittent failure. ts-nocheck in test setup

assets/src/components/tabBar.tsx, assets/src/skate.d.ts, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/tabBar.test.tsx.snap, assets/tests/components/tabBar.test.tsx, lib/skate_web/templates/layout/_drift.html.eex
Asana Task: [Test moving the Drift entrypoint to the nav bar (above the ? icon) to simplify the Skate UI](https://app.asana.com/0/1148853526253426/1173065850148382)
Default state:
The button opens the bigger sidebar:
Instead of the former smaller popup:
If the window is narrow, it fills the whole screen instead:
To close the chat window, there's a ❌ in the new bigger sidebar, or you can click the tab bar 💬 again.
=> Open drift from tab bar

lib/realtime/block_waiver.ex, test/realtime/block_waiver_test.exs
Asana Task: [Don't show/highlight block waivers for invalid Transitmasters in Skate](https://app.asana.com/0/1148853526253426/1166921367572633)
=> filter out block waivers for bad TM units

assets/src/util/dateTime.ts, assets/tests/components/STABLE/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/STABLE/propertiesPanel/__snapshots__/blockWaiverBanner.test.tsx.snap, assets/tests/components/STABLE/propertiesPanel/__snapshots__/blockWaiverList.test.tsx.snap, assets/tests/components/STABLE/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap, assets/tests/components/STABLE/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/components/__snapshots__/propertiesList.test.tsx.snap, assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/__snapshots__/searchResults.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/propertiesList.test.tsx, assets/tests/components/propertiesPanel/__snapshots__/blockWaiverBanner.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/blockWaiverList.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/util/dateTime.test.ts
Asana Task: [Mini-schedule | Format times](https://app.asana.com/0/1148853526253426/1176968901192792)
Also affects the time formatting for logon times and block waivers.
=> change time formatting

lib/schedule/minischedule/load.ex, lib/schedule/minischedule/trip.ex, test/schedule/minischedule/load_test.exs
Card: https://app.asana.com/0/1148853526253426/1170698291365294
Lynn has some "Deadhead to" (pull back) and "Deadhead from" (pull out)
activities. Everywhere else, deadheads are represented as a trip with no
route_id. Here we convert those deadheads into dummy trips that get
tacked onto the correct end of the adjacent piece.
=> Convert leading/following deadhead activities

assets/css/_minischedule.scss, assets/src/components/propertiesPanel/minischedule.tsx, assets/src/helpers/dom.ts, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx
Asana Task: [Mini-schedule | Trip List Component | Past Trip or Event row styling](https://app.asana.com/0/1148853526253426/1153870789408625)
=>  style past and future trips and pieces 

assets/css/_icon_alert_circle.scss, assets/src/components/iconAlertCircle.tsx, assets/src/models/blockWaiver.ts, assets/tests/components/__snapshots__/iconAlertCircle.test.tsx.snap, assets/tests/components/__snapshots__/ladder.test.tsx.snap, assets/tests/components/iconAlertCircle.test.tsx, assets/tests/components/ladder.test.tsx, assets/tests/models/blockWaiver.test.ts
Card: https://app.asana.com/0/1148853526253426/1176421268419395
For vehicles, we now only show the alert icon on the route ladder if there's a current block waiver, as opposed to a past or future one. We also extend the definition of "current" in this case to cover future block waivers that start no more than 240 minutes in the future.
=> Show alert icons on route ladders for current block waivers only

assets/css/_minischedule.scss, assets/src/components/propertiesPanel/minischedule.tsx, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx
Card: https://app.asana.com/0/1148853526253426/1153848861994002
We show a summary of the "duty details" of the given run in the run view
in the minischedule: the "spread" (total length of the working day),
number of hours actually spent working, and number of hours on paid
break.
=> Show duty details of run in minischedules

assets/css/_minischedule.scss
Asana Task: [🐞 minischedules graphical problem with long place names](https://app.asana.com/0/1148853526253426/1180667035759089)
Before:
After:
(I changed the text to force it to wrap, but the asana card has an example of it happening with real text.)
=> Fix line length with long minischedule rows.

assets/css/properties_panel/_header.scss
Asana Task: [🐞 Last GPS ping in VPP can cause weird wrapping issues](https://app.asana.com/0/1148853526253426/1180518784070169)
Headsign will wrap without the time wrapping:
Removed the padding between headsign and last gps ping so the headsign can be longer without wrapping:
and make headsign less likely to wrap and unwrap by preventing width changes until the data is 100 seconds old
=> Prevent wrapping of time since last gps ping

.dialyzer.ignore-warnings, codecov.yml, lib/skate_web/controllers/deliberately_fail_controller.ex, lib/skate_web/router.ex
No card. Added this to deliberately generate a harmless error in production, so that we can make sure that Sentry is working properly in prod.
=> Add action that deliberately fails, to test Sentry

assets/css/_leaflet.scss, assets/css/_properties_panel.scss
Card: https://app.asana.com/0/1148853526253426/1183408998643817
Adds the proper SVGs to the fullscreen buttons in the search and shuttles pages.
=> Use icon in all fullscreen buttons

assets/css/_minischedule.scss, assets/src/components/propertiesPanel/minischedule.tsx, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap, assets/tests/components/propertiesPanel/minischedule.test.tsx
Asana Task: [Minischedules | Show active status on more than just revenue trips](https://app.asana.com/0/1148853526253426/1180597825747907)
One problem: The 🚍 icon doesn't play as nicely with highlighting the stroke as the simple triangles do. Any ideas what to do about that?
=> highlight pullout and deadhead minischedule rows

assets/css/_properties_panel.scss
Asana Task: [VPP should be full-width on mobile devices](https://app.asana.com/0/1148853526253426/1176894565066953)
minimum width before it fills the screen:
maximum width where it fills the screen:
iphone size:
=> make VPP fullscreen on small screen

assets/src/components/map.tsx, assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap
Asana Task: [🐞 VPP map appears to automatically close on mobile](https://app.asana.com/0/1148853526253426/1185530236239773)
We were preventing closing the VPP when swiping on the map by [checking here](https://github.com/mbta/skate/blob/bd06e91dbd470fe1f678f99ee6f7bd7fb9e8d39e/assets/src/components/propertiesPanel.tsx#L20), but I guess we accidentally removed the id.
=> bugfix don't close vpp when swiping map

Dockerfile, assets/package-lock.json, assets/package.json, assets/src/components/propertiesPanel/minischedule.tsx, assets/tsconfig.json, assets/webpack.config.js, build.sh
Card: https://app.asana.com/0/1148853526253426/1184712585012913
Sentry has the ability to accept an uploaded sourcemap for our frontend code, so that instead of having stacktraces that look like this:
we can have stacktraces that look like this:
This PR adds such an upload to our npm `deploy` script.
One thing to note is that this does leave a public-facing `app.js.map` that one could download if they knew to look at, e.g., https://skate-dev.mbtace.com/js/app.js.map. Since our code is all open-source that seems OK to me.
=> Upload sourcemaps to Sentry

config/dev.exs, config/prod.exs, config/releases.exs, lib/geonames.ex, lib/skate/application.ex, lib/skate/secrets_manager.ex, test/geonames_test.exs, test/skate/application_test.exs, test/skate/secrets_manager_test.exs
Don't merge until [the token is added to aws secrets manager](https://app.asana.com/0/1113179098808463/1185267665560161) and we have a chance to test this in dev. (I couldn't check the secret managing part locally.)
Asana Task: [Require token for nearest intersection service calls](https://app.asana.com/0/1148853526253426/1185064914992633)
The dev config still uses the free url, so you won't need to set the token locally.
=> Require token for nearest intersection service calls

assets/css/app.scss, assets/src/app.tsx
Card: https://app.asana.com/0/1148853526253426/1152520728603475
By setting the `font-size` for `input`s to 24px (rather than the 16px that's theoretically supposed to work), the e.g. search input no longer zooms in when selected.
=> Add hack to keep iPhones from zooming in on inputs

lib/realtime/block_waiver.ex, lib/realtime/ghost.ex, lib/realtime/timepoint_status.ex, lib/realtime/vehicle.ex, lib/schedule/block.ex, lib/schedule/data.ex, test/concentrate/consumer/stop_time_updates_test.exs, test/realtime/block_waiver_test.exs, test/realtime/ghost_test.exs, test/realtime/timepoint_status_test.exs, test/realtime/vehicle_test.exs, test/realtime/vehicles_test.exs, test/schedule/block_test.exs, test/schedule/data_test.exs, test/schedule_test.exs
Refactor in preparation for [Detect pullouts dynamically based on the duration of the pullout, instead of a fixed threshold before the trip](https://app.asana.com/0/1148853526253426/1182075650453425)
To do that task, I'm planning on setting `block.start_time` to include the nonrevenue time, but that means that block needs to be a struct with a `start_time` field instead of calculating it from revenue trips.
This PR should have no user-facing changes. The `start_time` is still calculated as the start of the first revenue trip. I'll mix in the nonrevenue trips later.
=> make blocks a struct instead of a list

assets/package-lock.json, assets/package.json
We had a bunch of dependabot PRs built up, so I figured I'd bundle them together rather than merging them one by one.
Replaces:
* #760
* #763
* #769
* #771
* #776
* #778
* #780
* #781
* #782
* #784
I also ran `npm audit fix`.
I've checked all the changelogs for breaking changes and non applied to us.
=> Frontend dependency upgrades

lib/realtime/vehicles.ex, lib/schedule/block.ex, test/schedule/block_test.exs, test/schedule_test.exs
Asana Task: [Detect pullouts dynamically based on the duration of the pullout, instead of a fixed threshold before the trip](https://app.asana.com/0/1148853526253426/1182075650453425)
~Builds on top of #779. Wait until that merges to review this.~
This screenshot was taken at 16:36:38.
The route 23 pullout is scheduled from 16:35 to 16:48. The route 77 pullout is scheduled from 16:36 to 16:54. In both cases, revenue service was more than 10m away, so prod showed nothing in either incoming box.
run 123-1150 is scheduled to pull out from 17:01 to 17:05
At 16:55, prod showed a ghost bus for it:
This PR didn't show a ghost bus:
=> Show pulling out ghosts buses based on scheduled pullout times instead of 10min threshhold

assets/css/_page.scss, assets/css/_settings_page.scss, assets/css/app.scss, assets/src/components/settingsPage.tsx, assets/tests/components/__snapshots__/settingsPage.test.tsx.snap
Asana Task: [Settings Inputs could be more responsive](https://app.asana.com/0/1148853526253426/1187547356580673)
Before:
After:
To completely prevent the problem at those very small screen sizes would require a design for how to put the dropdown below the label, which isn't worth it. It's at least readable and usable at these small sizes now.
Only the last commit has the change. The other two commits are cleanups from while I figured out how the settings page works.
=> Allow settings page to shrink more responsively

lib/concentrate/consumer/stop_time_updates.ex, lib/notifications/notification.ex, lib/notifications/notification_server.ex, lib/realtime/block_waiver.ex, lib/realtime/block_waiver_store.ex, lib/schedule/block.ex, lib/skate/application.ex, test/notifications/notification_server_test.exs, test/realtime/block_waiver_store_test.exs
Block waivers are now forwarded to a new NotificationsServer, which
creates appropriate notifications for each. For the moment, we're not
doing anything with said notifications except logging them.
=> Turn block waivers into notifications

hastus_oig/skate.id
they can share a start_time with the following trip,
so you need to check the end_time to sort them correctly
Example:
before:
```
abc40011;123;    9077;Crad-338;06:00;09:00;cabot;cabot;  rad;   45682341
abc40011;123;    9077;Crad-338;06:00;06:00;cabot;cabot;;   45684791
```
after:
```
abc40011;123;    9077;Crad-338;06:00;06:00;cabot;cabot;;   45684791
abc40011;123;    9077;Crad-338;06:00;09:00;cabot;cabot;  rad;   45682341
```
=> in hastus export, sort 0-duration trips correctly

assets/src/components/notifications.tsx, assets/src/skate.d.ts, assets/tests/components/notifications.test.tsx
Asana Task:
[Test Fullstory custom event tracking using dummy cards](https://app.asana.com/0/1148853526253426/1191912668336954)
part of [Notifications tracking?](https://app.asana.com/0/1148853526253426/1191223285175310)
This sends "Notification delivered" on every notification (but doesn't do the "Notification stacked" or "Notification VPP unavailable" that the second task asks for.)
I verified with https://github.com/mbta/skate/commit/fc0bcaccf604534511d410d50ed759929c8e799f (which is currently deployed to dev) that `FS.event()` is getting called, and I think that it's getting sent to fullstory, but it's a little opaque how fullstory does its stuff, so @ahakuta , can you check that the event made it to the fullstory dashboard? (It'd be from me on firefox this afternoon)
=> fullstory event for delivering a notification

assets/src/components/notifications.tsx, assets/src/skate.d.ts, assets/tests/components/notifications.test.tsx
Asana Task: [Notifications tracking](https://app.asana.com/0/1148853526253426/1191223285175310)
That task lists 5 notifications, only 1 of which needed to be done by this PR.
* Notification delivered: handled by #835 
* Notification stacked: this PR
* Notification VPP unavailable: not possible yet
* Jumps to VPP: covered by CSS selector `.m-notifications__card-info`
* Closes notification: covered by CSS selector `.m-notifications__close`
Instead of making a new event for it, I added a property `num_stacked_int` to the existing event. I assume you can access those properties on fullstory and filter to where the number stacked ≥2. Is that okay @ahakuta ?
=> send number of stacked notifications to fullstory

config/config.exs, lib/geonames.ex
This is a guess as to what might fix [🐛Investigate Geonames access failures](https://app.asana.com/0/1148853526253426/1193058913335769)
The situation is most succinctly described here: https://campezzi.ghost.io/httpoison-ssl-connection-closed/
~I'll deploy to dev, and if that is the issue, then this should fix it.~
Dev only sees this error every few days, and without a specific way to reproduce it, I think we won't be able to see if this works until it's on prod where we'd be able to notice the errors stopping. We can revert it if it doesn't solve the problem on prod.
=> Force geonames to use TLS v1.2

lib/notifications/notification.ex, lib/notifications/notification_server.ex, lib/realtime/server.ex, test/notifications/notification_server_test.exs, test/realtime/server_test.exs
Card: https://app.asana.com/0/1148853526253426/1191003352789105
The realtime server now tracks vehicles by trip ID, and allows querying on one or more trip IDs. The notification server uses this feature to augment the `Notification`s that it creates by adding data from the active vehicle, if any.
=> Realtime server tracks vehicles by trip ID

assets/css/_search_page.scss
Asana Task: [🐛Left hand navigation bar overlaps VPP when I'm on search](https://app.asana.com/0/1148853526253426/1185722272692287)
the search page is smaller than the full screen to show the tab bar
the VPP needs overflow-x: visible to see it fullscreen over the tab bar
on mobile, the map is hidden by showing it below the screen
which needed overflow-y: hidden to keep the user from scrolling to it
this combination of overflow-x: visible; overflow-y: hidden doesn't work
this commit moves the map from position: absolute to position: fixed
so it doesn't need overflow-y: hidden to stay hidden
=> bugfix tab bar was showing on mobile search page VPP

assets/css/_notifications.scss, assets/src/components/notifications.tsx, assets/src/components/propertiesList.tsx, assets/tests/components/__snapshots__/notifications.test.tsx.snap, assets/tests/components/notifications.test.tsx, assets/tests/components/propertiesList.test.tsx
If we successfully matched a vehicle when the notification was made.
Asana Task: [Update notification card templates with operator and vehicle information](https://app.asana.com/0/1148853526253426/1191564362053833)
In those fake notifications, the bottom one is as if it was matched to a vehicle, and the top one wasn't matched.
=> Notifiations show details from the matched vehicle

assets/src/components/notifications.tsx, assets/src/models/notificationData.ts, assets/src/realtime.d.ts, assets/tests/components/notifications.test.tsx, assets/tests/hooks/useNotifications.test.tsx
Asana Task: [🐛Notification has "null" value for operator, and doesn't link to a run that is currently active/has a waiver](https://app.asana.com/0/1148853526253420/1194947689037481)
We were checking for the operator being `undefined`. This change changes that to match the `null` that the backend is sending us.
=> use null for missing notification data instead of undefined

assets/src/components/app.tsx, assets/src/components/appStateWrapper.tsx, assets/src/components/ladderPage.tsx, assets/src/components/notifications.tsx, assets/src/contexts/notificationsContext.tsx, assets/src/realtime.d.ts, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/notifications.test.tsx, assets/tests/contexts/notificationsContext.test.tsx
Asana Task: [Restrict notification cards to only appear on route ladder view](https://app.asana.com/0/1148853526253426/1194621236689393)
=> Show notifications only on ladder page 

assets/src/hooks/useVehicleAndRouteForNotification.ts, assets/tests/hooks/useVehicleAndRouteForNotification.test.tsx
Card: https://app.asana.com/0/1148853526253426/1197215845308505
We introduced the convention that an undefined result here indicated
that we were in the process of loading the vehicle, whereas a null
result would indicate we tried and failed. However, we didn't adjust the
Fullstory tracking code accordingly. Fixed.
=> Fix tracking in useVehicleAndRouteForNotification

assets/src/components/inactiveNotificationModal.tsx, assets/src/hooks/useVehicleAndRouteForNotification.ts, assets/src/models/notificationData.ts, assets/src/realtime.d.ts, assets/tests/components/__snapshots__/inactiveStateModal.test.tsx.snap, assets/tests/components/__snapshots__/modal.test.tsx.snap, assets/tests/components/inactiveStateModal.test.tsx, assets/tests/components/modal.test.tsx, assets/tests/components/notifications.test.tsx, assets/tests/contexts/notificationsContext.test.tsx, assets/tests/hooks/useNotifications.test.tsx, assets/tests/hooks/useVehicleAndRouteForNotification.test.tsx, assets/tests/state.test.ts, lib/notifications/notification.ex, lib/notifications/notification_server.ex, test/notifications/notification_server_test.exs
Card: https://app.asana.com/0/1148853526253426/1194634240558553
We have a separate Fullstory event, and different copy, for when the run or runs in question are in the future.
=> Treat upcoming notifications separately when clickthrough fails

assets/src/hooks/useVehicleAndRouteForNotification.ts, lib/notifications/notification_server.ex, lib/realtime/server.ex, lib/skate_web/channels/vehicle_channel.ex, test/realtime/server_test.exs, test/skate_web/channels/vehicle_channel_test.exs
Card: https://app.asana.com/0/1148853526253426/1197215845308509
We had been indexing vehicles by trip ID in the realtime server, so that
when a user clicked a notification, we could use the trip IDs associated
with the notification to look up the pertinent vehicle.
This led to a counterintuitive behavior where, if a vehicle was on a run
affected by a block waiver, but not on one of the affected trips, it
would not be considered associated with the waiver.
Here we change to indexing and retrieving vehicles by run ID instead, to
avoid that problem.
=> Index vehicles by run ID for notification purposes

.dockerignore
It was successfully running all the migrations it had, it just didn't know about any of them!
This will include the migrations folder in the docker image.
I checked the logs for the dev instance I deployed this on, and it did run the migration, and dev is working again.
=> bugfix: Include migrations in docker

data/timepoint_order.json, lib/schedule/helpers.ex, lib/schedule/timepoint_order.ex
Followup to #895 
I looked for all the routes that ran into [this kind of conflict](https://github.com/mbta/skate/pull/895#discussion_r508555899) and added hints (manual overrides) to straighten them out.
There are still conflicts that can't be straightened into a line with timepoint order hints in:
* 708 and 60 (there's a loop with multiple layover points)
* 26 (a loop that sometimes goes clockwise and sometimes counterclockwise)
* 23 (a [bug in GTFS](https://app.asana.com/0/881264583703207/1198563159603145) means one of the variants is listed in the wrong direction)
* 435 (a variant loops to the same timepoint twice, which we can't show)
but I've added hints to be sure those cases are being drawn in the best way possible.
I did not search for places where a branch or short turn (like …
=> Add more timepoint order hints

assets/src/components/inactiveNotificationModal.tsx, assets/src/components/modal.tsx, assets/src/components/notificationDrawer.tsx, assets/src/components/notifications.tsx, assets/src/contexts/notificationsContext.tsx, assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap, assets/tests/components/__snapshots__/notifications.test.tsx.snap, assets/tests/components/inactiveStateModal.test.tsx, assets/tests/components/notificationDrawer.test.tsx, assets/tests/components/notifications.test.tsx, assets/tests/contexts/notificationsContext.test.tsx
Card: https://app.asana.com/0/1148853526253426/1192202587402579
Now we only show the most recent notification, which we can now hide but no longer remove. The distinction will become important when we start populating the drawer.
=> Show at most one floating notification

assets/src/hooks/useVehicles.ts, assets/tests/hooks/useVehicles.test.ts
Card: [Add FS custom event tracking when a bus goes invalid on a ladder](https://app.asana.com/0/1148853526253426/1199159279046397/f)
This is my first PR, and it has side-effects in a system that I don't yet have access to, so it should receive extra-careful product review. 😅 
I got a little tangled up with the intricacies of testing channels since I haven't done much with that in the past. I'd _like_ to additionally test that a FullStory event _doesn't_ get triggered when a bus stays valid between two different messages, but I was having a lot of trouble crafting a test where the channel receives one message and then another.
=> feat: send FullStory notification when bus goes invalid

assets/src/models/notificationData.ts, assets/tests/hooks/useNotifications.test.tsx, lib/notifications/db/notification.ex, lib/notifications/notification.ex, lib/notifications/notification_reason.ex, lib/notifications/notification_server.ex, lib/realtime/block_waiver_store.ex, priv/repo/migrations/20201110152910_create_notifications.exs, test/notifications/notification_server_test.exs
Card: https://app.asana.com/0/1148853526253426/1192202587402599
We now store notifications in the database when they come in. There is some extra logic that prevents identical notifications from being logged or written by multiple nodes at once.
=> Store notifications in the database

lib/realtime/train_vehicles_store.ex, test/realtime/train_vehicles_store_test.exs
Card: [🐞 Skate missing GL vehicles](https://app.asana.com/0/1148853526253426/1185722272692310/f)
The gist of the problem has to do with the transformation of the `Green-B`, `Green-C`, etc. GTFS route IDs into one combined `Green` route for sending to the front-end. Some parts of the code were doing this transformation correctly, others weren't, so updated and new vehicles weren't being reflected.
=> fix: keep Green Line locations up-to-date with API stream

assets/src/hooks/useNotifications.ts, assets/tests/hooks/useNotifications.test.tsx, lib/notifications/db/notification.ex, lib/notifications/db/notification_user.ex, lib/notifications/notification.ex, lib/skate/settings/db/user.ex, lib/skate_web/channels/notifications_channel.ex, lib/util/time.ex, priv/repo/migrations/20201203204900_add_indexes_for_notification_fetch_on_page_load.exs, test/notifications/notification_server_test.exs, test/notifications/notification_test.exs, test/skate/application_test.exs, test/skate_web/channels/notifications_channel_test.exs
Card: https://app.asana.com/0/1148853526253426/1192202587402591
When a user opens Skate, they get any notifications that are for routes they subscribe to, and that have an `end_time` no more than 8 hours in the past.
=> Return unexpired notifications on channel join

assets/src/components/notificationDrawer.tsx, assets/tests/components/notificationDrawer.test.tsx
Card: [Notification drawer tracking](https://app.asana.com/0/1148853526253426/1199209745954664/f)
See my comments on the ticket - everything listed in the requirements already had a distinct CSS class, except for these two things.
=> feat: CSS classes to differentiate mark read / unread links

assets/src/components/inactiveNotificationModal.tsx, assets/src/components/modal.tsx, assets/tests/components/__snapshots__/inactiveStateModal.test.tsx.snap, assets/tests/components/__snapshots__/modal.test.tsx.snap, assets/tests/components/inactiveStateModal.test.tsx
Card: [Remove the "Keep" and "Remove" buttons from the modal when linking to VPP is not possible](https://app.asana.com/0/1148853526253426/1199696487088341/f)
=> feat: remove unused buttons on inactive notification modal

assets/src/components/notificationDrawer.tsx, assets/tests/components/notificationDrawer.test.tsx
Card: [Don't show "Mark all as read" link in the inbox if all notifications are already read](https://app.asana.com/0/1148853526253420/1199718135066077/f)
=> fix: hide "mark all as read" link when no notifications are unread

assets/src/components/ladderPage.tsx, assets/src/components/rightPanel.tsx, assets/tests/components/ladderPage.test.tsx, assets/tests/components/rightPanel.test.tsx
Card: [When successfully linking to a ghost or VPP for a vehicle from a notification, highlight the applicable vehicle or ghost on the ladder](https://app.asana.com/0/1148853526253426/1199224182441183/f)
This refactors things a bit so that the `RightPanel` component no longer has a separate idea of "selected vehicle" versus "vehicle from notification," and the matter is instead handled one level up so that the vehicle selected from a notification can also be passed through as the vehicle to highlight.
=> fix: highlight ghost/vehicle on ladder if selected from notification

lib/notifications/block_waiver_backfiller.ex, lib/notifications/db/block_waiver.ex, lib/notifications/notification.ex, lib/notifications/supervisor.ex, priv/repo/migrations/20210106131944_create_block_waivers.exs, test/notifications/block_waiver_backfiller_test.exs, test/notifications/notification_test.exs
Card: https://app.asana.com/0/1148853526253426/1199525699944668
This PR does two things:
* Notifications created going forward will have block-waiver-specific fields duplicated to the new `block_waivers` table
* Existing notifications will get gradually backfilled with the same
This is the first part of a gradual refactoring of our notifications DB schema to support polymorphic associations.
=> Duplicate notifications to block waivers

data/timepoint_order.json
Card: [🐛 Routes 108, 100, and 134 are showing incorrect timepoints](https://app.asana.com/0/1148853526253426/1199212087315197/f)
I'm also going to give some though as to how we could improve the process for doing this programmatically, but any changes that come out of that brainstorming are likely to require a followup ticket anyway.
=> chore: reorder timepoints on the 100, 108, and 134.

lib/notifications/notification.ex, test/notifications/notification_test.exs
Ticket: [Properly handle case in transaction when inserting to block_waivers fails](https://app.asana.com/0/0/1199663255721070/f)
Currently if there's a conflict on the block_waivers table it will
blow up completely instead of just rolling back the transaction. This
changes that, so that we can now guard against duplicate notifications
just with the unique index on block_waivers and not relying on the
unique index on notifications, which we're about to drop.
=> fix: correctly handle conflicts on block_waivers

priv/repo/migrations/20210120185349_read_from_block_waivers.exs
Ticket: [Migration to drop notifications unique index and allow nulls](https://app.asana.com/0/0/1199663255721071/f)
* make fields on notifications not required, as they're now duplicated
from block_waivers.
* remove unique constaint on notifications
=> chore: necessary migration

lib/realtime/data_status_alerter.ex, lib/realtime/supervisor.ex, test/realtime/data_status_alerter_test.exs
Card: https://app.asana.com/0/1148853526253426/1199651591931861
One subtlety here is that, on a deploy or other server restart, it will be normal to possibly have a couple of `:outage` statuses as data is in the process of being loaded. To avoid unnecessary pages, we should check the logs after deploying to dev, to get an idea of how many messages will be generated normally, and then we'll set the threshold for alerting somewhere above that.
=> Log warning if data status goes to :outage

priv/repo/migrations/20210216142615_add_vehicle_adherence_color_to_user_setting.exs
First part of work for [Allow user to toggle late and early adherence colors](https://app.asana.com/0/1148853526253426/1199900940371686/f)
I chose the names `early_red` and `early_blue` as a quick description of each state that the setting could be in, but let me know if you have any other suggestions for terminology. I think it's reasonably intuitive, though, especially based on the mock-ups for the [settings overhaul ticket](https://app.asana.com/0/1148853526253426/1199930082433254/f).
=> chore: migration for vehicle adherence color setting

assets/src/components/inactiveNotificationModal.tsx, assets/src/hooks/useMinischedule.ts, assets/src/util/dateTime.ts, assets/tests/components/__snapshots__/inactiveStateModal.test.tsx.snap, assets/tests/components/__snapshots__/modal.test.tsx.snap, assets/tests/components/inactiveStateModal.test.tsx, assets/tests/components/modal.test.tsx, assets/tests/hooks/useMinischedule.test.ts, assets/tests/util/dateTime.test.ts
Ticket: [More detailed modals when linking to a run from a notification isn't possible](https://app.asana.com/0/1148853526253426/1199873489874876/f)
Note that I'm still trying to reproduce / dig into an issue with runs saying they're on break when the break is actually done, but so far I've tried several cases with no luck.
The current API for fetching schedules relies on GTFS trip IDs, and the notifications code already maps the original run to trip IDs. Fetching a run by run ID would require also knowing the current service, which is a bit of a hairier problem. I think the run ID -> GTFS trip ID(s) -> run ID mapping should be consistent, though. For fetching runs for potentially several trip IDs I just did multiple API calls because the number is going to be at most a few in any given …
=> Better link failure modal copy

assets/src/components/notificationContent.tsx, assets/src/contexts/routesContext.tsx, assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap, assets/tests/components/__snapshots__/notifications.test.tsx.snap, assets/tests/components/notificationDrawer.test.tsx, assets/tests/components/notifications.test.tsx
Ticket: [Ensure that notifications use the same route labels as the route ladders in Skate](https://app.asana.com/0/1148853526253426/1199900940371663/f)
=> fix: display route name (rather than ID) for notifications

assets/src/userSettings.ts, assets/tests/userSettings.test.ts
Ticket: [Clean up userSettings.ts once deployed to prod](https://app.asana.com/0/1148853526253426/1199999682730453/f)
=> chore: don't allow SettingsData values to be undefined anymore

priv/repo/migrations/20210312200638_remove_unneeded_notifications_columns.exs
Ticket: [Remove block waiver attributes from notifications table](https://app.asana.com/0/1148853526253426/1199546435658878/f)
I have had this running locally and notifications are getting created without any errors. This is just the schema change, the backfiller was already removed in a #1007.
=> chore: remove unused columns on notifications table

assets/src/components/swingsView.tsx, assets/tests/components/__snapshots__/swingsView.test.tsx.snap, assets/tests/components/swingsView.test.tsx
Asana ticket: [Swings beta: extra time cushion, dynamically remove past swings from list.](https://app.asana.com/0/1200180014510248/1200284850527481/f)
A couple of quick adjustments that came out of our post-standup chat:
* Give 10 minute cushion for showing past swings
* Dynamically remove swings older than cushion
=> feat: pre-launch adjustments

semaphore/test.sh
Codecov is going away soon (read: this weekend), so we should remove the step that does the upload. I'll also go in and disable it as a required step to merge.
=> build: remove codecov upload step

lib/concentrate/consumer/vehicle_positions.ex, lib/realtime/server.ex, test/realtime/server_test.exs, test/support/factory.ex
Asana Ticket: [Make data outage logic independent of new data coming in](https://app.asana.com/0/1148853526253426/1200062807015666/f)
I considered making this a completely independent GenServer that references the ETS table, but because the actual name of the ETS table is only accessible by calling the `Realtime.Server` process to begin with, I decided to just keep it in there.
=> fix: run data status check every 30s, even if no updates come in

.github/workflows/deploy-dev.yml
Small change that I forgot to actually open a PR for last week.
=> fix: don't rely on branch for build-push-ecr

Dockerfile
We're now on Alpine 3.14 and it looks like nodejs-npm no longer
exists: https://superuser.com/a/1424979
=> build: use npm rather than nodejs-npm from APK

assets/src/components/propertiesPanel/minischedule.tsx, assets/tests/components/propertiesPanel/__snapshots__/minischedule.test.tsx.snap
Asana ticket: [⚙️ Mini Schedules: report time vs. swing on time to align with Swings View ](https://app.asana.com/0/1200180014510248/1200360037381727/f)
I do have one outstanding question on the ticket about how to handle the "swing-on mid route" copy (if it needs to be changed at all), so there might be a subsequent commit for that.
=> feat: update minischedule copy to reference "report time"

assets/package-lock.json, assets/package.json
We have moved over ti Tippy but it looks like we never actually
cleaned up the dependency on react-tooltip
=> build(deps): remove react-tooltip dependency

assets/package-lock.json, assets/package.json
Asana ticket: [⚙️ Clean up Skate dependabot PRs](https://app.asana.com/0/1200180014510248/1200409866298290/f)
I've run this branch both locally and on skate-div without incident. If we ever decide we want to use this tool in the future we can re-add it, but I figure there's no reason to keep it in our dependencies if we aren't getting value from it.
=> build(deps-dev): remove unused webpack-bundle-analyzer dependency

assets/src/hooks/useRouteFilter.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/routePicker.test.tsx.snap, assets/tests/hooks/useRouteFilter.test.tsx
Asana ticket: [⚙️ CTx / SLx routes show up when searching for their 7xx-series route numbers](https://app.asana.com/0/1200180014510248/1200578295576933/f)
=> fix: only filter routes by name, not ID

assets/src/components/lateView.tsx, assets/src/helpers/array.ts, assets/tests/components/__snapshots__/lateView.test.tsx.snap, assets/tests/components/lateView.test.tsx, assets/tests/helpers/array.test.ts
Asana ticket: [⚙️  Investigate why the same buses appear multiple times in the Late View](https://app.asana.com/0/1200180014510248/1200677474325481/f)
It turns out that a) we weren't doing anything to filter out ghosts that appeared as both on one route and incoming for another and b) just filtering by `route_status` as either `on_route` or `laying_over` still left some gaps / edge cases. I decided to just do the thing we actually _want_ and explicitly filter down to showing at most one entry in the late view per run ID.
=> Remove duplicate late view entries

lib/realtime/block_waiver_store.ex, test/realtime/block_waiver_store_test.exs
Asana ticket: [🐞 Block waivers not showing up in Skate ](https://app.asana.com/0/1148853526253437/1200899029361209/f)
This doesn't fix the underlying issue (see comments on ticket for things I've looked into so far), but it does provide some logging that should be useful in figuring out what's going on in future scenarios. The `BlockWaiverStore` level is good for logging because it's after the waivers have been ingested via the BusLoc TripUpdates file and reconstructed, but before they're sent to the `Notifications` server and written to the database. That means this information will help us figure out which of those parts of the application is causing the problem.
=> feat: log block waiver keys for future debugging

assets/src/api.ts, assets/src/components/propertiesPanel/minischedule.tsx, assets/src/hooks/useMinischedule.ts, assets/tests/api.test.ts, assets/tests/hooks/useMinischedule.test.ts
Asana ticket: [⚙️ Minischedules showing incorrect run with mid-route swing](https://app.asana.com/0/1200180014510248/1200317928103334/f)
This includes both the back-end and front-end changes, but I'll rebase onto master once I merge #1267, making this only the front-end changes. The other PR should be reviewed first.
=> Correct minischedule run with mid route swings

priv/repo/migrations/20211025154033_create_route_tab.exs
Asana ticket: [Create DB schema for presets](https://app.asana.com/0/0/1201189412881320/f)
I'm reasonably certain that this is the schema we I'll want, but I'm going to keep this marked as a draft at first until I have a chance to implement some of the functionality that goes along with it.
=> chore: migration to add route_tabs and user_route_tabs tables

assets/css/_ladder_page.scss, assets/src/components/app.tsx, assets/src/components/ladderPage.tsx, assets/src/components/routeLadder.tsx, assets/src/components/routeLadders.tsx, assets/src/components/routePicker.tsx, assets/src/models/routeTab.ts, assets/src/state.ts, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/ladderPage.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/components/routeLadders.test.tsx, assets/tests/components/routePicker.test.tsx, assets/tests/factories/routeTab.ts, assets/tests/models/routeTab.test.ts, assets/tests/state.test.ts, lib/skate/settings/db/route_tab.ex, lib/skate/settings/route_tab.ex, lib/skate_web/controllers/page_controller.ex, lib/skate_web/templates/page/index.html.eex, test/skate/settings/route_tab_test.exs, test/skate_web/controllers/page_controller_test.exs
Asana ticket: [⚙️ Live prototype: Implement logic + interactions for Presets tab ](https://app.asana.com/0/1200180014510248/1201087271304728/f)
This PR contains a few somewhat-disparate pieces of groundwork for presets and tabs, and the commits should probably be reviewed separately. ~~One of them is a database migration, but since the code that references these database fields isn't written yet, I feel okay not separating it out into its own PR.~~ Never mind, there are uses of the new tables. I have reopened #1311 as a separate PR. Probably the meatiest commit is the last one, which adds the basics of tab interactions to the front-end. Future PRs will sync this up with the tab data on the back-end, allow saving as presets, etc.
=> Foundational work for presets and tabs

lib/skate/settings/db/route_tab.ex, lib/skate/settings/db/tab_settings.ex, lib/skate/settings/route_tab.ex, priv/repo/migrations/20211206204239_extract_tab_settings_from_route_tabs.exs, test/skate/settings/route_tab_test.exs
This effectively separates the data in a `RouteTab` from the metadata, moving the data into a new `TabSettings` table. This would be an odd way to do things except that this will make implementing presets much simpler.
=> Extract TabSettings from RouteTab

lib/schedule/fetcher.ex, test/schedule/fetcher_test.exs
Asana ticket: [Improve Skate high memory warning](https://app.asana.com/0/1152340551558956/1200080248619320/f)
This simple change causes the `Schedule.Fetcher` process to [hibernate](https://www.erlang.org/doc/man/erlang.html#hibernate-3) after doing a full fetch / parse of new schedule data. This does a full GC pass and cleans up a lot of memory (that probably made it onto the old heap since it takes a while to parse). Since the process only actually needs to execute every few minutes and isn't an interactive / low-latency kind of component, the added time for hibernation should be acceptable. This change will make the high-memory alert condition more meaningful with some other small tweaks.
Below, see a graph of `max(memtot)` as reported by Ehmon on skate-dev before, during, and after …
=> feat: hibernate Schedule.Fetcher process after fetching new data

lib/skate/ueberauth/strategy/fake.ex
Ueberauth was recently updated and the new version requires CSRF
protection, or explicitly setting the ignore_csrf_attack flag. Doing
the latter since this isn't a real strategy.
=> fix: change fake Ueberauth strategy

.github/workflows/ci.yml
Thanks for catching this @paulswartz.
=> ci: do checkout before ASDF cache, making .tool-versions present

lib/schedule/fetcher.ex, test/schedule/fetcher_test.exs
Asana ticker: [⚙️ Log time spent in GenServer.call from Schedule.Fetcher to Schedule](https://app.asana.com/0/1200180014510248/1201523184137409/f)
I also did other experimenting but none of it was really fruitful in terms of improving performance - see my comment on the Asana ticket.
Note that we're still only doing the schedule fetch on app startup, so we'll only see this logging when a new instance starts up.
=> feat: log time spent sending data message from Schedule.Fetcher

lib/notifications/notification.ex, test/notifications/notification_server_test.exs
Asana ticket: [⚙️[extra] Change new notification logging from warning to info](https://app.asana.com/0/1200180014510248/1201601333711904/f)
This will make searching the logs slightly easier by not showing us stuff about routine app functioning at the `warn` level.
=> chore: reduce new notification log level to info

assets/package.json, assets/src/api.ts, assets/src/components/ladderPage.tsx, assets/src/hooks/usePersistedStateReducer.ts, assets/src/models/routeTab.ts, assets/src/state.ts, assets/tests/api.test.ts, assets/tests/factories/routeTab.ts, assets/tests/hooks/usePersistedStateReducer.test.ts, assets/tests/models/routeTab.test.ts, assets/tests/state.test.ts, lib/skate/settings/route_tab.ex, lib/skate_web/controllers/route_tabs_controller.ex, priv/repo/migrations/20211206204239_extract_tab_settings_from_route_tabs.exs, test/skate/settings/route_tab_test.exs, test/skate_web/controllers/route_tabs_controller_test.exs, test/support/factory.ex
This reworks how we sync the route tabs open in a user's browser to the backend DB.
One key aspect is that, after the route tabs have been initialized on page load from the `data-route-tabs` JSON in the HTML, updates only flow from the browser to the backend. When we PUT an update of the route tabs state to the backend, we disregard the server's response, apart from checking its status code. The database IDs of route tabs are as a consequence no longer of interest to the frontend. To put it another way, the definitive route-tabs state is that in the client's browser; we are only interested in saving that state to the backend so that we can use it to initialize future sessions.
That still leaves one race condition possible. Imagine that the route-tabs state in the browser starts out in …
=> Correct race condition and possible duplicate orderings in route tabs

lib/skate_web/controllers/page_controller.ex, lib/skate_web/controllers/route_tabs_controller.ex, test/skate_web/controllers/page_controller_test.exs, test/skate_web/controllers/route_tabs_controller_test.exs
Asana ticker: [⚙️ Get existing tabs and presets work into a good state ](https://app.asana.com/0/1200180014510248/1201646081199337/f)
Tabs and presets is a feature that is not yet live to our actual users, being developed behind a feature flag. I need to make some slight changes to the data model, mainly using client-generated UUIDs as the primary key. Since nobody is actually using this feature, the easiest way to handle the transitional state during the deploy is to simply make the application no longer use those tables. Once the changes are made and the relevant utility functions are updated I'll undo the changes in this PR.
=> Temporarily disable tabs backend

lib/skate_web/controllers/page_controller.ex, lib/skate_web/controllers/route_tabs_controller.ex, test/skate_web/controllers/page_controller_test.exs, test/skate_web/controllers/route_tabs_controller_test.exs
Asana ticket: [⚙️ Get existing tabs and presets work into a good state ](https://app.asana.com/0/1200180014510248/1201646081199337/f)
Now re-enabling the page controller and API functionality that uses route tabs. This will have to be deployed _after_ the migration that updates the schema itself. Another PR with updates to the front-end functionality is following directly behind this one.
=> feat: re-enable route tabs backend, with UUID support

assets/package-lock.json, assets/package.json, assets/src/components/ladderPage.tsx, assets/src/models/routeTab.ts, assets/src/state.ts, assets/tests/components/ladderPage.test.tsx, assets/tests/factories/routeTab.ts, assets/tests/hooks/usePersistedStateReducer.test.ts, assets/tests/models/routeTab.test.ts, assets/tests/state.test.ts
Asana ticket: [⚙️ Get existing tabs and presets work into a good state](https://app.asana.com/0/1200180014510248/1201646081199337/f)
This should be the last major piece of the schema refactor and move to UUIDs.
=> Front-end support for route tabs UUID

assets/css/_ladder_page.scss, assets/package-lock.json, assets/package.json, assets/src/components/closeButton.tsx, assets/src/components/ladderPage.tsx, assets/src/components/presets.tsx, assets/src/components/routePicker.tsx, assets/src/models/routeTab.ts, assets/src/state.ts, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/presets.test.tsx.snap, assets/tests/components/__snapshots__/routePicker.test.tsx.snap, assets/tests/components/ladderPage.test.tsx, assets/tests/components/presets.test.tsx, assets/tests/models/routeTab.test.ts, assets/tests/state.test.ts, lib/skate/settings/route_tab.ex, lib/skate_web/controllers/route_tabs_controller.ex
Asana tickets: [⚙️Presets panel - list the existing presets + save / open them ](https://app.asana.com/0/1200180014510248/1201367915520953/f) and [⚙️  Implement close tab interaction ](https://app.asana.com/0/1200180014510248/1201448223729774/f)
To the reviewer: there's more documentation in Notion about this feature, just let me know if you'd like links for more background. This functionality is still behind a feature flag so not yet going out to users. Styling and some other parts of the tabs / presets interactions will be in forthcoming PRs.
=> Save and list presets, close tabs

.adr-dir, .tool-versions, documentation/adr/0001-record-architecture-decisions.md, documentation/adr/0002-use-persistent-term-to-store-schedule-state.md
Offering this as a proposal to document internal engineering choices, for our use as well as to help onboard future engineers/PMs.
=> use ADRs, document switch to :persistent_term

rel/env.sh.eex
If `curl` fails, ignore it with `true` which will give an empty instance ID.
=> fix: don't crash if we can't access instance id

assets/src/components/closeButton.tsx, assets/src/components/inputModals/createPresetModal.tsx, assets/src/components/inputModals/deletePresetModal.tsx, assets/src/components/inputModals/savePresetModal.tsx, assets/src/components/ladderPage.tsx, assets/src/components/modal.tsx, assets/src/components/presets.tsx, assets/src/models/routeTab.ts, assets/src/state.ts, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/modal.test.tsx.snap, assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap, assets/tests/components/__snapshots__/presets.test.tsx.snap, assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/__snapshots__/swingsView.test.tsx.snap, assets/tests/components/inputModals/createPresetModal.test.tsx, assets/tests/components/inputModals/deletePresetModal.test.tsx, assets/tests/components/inputModals/savePresetModal.test.tsx, assets/tests/components/ladderPage.test.tsx, assets/tests/components/modal.test.tsx, assets/tests/components/presets.test.tsx, assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/header.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/models/routeTab.test.ts, assets/tests/state.test.ts
Asana ticket: [⚙️ Implement preset modals](https://app.asana.com/0/1200180014510248/1201286872028647/f)
Note that I'm using React Testing Library over Enzyme as much as possible going forward due to the fact that Enzym's future support prospects seem dubious. On side-effect of this is that one of my tests needed a way to find and click on a `CloseButton` component, and since none of the other methods of selecting elements from RTL really worked I had to use the `data-testid` hatch, thereby changing a ton of snapshots. I don't love this solution but it appears to be the best for now, and as we go and rework the design of Skate and make it conform more to best practices around accessibility, this solution may no longer be needed (since a lot of the RTL selection methods are based on things …
=> Preset modals

.github/workflows/deploy-prod.yml
Asana ticket: [Add GitHub Action for doing existing skate-prod deploy](https://app.asana.com/0/0/1201796368174144/f)
As part of migrating to ECS we're first going to cut over skate-dev. Up to this point, I've been deploying skate-prod by simply going into the AWS console and deploying the image built by the skate-dev deploy. However, this won't be an option once skate-dev is on ECS (it still builds and pushes to ECR, but those images don't show up as application versions to deploy in Beanstalk without extra steps). This is a stopgap to make sure we don't find ourselves in a position of being unable to deploy skate-prod for a period, or unable without taking complicated extra steps. Later on in the migration process once we move skate-prod over I'll make a new ECS-based deploy workflow for …
=> build: GitHub action to deploy to prod (Elastic Beanstalk)

assets/src/hooks/usePersistedStateReducer.ts, assets/src/state.ts, assets/tests/hooks/usePersistedStateReducer.test.ts, assets/tests/state.test.ts
Asana ticket: [⚙️ Fix behavior of route tabs push with multiple updates](https://app.asana.com/0/1200180014510248/1201725368292425/f)
The ticket contains a detailed description of the exact bug observed. Basically, due to the order in which hooks were rerendered and promises were resolved, it was possible to have the `usePersistedStateReducer` hook send the `startingRouteTabsPush` action while not having the most recent copy of the route tabs to push, thereby removing the more-recent route tabs data without actually pushing it to the server. This replaces it with a simple FIFO queue, which potentially results in more server requests than are strictly necessary, but which avoids the bad race condition case.
In addition, I limited the retry logic to retrying at most two times, to prevent …
=> Fix tabs push

lib/skate/settings/db/user.ex, lib/skate/settings/route_settings.ex, lib/skate/settings/route_settings_migrator.ex, lib/skate_web/controllers/route_settings_controller.ex, test/notifications/notification_server_test.exs, test/notifications/notification_test.exs, test/skate/settings/route_settings_migrator_test.exs, test/skate/settings/route_settings_test.exs, test/skate_web/controllers/notification_read_states_controller_test.exs
Asana ticket: [⚙️ Migrate user settings for tabs + presets](https://app.asana.com/0/1200180014510248/1201481603842987/f)
Note that this doesn't actually enable the process in the supervision tree, that will be in the PR to roll tabs and presets out.
The logic ended up being complicated enough that I opted for this GenServer rather than a real Ecto migration, not to mention the fact that it's not _truly_ reversible so putting it in a migration with an `up` and `down` function would have been slightly disingenuous. This means we have to take care to look at `inserted_at` and `updated_at` values to make sure we're not blowing away subsequent changes by users, given that we don't have the tracking in the `schema_migrations` table to check whether or not the migration has run yet.
=> feat: process to migrate route_settings to route_tabs

assets/src/hooks/useGarageFilter.tsx, assets/tests/components/__snapshots__/routePicker.test.tsx.snap, assets/tests/hooks/useGarageFilter.test.tsx
Asana ticket: [⚙️Make garage filter default to collapsed](https://app.asana.com/0/1200180014510248/1201862941782408/f)
The (now-default) collapsed state is shown here:
The Asana ticket includes a recording of a weird user interaction that results from the garage filter taking up a lot of vertical space - leaving it collapsed by default makes this less likely, while still hopefully being prominent enough that users see that it's there to expand if they need it.
=> feat: leave garage filter collapsed by default on page load

lib/notifications/notification.ex
Asana ticket: followup from [⚙️ Deliver notifications based on tabs they have open](https://app.asana.com/0/1200180014510248/1201699907939374/f)
Context: I did a rebase and accidentally dropped this (important) line from the original PR before merging. I went through and made sure that the other changes made it in properly.
=> fix: restore line dropped in rebase

assets/src/components/app.tsx, assets/tests/components/app.test.tsx
Asana ticket: [⚙️ Late view - base routes on tabs](https://app.asana.com/0/1200180014510248/1201880022483803/f)
The Late View uses the contents of the `VehiclesByRouteIdContext`, and Late View users want to be able to monitor routes across all of their open tabs simultaneously. This will somewhat increase the amount of network traffic coming across the WebSocket relative to only subscribing to the current tab's worth of routes, but since the data on each individual vehicle is relatively small and only updates every few seconds, I don't think this is a huge problem. Also, having this data already loaded makes switching back and forth between tabs slightly more instantaneous.
=> fix: include vehicles from all tabs in VehiclesByRouteIdProvider

.github/workflows/deploy-dev-blue.yml, .github/workflows/deploy-dev-ecs.yml, .github/workflows/deploy-prod-ecs.yml, Dockerfile, assets/package-lock.json, assets/package.json, assets/webpack.config.js, upload_assets.sh
Asana ticket: [⚙️ Skate deploy: don't upload Sentry source maps directly from Docker build](https://app.asana.com/0/1152340551558956/1200443690692985/f)
I considered caching the `sentry-cli` install between builds, but a) the step to install it takes only ~7 seconds and b) I wasn't sure what we would use as a cache key (we don't have `.tool-versions` or something like that).
Regarding the choice of installation method, NPM in included on the [list of packages](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) that come with the `ubuntu-latest` environment for GitHub Actions. There are [other options](https://docs.sentry.io/product/cli/installation/) but this seemed preferable alternatives like the `curl ... | bash` pattern.
I have tested …
=> build: upload source maps to Sentry from upload_assets.sh

lib/skate_web/controllers/swings_controller.ex, test/skate_web/controllers/swing_controller_test.exs
Asana ticket: [⚙️Remove old version of swings API](https://app.asana.com/0/1200180014510248/1201890023661626/f)
Quick followup to #1431 now that that's been released.
=> chore: remove old swings API endpoint that doesn't take argument

assets/css/_ladder_page.scss, assets/css/_route_ladders.scss, assets/src/components/ladderPage.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap
Asana ticket: [⚙️Examine Skate viewport weirdness](https://app.asana.com/0/1200180014510248/1201890023661633/f)
We were applying `height: 100%` to the top-level route ladders component, making it as tall as its container, but neglected to update this when we added the tab bar on top. This was causing the route ladders to extend slightly below what was supposed to be the bottom of the page, like so:
In particular, this was bad because it was causing the horizontal scrollbar to disappear off the bottom of the screen unless you scrolled down a few pixels. With the change, the layout looks much better and the app no longer scrolls vertically:
=> fix: prevent ladders page from overflowing vertical sizing of app

assets/css/_input_modal.scss, assets/src/components/inputModal.tsx, assets/src/components/inputModals/createPresetModal.tsx, assets/src/components/inputModals/deletePresetModal.tsx, assets/src/components/inputModals/overwritePresetModal.tsx, assets/src/components/inputModals/savePresetModal.tsx, assets/tests/components/__snapshots__/modal.test.tsx.snap, assets/tests/components/inputModal.test.tsx
Asana ticket: [⚙️ Key shortcuts: User can "save" by clicking the "return key"](https://app.asana.com/0/1200180014510248/1201862253651608/f)
In terms of being able to press the "return" key, I'm mainly relying on autofocusing the corresponding button to just rely as much as possible on default browser behavior instead of ad-hoc custom event handlers. Similarly, I made the create preset modal into a form so that the return key would trigger a submit, just moving the already-existing logic into a custom `onSubmit` handler. Since all of the modals share the same basic functionality with the "escape" key I went ahead and made a shared top-level modal component and defined the handler there.
=> Keyboard shortcuts for presets modals

assets/css/_presets.scss, assets/src/components/presets.tsx, assets/tests/components/__snapshots__/presets.test.tsx.snap
Asana ticket: [⚙️ Grey out "Save as Preset" button when inactive](https://app.asana.com/0/1200180014510248/1201862941782394/f)
Active state (already implemented previously):
New disabled state:
=> feat: disabled state for save as preset button

config/config.exs
Something unusual happened with pattern typicality on the SL2 (742) recently, meaning that the typical trip had less than 10 stop times on it. The underlying schedule data still looks fine for Skate's purposes, so I'm reducing (but not removing) the required number of stop times. In addition, I have created [a ticket](https://app.asana.com/0/1152340551558956/1201994849078241/f) for better logging - in this case I had to do some local debugging that could have been obviated by just being able to look at logs in prod. This has been successfully deployed to dev.
=> fix: reduce required number of stop times on SL2 for health check

priv/repo/migrations/20220308201555_remove_route_settings.exs
Asana ticket: [⚙️ Remove old non-tabs ladder page code](https://app.asana.com/0/1152340551558956/1201442401995240/f)
Removing the one last bit of old-style route settings code / infrastructure. Also adds an index to `route_tabs` to make delivering notifications more efficient - I'll watch the deploy on dev and make sure that doing this part of the migration is relatively snappy.
=> chore: drop route_settings table

lib/skate/settings/db/user.ex
Asana ticket: [⚙️ Fix Ecto.StaleEntryError on update to route_tabs](https://app.asana.com/0/1200180014510248/1201880022483811/f)
We've seen this error occasionally reported in Sentry, but I haven't quite been able to reproduce it locally or fully figure out why there's a stale entry happening in the first place. It's probably something related to the logic in `Skate.Settings.RouteTab.update_all_for_user!/2` combined with the schema definitions. Based on the [Ecto documentation](https://hexdocs.pm/ecto/Ecto.Changeset.html#module-the-on_replace-option) it seems like changing the `on_replace` option from `delete` to `delete_if_exists` is at least a good first step that's unlikely to hurt anything.
=> fix: use delete_if_exists for route_tabs association on user

lib/skate/application.ex
Asana ticket: [[extra] Misc Elixir dependabot upgrades](https://app.asana.com/0/1200180014510248/1202075746704834/f)
Prevent a race condition on shutdown where the web endpoint can still be running when important other processes like Realtime.Server are already shut down, causing errors.
I noticed this after merging #1382. My theory is that the [Postgrex change](https://github.com/elixir-ecto/postgrex/blob/master/CHANGELOG.md#v0160-2022-01-23) to cancel all pending requests before closing the socket slightly increased the amount of time required to shut down the `Skate.Repo` process, meaning that the pre-existing race condition where the various realtime data processes could shut down before the web endpoint much more likely to actually trigger. Example error:
```
d682a7c02944 …
```
=> fix: reorder children in application supervisor

assets/css/_drawer_tab.scss, assets/css/_garage_filter.scss, assets/css/_ladder_page.scss, assets/css/_presets.scss, assets/css/_route_filter.scss, assets/css/_route_ladder.scss, assets/css/_search_form.scss, assets/css/_ui_kit.scss, assets/src/components/ladderPage.tsx, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/ladderPage.test.tsx
Asana ticket: [⚙️ Fix up button-icon CSS mixin](https://app.asana.com/0/1152340551558956/1201979636832835/f)
Previously, the `button-icon` mixin used `inline-block` display, which is fine but didn't really line up well with most of the places in the application that use the mixin, resulting in a lot of weird hacks to override the styles it set, as well as some places with minor styling bugs. In particular, the bounds of the containing `<span>` element often ended up not lining up well with the `<svg>` element inside. This uses flex display for the mixin, cleans up the existing hacks / overrides, and fixes a couple of minor pre-existing layout bugs. The comments of the tickets include screenshots of all of the locations in the application where this mixin is used (albeit mainly to …
=> fix: use flex display for button-icon mixin

assets/src/components/nav.tsx, assets/tests/components/nav.test.tsx, config/dev.exs, config/test.exs, lib/skate/ueberauth/strategy/fake.ex, lib/skate_web/auth_manager.ex, lib/skate_web/controllers/page_controller.ex, lib/skate_web/templates/page/index.html.eex, test/skate/ueberauth/strategy/fake_test.exs, test/skate_web/auth_manager_test.exs, test/skate_web/controllers/page_controller_test.exs, test/support/conn_case.ex
Asana ticket: [⚙️ Add support for beta group in Nav component](https://app.asana.com/0/1200180014510248/1202131476892155/f)
In addition to running this locally I've put it on dev-blue and tested it there by adding myself to the group.
This will allow us to develop the new navigation incrementally behind the beta group flag, but we won't actually be adding any users to it in prod until it's actually up to the level of quality that we want to be providing.
=> Nav beta group

assets/.eslintrc.js, assets/package-lock.json, assets/package.json, assets/src/components/nav.tsx, assets/src/hooks/useDeviceType.ts, assets/src/skate.d.ts, assets/tests/api.test.ts, assets/tests/components/nav.test.tsx, assets/tests/components/routeLadder.test.tsx, assets/tests/hooks/useDeviceType.test.ts, assets/tests/hooks/useRoutes.test.ts, assets/tests/hooks/useShapes.test.ts, assets/tests/hooks/useShuttleRoutes.test.ts, assets/tests/hooks/useSwings.test.tsx, assets/tests/hooks/useTimepoints.test.ts, assets/tests/setup.tsx, config/config.exs
Asana ticket: [⚙️ Nav component: code to determine mobile vs. tablet vs. desktop](https://app.asana.com/0/1200180014510248/1202131476892160/f)
This change has two main pieces:
1. Creating a new, reusable `useDeviceType` hook to determine whether our screen size counts as mobile vs. tablet vs. desktop.
1. Updating the `<Nav>` component to render unique placeholder text depending on which of these screen size classes is present.
1. Added a feature flag for the nav beta in addition to the user group, so that we don't have to constantly add and remove people from the group on dev for testing.
I also went ahead and disabled an ESLint rule that was an issue for a lot of our tests, but disabled it on tests only.
=> Render different versions of Nav based on screen size

Dockerfile
Additionally adding a run of `apk upgrade` to catch any upgrades to the packages in the base image.
=> Bump Alpine version

assets/css/nav/_top_nav.scss
Asana ticket: related to [⚙️ Implement top nav (desktop / tablet version)](https://app.asana.com/0/1200180014510248/1201682620805412/f)
Here is an example of what the logo SVG looked like before:
This covered up other elements of the page making them un-clickable.
=> fix: specify size of logo icon SVG so it doesn't get too large

assets/src/components/notifications.tsx, assets/src/components/settingsPage.tsx, assets/src/contexts/notificationsContext.tsx, assets/tests/components/__snapshots__/settingsPage.test.tsx.snap, assets/tests/components/settingsPage.test.tsx, assets/tests/contexts/notificationsContext.test.tsx
Asana ticket: [🐛 Clicking on a notification from any screen other than the route ladder never opens VPP](https://app.asana.com/0/1148853526253437/1199702340260447/f)
The underlying issue was that the logic to actually trigger the VPP opening based on which notification is selected was in the `Notifications` component itself, which also takes care of rendering the pop-up notification card when a new notification comes in. This component is only present on pages where this pop-up should display. I moved the logic in question over to the notifications context provider, which already has some other logic in it. This more appropriately separates out the visual presentation of the pop-up from the application logic to open the VPP. This also gave me a chance to add a better test for the logic in …
=> Make opening notifications work from all modes

assets/src/hooks/useChannel.ts, assets/tests/hooks/useChannel.test.ts, assets/tests/hooks/useVehiclesForRunIds.test.ts, assets/tests/testHelpers/socketHelpers.ts
Asana ticket: [⚙️ Improve performance of opening VPP or showing error when clicking notification](https://app.asana.com/0/1152340551558956/1201890023661619/f)
This ended up being an interesting one. The `useChannel` hook has a `closeAfterFirstRead` option to close the channel after the initial message rather than continuing to return updates. This is used in on specific place, namely the `useVehiclesByRunId` hook when it's called by `useVehicleForNotification`. The problem is that this argument wasn't actually implemented quite correctly. When the argument was set to true, the function was not adding `receive` handlers on the push object from `channel.join()` and was just closing out the channel when the `channel.on` handler runs. However, this is actually backwards from the way it should …
=> Speed up notification open

assets/src/components/ladderPage.tsx, assets/src/helpers/array.ts, assets/src/hooks/useMinischedule.ts, assets/src/hooks/useNotifications.ts, assets/src/hooks/useSwings.ts, assets/tests/helpers/array.test.ts, assets/tests/hooks/useMinischedule.test.ts, assets/tests/hooks/useNotifications.test.tsx, assets/tests/hooks/useSwings.test.tsx
Asana ticket: [⚙️ [extra] First batch of useEffect hooks cleanup](https://app.asana.com/0/1152340551558956/1202292117886162/f)
A few quick notes on the approach:
1. For the changes in the `LadderPage` component, I felt comfortable just using `routeTabs` as a dependency directly because it's fairly easy to understand how and why it changes in the state reducer, plus the effect doesn't do any sort of API calls or other expensive opertations.
2. For the other hooks with some sort of array dependency, I have opted to check arrays element-by-element for equality. This guards against things like references to two arrays containing the same elements in the same order, but doesn't handle cases where the arrays contain the same elements in different orders. I think this is fine for the particular …
=> First batch of useEffect cleanup

assets/css/_notification_drawer.scss, assets/src/components/notificationDrawer.tsx
Asana ticket: followup on [⚙️ [extra] Clean up ignored jsx-a11y errors](https://app.asana.com/0/1152340551558956/1202375393472375/f)
This reverts commit cf2f0ac13e4b17004427c29a8533044b277d0a46.
I somehow forgot about the fact that the whole submenu is itself nested inside of a button, so I can't turn the anchor tag into a button without creating a nested buttons scenario. This just reverts the relevant commit from the other PR.
=> Revert "fix: change anchor in ellipsis submenu to button"

assets/src/components/nav/topNavMobile.tsx, assets/tests/components/nav/topNavMobile.test.tsx, lib/skate_web/templates/layout/_drift.html.eex
Asana ticket: [⚙️ Update Drift to most recent version](https://app.asana.com/0/1200180014510248/1202424493437018/f)
This adds a handler to close the widget whenever the chat closes, so we don't have the widget just hanging out there taking up screen space. I confirmed that this works as intended whether you're closing the chat from the widget itself, or using the nav entry which calls the Drift API.
=> feat: close Drift widget on chat close

assets/src/hooks/useShapes.ts, assets/tests/hooks/useShapes.test.ts
https://app.asana.com/0/1148853526253437/1202207261666275/f
Simple fix - adding tripID to dependency array in useMapShape hook
=> fix: Shape on map in VPP not updating when trip changes

assets/css/_nav.scss, assets/css/_search_page.scss
Asana ticket: [🐛 Tab bar covers part of VPP on search page on mobile](https://app.asana.com/0/1148853526253437/1202412997478435/f)
I tracked this down to the fact that the search page CSS was changed to set `overflow: auto` specifically on mobile. Also tweaks the z-index of the bottom nav to make sure that it remains underneath all of the top nav content (i.e. hamburger menu) while also preventing box-shadows from various modals from bleeding out over the bottom nav. I suspect this issue may have been the original impetus for the `overflow: auto`, so this solves the problem not just on the search page but more generally.
=> fix: don't mess with autoflow on mobile search page

assets/css/_garage_filter.scss, assets/src/hooks/useGarageFilter.tsx, assets/src/hooks/usePersistedStateReducer.ts, assets/src/state.ts, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/routePicker.test.tsx.snap, assets/tests/hooks/useGarageFilter.test.tsx, assets/tests/state.test.ts
Created a `showGaragesFilter` global variable.
Added the following to local storage:
1. `notificationDrawerIsOpen`
2. `openView`
3. `selectedVehicleOrGhost`
4. `pickerContainerIsVisible`
5. `showGaragesFilter`
=> feat: persistent state on reload for views and filter visibility

assets/.eslintrc.js, assets/package-lock.json, assets/package.json, assets/src/components/map.tsx, assets/src/components/notificationDrawer.tsx, assets/src/contexts/notificationsContext.tsx, assets/src/helpers/array.ts, assets/src/hooks/useChannel.ts, assets/src/hooks/useDataStatus.ts, assets/src/hooks/useMinischedule.ts, assets/src/hooks/useNotifications.ts, assets/src/hooks/usePersistedStateReducer.ts, assets/src/hooks/useSocket.ts, assets/src/hooks/useTrainVehicles.ts, assets/src/hooks/useVehicleForId.ts, assets/src/hooks/useVehicleForNotification.ts, assets/src/hooks/useVehicles.ts, assets/src/hooks/useVehiclesForBlockIds.ts, assets/src/hooks/useVehiclesForRunIds.ts, assets/tests/helpers/array.test.ts, assets/tests/hooks/useChannel.test.ts, assets/tests/hooks/useMinischedule.test.ts, assets/tests/hooks/useVehicleForId.test.ts, assets/tests/hooks/useVehicleForNotification.test.tsx, assets/tests/hooks/useVehicles.test.ts
Asana ticket: [⚙️ Finish cleanup of dependencies in useEffect hooks, adopt linter rule](https://app.asana.com/0/1152340551558956/1201957254872278/f)
This finally gets rid of all of the uses of `JSON.stringify`. There are still quite a few cases of `useEffect` hooks with non-exhaustive dependencies. Some I was able to fix up quite easily, others look like they're going to be harder. In any event I have enabled the linter rule so we won't accumulate more problems going forward.
=> More useEffect fixes

README.md, upload_assets.sh
Asana ticket: [⚙️ Add browser support document to Skate README](https://app.asana.com/0/1200180014510248/1202570518287804/f)
This just adds the browser support policy that @molinash drafted and I reviewed. The purpose of the PR is mainly just to correctly get that into Markdown format in the README, but I'm also open to comments on the content of the policy itself.
=> docs: add browser support policy to README

lib/schedule/data.ex, lib/schedule/gtfs/route.ex, test/schedule/gtfs/route_test.exs
Asana: https://app.asana.com/0/1148853526253437/1201220680602259/f
Manually identifies the private carrier routes by route ID and filters them out of GTFS pull of routes.
=> Add filter to remove private carrier routes

assets/src/app.tsx, assets/src/hooks/useAppcues.ts, assets/tests/hooks/useAppcues.test.tsx
window.username was previously set in fullStory.
Instead, pull username from meta tag.
=> Eliminate references to window.username

assets/css/_card.scss, assets/css/app.scss, assets/css/properties_panel/_stale_data_properties_panel.scss, assets/src/components/card.tsx, assets/src/components/notificationCard.tsx, assets/src/components/propertiesPanel.tsx, assets/src/components/propertiesPanel/staleDataPropertiesPanel.tsx, assets/src/helpers/vehicleLabel.ts, assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap, assets/tests/components/__snapshots__/notifications.test.tsx.snap, assets/tests/components/card.test.tsx, assets/tests/components/propertiesPanel.test.tsx, assets/tests/components/propertiesPanel/staleDataPropertiesPanel.test.tsx, assets/tests/helpers/vehicleLabel.test.ts
Asana ticket: [⚙️ Implement new designs letting users know VPP data is stale](https://app.asana.com/0/1148853526253445/1202488036843591/f)
It tried to keep the commits as clean and well-organized as possible, so it should be possible to review by going commit-by-commit if that's easier than looking at the whole thing at once.
I did end up creating a new `StaleDataHeader` component rather than reusing the existing `Header`. `StaleDataHeader` is based on `Header` but the two ended up being different enough that it proved hard to integrate all of the desired logic into `Header` without producing a bunch of spaghetti code.
=> Stale VPP data message

assets/css/_nav.scss, assets/css/_swings_view.scss, assets/src/components/lateView.tsx, assets/src/components/nav.tsx, assets/src/components/nav/bottomNavMobile.tsx, assets/src/components/nav/leftNav.tsx, assets/src/components/nav/mobilePortraitNav.tsx, assets/src/components/nav/topNav.tsx, assets/src/components/nav/topNavMobile.tsx, assets/src/components/swingsView.tsx, assets/src/components/tabBar.tsx, assets/src/state.ts, assets/tests/components/lateView.test.tsx, assets/tests/components/nav/bottomNavMobile.test.tsx, assets/tests/components/nav/leftNav.test.tsx, assets/tests/components/nav/mobilePortraitNav.test.tsx, assets/tests/components/nav/topNav.test.tsx, assets/tests/components/nav/topNavMobile.test.tsx, assets/tests/components/swingsView.test.tsx, assets/tests/components/tabBar.test.tsx, assets/tests/state.test.ts
Asana ticket: [⚙️ Nav | Implement mobile portrait changes](https://app.asana.com/0/1200180014510248/1202630445285825/f)
As part of this I split the components up a bit to create a separate `MobilePortraitNav` component that takes care of the logic to show / hide the top + bottom nav depending on whether or not a view is open. The "is a view open" logic is actually kind of complicated. As far as I can tell, for now it will be specific to mobile nav but in the future it might be good to make it a utility function... somewhere, I'm not sure what the most logical spot would be.
=> Mobile portrait nav changes

assets/css/_late_view.scss, assets/package.json, assets/src/components/lateView.tsx, assets/tests/components/__snapshots__/lateView.test.tsx.snap
Asana ticket: [⚙️ Nav | Late View should open on the right, like other views](https://app.asana.com/0/1200180014510248/1202630445285831/f)
For the drawer tab, I was initially thinking I'd add an optional prop to flip it, but seeing that the late view CSS already defines some custom styling for its drawer tab and realizing I could get away with `transform: scaleX(-1)` to flip it, I decided to go with that, especially given that we're going to be getting rid of the drawer tab on late view as part of some of the other nav changes anyway.
I also fixed up some minor things that had been bugging me in `package.json`.
=> Make late view open on the right

assets/css/_late_view.scss
Asana ticket: [🐞 [extra] Late view taking up entire screen](https://app.asana.com/0/1200180014510248/1202707315274268/f)
With the old nav combined with the changes to make late view open on the right, we were setting both `left` and `right` values for the late view that caused it to take up basically the whole screen.
=> fix: don't make late view take up full screen on old nav

lib/schedule/swing.ex, test/schedule/swing_test.exs
Asana ticket: [[extra] Fix issue with parsing + loading fall schedule](https://app.asana.com/0/1200180014510248/1202737931015267/f)
The contents of `piece.trips` can actually include not just `Trip` structs but also `AsDirected` structs, which was causing an error. This adds come handling for that case, opting to simply ignore anything in the schedule that looks like a swing where the swing on / off trip is actually a work as directed piece.
=> fix: handle cases of %Schedule.AsDirected{} turning up in pieces

assets/src/components/nav/leftNav.tsx, assets/src/components/nav/topNavMobile.tsx, assets/src/contexts/notificationsContext.tsx, assets/src/hooks/useVehicleForNotification.ts, assets/tests/components/nav/leftNav.test.tsx, assets/tests/components/nav/topNavMobile.test.tsx, assets/tests/contexts/notificationsContext.test.tsx, assets/tests/hooks/useVehicleForNotification.test.tsx
Asana ticket: [⚙️ Google Analytics | Custom events for Notifications](https://app.asana.com/0/1200180014510248/1202675730248192/f)
This just adds tagging for some events in Google Analytics for some research we're trying to do on usage of the notifications feature. The `tagManagerEvent` function is a helper that encapsulates the modification of the global `window.dataLayer` state that's used to pass things into Google Tag Manager.
=> Notification events

assets/src/util/dateTime.ts, assets/tests/components/propertiesPanel/minischedule.test.tsx, assets/tests/util/dateTime.test.ts
ticket: https://app.asana.com/0/1148853526253437/1202737931015251/f
Interprets the offset given to `formattedScheduledTime` in seconds to match the unit as defined in the TM XML API.
=> fix(formattedScheduledTime): Interpret given offset in seconds

assets/src/components/propertiesList.tsx, assets/tests/components/propertiesList.test.tsx
Asana ticket: [⚙️ Update data null message](https://app.asana.com/0/1200180014510248/1202883819004130/f)
Previously, when we were missing operator information, the application would display "null null #null" in that field. This provides a more user-friendly "Not Available" message as well as handling intermediate cases where some pieces of the operator information are available but others aren't.
=> fix: better handle partially- or fully-missing operator information

assets/css/_nav.scss, assets/css/_notification_drawer.scss, assets/css/_properties_panel.scss, assets/css/_swings_view.scss, assets/css/app.scss, assets/css/properties_panel/_vehicle_properties_panel.scss, assets/src/components/nav/mobilePortraitNav.tsx, assets/tests/components/nav/mobilePortraitNav.test.tsx
ticket: https://app.asana.com/0/1148853526253437/1202946731207901/f
The issue seemed to be that when opening the VPP, the page was rendered with a new grid, which seemed to reset the scroll position of the ladder page. 
I'm not sure that the approach I've taken here is the cleanest one. My intention was to fix the issue without having to introduce storing the scroll position in state. By using one grid class and conditionally hiding the top / bottom navs, the scroll reset issue is no longer a problem. If there is a cleaner or more conventional approach here I am certainly open to changing!
I also wasn't sure of the best way to introduce a regression test for this - there is already test coverage to make sure the navs are conditionally shown / hidden, but maintaining scroll position seems …
=> fix(MobilePortraitNav): use single grid layout to prevent scroll position resetting when a view is opened

.github/workflows/deploy-dev-green.yml
Adds new dev-green deployment action, largely copied from the dev-blue action. 
As part of this new environment setup, a new dev-green environment will need to be configured for the repo and require reviewers set if deploy approvals are desired. I don't seem to have the permissions to enable that - @lemald can you?
=> chore: Add dev-green deployment action

lib/report/user_names_and_uuids.ex, lib/skate/settings/db/user.ex, lib/skate/settings/route_tab.ex, lib/skate/settings/user.ex, lib/skate/settings/user_settings.ex, lib/skate/ueberauth/strategy/fake.ex, lib/skate_web/controllers/auth_controller.ex, lib/skate_web/controllers/page_controller.ex, test/notifications/notification_server_test.exs, test/notifications/notification_test.exs, test/report/user_names_and_uuids_test.exs, test/skate/settings/route_tab_test.exs, test/skate/settings/user_settings_test.exs, test/skate/settings/user_test.exs, test/skate/ueberauth/strategy/fake_test.exs, test/skate_web/controllers/auth_controller_test.exs, test/skate_web/controllers/notification_read_states_controller_test.exs, test/skate_web/controllers/page_controller_test.exs, test/skate_web/controllers/report_controller_test.exs, test/skate_web/controllers/route_tabs_controller_test.exs, test/skate_web/controllers/swing_controller_test.exs, test/skate_web/controllers/user_settings_controller_test.exs, test/skate_web/router_test.exs, test/support/conn_case.ex
ticket: https://app.asana.com/0/1152340551558956/1201189412881312/f
This moves the logic for creating/updating user records into the login flow and adds functionality for saving the user's email.
=> feat: Save user email on login

assets/css/_leaflet.scss, assets/css/_vehicle_map.scss, assets/css/app.scss, assets/css/properties_panel/_vehicle_properties_panel.scss
ticket: https://app.asana.com/0/1200180014510248/1203057881715593/f
Note this adjusts the controls on mobile landscape whether the notch is on the left or righthand side. 
Tested using Xcode simulator on iphone 14 pro max
=> fix(Map): controls not blocked by iphone 'notch' in mobile landscape

README.md
When reading through I noticed that the `POSTGRES_PASSWORD` variable spelling in the `README.md` didn't match the variable in `.envrc.example`.
---
Also, first PR! 🎉
=> fix(README): remove extra `s` from `POSTGRES_PASSWORD`

lib/skate_web/channels/notifications_channel.ex, test/skate_web/channels/notifications_channel_test.exs
This updates the format of the initial notifications message to support the new format expected in https://github.com/mbta/skate/pull/1765 (`%{data: %{initial_notifications: initial_notifications}}`). This PR will need to be merged & deployed first to ensure that both the new and old frontends are simultaneously supported during the deploy of https://github.com/mbta/skate/pull/1765.
=> feat(NotificationsChannel): support new format of initial notifications message

assets/css/_vehicle_map.scss, assets/src/components/map.tsx, lib/schedule.ex, lib/schedule/data.ex, lib/schedule/shape_with_stops.ex, lib/skate_web/controllers/shape_controller.ex, test/schedule/data_test.exs, test/schedule/shape_with_stops_test.exs, test/schedule_test.exs, test/skate_web/controllers/shape_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1203119002718952/f
This PR mostly pulls from https://github.com/mbta/skate/pull/1752 with additional testing.
I couldn't find a suitable way to test for the tooltip's appearance on stop hover in the map component. It seems that the tooltip is only added to the DOM on hover, and after trying a few ways to pass accessible selectors (`title`, `alt`), I didn't find a way to hover over the stop in testing to trigger the tooltip. This is one of the rare cases where I wish RTL had a workaround to find an element by class name! Open to suggestions for other ways to unit test this behavior.
=> feat: Bus stops added to the VPP

assets/package-lock.json, assets/package.json, assets/src/api.ts, assets/src/hooks/useChannel.ts, assets/src/hooks/useNotifications.ts, assets/src/hooks/usePersistedStateReducer.ts, assets/src/models/ladderDirection.ts, assets/src/models/notificationData.ts, assets/src/models/routeTab.ts, assets/src/models/swingsData.ts, assets/tests/api.test.ts, assets/tests/hooks/useChannel.test.ts, assets/tests/hooks/useNotifications.test.tsx, assets/tests/hooks/useNotificationsReducer.test.tsx, assets/tests/hooks/usePersistedStateReducer.test.ts, assets/tests/models/notificationData.test.tsx
Asana ticket: [⚙️ Adopt Superstruct](https://app.asana.com/0/1152340551558956/1201917242620476/f)
It will help to refer to the [section of the Superstruct docs on Typescript](https://docs.superstructjs.org/guides/06-using-typescript) to understand these changes.
There are many places in the code that we will eventually want to change to use Superstruct, but for new this gets us started with a few examples. In particular, it establishes the `checkedApiCall` and `useCheckedChannel` corollaries of the existing `apiCall` and `useChannel` functions, which will be important for most future places where we want to use the library.
We already had the convention of having a separate `FooData` type in addition to `Foo` and having a parser to transform from the former to the latter. I have built on …
=> Use Superstruct for (some) back-end data

priv/repo/migrations/20221031170029_add_test_group.exs
Asana ticket: [⚙️ Database work for user test groups](https://app.asana.com/0/1200180014510248/1202519045249746/f)
The one thing worth noting about this change is that normally for a join table like this I wouldn't include a primary key, but the way that Ecto implements `through` associations (see upcoming PR) seems to require a primary key on the intermediate table. In any event I don't think it hurts anything even if it later turns out we figure out a way to avoid using it.
=> chore: migration to add test_groups and test_groups_users tables

assets/src/components/map.tsx, assets/tests/components/map.test.tsx
When the `Autocenterer` calls `autoCenter` in rapid succession before the animation of the map pan/zoom is finished, the autocentering control gets disabled by out of order events recieved by `useMapEvents`.
This PR uses `dragstart` to detect _user_ input, which disables the autocentering mode. In addition, the movestart handler has been changed to `zoomstart` because there are no other _user specific_ events fired when the zoom level also changes, and `zoomstart` is fired by `[leaflet::]setView` when the zoom level needs to change.
---
Asana Ticket: https://app.asana.com/0/1148853526253437/1199678649889552/f
=> fix(components/map): ensure autocentering stays on when backgrounded

lib/report.ex, lib/report/user_configurations.ex, test/report/user_configurations_test.exs, test/report_test.exs
ticket: https://app.asana.com/0/1152340551558956/1201646081199380/f
A new report to understand how users will be affected by the above ticket. 
There is an existing `UserSettings` report that includes only settings with no username attached. I opted to create a new report for this specific use case, but can combine into the existing `UserSettings` report if that seems more appropriate.
=> feat(Reports): New report for all user configuration

lib/report/user_configurations.ex, test/report/user_configurations_test.exs
A fix for https://github.com/mbta/skate/pull/1784 - 
using `inspect` resulted in strings being turned for lists where the numbers in that list were all codepoints. For example, someone with a tab that has 7 routes and another with 8 would return '\a\b', instead of the expected "[7, 8]". 
Now, the number of routes is converted to a string & concatenated.
=> fix(Report.UserConfigurations): routes per tab as comma separated list

assets/src/userTestGroups.ts, assets/tests/laboratoryFeatures.test.ts, assets/tests/userTestGroups.test.ts, lib/skate/settings/db/user.ex, lib/skate_web/controllers/page_controller.ex, lib/skate_web/templates/page/index.html.eex, test/skate_web/controllers/page_controller_test.exs
This implements access to a user's test groups via storing the information in the database schema, rendering it to the frontend, and providing a utility function to access the data.
---
Closes: https://app.asana.com/0/1200180014510248/1202519045249749/f
=> feat(skate/test-groups): send test group information to frontend

Dockerfile
No ticket, just a quick fix to make the deploy work again.
=> chore: update hash of AWS certificate bundle for RDS

lib/skate/settings/user.ex, lib/skate_web/auth_manager.ex, lib/skate_web/channels/vehicles_channel.ex, lib/skate_web/controllers/auth_controller.ex, lib/skate_web/controllers/notification_read_states_controller.ex, lib/skate_web/controllers/page_controller.ex, lib/skate_web/controllers/route_tabs_controller.ex, lib/skate_web/controllers/user_settings_controller.ex, test/skate/settings/user_test.exs, test/skate_web/auth_manager_test.exs, test/skate_web/channels/notifications_channel_test.exs, test/skate_web/channels/vehicles_channel_test.exs, test/skate_web/controllers/notification_read_states_controller_test.exs, test/skate_web/controllers/page_controller_test.exs, test/skate_web/controllers/route_tabs_controller_test.exs, test/skate_web/controllers/test_group_controller_test.exs, test/skate_web/controllers/user_settings_controller_test.exs, test/support/channel_case.ex, test/support/conn_case.ex
ticket: https://app.asana.com/0/1200180014510248/1203331355829267/f
Followed the basic setup instructions from https://hexdocs.pm/guardian/introduction-implementation.html#basic-setup.
This allows us to move away from the AD username as the subject of the token to Skate's internal user id PK. The old username format is supported for backwards compatibility and can be removed once all the outstanding old tokens are expired (expected after 1 hour of deploying, will confirm with logs)
=> feat(AuthManager): Accept user_id as token subject

.github/workflows/ci.yml
I upgraded some of the other GitHub Actions we used in #1759 but it looks like I forgot about this one.
=> chore(ci): bump version of upload-artifact to one that uses Node 16

lib/skate_web/auth_manager.ex, test/skate_web/auth_manager_test.exs, test/skate_web/channels/channel_auth_test.exs, test/skate_web/channels/data_status_channel_test.exs, test/skate_web/channels/notifications_channel_test.exs, test/skate_web/channels/train_vehicles_channel_test.exs, test/skate_web/channels/user_socket_test.exs, test/skate_web/channels/vehicle_channel_test.exs, test/skate_web/channels/vehicles_channel_test.exs
ticket: https://app.asana.com/0/1200180014510248/1203331355829267/f
This must be deployed 60+ minutes after https://github.com/mbta/skate/pull/1790 to ensure that there are no valid tokens with the old format out in the wild. Confirm no more logs of `old_pattern_matched` before deploying.
=> feat(AuthManager): Remove support for old username-only resource/subject

Dockerfile
to fix failing deploys: https://github.com/mbta/skate/actions/runs/3489790242
=> chore: Update AWS certificate bundle hash

Dockerfile
Seems it updated again because of https://github.com/mbta/skate/actions/runs/3498816299
I'll open a tech debt ticket to look into automating this.
=> chore(aws-cert-bundle): update pinned file hash

config/config.exs, config/prod.exs, test/skate_web/channels/user_socket_test.exs
Ticket: https://app.asana.com/0/1200180014510248/1203412139193191/f
Phoenix Sockets use the Phoenix Logger, so we need to configure its filter parameters too.
=> fix(Logger): Filter socket logs too

assets/src/components/app.tsx, assets/src/components/map.tsx, assets/src/components/mapPage.tsx, assets/src/components/nav/bottomNavMobile.tsx, assets/src/components/nav/leftNav.tsx, assets/src/components/searchForm.tsx, assets/src/components/searchPage.tsx, assets/src/components/searchResults.tsx, assets/src/hooks/useShapes.ts, assets/src/userTestGroups.ts, assets/src/util/mapMode.tsx, assets/src/util/streetViewUrl.ts, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/map.test.tsx, assets/tests/components/mapPage.test.tsx, assets/tests/components/nav.test.tsx, assets/tests/components/nav/bottomNavMobile.test.tsx, assets/tests/components/nav/leftNav.test.tsx, assets/tests/components/searchForm.test.tsx, assets/tests/components/searchPage.test.tsx, assets/tests/components/searchResults.test.tsx, assets/tests/hooks/useShapes.test.ts, assets/tests/util/mapMode.test.tsx, assets/tests/util/streetViewUrl.test.ts, lib/skate_web/router.ex
ticket: https://app.asana.com/0/1200180014510248/1203329634351702
There are some minor comments in the thread for that ticket, but I don't think they should block an initial review.
My general approach for this ticket was to create a new `MapPage` component as a copy of the existing `SearchPage` so that it is easy to make changes to the component without affecting the old `SearchPage` that all users should currently still see. The `MapPage.test.tsx` file is a copy of `SearchPage.test.tsx` as well, with only the relevant click interaction tests changed.
=> feat: setup for separate maps mode

lib/concentrate/consumer/vehicle_positions.ex, lib/realtime/alerts_fetcher.ex, lib/realtime/server.ex, lib/realtime/supervisor.ex, lib/skate_web/channels/alerts_channel.ex, lib/skate_web/channels/user_socket.ex, test/realtime/alerts_fetcher_test.exs, test/realtime/server_test.exs, test/skate_web/channels/alerts_channel_test.exs, test/skate_web/channels/vehicle_channel_test.exs, test/skate_web/channels/vehicles_channel_test.exs
Asana ticket: [🎨⚙️ Show existing diversions on route ladder](https://app.asana.com/0/1200180014510248/1203142766477809/f)
This is exclusively the back-end code for the ticket. The front-end will follow in another PR, and we'll want to release the back-end first so that the channel is available when the front-end code is deployed.
There were a few possible ways to pull this alert data in and make it available to the channel. It may have been advantageous to use [Server Sent Event-based streaming](https://www.mbta.com/developers/v3-api/streaming), both for reducing latency and conserving bandwidth. However, that would involve managing the alerts on a by-ID basis, whereas we prefer to keep them grouped by route ID for internal purposes. This wasn't an insurmountable barrier but it would have …
=> Detour alerts backend

lib/realtime/data_status_pub_sub.ex, lib/realtime/server.ex, lib/skate_web/authenticated_channel.ex, lib/skate_web/channels/alerts_channel.ex, lib/skate_web/channels/channel_auth.ex, lib/skate_web/channels/data_status_channel.ex, lib/skate_web/channels/notifications_channel.ex, lib/skate_web/channels/train_vehicles_channel.ex, lib/skate_web/channels/vehicle_channel.ex, lib/skate_web/channels/vehicles_channel.ex, test/skate_web/channels/alerts_channel_test.exs, test/skate_web/channels/channel_auth_test.exs, test/skate_web/channels/data_status_channel_test.exs, test/skate_web/channels/notifications_channel_test.exs, test/skate_web/channels/train_vehicles_channel_test.exs, test/skate_web/channels/vehicle_channel_test.exs, test/skate_web/channels/vehicles_channel_test.exs
When initiating a connection to the server the token is validated, but when joining a channel the socket is not checked to be authenticated.
[Phoenix.Channel Documentation on Authorization](https://hexdocs.pm/phoenix/Phoenix.Channel.html#module-authorization) says that 
> Your channels must implement a join/3 callback that authorizes the socket for the given topic.
So this PR modifies all channel `join/3` callbacks to instead be `join_authenticated/3` which is wrapped by `SkateWeb.AuthenticatedChannel` (name and file location not final) so that authentication code does not need to be manually written and managed for new topics, and should make implementing new channels safer.
Use of `SkateWeb.AuthenticatedChannel` shims a `Phoenix.Channel` `@callback join/3` into the module, which firsts …
=> fix(skate-web/channels): ensure token is authenticated when joining channels

lib/geonames.ex, test/geonames_test.exs
Asana ticket: [⚙️ Investigate intermittent external API request errors](https://app.asana.com/0/1148853526253437/1203468822722733/f)
This adds some simple logic to retry Geonames API requests once if they fail. This is done synchronously in the request to `IntersectionController`, but since the front-end doesn't block on that request I'm not too worried about the latency. Also, failed requests take only ~50ms on average. In about an hour of testing on dev-blue we logged 44 failed requests and every one of them succeeded with the single retry, so I'm fairly confident that this will put a big dent in the number of user-visible failures.
=> Retry failed Geonames requests

lib/schedule.ex, lib/schedule/data.ex, lib/schedule/gtfs/stop.ex, lib/schedule/shape_with_stops.ex, lib/skate_web/controllers/stop_controller.ex, lib/skate_web/router.ex, test/schedule/data_test.exs, test/schedule/gtfs/stop_test.exs, test/schedule_test.exs, test/skate_web/controllers/shape_controller_test.exs, test/skate_web/controllers/stop_controller_test.exs, test/support/factory.ex
ticket: https://app.asana.com/0/1200180014510248/1203442408293386/f
This PR includes setting the `location_type` field on stops when parsing from GTFS and adding a new StopController for getting all stops where the `location_type` is `:station`.
To be used on the FE for adding stations to the map, see https://github.com/mbta/skate/pull/1872
=> feat: Add endpoint for getting all stations

assets/src/components/scheduleAdherence.tsx, assets/src/components/vehicleRouteSummary.tsx, assets/tests/components/shuttleMapPage.test.tsx, assets/tests/components/vehiclePropertiesCard.test.tsx, assets/tests/components/vehicleRouteSummary.test.tsx, assets/tests/factories/ghost.ts, assets/tests/factories/vehicle.ts
This slipped through #1873 
This is the simplest fix for this, but I think this logic should be pushed down further into the components used so that they can be used in more contexts. 
So looking for thoughts on if it's worth perusing allowing `ScheduleAdherence` to handle `Ghosts` and `Shuttles` by returning `null` to disable rendering instead of handling that within `VehicleRouteSummary`.
I kinda feel that the `output` element returned by `VehicleRouteSummary` should always be returned (and this thought currently applies to sub elements which create elements in the accessibility tree) and the text content within the accessibility nodes should be removed instead.
---
Related: #1873 
Asana Ticket: https://app.asana.com/0/1200180014510248/1203502925530262/f
=> fix: do not display adherence info for shuttles

assets/src/components/map.tsx
This does an initial refactor to <Map/> needed to be able to have a separate implementation and more control over the autocentering function needed to complete the asana ticket.
Looking for feedback related to feasibility and if this seems like the right direction to go in to allow autocenterer to be wielded with more specificity.
This does not change any functionality of the autocenterer or the map and does it's best to preserve existing tests and features. Tests have been used to ensure that functionality remains the same as it did before this PR so that it may be iterated on in the future.
If I were to spend more time on this, I would convert the RecenterButton control to be a `input[checkbox] role=switch` and change tests to use `toBeChecked()` instead of the existing tests which test …
=> refactor(ts/components/map): separate Autocenterer from map to allow configuration through composition

assets/css/_vehicle_route_summary.scss, assets/src/components/mapPage.tsx, assets/src/components/vehiclePropertiesCard.tsx, assets/src/components/vehicleRouteSummary.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/mapPage.test.tsx, assets/tests/components/vehiclePropertiesCard.test.tsx
This does the final work allowing the VPC to also handle ghost types. Additionally, there were a few easy style changes that I ran by design and added as well. 
I see the biggest issue being around where to put type boundaries for components. I felt it was best to have a component handle as many relevant types as possible (within reason) until a final verdict is reached where only a single type can pass. 
This is why the current location component can accept a `VehicleOrGhost` argument, despite always returning the same string for a ghost, this is made type safe by the component which is used which can only display a location if the type is a `Vehicle`.
---
Asana Ticket: https://app.asana.com/0/1200180014510248/1203641819945189/f
=> fix(ts/components/mapPage): ghost card implementation and fixes

assets/css/nav/_left_nav.scss, assets/src/components/app.tsx, assets/src/components/mapPage.tsx, assets/src/components/nav.tsx, assets/src/components/nav/leftNav.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/mapPage.test.tsx, assets/tests/components/nav.test.tsx, assets/tests/components/nav/leftNav.test.tsx
Asana ticket: [⚙️ Better Maps | Disabled Left Nav View Buttons](https://app.asana.com/0/1200180014510248/1203641819945181/f)
This should address all of the acceptance criteria aside from the tooltip. The issue with the tooltip is that, if we set `disabled` on the button, the various events that might trigger the tooltip, like mousing over it, don't fire. It would probably be possible to work around this somehow, for instance by not actually using the `disabled` attribute, that would result in less standard HTML and presumably break web conventions. We'll revisit this and decide whether it's worth somehow including. A couple of other minor things:
1. I may revisit some of the styling of the SVG icons themselves in the disabled state based on design feedback.
2. After discussion on Slack we …
=> Disable views on search map

assets/css/_ui_kit.scss, assets/css/_vehicle_map.scss, assets/src/components/map.tsx, assets/src/components/mapMarkers.tsx, assets/src/components/stopCard.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/mapMarkers.test.tsx
I grouped vehicles into panes to make debugging in devtools easier as well as making z-index/stacking context a little easier to manage, we could do this manually by setting z-index per item if that'd be preferred, but I liked the way that panes helped keep things grouped. A difficulty here is that I don't think `BaseMap` should have as many props as it does and provide as much default functionality as it does, mainly because we'd have to add more props to allow users of `BaseMap` to put things into the pane's that it reserves for itself.
I also dislike that pane's specify their z-index via the `style` attribute, but there wasn't a `zindexOffset` like there is for `Markers`. Leaflet seems to set z-index according via css which matches the [pane `z-index` values provided in the leaflet …
=> feat(map-stops): tap targets selection state and style+size updates

assets/css/_vehicle_map.scss, assets/src/components/mapMarkers.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/src/data/shapesBlue.ts, assets/src/data/shapesGreen.ts, assets/src/data/shapesMattapan.ts, assets/src/data/shapesOrange.ts, assets/src/data/shapesRed.ts, assets/src/schedule.d.ts, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap, assets/tests/components/mapMarkers.test.tsx, assets/tests/components/mapPage.test.tsx, assets/tests/components/mapPage/mapDisplay.test.tsx
ticket: https://app.asana.com/0/1200180014510248/1203766403597552/f
**Note:  userEvent => fireEvent for some tests**
Adding a tooltip to shapes caused existing tests to fail where a route shape is clicked. Kudos to @firestack for helping me debug and pointing me to the fact that the `clientX` and `clientY` were undefined [here](https://github.com/Leaflet/Leaflet/blob/9c58fcdd0a61167bafc4496528aaece1e4fe44af/src/dom/DomEvent.js#L259), leading to an `Invalid LatLng object: (NaN, NaN)` error. 
Stepping into [here](https://github.com/Leaflet/Leaflet/blob/3f5ea5a271b41ec09147ea774fea90bc960a1ab2/src/map/Map.js#L1419), `clientX/Y` was not `in src` [here](https://github.com/Leaflet/Leaflet/blob/3f5ea5a271b41ec09147ea774fea90bc960a1ab2/src/core/Util.js#L14). This was not the case when stepping …
=> feat(RouteShape): Tooltip + updated selected, hover states

assets/src/components/nav.tsx, assets/src/components/nav/mobilePortraitNav.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap
Asana ticket: [⚙️🐞 Better Maps | Investigate how to not re-render components when breakpoint changes ](https://app.asana.com/0/1148853526253437/1203180633835795/f)
This just reorders the children of `<Nav />` so that, regardless of which variant of the nav is rendered, the children end up under a `<div>` which is the first child of the main `<div>` of the overall nav component. This keeps the children in the same place in the UI tree and therefore causes React to preserve their state. The React documentation on [Preserving and Resetting State](https://beta.reactjs.org/learn/preserving-and-resetting-state) was a useful reference here (kudos to @firestack for pointing me to it).
=> fix: position children in the same spot under Nav in all variants

assets/src/components/mapMarkers.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/src/components/stopCard.tsx, assets/src/contexts/mapSafeAreaContext.tsx
This PR implements a simple way of getting the "safe zone" passed down into the component tree to use leaflet's `autoPanPadding` features[^1]. We could probably also use the new context provider to provide the safe zone bounds for the follower logic too.
The two largest problems were
- Should this be done via Context or Prop Drilling? (or something else?)
- What should these new components/contexts/types be named. (All the names are composite names, which has been difficult to find something which feels "right")
I'm still considering the names used and would appreciate any input's y'all may have.
- Design and product approved this solution as ok for MVP fidelity
---
Asana Ticket: https://app.asana.com/0/inbox/1203014709797732/1203674636294159/1203947212316076
[^1]: …
=> feat(ts/components/stopCard): prevent stop card from being obscured

assets/css/_leaflet.scss, assets/css/_map_page.scss, assets/css/_search_page.scss, assets/css/properties_panel/_vehicle_properties_panel.scss, assets/src/components/mapPage.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/mapPage.test.tsx
Asana ticket: [⚙️ Better Maps | Search Map behavior at <=800px](https://app.asana.com/0/1200180014510248/1203888345713854/f)
Simply removing the unneeded code seems to have worked as expected. I did also have to play around with the z-index of the search drawer a little bit because on narrow screens it becomes apparent that the Leaflet controls actually have a higher z-index than what we were using, so I replaced `$leaflet-pane-z-index` with a new variable that represents the maximum z-index out of the entire Leaflet CSS file.
=> Map page narrow screen behavior

assets/css/_late_view.scss, assets/css/_notification_drawer.scss, assets/css/_swings_view.scss, assets/css/app.scss
Non-ticketed hotfix.
We updated the `z-index` of the search panel to make sure it appears above all of the contents of the Leaflet map, however it turns out that on mobile the search panel is now staying on top of the view - see attached screenshot.
This update keeps the navbar above the views, and also integrates views into the `$z-page-layout-context` map we have. It doesn't integrate those with the `$max-leaflet-z-index` constant unfortunately as I suspect that might be a larger lift (at least on the QA side) and I'd like to get this fix out.
=> fix: don't position search page contents over views

assets/css/_vehicle_map.scss, assets/css/app.scss, assets/css/map/controls/_street_view_switch.scss, assets/src/app.tsx, assets/src/components/map.tsx, assets/src/components/map/controls/StreetViewSwitch.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap
A few notes
I added a prefix to the BEM class name when I moved it into it's own file since this feels like it's own component rather than just a subcomponent of the map.
Also, I was able to stop fighting with leaflet and bootstrap css specificity by importing them first before any of our styles, I don't think I missed anything or caused any problems and I didn't see anything but that might be a good thing to mull over a bit.
Also bootstrap's component was making it somewhat difficult to get layout to look nice, so I ended up overriding padding and margins to shrinkwrap the div to the input, I don't like having had to override bootstrap and worry I may have misunderstood why the padding/negative margins were used in the first place.
---
Asana Ticket: …
=> feat(ts/components/map): make street view switch fit on smaller screen sizes

assets/package-lock.json, assets/package.json
This reverts commit 27f6943a7a5902ecd82fd88e83e986c23954e43d.
We got a bunch of new warnings about updates not being wrapped in `act` - we'll eventually need to revisit this and identify the root cause but for now I'm going to revert.
=> Revert "build(deps-dev): bump @testing-library/react in /assets (#1932)"

assets/src/components/routeLadder.tsx, assets/src/helpers/svgIcon.tsx, assets/src/util/mapMode.tsx, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/routeLadder.test.tsx, assets/tests/helpers/icon.test.tsx, assets/tests/helpers/svgIcon.test.tsx, assets/tests/testHelpers/selectors/components/routeLadder.ts
So I found that [SVG refactor](https://github.com/mbta/skate/pull/1874) did cause the Tippy issues due to the `ref` prop not being available for `Tippy` to use to hook into events the DOM node will receive.
So while we could wrap every `<SvgIcon/>` that's a direct child of a `Tippy` with a element which Tippy could use the `ref` prop on, I felt that making `<SvgIcon/>` work "correctly" was the better choice.
This had downstream effects
- `SvgIcon`'s are now `ExoticComponent`s, which means they cannot be called directly, and instead need to be instantiated via JSX.
- Usages of `SvgIcon` which assumed what the shape(parameters + return type) of the function would be needed to be updated to use `JSXElementConstructor` instead (mapMode.tsx).
---
Asana Ticket: …
=> [⚙️🐞] fix(ts/components/routeLadder): route ladder detour icon popup

assets/src/components/mapPage/mapDisplay.tsx
The stop markers were under the station markers because the stop markers used the default `z-index` of the markers pane (`400`) but the station markers were moved into their own pane of `z-index` `410`.
This makes another pane similar to the `routeStopMarkers` pane at `zIndex` `450` as this was the easiest way to address this bug.
I tried to reuse the existing `routeStopMarkers` pane by setting `pane="routeStopMarkers"` on the `<StopMarker>` component, but this breaks both encapsulation and tests. While I think that would be one of the nicer solutions, it required a larger refactor than would be useful to make it work.
Similarly, I've been considering pulling out some self contained components of the `<BaseMap>`, such as converting the `stations` prop into a `includeStations` prop similar …
=> fix(ts/components/mapPage): put stop markers on top of station markers

assets/src/components/map.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/src/components/propertiesPanel/miniMap.tsx, assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx, assets/src/components/searchPage.tsx, assets/src/components/shuttleMapPage.tsx, assets/tests/components/map.test.tsx, assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx, assets/tests/components/shuttleMapPage.test.tsx, assets/tests/testHelpers/selectors/components/map.ts, config/dev.exs
Asana ticket: [⚙️🐛 Subsequent clicks on shuttle map entry don't start auto-centering](https://app.asana.com/0/1148853526253437/1203884615154359/f)
=> Make shuttle map re-enable autocenter when selected shuttle changes

assets/src/components/lateView.tsx, assets/tests/components/__snapshots__/lateView.test.tsx.snap
No Asana ticket, just something we noticed as a consequence of #1962 .
=> fix: add fs-mask class to operator name in Late View

assets/src/components/crowdingIcon.tsx, assets/src/components/ladder.tsx, assets/src/components/map.tsx, assets/src/components/map/controls/StreetViewSwitch.tsx, assets/src/components/mapMarkers.tsx, assets/src/components/mapPage/vehiclePropertiesCard.tsx, assets/src/components/notificationBellIcon.tsx, assets/src/components/propertiesPanel/header.tsx, assets/src/components/propertiesPanel/minischedule.tsx, assets/src/components/routePill.tsx, assets/src/components/routeVariantName.tsx, assets/src/components/scheduleAdherence.tsx, assets/src/components/streetViewButton.tsx, assets/src/components/vehicleIcon.tsx, assets/src/helpers/dom.ts, assets/tests/helpers/dom.test.ts
the `className` function often collides with either local variables or sometimes even props/arguments. This rename is intended to make it clear what the function does as well as have less collisions.
=>  refactor(ts/helpers/dom): rename function `className` to `joinClasses` 

assets/src/components/mapPage/mapDisplay.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/mapPage.test.tsx
Asana ticket: [⚙️🐛 Selected vehicle can disappear from map in Search Map page](https://app.asana.com/0/1200180014510248/1204291981474926/f)
It turns out that we actually had the vehicle from `useVehicleForId`, but the actual display was happening via the `RouteVehicles` component which uses `useVehiclesForRoute`. This separates things out so that `SelectedVehicleDataLayers` always displays the selected vehicle directly, and `RouteVehicles` displays all of the vehicles on the route _except for_ the selected one.
Also extends one of the snapshot `MapPage` tests to display a non-primary vehicle on the route, to verify that both are rendered properly before and after this change.
=> Stop selected vehicle from disappearing when no longer on its original route

assets/src/components/notificationBellIcon.tsx, assets/src/components/notificationDrawer.tsx, assets/src/components/notifications.tsx, assets/src/hooks/useNotificationsReducer.ts, assets/tests/components/__snapshots__/notificationDrawer.test.tsx.snap, assets/tests/components/notificationDrawer.test.tsx, assets/tests/contexts/notificationsContext.test.tsx, assets/tests/hooks/useNotificationsReducer.test.tsx
ticket: https://app.asana.com/0/1148853526253437/1202584021125991/f
This adds `null` to the type of notifications.
A couple of other approaches I considered
* using `FetchResult` 
* incorporating the existing `isInitialLoad` variable which isn't currently part of the state returned by `useNotificationsReducer`
Ultimately I opted for this simpler change of only adding `null` to the type, but open to other suggestions!
=> feat(NotificationsDrawer): New loading state

assets/src/api.ts, assets/tests/api.test.ts
Asana ticket: [⚙️ Add defaultResult for fetchRoutes API call](https://app.asana.com/0/1148853526253437/1201313313124099/f)
This ended up being fairly easy as changing the types to make `defaultResult` required revealed that `fetchRoutes` and `fetchSwings` are the only places that it needed to be added. If we're not yet adding a separate user-facing loading state, an empty array is a sensible return value (and is what is used for other similar API calls that return arrays, like the similar `fetchShuttleRoutes`).
=> refactor: require defaultResult for apiCall

lib/skate/application.ex, lib/skate/remove_users_without_email.ex, lib/skate/settings/user.ex, test/skate/remove_users_without_email_test.exs, test/skate/settings/user_test.exs, test/support/factory.ex
We confirmed locally that when a user is deleted in the DB the deletion cascades to records linked via foreign key. We considered writing a test for this but due to unknown complexity opted for testing manually.
We've deployed this on dev green and successfully removed 1 user which did not have an email associated. We also need to run this on `dev blue`, `dev`, and `prod` to clean up the DB records for each environment, before we remove this code in #2026.
DB Cleanup applied to
---
- https://app.asana.com/0/0/1204389997693497
=> cleanup(ex/skate/database): remove users without email

lib/skate_web/templates/layout/app.html.eex
I noticed that the `meta` `charset` tag wasn't the first entry in the `head` tag. We use UTF-8 which is the default `charset` so this shouldn't have any impact on browsers parsing this page.
[`<meta charset>` tag MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset)
=> fix(frontend-template): put meta `charset` tag in first `1024` bytes

assets/css/_u_no_overscroll.scss, assets/css/app.scss
While this does clean up overscroll on iOS, this also disables pull to refresh on both iOS and Android Chrome.
I tried querying fullstory for users who use the pull to refresh feature, but there was no definitive way to find when a scroll triggered a refresh, especially as pull to refresh doesn't actually show up in fullstory.
For this reason, this should not be merged without design and product review.
I have tested and confirmed that this works on a real iPhone, but the behavior is unchanged in the simulator because it turns out that it does not respect these css properties.
---
EDIT: So I've learned that [`overscroll-behavior` was implemented on iOS as of Sep 2022](https://caniuse.com/css-overscroll-behavior), which is a bit to recent to rely upon. Fortunately, css simply ignores this …
=> fix(ui/overscroll): disable overscroll behavior

lib/skate_web/auth_manager/error_handler.ex, lib/skate_web/controllers/auth_controller.ex, test/skate_web/auth_manager/error_handler_test.exs, test/skate_web/controllers/auth_controller_test.exs
Asana ticket: [⚙️ Prevent infinite redirects on auth failure](https://app.asana.com/0/1152340551558956/1201523184137417/f)
I opted to use the Plug session to store a retry count in cookies and allow at most 3 tries. This will likely be enough to still prevent most of the user-facing errors while also not causing people to hit a redirect loop. We still reset the retry count on either a successful login or when the limit is hit, so the user can always hit refresh to try again manually.
=> feat: limit auth failure retry to 3 attempts

README.md, mix.exs
I'd gotten used to the aliases that come in Phoenix 1.7 and I want them back! 😭
These are a few quality of life improvements that make setting up a new project folder or getting up to speed a bit faster and require less manual interaction.
I basically just copied the aliases from the my-charlie project that were generated by the phoenix application template and updated the readme a bit.
=> feat(mix): add mix aliases for setup and reset

assets/css/_map_page.scss, assets/css/_search_page.scss
ticket: https://app.asana.com/0/1148853526253437/1204649005443955/f
This PR sets the z-index of the map and search drawer within the search page. This creates a new stacking context for each, so that they can be z-indexed relative to each other as a whole unit. In trying to better understand stacking contexts for this ticket, I found the folder and file analogy in[ this article ](https://www.lullabot.com/articles/understanding-debugging-stacking-contexts)very helpful! 
This PR makes the same change to the new map page too, which didn't have the same bug but was prone to the same issue of search drawer & map elements being within a single stacking context.
=> fix(SearchPage): Resolve mobile z-index issues

lib/concentrate/vehicle_position.ex, test/concentrate/vehicle_position_test.exs
ticket: https://app.asana.com/0/1148853526253437/1204382924233721/f
=> fix(Concentrate.VehiclePosition.merge/2): Prioritize swiftly block_id when there isn't a block overload

assets/css/_map_page.scss
Asana ticket: followup on [⚙️ Better Maps | RPC Usability Updates](https://app.asana.com/0/1200180014510248/1204680913839484/f)
Related to [this comment](https://github.com/mbta/skate/pull/2077#discussion_r1228180802), it turns out that the exact location of the `<hr/>` in the DOM varied depending on whether search results or a selection was being displayed, so fixing the CSS for one broke it for the other. Working around that by just going with the descent combinator rather than direct child.
=> fix: proper styling of hr regardless of search state

assets/css/_map_page.scss
When the parent flexbox is laying out elements, it shrinks this one as there is no `min-height`. This tells flex to not do that.
- set flex to
- minimum size `1px`
- do not shrink
- do not grow
--- 
Merge after #2088
=>  fix(css/_map_page): make visual separator visible on results view 

lib/realtime/vehicles.ex, lib/schedule.ex, lib/schedule/data.ex, lib/schedule/trip.ex, test/realtime/vehicles_test.exs, test/schedule/data_test.exs, test/schedule/trip_test.exs, test/schedule_test.exs
ticket: https://app.asana.com/0/1148853526253437/1204758166006987/f
Since the only use of `active_trips` was within `Realtime.Vehicles`, I opted to remove it in favor of `trips_starting_in_range`. If you think it should be preserved, I'll add it back in!
=> fix(Realtime.Vehicles): don't list interlining vehicles as incoming on their old route)

config/config.exs, config/runtime.exs, lib/skate/application.ex, lib/skate/warm_up.ex, test/skate/warm_up_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204865954744424/f
This adds logic to attempt concurrent queries to the DB prior to running the migrator to ensure that the connections have started. This is based on the discussion and recommendation in this issue: https://github.com/elixir-ecto/ecto/issues/3428
> Postgrex is asynchronous when it connects to the database. So when the repo starts, you may not have a connection yet. If your database is loaded with extensions, this bootstrap time can be high.
>
>My suggestion is to have a single process immediately after Ecto.Repo in the supervision tree that is responsible for checking for the repository availability:
Two test deployments to dev-green succeeded without DBConnection.ConnectionErrors or task thrashing in ECS:
=> feat(Application): test for connections before running migrator

.envrc.template, assets/src/components/map.tsx, assets/src/tilesetUrls.ts, assets/tests/tilesetUrls.test.ts, config/dev.exs, config/runtime.exs, lib/skate_web/controllers/page_controller.ex, lib/skate_web/templates/page/index.html.eex, test/skate_web/controllers/page_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204573236791609/f
This ticket adds new tileset environment variables to distinguish between the base & satellite URLs. 
I'll add a corresponding terraform PR as well if these variable names look good. 
For the latency consideration of this ticket, testing with throttling for chrome's "fast 3G" setting, satellite tiles were taking ~2 seconds for the first load. Subsequent loads were faster due to browser caching. For the base tileset at the same network speed & location, tile requests took 1-1.5s. 
The ArcGIS tiles have permissive [terms of use](https://massgis.maps.arcgis.com/home/item.html?id=bd1ea555a71649508cb215edcc73feaa):
> No restrictions apply to these data
Order of operations:
* Merge terraform PR configuring these variables
* …
=> feat(tilesetUrls): Expose satellite tileset url

lib/concentrate/parser/swiftly_realtime_vehicles.ex, test/concentrate/parser/swiftly_realtime_vehicles_test.exs
Asana ticket: [⚙️ Ignore operator data from Swiftly](https://app.asana.com/0/1200180014510248/1204818709617516/f)
I figured that since we want to ignore this data entirely it made more sense to simply remove the logic for parsing it, rather than writing some complicated merge logic to discard it, but I'm open to changing my mind on that.
=> feat: don't parse Swiftly operator data

assets/css/app.scss, assets/src/hooks/useScreenSize.ts, assets/tests/hooks/useScreenSize.test.ts
Safari excludes it's scrollbar[^scrollbar-state] from it's media queries by default[^1], so when `useScreenSize` changes the layout of the page, the change in layout can change the width that the media query recieves, which in the `15px` between our tablet breakpoint `1340` and `1355`, will flip flop back and forth between the two breakpoints as the media query changes values.
To fix this, I've changed `useScreenSize` to query the viewport size in javascript, rather than the size that the media queries are getting. This is more in-line with `@media` standards, as the `width` media query is supposed to test against the viewport, not the document width or the viewport without the scrollbar.[^3]
[W3C media query specification for width](https://www.w3.org/TR/css3-mediaqueries/#width):
> The …
=> fix: Safari flash issues

lib/realtime/server.ex, lib/realtime/vehicle_or_ghost.ex, lib/skate_web/channels/user_socket.ex, lib/skate_web/channels/vehicles_search_channel.ex, test/realtime/server_test.exs, test/realtime/vehicle_or_ghost_test.exs, test/skate_web/channels/vehicles_search_channel_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204956501632025/f
This new channel accepts messages to change the value for limit as well as the other search parameters. Otherwise, if limit was part of the topic, then increasing the limit would result in leaving the old topic, resulting in search results being cleared. I'm not totally a fan of how this means the `vehicles_search` topic is generic... very open to alternative ideas! 
I played around a bit with hooking this up to the frontend in `kb-limited-search-results-hook` to make sure we can communicate with this new channel as expected.
=> feat: New vehicle search channel that accepts a limit

assets/css/_circle_x_icon.scss, assets/css/_filter_accordion.scss, assets/css/_map_page.scss, assets/css/_old_search_form.scss, assets/css/_search_form.scss, assets/css/app.scss, assets/src/components/circleXIcon.tsx, assets/src/components/filterAccordion.tsx, assets/src/components/mapPage.tsx, assets/src/components/oldSearchForm.tsx, assets/src/components/searchForm.tsx, assets/src/components/searchPage.tsx, assets/src/components/toggleIcon.tsx, assets/src/helpers/svgIcon.tsx, assets/src/models/searchQuery.ts, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/oldSearchForm.test.tsx.snap, assets/tests/components/__snapshots__/searchForm.test.tsx.snap, assets/tests/components/__snapshots__/searchPage.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/oldSearchForm.test.tsx, assets/tests/components/searchForm.test.tsx, assets/tests/models/searchQuery.test.ts, assets/tests/state/searchPageState.test.ts, assets/tests/testHelpers/selectors/components/map/markers/stopIcon.ts, assets/tests/testHelpers/selectors/components/searchForm.tsx, assets/tests/testHelpers/selectors/components/vehiclePropertiesPanel.tsx
This does a few things to create new components based on old components, while avoiding accidentally modifying the old components.
- Copy `SearchForm` to `OldSearchForm`, update references to point to `OldSearchForm`
- Update `SearchForm` to match new designs, use on Map Page.
- Create `FilterAccordion` mostly from `GarageFilter`
- It's not _exactly_ the same, so I didn't feel comfortable making the `GarageFilter` depend on this component. But I do think we could. Will either implement here or open a ticket based on dev feedback.
- Build a "interactive"(focus state, similar to the bus stop icons) `CircleXIcon`
- note: I don't like that this component name matches that of our `CircleXIcon` from our `icons.tsx` file, but I was unsure what to name it otherwise.
Additionally, the Filter …
=> feat: Implement new search components

assets/src/components/mapPage.tsx, assets/src/components/searchForm.tsx, assets/src/models/searchQuery.ts, assets/tests/components/__snapshots__/searchForm.test.tsx.snap, assets/tests/components/mapPage.test.tsx, assets/tests/components/searchForm.test.tsx, assets/tests/testHelpers/selectors/components/searchForm.tsx
I refactored this component to be able to provide access to the state of the search form for more concise testing.
While building the autocomplete component in the search form, I found that I needed to be able to control the filters and other autocomplete states, but did not want to run into other devs by editing the `StateDispatchContext` reducer just yet.
=> testing(ts/components/[New]SearchForm): refactor search form to expose properties for testing

config/config.exs
ticket: https://app.asana.com/0/1200180014510248/1204925487890874/f
Over the last 30 days, there were 18 occurrences logged where the warmup succeeded in the first 3 attempts and 14 where it did not. Increasing the number of attempts to 5 to hopefully further reduce those failures, which can cause ECS tasks to churn.
<details>
<summary>Tangent investigation to possibly remove Skate.Warmup entirely</summary>
I also looked into whether making `Ecto.Migrator` a child of the supervisor on startup could remove the need for this `Skate.Warmup` all together. Using `Ecto.Migrator` was a change proposed for the [original ticket ](https://app.asana.com/0/1148853526253434/1204865954744424/f)b/c the way migrations were previously run might have been hiding meaningful logs. I didn't explore that …
=> feat(Skate.WarmUp): Increase number of attempts

config/config.exs, lib/skate/warm_up.ex
ticket: https://app.asana.com/0/1200180014510248/1204925487890874/f
Adding some logging to see why warmups fail. I wanted to increase the query timeout based on [this suggestion](https://mbta.slack.com/archives/G01E809HUF2/p1690406117348129?thread_ts=1690394656.624479&cid=G01E809HUF2), but that seemed more challenging than expected based on the findings below. Instead, I'm tempted to *decrease* the timeout between attempts & increase the maximum attempt count in order to get a better since of how long it would take to get a successful attempt. But we do have`Postgrex.Protocol timed out because it was handshaking for longer than 15000ms` error messages, which is maybe enough of a signal that the connection is taking longer than 15 seconds.
Some alternatives that didn't quite pan out, but …
=> feat(Skate.Warmup): More logging for failed queries

assets/src/components/mapPage/searchResultsByProperty.tsx, assets/src/components/searchResults.tsx, assets/src/hooks/useSearchResults.ts, assets/src/hooks/useSearchResultsByProperty.ts, assets/src/util/fetchResult.ts, assets/tests/components/mapPage/searchResultsByProperty.test.tsx, assets/tests/factories/searchQuery.ts, assets/tests/hooks/useSearchResults.test.ts, assets/tests/hooks/useSearchResultsByProperty.test.ts
ticket: https://app.asana.com/0/1200180014510248/1204956501632025/f
=> feat(searchResultsByProperty): No results found message when no results for any property

assets/css/_grouped_autocomplete.scss, assets/css/_search_form.scss, assets/css/app.scss, assets/src/components/groupedAutocomplete.tsx, assets/src/components/searchForm.tsx, assets/src/hooks/useAutocompleteResults.ts, assets/src/models/searchQuery.ts, assets/src/util/math.ts, assets/src/util/operatorFormatting.tsx, assets/tests/components/__snapshots__/searchForm.test.tsx.snap, assets/tests/components/groupedAutocomplete.test.tsx, assets/tests/components/searchForm.test.tsx, assets/tests/factories/searchProperties.ts, assets/tests/hooks/useAutocompleteResults.test.ts, assets/tests/testHelpers/selectors/components/groupedAutocomplete.ts, assets/tests/util/math.test.ts, assets/tests/util/operatorFormatting.test.ts
This creates a new control component for displaying autocomplete results and navigating that control with keyboard & mouse and moving and listening to the document focus state.
The component is then extended to use a hook to retrieve it's results from the back-end.
The the extended component is then embedded into the search form.
---
Asana Ticket: https://app.asana.com/0/1200180014510248/1204956501632027/f
=> feat(ts/components/GroupedAutocomplete): introduce autocomplete component

assets/css/_stop_card.scss, assets/src/components/stopCard.tsx, assets/src/models/shapeData.ts, assets/src/schedule.d.ts, assets/tests/components/stopCard.test.tsx
ticket: https://app.asana.com/0/1200180014510248/1205139488063013/f
PR 1 / 3 in transitioning to read `routes` for a stop, which includes all routes, rather than `connections`, which omits the current route in view.
1 - This
2 - https://github.com/mbta/skate/pull/2165
3 - https://github.com/mbta/skate/pull/2166
Each PR will be merged and deployed separately to prevent a mismatch of fields between the frontend and backend.
Please leave any overarching concerns about this 3 step deployment approach on this PR!
=> feat(StopCard): If there is a routes field, use that rather than connections

assets/src/components/stopCard.tsx, assets/src/models/shapeData.ts, assets/src/schedule.d.ts, assets/tests/components/stopCard.test.tsx, assets/tests/models/shapeData.test.ts, lib/schedule/data.ex, lib/schedule/gtfs/stop.ex, test/schedule/gtfs/stop_test.exs, test/schedule_test.exs, test/skate_web/controllers/route_pattern_controller_test.exs, test/skate_web/controllers/shape_controller_test.exs, test/skate_web/controllers/stop_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1205139488063013/f
PR 3 / 3 in transitioning to read routes for a stop, which includes all routes, rather than connections, which omits the current route in view.
1 - https://github.com/mbta/skate/pull/2164
2 - https://github.com/mbta/skate/pull/2165
3 - This
Each PR will be merged and deployed separately to prevent a mismatch of fields between the frontend and backend.
=> feat(StopCard): Remove unused references to connections field

assets/src/api.ts, assets/src/hooks/useLocationSearchResultById.ts, assets/src/hooks/useLocationSearchSuggestions.ts, assets/src/models/locationSearchSuggestion.ts, assets/src/models/locationSearchSuggestionData.ts, assets/tests/api.test.ts, assets/tests/factories/locationSearchSuggestion.ts, assets/tests/factories/locationSearchSuggestionData.ts, assets/tests/hooks/useLocationSearchResultById.test.ts, assets/tests/hooks/useLocationSearchSuggestions.test.ts, assets/tests/models/locationSearchSuggestionData.test.ts, lib/skate/location_search/aws_location_request.ex, lib/skate/location_search/place.ex, lib/skate/location_search/suggestion.ex, lib/skate_web/controllers/location_search_controller.ex, lib/skate_web/router.ex, test/skate/location_search/aws_location_request_test.exs, test/skate_web/controllers/location_search_controller_test.exs, test/support/factory.ex
Asana ticket: part of [⚙️ Better Maps | Search | Users can search by location](https://app.asana.com/0/1200180014510248/1204971421569464/f)
Most of this is pretty straightforward data plumbing to get the information we need from Amazon and then provide it to the Skate front-end in the form of hooks.
=> Provide autocomplete-related data for location search

assets/src/hooks/useSearchResults.ts, assets/tests/hooks/useSearchResults.test.ts
When a user lands on the search map page but hasn't performed a search yet, don't subscribe to an empty search.
=> fix(useLimitedSearchResults): Don't subscribe to topic when query is empty

.github/workflows/deploy-base.yml, .github/workflows/deploy-dev-blue.yml, .github/workflows/deploy-dev-ecs.yml, .github/workflows/deploy-dev-green.yml, .github/workflows/deploy-prod-ecs.yml, Dockerfile, assets/src/components/searchForm.tsx, config/prod.exs, lib/skate_web/templates/layout/_sentry.html.eex, upload_assets.sh
ticket: https://app.asana.com/0/1152340551558956/1205212771706510/f
This is largely based on Glides' setup of releases https://github.com/mbta/glides/pull/936. There are some differences in this approach in order to limit the scope of this PR based on Skate's existing setup, but I'll call those out with specific comments.
Note: It seems that Sentry may be moving towards "Artifact Bundles" using debug IDs (see [What are Artifact Bundles](https://docs.sentry.io/platforms/node/sourcemaps/troubleshooting_js/artifact-bundles/), debug ID as mandatory and releases as optional in [Uploading Source Maps](https://docs.sentry.io/platforms/node/sourcemaps/uploading/typescript/)). I attempted to take that approach in [kb-sentry-stack-fix](https://github.com/mbta/skate/tree/kb-sentry-stack-fix) but was …
=> feat: Fix sentry source maps

Dockerfile
This is just a random one-off change based on playing around with getting the Skate Dockerfile to build on an ARM system. Currently Skate only runs on Intel systems in production and we don't do a ton of local development inside of Docker, but I think it's good practice to make our build as architecture-independent as possible. It would also be possible to actually do some conditional shell logic to only add the dependencies on non-amd64 systems instead of just `RUN`ing `apk add` unconditionally, but I think that logic could actually be kind of brittle and the added dependencies are only present in the intermediate build image anyway. I'm open to feedback on whether we should do this at all or the specifics of the approach!
=> fix: add build dependencies to assets-builder

.tool-versions, Dockerfile, assets/package-lock.json, assets/package.json
Based on the [Node release schedule](https://github.com/nodejs/release#release-schedule), 20 is the latest version that will be promoted to LTS status, receiving support until 2026. This was mostly a pretty simple upgrade, though ff6bf8c2 involved running `npm install --package-lock-only` to rebuild `package-lock.json` for the new version, which results in a really big diff. In addition, this process caught a conflict in our dependencies that wasn't being flagged previously for some reason, so I upgraded to a new minor version of sass-loader to resolve the issue. I've tested everything locally and also run a successful deploy to dev-green.
=> Move to Node 20

.github/workflows/deploy-base.yml, assets/src/components/searchForm.tsx
See commits associated with a test release [here](https://mbtace.sentry.io/releases/refs-pull-2194-merge_beac67df4cfa3e831eb2d64463702849e4a79144/commits/?project=5303927)
This [sentry error](https://mbtace.sentry.io/issues/4397615686/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0) shows a "Suspect Commit"  & "Open this line in GitHub" link which now both point to the Skate repo, though neither is quite right (likely because this error is from a PR rather than a commit to the master branch)
=> ci: auto associate git commits with release

assets/src/components/mapPage/routePropertiesCard.tsx
Given we have planning Monday, I figured I'd get this done since it was fairly easy and to avoid digging into something deeper at the end of the week.
---
Asana Ticket: https://app.asana.com/0/1200180014510248/1204807646620475/f
=> feat:fix(ts/components/routePropertiesCard): make direction selector label stretch to size of button

assets/src/hooks/usePersistedStateReducer.ts, assets/tests/hooks/usePersistedStateReducer.test.ts
ticket: https://app.asana.com/0/1148853526253437/1204432665252080/f
I was unable to reproduce the flaky test's failure across 1000+ runs, so it has been tricky confirming if these two changes address the root of the problem, but it seems to me that both of these changes would reduce the likeliness of flaky behavior. 
1. awaiting `act`-  this allows us to remove the use of intermediate state variables & `waitFor` in the tests by waiting until all side effects are resolved. Act is still a bit mysterious to me, but I referenced [this explanation](https://github.com/threepointone/react-act-examples/blob/master/sync.md#promises) linked from[ the rtl docs](https://testing-library.com/docs/preact-testing-library/api/#act) for this approach.
2. `useRef` instead of `useState` in the …
=> fix(usePersistedStateReducer.test): Fix flaky test of push tab retry

lib/schedule.ex, lib/schedule/data.ex, lib/schedule/fetcher.ex, lib/skate_web/controllers/stop_controller.ex, lib/skate_web/router.ex, test/schedule/data_test.exs, test/schedule_test.exs, test/skate_web/controllers/stop_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204906972532767/f
As-is, the response data for all stops is 2.77kB and can take ~0.75s for the initial load. I am considering doing a performance improvement to store only `route_ids` on a `stop` rather than `routes` so that less data is returned, which would require separate backend + frontend changes. But sharing now to get initial feedback on this approach!
=> feat(StopController): endpoint for all stops / stations

assets/src/api.ts, assets/src/data/stopsBlue.ts, assets/src/data/stopsGreen.ts, assets/src/data/stopsMattapan.ts, assets/src/data/stopsOrange.ts, assets/src/data/stopsRed.ts, assets/src/hooks/useAllStops.ts, assets/src/models/shapeData.ts, assets/src/models/stopData.ts, assets/src/schedule.d.ts, assets/tests/api.test.ts, assets/tests/components/map.test.tsx, assets/tests/factories/shape_data.ts, assets/tests/factories/stop.ts, assets/tests/factories/stopData.ts, assets/tests/hooks/useAllStops.test.ts, assets/tests/models/shapeData.test.ts, assets/tests/models/stopData.test.ts, assets/tests/testHelpers/selectors/components/mapPage/map.ts, lib/schedule/gtfs/stop.ex, test/schedule/gtfs/stop_test.exs, test/skate_web/controllers/shape_controller_test.exs, test/skate_web/controllers/stop_controller_test.exs
ticket: https://app.asana.com/0/1200180014510248/1204906972532767/f
Adding the nearby stop markers is done as part of https://github.com/mbta/skate/pull/2201, but these hook + typing changes were starting to feel substantial enough to separate out for an isolated review.
This also adds the `vehicle_type` field to `stop`,[ which is null for stations and populated for stops](https://github.com/mbta/gtfs-documentation/blob/master/reference/gtfs.md#stopstxt)
=> feat(useAllStops): Add hook + update typing to support rendering nearby stops

.dockerignore, lib/skate/application.ex, lib/skate/migrate.ex, mix.exs, priv/repo/async_migrations/20230830202227_first_async_migration.exs, test/skate/migrate_test.exs, test/test_helper.exs
ticket: https://app.asana.com/0/1200180014510248/1205378257072522/f
References: 
* [Approach for splitting migrations into two directories](https://dashbit.co/blog/automatic-and-manual-ecto-migrations)
* [Approach for running migrations async on application startup (Arrow)
](https://github.com/mbta/arrow/blob/master/lib/arrow/repo/migrator.ex)
Note: Originally I was considering exposing admin UI to run migrations, but in looking at the approach taken in the Arrow repo, I liked the ability to still trigger the migration automatically on deploy but in a way that doesn't block application start. This still seemed fitting with the spirit of the original [infra thread](https://mbta.slack.com/archives/G01E809HUF2/p1682622136324209) that explored alternative approaches to running all queries in …
=> feat(Skate.Migrate): Support running a subset of migrations async

lib/report.ex, lib/report/notifications_count_estimate.ex, test/report/notifications_count_estimate_test.exs, test/report_test.exs
Asana ticket: part of [⚙️ Bulk delete old notifications_users records](https://app.asana.com/0/1148853526253420/1204432817126652/f)
We don't want to `SELECT count(*)` because that can actually be slow with Postgres' MVCC model, so I followed [these instructions](https://wiki.postgresql.org/wiki/Count_estimate) to get Postgres' internal estimate for the size of the table. This should be sufficient as I only need a rough order of magnitude of how many records we're going to have to delete. When I tried it out on dev-blue, the GET request to `/reports/notifications_count_estimate` took only around 9 ms total.
=> feat: get the Postgres estimate of rows in notifications table

lib/concentrate/parser/gtfs_realtime_enhanced.ex, test/concentrate/parser/gtfs_realtime_enhanced_test.exs, test/support/factory.ex
Asana ticket: background work related to [⚙️ Better Maps | Show pull-backs](https://app.asana.com/0/1200180014510248/1204946801340572/f)
Transit Data is going to no longer using these trip IDs from Busloc in the Concentrate feed, but we still want them. For now we'll check for the new field but fall back to the old one if present, so that we don't need to do deploys simultaneously.
=> feat: handle new tm_trip_id field

assets/css/map/controls/_layers_control.scss, assets/src/components/map/controls/layersControl.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/src/hooks/usePullbackVehicles.ts, assets/src/state/mapLayersState.ts, assets/src/userInTestGroup.ts, assets/tests/components/map/controls/layersControl.test.tsx, assets/tests/components/mapPage/mapDisplay.test.tsx, assets/tests/hooks/usePullbackVehicles.test.ts, assets/tests/state/mapLayerState.test.ts, assets/tests/testHelpers/selectors/components/map.ts, lib/concentrate/consumer/vehicle_positions.ex, lib/realtime/server.ex, lib/realtime/vehicle.ex, lib/schedule/block.ex, lib/skate_web/channels/vehicles_channel.ex, test/realtime/server_test.exs, test/realtime/vehicle_test.exs, test/schedule/block_test.exs, test/skate_web/channels/vehicles_channel_test.exs
Asana ticket: [⚙️ Better Maps | Show pull-backs](https://app.asana.com/0/1200180014510248/1204946801340572/f)
This PR covers everything except for changes to the VPC for pull-backs to show their destination garage. I'm going to put that into a separate PR and release so that I don't have to start out with the new field being `optional` in Superstruct and then later change it to only `nullable`.
It's a minor thing but I don't think I've been entirely consistent with how I've written variables that involve "pull back" in their names. With snake_case I find that `pull_back` looks natural whereas for whatever reason I find `pullback` without capitalizing the "B" looks better in camelCase, but feel free to push back on that.
=> Layer to show pull-backs on search map

priv/repo/async_migrations/20230914153345_add_notifications_created_at_index.exs
Asana ticket: followup on [⚙️ Add index to notification_users table](https://app.asana.com/0/1148853526253420/1204432817126661/f)
I was sort of on the fence about keeping this column at all versus using `inserted_at`, but even if it's not the case now I can imagine a future state where the time that a notification was created doesn't necessarily match when it was reflected in our system. Along with `user_id` on `users_notifications`, this column is the main one used to filter the notifications to serve to a user in [`unexpired_notifications_for_user/2`](https://github.com/mbta/skate/blob/62ee67108692175660edbc882d21fd23823a29bc/lib/notifications/notification.ex#L177). At the current size of the tables I don't think it will make a measurable impact on performance, but if we decide to start …
=> feat: add index for created_at on notifications

assets/src/components/map.tsx, assets/src/components/map/controls/recenterControl.tsx, assets/src/components/map/follower.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/tests/components/map.test.tsx
I was getting a bit annoyed finding these when working on the user location button, so I've factored it out to make it a bit cleaner.
---
Asana Ticket: https://app.asana.com/0/1148853526253420/1205411312261324/f
=> refactor(ts/components/follower): move `follower` and `recenterControl` out of `map.tsx`

.tool-versions, Dockerfile
Node 20.8 is out but it's only about a day old at this point and there isn't an image for it on Docker Hub yet, so I'm going with 20.7.
=> chore: bump node to version 20.7.0

assets/package-lock.json, assets/package.json, assets/webpack.config.js
---
Asana Ticket: [⚙️ Switch to using Asset modules to load SVG's](https://app.asana.com/0/1148853526253420/1205512287746848)
=> cleanup(webpack): remove `svg-inline-loader`

assets/src/hooks/useChannel.ts, assets/tests/hooks/useChannel.test.ts, assets/tests/testHelpers/socketHelpers.ts
Asana ticket: [⚙️ Gracefully handle sessions where authentication expires](https://app.asana.com/0/1148853526253420/1205451125311872/f)
I've been testing this out locally by adjusting `Skate.Ueberauth.Strategy.Fake` to give a token that's only valid for 10 seconds and finding that it works better than before.
On the search page without an active search, the user won't be making any API requests or subscribed to any channels that would notice that the auth is expired (notably, the data status channel sends an `auth_expired` message from the backend but the frontend doesn't do anything with it - something else to look into). In the old state, this meant that when a user goes and tries to perform a search it would silently fail to join the channel.
=> fix: reload page when channel join fails due to authentication

assets/css/map/controls/_layers_control.scss, assets/src/components/map/controls/layersControl.tsx
Asana Ticket: [⚙️ 🐛 Fix radio buttons in map layers menu to no longer look "stretched"](https://app.asana.com/0/1148853526253420/1205524997955955/f)
=> fix(ts/layers_control): make radio button circular and expand option tap targets

assets/src/hooks/useChannel.ts, assets/tests/hooks/useChannel.test.ts, assets/tests/hooks/useNotifications.test.tsx, assets/tests/hooks/useNotificationsReducer.test.tsx, lib/skate_web/authenticated_channel.ex, lib/skate_web/channels/alerts_channel.ex, lib/skate_web/channels/data_status_channel.ex, lib/skate_web/channels/notifications_channel.ex, lib/skate_web/channels/train_vehicles_channel.ex, lib/skate_web/channels/vehicle_channel.ex, lib/skate_web/channels/vehicles_channel.ex, lib/skate_web/channels/vehicles_search_channel.ex, test/skate_web/channels/vehicles_search_channel_test.exs
Asana ticket: [⚙️ Gracefully handle sessions where authentication expires](https://app.asana.com/0/1148853526253420/1205451125311872/f)
This extends the `AuthenticatedChannel` behaviour so that `handle_info` and `handle_in` also check the token status before further processing. There are some other callbacks we could implement like `handle_out` but since we don't currently use them I haven't implemented them yet.
I also updated the `useChannel` and related hooks so that any channels using them will auto-reload on `auth_expired` messages.
=> AuthenticatedChannel improvements

assets/package-lock.json, assets/package.json
No Asana ticket, ad-hoc change to hopefully reduce Node errors in CI.
The choice of packages to upgrade was based on warnings about compatibility that we were seeing as part of `npm install`. However, not all of these could be upgraded because some of them are recursive dependencies where the direct dependencies are already at their latest version and their dependencies require the outdated version of the recursive dependency.
=> Random JS dep updates

assets/src/skate.d.ts, lib/skate_web/templates/layout/_sentry.html.eex
Asana ticket: last bit of [⚙️ Integrate Fullstory and Sentry](https://app.asana.com/0/1148853526253420/1205560495149255/f)
Now that we're using `window.sentryInitialization`, we can get rid of the old `window.sentry` and any references to it.
=> Minor Sentry cleanup

lib/schedule/hastus/trip.ex, test/schedule/hastus/trip_test.exs
Asana ticket: [⚙️ Fix negative duration layovers in minischedules](https://app.asana.com/0/1148853526253420/1205367064394203/f)
It turned out that the issue was that the trips were in reverse order in the GTFS `trips.txt` (which is fine, that file isn't guaranteed to be in any particular order). This adds logic to explicitly sort the trips by their numeric suffix.
I'm sort of of two minds on the `try` / `rescue` part of the code. On the one hand either the pattern matching on the return value of `Regex.scan/3` or the call to `String.to_integer/1` could in theory raise an error, but because of the way `original_id_to_through_routed_trip_ids` is built this case should never happen. That said, if it somehow _did_ happen it could be very bad and would cause the application to fail to fully …
=> fix: sort through-routed trips numerically

assets/src/models/minischeduleData.ts, lib/schedule/hastus/trip.ex, test/schedule/hastus/trip_test.exs
Asana ticket: continuing work from [⚙️ Fix negative duration layovers in minischedules](https://app.asana.com/0/1148853526253420/1205367064394203/f)
The comment I left in `Schedule.Hastus.Trip` explains the rationale behind this change. I have checked the current GTFS and verified that all of the through-routed trips start and end with `stop_times` that have a timepoint ID associated with them, meaning that they will get an origin filled in. That said, I've also updated the front-end code to not crash if it does get a blank start / end place for a trip.
=> fix: don't use HASTUS start / end place for through-routed trips

assets/src/components/mapPage/mapDisplay.tsx
Asana Ticket: [⚙️🐞 When selected route direction changes excluded nearby bus stops do not update](https://app.asana.com/0/1148853526253420/1205560497394206/f)
=> fix(ts/components/NearbyStops): refresh stops when inputs to function change

.github/workflows/deploy-base.yml
This PR updates the deploy workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user
Successful dev deploy [here](https://github.com/mbta/skate/actions/runs/6616916102)
=> Chore: Update GitHub actions to use assumed role

assets/css/_skate_ui.scss, assets/src/components/app.tsx, assets/src/components/mapPage.tsx, assets/src/components/mapPage/vehiclePropertiesCard.tsx, assets/src/components/propertiesPanel.tsx, assets/src/components/propertiesPanel/ghostPropertiesPanel.tsx, assets/src/components/propertiesPanel/header.tsx, assets/src/components/propertiesPanel/staleDataPropertiesPanel.tsx, assets/src/components/propertiesPanel/vehiclePropertiesPanel.tsx, assets/src/components/rightPanel.tsx, assets/src/userInTestGroup.ts, assets/src/util/mapMode.ts, assets/tests/components/__snapshots__/propertiesPanel.test.tsx.snap, assets/tests/components/mapPage.test.tsx, assets/tests/components/propertiesPanel.test.tsx, assets/tests/components/propertiesPanel/__snapshots__/ghostPropertiesPanel.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/header.test.tsx.snap, assets/tests/components/propertiesPanel/__snapshots__/vehiclePropertiesPanel.test.tsx.snap, assets/tests/components/propertiesPanel/ghostPropertiesPanel.test.tsx, assets/tests/components/propertiesPanel/header.test.tsx, assets/tests/components/propertiesPanel/staleDataPropertiesPanel.test.tsx, assets/tests/components/propertiesPanel/vehiclePropertiesPanel.test.tsx, assets/tests/testHelpers/selectors/components/closeButton.ts, assets/tests/util/mapMode.test.ts
Asana ticket: [⚙️ Link VPC Run # to VPP Run tab](https://app.asana.com/0/1148853526253420/1205703270277839/f)
Having the selection state for the VPP on the search maps page live in a `useState` hook in the component is probably not the long-term solution here, but I think it's an appropriate start for the purposes of this particular ticket.
One thing I'm not 100% sure on that I'd like feedback about is naming of callback function props and when those should or shouldn't start with `on`. My thinking was that clicking the run is a specific action / event handler so that should be `onRunClicked`, but closing the VPP can happen for a number of reasons and I opted to call it `closePanel`, but I'm open to changing that.
=> Link VPC run number to VPP

config/config.exs, lib/skate/application.ex
Asana ticket: [⚙️ Application can survive minor crashes](https://app.asana.com/0/1148853526253420/1205805990143476/f)
Go from :one_for_all to :rest_for_one to hopefully reduce the impact of processes like Oban crashing
My purpose in bundling the changes to the DB parameters is that I want to avoid the chance that deploying this causes further downtime by causing the Oban process on the existing containers to thrash.
=> feat: change application supervision strategy

lib/skate/application.ex
Asana ticket: [⚙️ Log unique message when Skate starts](https://app.asana.com/0/1148853526253420/1205805997139898/f)
I figure that once we do [⚙️ Use :mfa to log module information](https://app.asana.com/0/1148853526253420/1205805997139906/f) this will additionally specify that the logging is coming from `Skate.Application`, so I'm not explicitly including the module here like we do in some other log messages. I did also consider writing a test for this but it doesn't appear that there's a way to start a copy of the application under a different name for testing purposes, and there's no real logic to the logging so it doesn't make sense to factor out into a helper function and test that.
=> feat: log on application startup

assets/css/map/markers/_location_dot_icon.scss
---
- https://app.asana.com/0/0/1205658795320766
=> fix: Fix icon size for location search result marker

assets/css/_settings_page.scss
This is a follow-up to https://github.com/mbta/skate/pull/2270. The previous PR removed a few elements. This one removes the CSS classes that styled those elements, since those CSS classes aren't used anywhere else.
=> cleanup: Remove unused CSS classes for settings page

assets/stories/skate-components/map/markers/locationMarker.stories.tsx
This is a follow-up to [this PR](https://github.com/mbta/skate/pull/2271) to add a storybook story for the affected icon.
Question: I wasn't able to get the icon to load without being in the map context. It _feels_ like we should have a non-map version of the icon, but I sort of timeboxed the effort to add it. What do you all think?
=> feat(storybook): Add story for location marker icon

assets/src/components/app.tsx, assets/src/components/propertiesPanel.tsx, assets/src/components/propertiesPanel/header.tsx, assets/src/components/propertiesPanel/staleDataPropertiesPanel.tsx, assets/src/components/propertiesPanel/tabList.tsx, assets/src/components/rightPanel.tsx, assets/src/hooks/usePanelState.ts, assets/src/state/pagePanelState.ts, assets/tests/components/app.test.tsx, assets/tests/components/propertiesPanel.test.tsx, assets/tests/components/rightPanel.test.tsx, assets/tests/hooks/usePanelState.test.tsx, assets/tests/state/pagePanelState.test.ts, assets/tests/testHelpers/usePanelStateMocks.tsx
When working on #2273, I ended up breaking the MapPage feature which allowed opening the VPP to a specific page. I considered adding the first part of this PR in #2273, but I figured it was getting large enough it'd be easier to digest as a separate PR.
This "stores" the state of the active VPP Tab in the `usePanelState*` hooks because the `initialTab` prop was insufficient because switching pages wouldn't reset the state of `tabMode`, therefore `initialState` was only respected once. By pulling the state out into the panel state, the tab can now be remembered across pages, and each page has it's own tab mode.
---
Depends On: #2273 
Asana Ticket: https://app.asana.com/0/1148853526253420/1205762199809559/f
---
- To see the specific tasks where the Asana app for GitHub is being used, see …
=>  feat(ts/hooks/usePanelState): add `setTabMode` API 

assets/src/components/app.tsx, assets/src/components/nav.tsx, assets/src/components/nav/leftNav.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/nav.test.tsx, assets/tests/components/nav/leftNav.test.tsx
Depends On: #2273
Context: https://github.com/mbta/skate/pull/2273#discussion_r1386682374
Asana Ticket: https://app.asana.com/0/1148853526253420/1205762199809559/f
---
- https://app.asana.com/0/0/1205855740316544
=>  cleanup(ts/components/nav): remove unused `allowViews` prop 

assets/package-lock.json, assets/package.json
No Asana ticket, just a quick quality of life improvement for those of us who use a project-local installation of the language server so that it's pulled in by default.
=> chore(devtools): add typescript-language-server as a dev dependency

assets/css/_ladder_page.scss, assets/css/_late_view.scss, assets/css/_map_page.scss, assets/css/_notification_drawer.scss, assets/css/_picker_container.scss, assets/css/_properties_panel.scss, assets/css/_search_page.scss, assets/css/_skate_ui.scss, assets/css/_swings_view.scss, assets/css/_ui_kit.scss, assets/css/app.scss, assets/src/components/nav.tsx, assets/src/components/nav/mobilePortraitNav.tsx, assets/src/components/viewHeader.tsx, assets/src/hooks/usePanelState.ts, assets/tests/components/nav.test.tsx, assets/tests/components/nav/mobilePortraitNav.test.tsx, assets/tests/components/viewHeader.test.tsx, assets/tests/hooks/usePanelState.test.tsx, assets/tests/testHelpers/usePanelStateMocks.tsx
Asana ticket: [⚙️ Views or panels should be full screen for < 800px](https://app.asana.com/0/1148853526253420/1205785606005457/f)
There were a couple of places that referenced a breakpoint of 480px from the old breakpoint variables, but I updated them to point to the new one because the new breakpoint was actually the relevant one for that context (the thing that determines which breakpoint the CSS should apply at is based on the `useScreenSize` breakpoints).
I followed the same pattern as with the mobile portrait nav where the nav components are explicitly hidden when a view is opened over them - for one thing the order of the z-indexes isn't right to have the panel go on top of the nav and switching them around causes issues (the drop shadow of some panels bleeds out over the top nav on …
=> Full-screen panels on small screens

test/api/stream_test.exs
I tried fixing this by addressing the [Bypass issue](https://github.com/PSPDFKit-labs/bypass/issues/120), but that didn't actually help. So instead I've decided to cut out the `ServerSentEventsStage` and replace it with the parse results that `Api.Stream` received from the tests before this change.
---
Asana Ticket: [⚙️ Fix false positive test failure in `stream_test.ex`](https://app.asana.com/0/1148853526253420/1206096617521840/f)
<details>
<summary><h3>CI Runs Information</h3></summary>
<dl>
<dt>Number of <code>stream_test</code> Failures in <a href="https://github.com/mbta/skate/pull/2303">#2303</a> so far</dt>
<dd>0</dd>
<dt>Total <a href="https://github.com/mbta/skate/pull/2303">#2303</a> Pipeline Runs</dt>
<dt>Total <a href="https://github.com/mbta/skate/pull/2303">#2303</a> Pushed …
=> fix(ex/api/stream_test): fix intermitently failing tests

mix.exs
Sometimes I get a little annoyed needing to run two commands to format the project, so this adds and alias which invokes all our formatters.
---
Asana Ticket: None
=> feat(ex/mix): add `mix fmt` alias

.github/dependabot.yml
Dependabot stopped updating our JS dependencies without notification. Upon looking into dependabot jobs, the error message tells us that our path based dependencies are the issue. This commit ignores dependencies that are managed by `mix` like `phoenix` and `phoenix_html`.
> **Update check skipped**
> Dependabot updates have stopped for your repository due to repeated errors. To see logs, click "Check for Updates" and Dependabot will try again.
> The last error message was:
>
> **Dependabot couldn't fetch all your path-based dependencies**
> The affected dependencies were `phoenix`.
>
> To use path-based dependencies with Dependabot the paths must be relative, resolve to a directory in this project's source code, and contain a valid JavaScript project.
> [Troubleshoot Dependabot …
=> fix(dependabot): ignore JS path based dependencies

Dockerfile
This is based on the value I got when downloading it on my personal connection.
=> chore: update AWS RDS cert bundle hash

assets/stories/skate-components/map/controls/layersControl.stories.tsx
Fixes the layers control stories to do what they say.
Found this when looking for references about how to use this control.
No Ticket.
=> fix(sb/map/layersControl): add `pullbackLayerEnabled` parameter as `undefined`

assets/css/_diversion_page.scss, assets/css/app.scss, assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/diversionPanel.tsx, assets/src/components/routePill.tsx, assets/stories/skate-components/detours/diversionPage.stories.tsx, assets/stories/skate-components/detours/diversionPanel.stories.tsx
This is only available & visible via Storybook at this moment.
I've styled this using bootstrap classes which some of we currently do not import. Given this is "lightly styled" I focused on CSS layout functionality and getting a few bootstrap classes right.
---
Asana Ticket: [⚙️🚧 Create lightly styled stub screen to display directions/missed stops](https://app.asana.com/0/1148853526253420/1206038957525484/f)
=> feat(ts/components/DiversionPage): create diversion page stub

mix.exs
No ticket.
I just noticed I was running `mix test && mix credo && mix dialyzer --quiet && mix sobelow` a lot, and I wanted a single command to do it all.
=> chore: Add mix check and mix assets.test tasks for convenience

lib/skate/settings/db/test_group.ex, lib/skate/settings/test_group.ex, lib/skate/settings/test_group_override.ex, lib/skate/settings/user.ex, lib/skate_web/controllers/page_controller.ex, lib/skate_web/controllers/test_group_controller.ex, lib/skate_web/controllers/test_group_html/test_group.html.heex, lib/skate_web/router.ex, test/skate/settings/test_group_test.exs, test/skate/settings/user_test.exs, test/skate_web/controllers/page_controller_test.exs, test/skate_web/controllers/test_group_controller_test.exs
---
- https://app.asana.com/0/0/1206195348204443
=> feat: Add override for test groups

assets/src/components/detours/detourMap.tsx, assets/tests/components/detours/detourMap.test.tsx
Asana ticket: slight follow-up on [⚙️🚧 Click on the map to draw, click on waypoints, and click on route to end](https://app.asana.com/0/1148853526253420/1206038957525487/f)
=> fix: off-by-one error when drawing detour point markers

assets/src/components/vehicleIcon.tsx
Fixes occasional errors in Storybook due to name collision with `Ghost` from "../realtime.d" on line 9 (https://github.com/mbta/skate/blob/main/assets/src/components/vehicleIcon.tsx#L9)
=> fix(ts/components/vehicleIcon): rename `Ghost` to `GhostIcon`

assets/src/components/propertiesPanel/minischedule.tsx
Found when adding new storybook pages, due to babel complaining about the conflict.
Basically the same as #2352.
=> fix(ts/components/minischedule): rename components to avoid collision with imported type names

assets/src/components/detours/detourMap.tsx, assets/src/util/math.ts, assets/tests/util/math.test.ts
The old implementation was not tested and returned the input `position` instead of the closest point within `positions`.
=> fix(ts/math): fix and test `closestPosition`

assets/src/components/detours/detourMap.tsx, assets/src/components/ladderPage.tsx, assets/src/components/map/controls/StreetViewSwitch.tsx, assets/src/components/map/controls/customControl.tsx, assets/src/components/nav.tsx, assets/src/components/routePicker.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/routePicker.test.tsx.snap, assets/tests/components/map/controls/customControl.test.tsx
Asana ticket: [⚙️🚧 Investigate/implement tabbing order](https://app.asana.com/0/1148853526253420/1206260856814692/f)
This provides some very basic fixes to the high-level navigation of Skate by tabbing, in particular on the route ladders page. For the most part this is accomplished through improvement to the layout of the DOM rather than explicitly setting `tabindex`. This uncovers a lot of additional issues like missing focus state, but it's at least a start.
=> Initial fixes to tab order

assets/css/detours/_detour_map.scss, assets/src/components/detours/detourMap.tsx, assets/tests/components/detours/detourMap.test.tsx
Asana ticket: [⚙️🚧 Have a green dot appear on hover](https://app.asana.com/0/1148853526253420/1206260856814698/f)
I haven't quite figured out getting the cursor to appear 1rem on either side of the route shape, but I at least have the cursor itself working.
=> feat: green dot cursor for existing route shape

assets/src/hooks/useDetour.tsx, assets/tests/hooks/useDetour.test.ts
I found that the directions persisted even after pressing undo to the very beginning. So this makes sure we clear it if we stop making API calls to update the state.
---
- https://app.asana.com/0/0/1206470407069009
=> fix(ts/hooks/useDetour): clear directions and coordinates when undoing points

assets/css/app.scss, assets/css/bootstrap.scss, assets/css/nav/_top_nav.scss, assets/src/components/nav/topNav.tsx, assets/src/userEmailAddress.ts, assets/src/userInTestGroup.ts, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/app.test.tsx, assets/tests/components/appStateWrapper.test.tsx, assets/tests/components/nav/topNav.test.tsx
---
- https://app.asana.com/0/0/1206526459943491
=> feat: Add logged-in-as element to desktop top nav

lib/skate_web/auth_manager.ex, lib/skate_web/auth_manager/pipeline.ex, test/skate_web/auth_manager_test.exs
**Asana ticket:** [Better handle transition state](https://app.asana.com/0/1148853526253420/1206613654510834/f)
This will help avoid unusual states around the time that we roll out Keycloak by requiring users to log back in via the new SSO flow as opposed to continuing to use their old token.
A note on Guardian terminology: it may seem weird that we weren't calling `Guradian.Plug.EnsureAuthenticated` before, but that mainly calls the optional `verify_claims` callback. The default `verify_claims` implementation just always accepts the claims so the plug wouldn't have done anything previously.
=> feat: "roll over" to new guardian tokens when enabling Keycloak

assets/css/_dropdown.scss, assets/src/components/map/dropdown.tsx
From the design review for the detour modal - I missed this when doing the original detour dropdown work.
[Design Review Asana Ticket](https://app.asana.com/0/1148853526253420/1206545095976211/f)
> The default text should use the body font color (#252627, Gray-900), not blue.
=> fix: Fix text color on the detour dropdown

.tool-versions, Dockerfile
This fixes an issue where running individual tests sometimes fails with this error:
node:internal/assert:14 throw new ERR_INTERNAL_ASSERTION(message);
More info here: https://github.com/nodejs/node/issues/48763
And here: https://github.com/nodejs/node/issues/50383
=> chore/fix: Upgrade node to 20.11.0

lib/skate_web/controllers/auth_controller.ex, test/skate_web/controllers/auth_controller_test.exs
Followup on #2408. Now that the old tokens are expired, we no longer have to check for a `sign_out_url` in the Guardian claims.
=> chore: remove fallback on signout URL from Guardian claims

assets/src/api.ts, assets/src/components/detours/detourDropdown.tsx, assets/src/components/detours/detourModal.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/diversionPanel.tsx, assets/src/components/dummyDetourPage.tsx, assets/src/components/mapPage.tsx, assets/src/components/mapPage/mapDisplay.tsx, assets/src/hooks/useDetour.tsx, assets/src/models/detour.ts, assets/src/models/detourShapeData.ts, assets/stories/skate-components/detours/diversionPage.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/factories/detourShapeFactory.ts, lib/schedule.ex, lib/schedule/data.ex, test/schedule/data_test.exs, test/schedule_test.exs, test/support/factory.ex
Asana ticket: [Provide easier access to route patterns by ID on backend](https://app.asana.com/0/0/1206644323693330/f)
My plan for the API is that the front-end is going to provide the back-end with the ID of the route pattern that the detour started from in addition to the detour shape. The route pattern will then allow the back-end to find the initial shape and, via the representative trip, get the stops. All of this needs the ability to look up a route shape by ID, though, and we don't currently have that, so I'm adding it.
I also snuck in a minor refactor (moving `detour.ts` to the models directory).
=> feat: function to look up route pattern by ID.

assets/css/_diversion_page.scss, assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/diversionPanel.tsx
This sets us up to have a scrolling body with a stable footer
prepares for: https://github.com/mbta/skate/pull/2420
---
- https://app.asana.com/0/0/1206694541310027
=> refactor: convert diversion panel to use layout panel components

assets/tests/testHelpers/mockHelpers.ts
Instant promise pretends to be a promise, but doesn't actually trigger the right behavior in react tests due to faking it. I'm not sure this was intendded when it was originally added, but I believe we can replace this with `Promise.resolve`
=> cleanup: deprecate instant promise

assets/src/components/detours/detourMap.tsx
This is in preparation for work to [widen and highlight the route shape on hover](https://app.asana.com/0/1205385723132845/1206423114607620). 
My plan for that is to paint two polylines with the same positions, one that's transparent (until hover) and has all the click and hover behavior, and one that is only the portion that's visible when not hovering. This refactor felt like a helpful precursor to that.
I could be persuaded to combine these into a single PR, but this actually did feel reasonable as a standalone change.
---
- https://app.asana.com/0/0/1206698934433014
=> refactor: Factor out `OriginalRouteShape` in `DetourMap`

assets/src/components/detours/diversionPanel.tsx
No ticket.
This was surfaced in [design review for the detour modal](https://app.asana.com/0/1148853526253420/1206545095976211/f), but I forgot to address it before merging.
=> fix: Update wording in 'Directions' section of the detour panel

assets/tests/components/detours/detourMap.test.tsx, assets/tests/components/detours/diversionPage.test.tsx
No ticket.
Emacs has been yelling at me about this for a while now. Apparently `fireEvent.click` calls don't need `await`.
=> chore(tests): Remove `await` from `fireEvent` calls

assets/tests/helpers/bsIcons.test.tsx
I realized I could do this with better ergonomics than `icon.test.tsx` but for the BS Icons which are fairly uniform, I attempted to encode the "rules" documented at the top of `bsIcons.tsx` into tests.
This does seem to accurately ensure each icon is "implemented" correctly, as I've tested by removing certain props from already existing icons.
=> feat:test(ts/components/bsIcons): add tests for Bootstrap Icons

assets/tests/components/detours/diversionPage.test.tsx, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
This depends on #2429 because I added some tests which also needed this, but to avoid merge conflicts I'm basing this off of #2429 
This follows the pattern in https://github.com/mbta/skate/blob/main/assets/tests/testHelpers/selectors/components/map/markers/stopIcon.ts#L4-L11
=>  refactor: extract original route query into byRole like API 

assets/src/hooks/useDetour.ts, assets/tests/hooks/useDetour.test.ts
Thanks to @firestack for catching.
=> fix: clear missed stops when detour is no longer in a finished state

assets/css/_z_indexes.scss, assets/css/app.scss, assets/css/bootstrap.scss, assets/css/bootstrap/_variable_overrides.scss, assets/src/components/detours/diversionPage.tsx, assets/tests/components/detours/diversionPage.test.tsx
Asana ticket: [Basic modal implementation](https://app.asana.com/0/1148853526253420/1206705505932432/f)
There is still some typography styling that I have to take care of as a follow-up.
As part of this, I moved our z-index maps out into their own file so that they could be imported without pulling the actual CSS rules in `app.scss` in. The reasoning behind this is that I wanted to reference them in our Bootstrap variable overrides, but for the Storybook stories that don't pull in the full app CSS and instead just some particular design system styles, it hit a compilation error because of not being able to find the variable.
=> feat: detour page exit confirmation modal

assets/src/components/detours/diversionPage.tsx, assets/src/hooks/useDetour.ts, assets/tests/hooks/useDetour.test.ts
This does the bare minimum to get the controls locked out in the finished state and get us started down the path of conditionally returning functions from `useDetour`. I'm expecting to open another PR which refactors the type that `useDetour` returns and collapse duplicated tests (e.g., tests with "does nothing" conditions, and removing "permission" booleans like `canUndo`).
=> init: lockout controls initial work

assets/css/bootstrap/_variable_overrides.scss, assets/css/typography/_variables.scss, assets/src/components/detours/diversionPanel.tsx
#2441 resurrected under a more descriptive branch name.
We don't need to re-add the `h2` class because it's undesired and wasn't doing anything anyway.
=> refactor: give Bootstrap access to typography variables sans Reboot

lib/skate/detours/route_segments.ex
Per some [feedback](https://github.com/mbta/skate/pull/2438#discussion_r1507643206) in the PR where this was introduced, I removed the usage of this Params struct, but I forgot to remove the struct itself.
=> fix: Remove useless Params

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .github/workflows/deploy-base.yml, .github/workflows/report-coverage.yml
No ticket.
There's still one deprecation warning in the `mbta/actions/dialyzer` action, but that will involve (I think) upgrading [this](https://github.com/mbta/actions/blob/119bf30dc6bdb9f7fc7264e3814462f397147689/dialyzer/action.yml#L17), which will take a bit more effort, just to make sure we do it right.
[Example of some of the warnings](https://github.com/mbta/skate/actions/runs/8113620719?pr=2451)
=> chore: Upgrade various workflow actions to get rid of Node 16 deprecation warnings

assets/src/components/detours/diversionPage.tsx
Some of these utility classes may no longer be necessary or make sense when we have Bootstrap, but for now it provides a really close match to the designs.
For the bottom padding of the modal body, design used 2rem. The Bootstrap utility classes for padding don't include an option that 2 * the base spacer size (1rem) by default, see the list [here](https://getbootstrap.com/docs/5.3/utilities/spacing/#sass-maps). I figured that 1.5rem might be a nice compromise without straying too much from Bootstrap defaults and writing our own CSS, but we'll see what design says.
---
- https://app.asana.com/0/0/1206705505932433
=> Style detour close modal

assets/.eslintrc.js, assets/package-lock.json, assets/package.json, assets/tests/api.test.ts, assets/tests/components/app.test.tsx, assets/tests/components/ladderPage.test.tsx, assets/tests/components/lateView.test.tsx, assets/tests/components/map.test.tsx, assets/tests/components/mapMarkers.test.tsx, assets/tests/components/mapPage/vehiclePropertiesCard.test.tsx, assets/tests/components/notificationCard.test.tsx, assets/tests/components/propertiesList.test.tsx, assets/tests/hooks/useAppcues.test.tsx, assets/tests/hooks/useNearestIntersection.test.ts, assets/tests/hooks/useNotifications.test.tsx, assets/tests/hooks/useNotificationsReducer.test.tsx, assets/tests/hooks/useScreenSize.test.ts, assets/tests/hooks/useVehicleForNotification.test.tsx, assets/tests/mapLimits.test.ts, assets/tests/models/vehicleStatus.test.ts, assets/tests/setup.tsx, assets/tests/state.test.ts, assets/tests/state/pagePanelState.test.ts, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx, assets/tests/userTestGroups.test.ts, assets/tests/util/operatorFormatting.test.ts
I almost committed a `test.only` in #2463 and was surprised that the linter didn't prevent me from doing so. Commits should be reviewable in order and auditable via `npm run lint:check` at each point in time
=> feat: add jest linter

assets/.eslintrc.js, assets/src/components/detours/diversionPage.tsx, assets/tests/components/detours/diversionPage.test.tsx
This gets the information we have into the text box on the share screen. This does not include connection points as that information is only available in the backend right now, I'm intending to open another PR which adds connection points to the API and adds it to this text.
---
- https://app.asana.com/0/0/1206710026837345
=> feat(ts/components/diversionPage): add share screen text stub

assets/css/app.scss, assets/css/map/controls/_map_button.scss, assets/src/components/map/controls/mapButton.tsx, assets/src/helpers/bsIcons.tsx, assets/stories/skate-components/map/controls/mapButton.stories.tsx
Asana ticket: [Create underlying button components](https://app.asana.com/0/1148853526253420/1206753759080074/f)
The main things I'm looking for feedback on here are:
1. The use of the `title` prop for the text in the button at large sizes and both how that should ultimately render in the HTML and how it should be exposed to users of the component.
2. The `size` property and whether or not the way it's used is weird (though nobody will be setting it explicitly to `undefined` except in Storybook so I don't think it's much of an issue).
3. The way I actually customized the Bootstrap buttons via overriding CSS variables in `_map_button.scss` wherever possible.
Also I would like to add at least a couple of basic automated tests, I think those will mostly be around the functionality for …
=> feat: map button components

assets/src/components/detours/detourMap.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/hooks/useDetour.ts, assets/tests/components/detours/detourMap.test.tsx, assets/tests/hooks/useDetour.test.ts
With the addition of DivertedRouteShape, OriginalRouteShape will always be clickable (since when it's not, we'll use DiveredRouteShape instead), so we no longer need a boolean to tell us to make it clickable.
=> cleanup: Remove originalShapeClickable

assets/stories/skate-components/detours/detourMap.stories.tsx
In [this PR][1], we removed originalShapeClickable as an attribute for the DetourMap, but in parallel, we introduced [storybook stories for DetourMap][2], which referenced `originalShapeClickable` at the time. Those two PR's were merged in rapid succession, so the builds for [the second one][2] never caught up with the fact that [the first one][1] had removed that argument.
[1]: https://github.com/mbta/skate/pull/2459
[2]: https://github.com/mbta/skate/pull/2457
=> fix: Remove originalShapeClickable from DetourMap stories

mix.exs
This should have been added in [this PR](https://github.com/mbta/skate/pull/2449), but I must have goofed at actually committing it (I know I added it in order to get the tests to run correctly on my machine, so I have no idea what happened).
=> fix: Don't consolidate Elixir protocols in test

assets/src/components/detours/detourMap.tsx
This mostly affects storybook right now, but also allows us to use these icons at different sizes in the future.
The sizes in-context are already fixed by the markers that wrap the icons, so this should have no user-facing effect
=> refactor: Don't fix the height and width for detour marker icons

assets/css/_diversion_page.scss
After some interactive pairing with Design, we arrived at this combination to set the size of the panel. 
---
It's possible we'll change this later but it's so small it's pretty easy to do :)
=> feedback(design):fix(css/diversionPage): make panel width the larger of `300px` or `22.5%` of the screen

assets/css/map/markers/_missed_stop_icon.scss, assets/stories/skate-components/map/markers/missedStopMarker.stories.tsx
In context, the missed stop icons are contained in a `c-stop-icon-container`, not a `c-missed-stop-icon-container`, so the hover behavior worked in the stories for the icons themselves, but not when they were actually drawn on the map.
=> fix: Fix hover behavior for missed stop icons

assets/css/_u_isolation.scss, assets/css/_z_indexes.scss, assets/css/app.scss, assets/css/bootstrap/_variable_overrides.scss, assets/css/detours/_detour_modal.scss
By changing the main application container to start it's own stacking context, the modals and tooltips created by react-bootstrap then by default cover the application contained in the `main` element without interference because of the new stacking context created. So now modals and tooltips show up in the order they're defined (as long as they don't have wildly huge z-index's themselves, or we'd need to apply this same isolation to modals as well)
---
- https://app.asana.com/0/0/1206808449589844
=> fix: make modal and tooltip appear over rest of application

assets/src/components/detours/detourFinishedPanel.tsx
This was caught in design review with Kathleen, `<Popover>` is what the designs use and it matches more closely.
---
- https://app.asana.com/0/0/1206810341002961
=> fix(ts/components/detourFinishedPanel): convert `Tooltip` to `Popover`

assets/src/api.ts, assets/src/hooks/useDetour.ts, assets/src/util/fetchResult.ts, assets/tests/api.test.ts, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/hooks/useDetour.test.ts
Asana ticket: [Version of apiCall that surfaces error states](https://app.asana.com/0/0/1206816132107678/f)
I'm opening this up for review as its own PR just because it's a pretty impactful change for the future of how we do API requests. I have a followup subtask to actually pass this result up through the hooks. I may or may not also do some work on [factoring out the hook logic into a general-purpose helper](https://app.asana.com/0/1148853526253420/1205240803395719/f) if it makes sense to.
=> refactor: apiCallWithError function

.github/dependabot.yml
We seem to be struggling to keep up with Dependabot PR's, which is causing us to leave older Dependabot PR's open for a long time. Reducing the number of PR's we allow to be open at a time might help us keep these under control more easily.
=> chore: Reduce number of allowable Dependabot PR's to 1

assets/src/components/detours/detourModal.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/components/dummyDetourPage.tsx, assets/stories/skate-components/detours/diversionPage.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx
Asana ticket: [⚙️ [extra] Pressing escape key on detour modal should ask confirmation before closing](https://app.asana.com/0/1148853526253420/1206845632479144/f)
This ended up involving more refactoring than I thought it would but I like that we can now rely on the Restart modal's handling of the escape key event itself. I think it does sort of expose a gap in our testing of the `<DetourModal>` component so I might additionally go in and add some tests for that.
=> fix: using escape key on detour modal prompts for close confirmation

assets/css/bootstrap.scss, assets/css/bootstrap/_theme_color_additions.scss, assets/src/components/detours/diversionPage.tsx, assets/src/helpers/bsIcons.tsx, assets/tests/components/detours/diversionPage.test.tsx
Asana ticket: [Surface error state in UI](https://app.asana.com/0/0/1206816132107680/f)
I'm particularly interested in feedback on how I added to the `ui-alert` theme color palette (or whatever the proper terminology is). It didn't quite fit into the existing map overrides or variable overrides, so I had to add a new override file, put I added a comment explaining why. I only bothered with the particular colors that are relevant for alerts (see [the Bootstrap documentation](https://getbootstrap.com/docs/5.3/components/alerts/#sass-loops) on how they generate CSS variables for each theme color).
=> Routing error alert

lib/skate/open_route_service_api/directions_request.ex, test/skate_web/controllers/detour_route_controller_test.exs
The the first commit is the actual functionality and tests, the other commits are just me trying to make it a bit cleaner. I can easily drop the later two commits if they're disliked.
---
- https://app.asana.com/0/0/1206826435176362
=> feat(ex/skate/open_route_service_api): send 40ft bus info to ORS for HGV profile routing

lib/skate/open_route_service_api/directions_request.ex, test/skate_web/controllers/detour_route_controller_test.exs
I realized we hadn't set the bus type on our HGV profile, so this adds that to the API request.
=> feat(ex/skate/open_route_service_api): add `vehicle_type` to ORS API call

.envrc.template, README.md
While onboarding, noticed a couple of env vars that are no longer quite so "optional" in first getting Skate running. Those are moved to the required vars section. Also noted Storybook run command in the README
=> docs: Updated .envrc with required vars; include storybook in README

assets/src/hooks/useDetour.ts, assets/tests/hooks/useDetour.test.ts
Asana task: [🚧⚙️🐛 Missed Stops section shows up in the detour panel before a route is connected](https://app.asana.com/0/1205385723132845/1206843243488989)
The `useDetour` hook is already aware of whether the detour has been completed or not, and uses that to decide whether `missedStops` should have stops or be an empty list. Instead of setting conditionals in each of the areas where `missedStops` is used (to verify that the detour is complete), I figured I could just set `missedStops` to undefined when detour not finished. It didn't break any tests (other than the obvious) so I hope that assumption makes sense!
=> fix: Missed Stops should not display until detour finished

.envrc, .envrc.template, .gitignore, README.md
In prep for importing env vars via 1password, I wanted a way to load in a user's local settings while also being able to provide a default direnv entrypoint.
This is a breaking change so everyone working on Skate will want to save and/or rename their `.envrc` file to `.envrc.private` before checking out commits after this. I'm fairly certain that git will warn you, but I want to make sure this is made explicit.
Because of this, I'm going to ask for explicit approval from all other active developers on Skate.
=> feat: setup default direnv file

.envrc.template
Instead of having users fill this in manually, we can source it directly from mix when we load direnv.
=>  feat(direnv/template): source secrets directly from `mix phx.gen.secret`

lib/skate/open_route_service_api.ex, lib/skate/open_route_service_api/client.ex, test/skate/open_route_service_api_test.exs, test/skate_web/controllers/detour_route_controller_test.exs
This returns errors from ORS and processes it into a smaller set of error values. The frontend is currently ignoring the return value of this so this can be made out of step with the frontend and therefore reviewed in a smaller chunk.
---
- https://app.asana.com/0/0/1206941188727470
=> feat: return `:no_route` error from ORS

assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/diversionPanel.tsx, assets/src/hooks/useDetour.ts, assets/stories/skate-components/detours/detourFinishedPanel.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx
The little things I like about this approach is that
- "Return to Regular Route" is put with other directions, which I think it should be!
- The direction is in the root hook instead of scattered in multiple components
- The test for `diversionPage` now sufficiently covers the check "was 'Return to Regular Route' added to the directions sequence"
- We can still choose to make directions more structured with typing later (per Josh's suggestion)
Also included, updating the Storybook story for this!
=> fix: Moved "Return to Regular Route" into root directions list

assets/src/api.ts
This was a small refactor I did while working on refactoring `fetchDetourDirections` to make it a bit easier to read and ignore phoenix related concerns.
---
You can see this code in use on the PR https://github.com/mbta/skate/pull/2534
=> refactor(ts/api/helpers): add `postJsonParameter` helper

config/runtime.exs, lib/skate/open_route_service_api/client.ex
this will require changes in dev infra to update the environment variables for locally hosted ORS.
`OPEN_ROUTE_SERVICE_DIRECTIONS_PATH` is no longer needed because the endpoint should be the same across ORS deployments with a proper `base_url`
---
I don't know how I didn't catch this in code review, but I realized that the API endpoint that the code expects to interact with doesn't change, and instead we were encoding part of the base url into the directions url due to starting with a root prefix `/`.
This makes the path controlled by the code so that what endpoint is expected cannot be changed out from under it, potentially giving it an incompatible endpoint. Now, we can encode a base url with a path suffix like so
```
OPEN_ROUTE_SERVICE_API_URL="http://localhost:8080/ors/" mix …
```
=> feat: use relative path for `directions_path` to merge with base url

config/dev.exs, config/runtime.exs, config/test.exs, lib/skate_web/endpoint.ex
When I [upgraded from Phoenix 1.17.10 to 1.17.11][0], I missed [the note in the changelog][1] indicating that Endpoint.init/2 was being deprecated.
It was deprecated in [this commit][2].
[0]: https://github.com/mbta/skate/pull/2393
[1]: https://github.com/phoenixframework/phoenix/blob/main/CHANGELOG.md#deprecation
[2]: https://github.com/phoenixframework/phoenix/commit/55395900f39a56a0431575f0f88eb89dd24c7a46#diff-28a3e2f0a9ad390131d7da1927ea8c13c9018a0f5319afe899c32cbeebdf2397R34-R37
=> chore: Remove Skate.Endpoint.init/2, deprecated in Phoenix 1.17.11

assets/src/api.ts, assets/src/util/result.ts, assets/tests/util/result.test.ts
This creates a new `Result` type and also uses it immediately in `api.ts` to show an example of it's usage. 
---
You can see this code in use on the PR https://github.com/mbta/skate/pull/2534
---
- https://app.asana.com/0/0/1207056301082043
=> feat: add api helper function to return `Result<T, E>` from API requests

assets/tests/hooks/useDetour.test.ts
Turns out, `waitFor` accepts either a promise or regular function, but always returns a promise. Ignoring that promise essentially means that the `expect`'s are ignored. This fixes that so our tests can be relied on.
https://testing-library.com/docs/dom-testing-library/api-async/#waitfor
```ts
function waitFor<T>(
callback: () => T | Promise<T>,
[...]
): Promise<T>
```
=> fix:test(ts/hooks/useDetour): add missing awaits for async

assets/src/hooks/useApiCall.ts, assets/tests/hooks/useApiCall.test.ts
This adds a generic hook for consuming Promise's, we currently only have a need for this with API results.
This will be combined with #2531 to make implementing API endpoints which may return an error easier.
---
You can see this code in use on the PR https://github.com/mbta/skate/pull/2534
---
- https://app.asana.com/0/0/1207056301082042
- https://app.asana.com/0/0/1207091097322621
=> init(ts/hooks/useApiCall): add hook for consuming api promises

assets/tests/components/detours/diversionPage.test.tsx, assets/tests/hooks/useDetour.test.ts
In #2534 I discovered quite a few tests fell over once I switched to using promises. These are changes that weren't specific to any changes I made in other PR's extracted for review (thanks `jj`!!).
=>  fix:test(ts/detours): fix tests acting outside of test boundry 

assets/src/api.ts, assets/src/hooks/useDetour.ts, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/hooks/useDetour.test.ts
This switches `fetchDetourDirections` over to use `apiCallResult` so that we can return errors from the backend. Switching to `apiCallResult` sets us up for https://github.com/mbta/skate/pull/2543 .
There were a few unrelated test issues due to introducing promises into the mix, so the commits should be reviewable in order to help discombobulate some of the changes.
Depends On:
- #2531
- #2533 
- #2539
- #2544
---
- https://app.asana.com/0/0/1207091097322625
- https://app.asana.com/0/0/1206816132107683
=>  refactor(ts/api/fetchDetourDirections): use `apiCallResult`

assets/jest.config.ts, assets/package-lock.json, assets/package.json
It's a little annoying when you have to reference docs without autocomplete to edit or modify jest config. This moves it into it's own config file that's also typescript so we can have a typed config :)
=> feat(ts/jest): move jest config to ts file

CODEOWNERS
Even if dependabot is running upgrades for us (or trying to), upgrades still need to go through a human review cycle.
Not tagging us in dependency-related PR's has led to dependency-related PR's sitting open for longer than they need to.
=> chore: Make skate-developers the codeowners for dependency lockfiles

assets/css/detours/_detour_map.scss
As a follow-up to https://github.com/mbta/skate/pull/2559, there's no reason to have the waypoint markers be the only ones with `display: block`.
=> fix: Set the start and end point markers to display: block

assets/tests/hooks/useApiCall.test.ts, assets/tests/testHelpers/PromiseWithResolvers.ts
I've needed this in a few refactors I've considered making. Any refactors to use `useApiCall` from #2533 require making changes to tests which made previously incorrect assumptions about promises. Often, there are tests which test out of order resolution, so a refactor where all tests are kept require this kind of helper.
=> refactor:test(ts/testHelpers): move `PromiseWithResolvers` to own file

.envrc.template
`mix phx.gen.secret` is apparently super slow, we recommend two invocations of it in our `.envrc.template`
```
$ time mix phx.gen.secret
vV+JV+dip2WKUSO0Im8JjAxCVcuDZzrTxAO0dx3/TmUF8R0bgbx/hyrhNRAA81LR
________________________________________________________
Executed in  702.51 millis    fish           external
usr time  466.12 millis   49.00 micros  466.07 millis
sys time  433.24 millis  613.00 micros  432.63 millis
```
It seems like we can instead replace this with `openssl rand`
---
Context: [Skate Dev Slack Thread](https://mbta.slack.com/archives/C047ZT8ACP5/p1714493416356879?thread_ts=1714492925.590479&cid=C047ZT8ACP5)
=> fix: replace `mix phx.gen.secret` in shell direnv 'hot path' with `openssl rand`

assets/tests/testHelpers/mockHelpers.ts
Small change to make typing pass through the `neverPromise` function.
=> feat: add type argument to `neverPromise`

assets/src/components/app.tsx
What's here is only a partial solution, because navigating to `/detours` will still give you a nav menu and a blank screen (rather than an actual, fully functioning dummy detour page). I think an "Actual Solution" would involve fiddling with the routes in `router.ex`, or would involve creating a real 404 page in the frontend, and I'm not sure that's worth the effort right now.
=> fix: Block dummy detour page unless the test group is enabled

assets/src/components/app.tsx, assets/src/components/minimalLadderPage.tsx, assets/src/userInTestGroup.ts, assets/stories/skate-components/pages/minimalLadderPage.stories.tsx, lib/skate_web/router.ex
Asana Ticket: https://app.asana.com/0/0/1207162343766762
=> feat: Add a placeholder minimal-route-ladders page

assets/src/hooks/useDetour.ts, assets/src/hooks/useNearestIntersection.ts, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/components/mapPage.test.tsx
Follow-up to #2566, both to start stress-testing the new `useNearestIntersection` (and `useApiCall`) and because the deprecation warning was annoying in `useDetour`.
Related:
- #2566
=> refactor: Have useDetour use the new useNearestIntersection

lib/skate_web/controllers/auth_controller.ex, test/skate_web/controllers/auth_controller_test.exs
If login fails due to a CSRF errors, which we usually have [happen in prod between 1 and 6 times per hour](https://mbta.splunkcloud.com/en-US/app/search/search?sid=1715186892.4890174), we currently just show a failure with the text `unauthenticated`.
If the issue is that the CSRF token used for login had expired or been used already, then retrying the login should address this by getting a new token and attempting login. This should allow us to figure out via our Splunk logs if the issue persists after retrying login.
See the individual commits for a walk through of my process on this.
---
Asana Ticket: https://app.asana.com/0/0/1207261350056001/f
=> test(ex/skate_web/auth_controller): test for csrf failure

lib/skate/application.ex
I was working on [Splunk CSRF Login Issue Dashboard](https://mbta.splunkcloud.com/en-US/app/search/skate_login_csrf_issue_tracking) and didn't have access to deployment version info in Splunk, so this felt like it should be easy to add.
Asana Ticket: https://app.asana.com/0/0/1207280328006578/f
=> feat(ex/application): add deployment version to startup log

.github/workflows/ci.yml
We occasionally run into these types of errors and we've been fighting a lot of flakeyness in our tests. I'm thinking that if we always run CI with this setting on we'll gather more information on which tests are causing this.
```
> npm --prefix=assets test
[...]
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
=> fix(gh/actions/ci): run npm tests with --detectOpenHandles so that we know which tests are leaking if it happens

assets/src/components/map.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
This temporarily fixes issues we've had with detours where you can't zoom in enough to precisely place waypoints. We'd ideally "just" render more zoom levels from our tile-server, but that's been difficult. If that cannot be done easily, merging this is a stopgap to make the detours experience better till we can fix our tiles in some form.
---
Asana Ticket: https://app.asana.com/0/0/1207286076249270/f
=> feat(ts/components/map): allow zooming in more than the tileset native zoom

assets/src/components/nav/leftNav.tsx, assets/src/components/nav/navMenu.tsx, assets/tests/components/__snapshots__/app.test.tsx.snap, assets/tests/components/__snapshots__/appStateWrapper.test.tsx.snap, assets/tests/components/nav/leftNav.test.tsx, assets/tests/components/nav/navMenu.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1206673444071869/f
=> feat: Direct `About Skate` clicks to the /user-guide endpoint

assets/src/hooks/usePatternsByIdForRoute.ts, assets/tests/components/app.test.tsx, assets/tests/hooks/usePatternsByIdForRoute.test.ts
This is some work I've had sitting around that I did while trying to implement the new detours flow.
The tests get a little bit better due to now having to handle promises correctly.
=> refactor(ts/hooks/usePatternsByIdForRoute): use `useApiCall`

config/dev.exs, lib/skate_web/components/layouts.ex, lib/skate_web/components/layouts/app.html.heex
Drift tends to be really loud in the console, it's super annoying locally, so this makes that configurable.
---
After using this for a bit, I'm really strongly in favor of this, _and/or_ opening a ticket to address the logs directly. But I've benefited greatly from having less noise in the logs while doing FE work.
=> feat(ex/components/app): disable `.drift` in local dev by default

assets/src/hooks/useDetour.ts
Just a little bit of cleanup and simplification, makes the [transition to state machines](#2607 ) a little cleaner.
=> cleanup:feat(ts/hooks/useDetour): convert `fetchFinishedDetour` to use `useApiCall`

assets/tests/components/mapPage/routePropertiesCard.test.tsx
I noticed that a lot of the tests for `<RoutePropertiesCard />` had to initialize a bunch of props that those tests didn't really care about. That cluttered up the tests and made it harder to tell what the tests actually cared about, so I copied [a pattern](https://github.com/mbta/skate/blob/6d7794c98876aeebe956dcb9340faf062a35bc8c/assets/tests/components/detours/detourMap.test.tsx#L27-L46) I saw in the `<DetourMap />` tests.
=> refactor(tests): Simplify tests for RoutePropertiesCard

assets/css/_route_pill.scss, assets/src/components/detours/diversionPanel.tsx, assets/src/components/routePill.tsx, assets/stories/skate-components/routePill.stories.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207260183650054
Test new format by adding className `c-route-pill--large-format` to any `RoutePill`. Otherwise, `RoutePill` defaults to smaller format.
=> feat: Updated route-pill with a new size, currently called "large-format"

assets/src/components/mapPage/routePropertiesCard.tsx, assets/stories/skate-components/routePropertiesCard.stories.tsx, assets/tests/components/mapPage/routePropertiesCard.test.tsx
Asana Ticket: https://app.asana.com/0/0/1207363543546275/f
=> feat: Allow RoutePropertiesCard to be open to "variants" or "stops" by default

assets/package-lock.json, assets/package.json, assets/src/hooks/useDetour.ts, assets/src/models/createDetourMachine.ts
Splitting #2615 up into two PR's, while trying to preserve context.
https://github.com/mbta/skate/pull/2607#issuecomment-2123630961
Asana Ticket: https://app.asana.com/0/0/1207381767522633/f
=>  feat(ts/hooks/useDetour): replace `state` variable with state machine 

assets/stories/skate-components/routePropertiesCard.stories.tsx
Its absence was throwing errors in the console and hiding the auto-collapse behavior (which is being removed in https://github.com/mbta/skate/pull/2619).
=> fix: Add selectRoutePattern to RoutePropertiesCard story

assets/tests/components/mapPage/routePropertiesCard.test.tsx
It got left in as an intermediate step while debugging when <RoutePropertiesCardWithDefaults /> was added, and is no longer needed.
=> fix(tests): Remove an unnecessary variable from RoutePropertiesCard tests

assets/src/components/detours/diversionPage.tsx, assets/src/hooks/useDetour.ts
This used to be #2615 but github thought I closed it >.>
---
https://github.com/mbta/skate/pull/2607/files#r1608932364
=> cleanup(ts/hooks/useDetour): replace `state` with `snapshot` from `createDetourMachine`

assets/css/_route_ladder.scss, assets/src/components/routeLadder.tsx, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap
After merging other PRs into the target branch and before merging the target branch into main, I realized a couple things were off. For one, the route pill needed to switch to the large format. For another, the alert icon didn't have the right margins both when visible / invisible.
=> fix: Reworked route ladder header layout

lib/skate/detours/route_segments.ex, lib/skate_web/controllers/detours_controller.ex, lib/skate_web/router.ex, test/skate/detours/route_segments_test.exs, test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1207449517841757/f
=> feat: Add backend for route segments for unfinished detours

assets/css/_route_ladder.scss
=> fix: Lil styling fix on the route ladder headers

assets/src/components/mapPage/routePropertiesCard.tsx
When writing tests for trying to assert how many route patterns are on screen, it wasn't actually possible to identify the group which contained all the radio buttons.
This enables test assertions such as the following
```ts
expect(
await within(
screen.getByRole("group", { name: "Variants" })
).findAllByRole("radio")
).toHaveLength(2)
```
=> fix(ts/components/rpc): make it possible to find RPC routes via `getByRole`

assets/src/components/detours/detourRouteSelectionPanel.tsx
Without this, we fail to control this combo box when we have an initial selected value.
```
● DiversionPage › 'Route Selection Panel' › when a route pattern is already selected, opens to selected pattern
expect(element).toHaveValue(route59)
Expected the element to have value:
route59
Received:
Select a route
1444 |       expect(
1445 |         screen.getByRole("combobox", { name: "Choose route" })
> 1446 |       ).toHaveValue(selectedRoutePattern.routeId)
|         ^
1447 |       expect(
1448 |         screen.getByRole("radio", {
1449 |           name: RPCRadioButtonName(selectedRoutePattern),
at tests/components/detours/diversionPage.test.tsx:1446:9
at step (tests/components/detours/diversionPage.test.tsx:44:23)
at Object.next (tests/components/detours/diversionPage.test.tsx:25:53)
at …
```
=> fix(ts/components/detourRouteSelection): control form value from react

assets/src/components/mapPage/routePropertiesCard.tsx
tests are succeeding where they should be failing because the HTML element is setting itself to `checked` even if the parent component did not instruct so.
=> fix(ts/components/rpc): make radio buttons react controlled

assets/src/components/detours/detourDropdown.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/components/dummyDetourPage.tsx, assets/src/hooks/useDetour.ts, assets/src/models/createDetourMachine.ts, assets/src/models/detour.ts, assets/stories/skate-components/detours/diversionPage.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/factories/originalRouteFactory.ts
To be able to control the route and variant, the state machine needs to be the source of truth for the active route and pattern. This moves the values into the state machine and updates callers to send the route and pattern.
Asana Ticket: https://app.asana.com/0/0/1207481283409966/f
=> feat(ts/detours): add context and input to detour machine

assets/src/hooks/useDetour.ts, assets/src/models/createDetourMachine.ts
Part 2 of the conversion of `useDetour` to a state machine!
This converts the `waypoint` (including `startPoint` and `endPoint`) to be managed by a state machine, instead of manual logic for managing the state. (Considering revisiting this decision about start and end points!)
Instead of managing separate `startPoint` and `endPoint`s, they're now derived from the waypoints array, this is done so that `startPoint` and `endPoint` are no longer containing implicit state of the status of the machine.
This PR involves a few dependencies and steps.
---
Depends on:
- #2605
- Makes the diff on this PR a bit easier to read 
- #2602 
- Fixes a test that would otherwise just be noise in this PR 
- #2616
- First introduces XState and an initial conversion 
---
This PR was done in these steps and such …
=> feat(ts/hooks/useDetour): control waypoints with state machine

assets/src/models/createDetourMachine.ts, assets/tests/components/detours/diversionPage.test.tsx
A fix to #2652 that #2607 enables.
Split into another PR because discussing the test may block #2607 
---
Depends On:
- #2607
=> fix(ts/models/createDetourMachine): clear detour when selecting route pattern

assets/src/components/groupedAutocomplete.tsx, assets/src/components/searchForm.tsx, assets/tests/components/__snapshots__/searchForm.test.tsx.snap, assets/tests/components/groupedAutocomplete.test.tsx, assets/tests/components/searchForm.test.tsx
There is 1 failing test, but I can't test it without the vpn! Will do tomorrow at the office
=> feat: Made searchForm into generic combobox with two variations (for search & select)

assets/src/components/detours/detourMap.tsx, assets/src/components/detours/diversionPage.tsx, assets/stories/skate-components/detours/detourMap.stories.tsx, assets/tests/components/detours/detourMap.test.tsx, assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1207555257756259/f
=> fix: Detour map not interactive until route pattern selected

assets/tests/components/detours/diversionPage.test.tsx, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
Followup for https://github.com/mbta/skate/pull/2662#issuecomment-2173266737
> The query selectors are a bit hard to read though, so it may be worth doing the abstraction where we can make the selectors within the expect a bit more readable to understand _[which]_ one is _actually_ not interactive. I think we have a ticket for this?
=>  test(ts/components/diversionPage): add helpers for route interativity 

lib/skate/detours/missed_stops.ex
Fell out of this comment: https://github.com/mbta/skate/pull/2640/files#r1640235180
Blocks:
- https://github.com/mbta/skate/pull/2640
=> refactor: Have `get_index_by_min_dist` just return the index

lib/realtime/trip_modification.ex, test/realtime/trip_modification_test.exs
Asana Ticket: https://app.asana.com/0/1205718271156548/1207635746210198/f
=> feat: Don't allow creating GTFS-TM messages for routes with duplicate stops

assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/diversionPanel.tsx, assets/src/hooks/useDetour.ts, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
Asana Ticket: https://app.asana.com/0/1205526445275136/1207636402402295/f
Follow-up To:
- https://github.com/mbta/skate/pull/2671
=> refactor: Rename "finish" variables and functions to "review"

assets/css/_map_page.scss, assets/css/_route_ladder.scss, assets/css/_ui_kit.scss, assets/css/nav/_bottom_nav_mobile.scss, assets/css/nav/_left_nav.scss
Asana ticket: https://app.asana.com/0/1205385723132845/1207446071151352
I originally thought I'd want to update the nav buttons to bootstrap, but that seemed a big scope bloat when only the colors needed shifting for now. So instead the scope bloat that I accepted was also changing the drawer-tab on the map page to be the lighter purple, since that was a simple fix (and it was obviously mismatched to the updated navbar.
=> fix: Updated nav buttons to use bootstrap primary token 2024 $eggplant-500

assets/src/components/map/utilities/reactDivIcon.tsx, assets/src/components/map/utilities/reactMarker.tsx, assets/tests/components/__snapshots__/mapPage.test.tsx.snap, assets/tests/components/__snapshots__/shuttleMapPage.test.tsx.snap
This changes `useReactDivIcon` to create the portal element and the `divIcon` at the same time so that we don't need two renders for this component to complete initialization. This prevents some issues in tests where "`An update to ReactMarker inside a test was not wrapped in act(...).`" occurs.
=> fix: Simplify `useReactDivIcon`

lib/skate/detours/route_segments.ex
Follow-up from [this PR comment](https://github.com/mbta/skate/pull/2637#discussion_r1624471270)
=> refactor: Replace `Enum.slice/2` calls with `Enum.split/2` in route segments algorithm

assets/css/_route_ladder.scss, assets/src/components/routeLadder.tsx, assets/src/components/routePill.tsx, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/routeLadder.test.tsx
Tests are a bit annoying to comprehend when trying to get this button solely via class names, this instead makes it possible to do `screen.getByRole("button", { name: "Route Options" })`
---
While reviewing the [tests](https://github.com/mbta/skate/blob/e47aa0764f9a0a259897026543c9194eec20744a/assets/tests/components/ladderPage.test.tsx#L565-L571) in #2647, I found it a little annoying to translate the class names into the actual button that was being referenced. For both accessibility and avoiding class names in our tests, this makes it possible to find the button solely on it's textual meaning.
=> feat(ts/components/routeLadder): add accessible name to route ladder toggle

test/skate/detours/trip_modification_publisher_test.exs
note: [flaky tests issue.](https://mbta.slack.com/archives/C047ZT8ACP5/p1720727594822019?thread_ts=1720726297.170749&cid=C047ZT8ACP5)
=> fix[1/2]:test(TripModificationPublisher): use `start_link_supervised` from `ExUnit` for tests

test/skate/detours/trip_modification_publisher_test.exs
context: [flaky MQTT tests thread](https://mbta.slack.com/archives/C047ZT8ACP5/p1720728369236849?thread_ts=1720726297.170749&cid=C047ZT8ACP5)
=> fix[2/2]:test(TripModificationPublisher): allow timeout up to `500ms` for mosquitto integration tests

test/support/factory.ex
No ticket, but while working on https://github.com/mbta/skate/pull/2687, I noticed that the ID's for this were hard-coded, so I figured this could be worth cleaning up.
=> refactor(tests): Use sequences for gtfs_route_pattern_factory ID's

lib/realtime/shape.ex, test/realtime/shape_test.exs
Co-authored-by: Kayla Firestack <kfirestack@mbta.com>
Blocking:
- https://github.com/mbta/skate/pull/2687
=> fix: Update `Realtime.Shape`'s pattern-matching so that it can accept `Util.Location.From`'s

assets/tests/components/detours/diversionPage.test.tsx, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
This is a prequel to some work that we're doing to disable clicking on the portion of a route shape that comes before the start point, in order to make it less likely that a dispatcher will draw a detour backwards. 
We need some tests to validate that we are doing ☝️ correctly, and that it's only enabled when the user is in a particular test group. This PR adds tests that validate the existing behavior.
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1207475016947553/f
Blocks:
- #2638
- #2639
=> tests: Add tests that assert on visible route sections

test/skate_web/controllers/detours_controller_test.exs, test/support/factory.ex
Stubbing `shape_with_stops_fn` (and, when #2687 rolls around, also `missed_stops_fn`) over and over again was making the tests mildly annoying to work with.
Blocking: 
- https://github.com/mbta/skate/pull/2687
=> tests: Clean up stubbed query functions in detours_controller_test

assets/tests/hooks/useDetour.test.ts
While debugging test issues with [this PR][1], I noticed that useDetour.test.ts was re-invoking originalRouteFactory.build() every time something would cause the hook to rerender, which can cause any hooks that depend on the input to rerender as well (which is not what would happen in real life, since the input isn't randomly changing).
This change updates `useDetourWithFakeRoutePattern` to take in the `originalRoute` as an argument so that the input is only computed once.
[1]: https://github.com/mbta/skate/pull/2638
Blocks:
- https://github.com/mbta/skate/pull/2638
=> fix(tests): Don't change the input on every useDetour test rerender

assets/src/util/result.ts
when using `JSON.stringify`, any `Symbol`'s are not serialized due to being ephemeral and unique. This means we'd need to have some [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#replacer) which can handle this and reconstruct these objects on de-serialize.
So instead, changing this over to a regular string, while less encapsulated, makes this serializable when serializing the xState context.
=> fix: encode enum tag with string

assets/src/components/detours/detourRouteSelectionPanel.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1207506333061758/f
Asana Ticket: https://app.asana.com/0/1205385723132845/1207529619386858/f
=> fix: show spinner when route patterns are loading from "empty"

assets/src/models/createDetourMachine.ts
I had _thought_ that doing `types: {} as {`, was a good idea initially because it _seemed_ to keep autocomplete and make commas unnecessary, which cleaned up diffs when things were changing a bit more.
But it turns out it actually does hide autocomplete, so I've "pushed down" the type definition objects one level from `types` to `types` keys
=> fix: push type definition cast down

lib/skate_web/controllers/detours_controller.ex
Had a new BadMapError when drawing a detour the wrong way. We should not try to send a published detour in that case.
https://mbtace.sentry.io/issues/5644599926/?project=5303878&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
=> fix: Basic check missed stops exists

assets/src/components/detours/detourModal.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/components/dummyDetourPage.tsx, assets/src/hooks/useDetour.ts, assets/src/util/isValidSnapshot.ts, assets/stories/skate-components/detours/diversionPage.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/hooks/useDetour.test.ts
This persists the state machine to `localStorage` and retrieves the last stored snapshot when the dummy detour page is opened.
> [!note]
> This is reviewable by commit to make it easier to understand all the changes.
----
Asana Ticket: https://app.asana.com/0/1205385723132845/1207529620198256/f
=> feat: persist last detour state to localStorage

assets/css/detours/_detour_map.scss, assets/src/api.ts, assets/src/components/detours/detourMap.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/hooks/useDetour.ts, assets/src/models/detour.ts, assets/src/models/unfinishedDetour.ts, assets/src/userInTestGroup.ts, assets/stories/skate-components/detours/detourMap.stories.tsx, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/factories/finishedDetourFactory.ts, assets/tests/hooks/useDetour.test.ts, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
As part of an effort to help dispatchers avoid errors, we want to prevent them from clicking on the portion of a route shape that would cause them to draw the detour backwards.
(In the above screenshot, the route flows from south to north, so the part of the route shape lying to the south of the start point is disabled.)
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1207449517841759/f
Depends on:
- #2637
- #2641
- #2696
Blocks:
- #2639
=> feat: Make the part of the route shape before the start point unclickable

assets/css/detours/_detour_map.scss, assets/src/components/detours/detourMap.tsx
As part of an effort to help dispatchers avoid errors, we want to make it visually clear which side of the start point is at risk of being diverted, and which side is "safe". This augments #2638 by changing the styling of the "maybe-diverted" side of the start point to make the visual difference between before and after the start point obvious.
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1207449517841760/f
Depends on:
- #2637 
- #2641 
- #2696 
- #2638
=> feat: Update styling for route after start point

assets/css/_route_ladder.scss, assets/src/components/routeLadder.tsx, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/minimalLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/ladderPage.test.tsx
Follow-up to:
- https://github.com/mbta/skate/pull/2697
Depends on:
- https://github.com/mbta/skate/pull/2710
=> cleanup: Rename c-new-route-ladder to c-route-ladder in CSS

assets/tests/components/ladderPage.test.tsx
Context: https://github.com/mbta/skate/pull/2647#discussion_r1633194691. At the time, https://github.com/mbta/skate/pull/2657 hadn't been merged yet, so this couldn't be done, but that's no longer the case.
Asana Ticket: https://app.asana.com/0/1205718271156548/1207533417539273/f
=> tests: Update selectors for "Add detour" dropdown in tests

lib/skate/location_search/aws_location_request.ex, test/skate/location_search/aws_location_request_test.exs
Depends-On:
- #2706 	
Asana Ticket: https://app.asana.com/0/1205385723132845/1205857827225835/f
=> fix: truncate aws location queries to 200 bytes

assets/src/components/detours/diversionPage.tsx, assets/src/models/createDetourMachine.ts, assets/tests/components/detours/diversionPageActivate.test.tsx
https://github.com/user-attachments/assets/748b3abf-29cf-4927-b3b1-6680e4598b39
Asana Ticket: https://app.asana.com/0/1205718271156548/1207935854187630/f
Subtask Of: https://app.asana.com/0/1148853526253420/1205836718156544/f
Depends on:
- https://github.com/mbta/skate/pull/2713
=> feat: Enter the "Activated" state when "Activate Detour" button is clicked

assets/src/components/routeLadder.tsx, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/ladderPage.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1207448960080664/f
=> feat: Suppress "Add detour" dropdown on mobile

config/config.exs, config/prod.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1205805997139906/f
Example Searches:
- `index="skate-dev-blue-application" "mfa=Schedule.Gtfs.FeedInfo.log_gtfs_version"`
- https://mbta.splunkcloud.com/en-US/app/search/search?sid=1722868815.5664121
- `index="skate-dev-blue-application" "mfa=Schedule.Gtfs.*"`
- https://mbta.splunkcloud.com/en-US/app/search/search?sid=1722868885.5664406
- `index="skate-dev-blue-application" mfa=*`
- https://mbta.splunkcloud.com/en-US/app/search/search?sid=1722868710.5663706
=> feat: add MFA to logs

config/dev.exs
As a follow-up to https://github.com/mbta/skate/pull/2733, it would be good to restore module names to dev logs. 
No Asana Ticket.
Follow-up to:
- https://github.com/mbta/skate/pull/2733
=> feat: Add mfa to dev logs

assets/src/api.ts
We've had many API helper functions in api.ts, and it's been up to the programmer to understand when and why to use something, so now I've documented them and (hopefully) deprecated the old ones.
Context: https://github.com/mbta/skate/pull/2729#discussion_r1713933871
=> doc: document api calls and deprecate old api calls

assets/tests/factories/vehicle_data.ts, assets/tests/hooks/useAutocompleteResults.test.ts, assets/tests/hooks/usePullbackVehicles.test.ts, assets/tests/hooks/useSearchResults.test.ts, assets/tests/hooks/useShuttleVehicles.test.ts, assets/tests/hooks/useVehicleForId.test.ts, assets/tests/hooks/useVehicleForNotification.test.tsx, assets/tests/hooks/useVehicles.test.ts, assets/tests/hooks/useVehiclesForBlockIds.test.ts, assets/tests/hooks/useVehiclesForRunIds.test.ts, assets/tests/models/vehicleData.test.ts
One of many steps associated with https://github.com/mbta/skate/pull/2603
Part of:
- https://github.com/mbta/skate/pull/2603
=> refactor: Explicitly export vehicleDataFactory

assets/src/hooks/useDetour.ts, assets/src/models/createDetourMachine.ts, assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1148853526253420/1207539825544288/f
=> refactor: Move `fetchNearestIntersection` to the state machine

assets/tests/components/mapMarkers.test.tsx, assets/tests/factories/trainVehicle.ts
One of many steps associated with https://github.com/mbta/skate/pull/2603
Part of:
- https://github.com/mbta/skate/pull/2603
Depends on:
- https://github.com/mbta/skate/pull/2751
- (implicit dependency, silly git conflicts)
=> refactor: Explicitly export trainVehicleFactory

config/config.exs, config/runtime.exs, lib/skate/application.ex
Some small cleanup related to removing our `Skate.Application.load_runtime_config/0` function
Related
- #2758
=> cleanup: move MBTA API config into runtime.exs

assets/css/_detour_list_page.scss, assets/css/app.scss, assets/src/components/detourListPage.tsx, assets/tests/components/__snapshots__/detourListPage.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1208155044119311/f
Depends on:
- https://github.com/mbta/skate/pull/2762
- Mostly because there's a git conflict if you try to merge this first, but also because this looks pretty bad without the updated table styling.
=> feat: Space out components on detour list page

assets/css/detours/_detour_table.scss, assets/src/components/detoursTable.tsx, assets/tests/components/__snapshots__/detourListPage.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205718271156548/1208155044119313/f
Depends on:
- https://github.com/mbta/skate/pull/2762
---
I considered extracting this to a separate component, but didn't for now because it's not exactly the same as other instances of similar-looking things. I'm open to doing that, either as a follow-up, or as a pre-work to this, if you all think it's a good idea.
=> feat: Styling for components in detours table cells

assets/css/bootstrap/_variable_overrides.scss, assets/css/utilities/_hideable.scss
No Asana Ticket.
We had our own custom collection of breakpoints, but Bootstrap also provides a ton of utility classes that allow us to easily make things responsive. The catch: Bootstrap's default breakpoints are different from the ones we were using.
This updates Skate's bootstrap-breakpoint variable to use our previous breakpoints, and the `u-hide-for-mobile` utility class to use the bootstrap breakpoint instead of our home-rolled one.
=> refactor: Update boostrap breakpoints and use them for u-hide-for-mobile

assets/css/detours/_detour_table.scss, assets/src/components/detourListPage.tsx, assets/src/components/detoursTable.tsx, assets/tests/components/__snapshots__/detourListPage.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1208226797938041/f
Depends on:
- https://github.com/mbta/skate/pull/2778
=> feat: Update detour list page and table styles for mobile

lib/skate/detours/detours.ex
Realized the db should be queried in order of most recently updated detours, for all cases.
=> fix: Need to query the table in order of latest updates

assets/css/_diversion_page.scss, assets/css/color/_definitions.scss, assets/src/components/detours/diversionPage.tsx
Asana [ticket](https://app.asana.com/0/1205385723132845/1208153509160224)
=> feat: Active detour panel header yellow for those in detour-pilot group

lib/skate/detours/detours.ex, lib/skate_web/components/layouts/barebones.html.heex, lib/skate_web/controllers/admin_html/index.html.heex, lib/skate_web/controllers/detours_admin_controller.ex, lib/skate_web/controllers/detours_admin_html.ex, lib/skate_web/controllers/detours_admin_html/index.html.heex, lib/skate_web/router.ex
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1208226890774790/f
=> feat: Admin page that shows detours and allows an admin to delete them all

assets/src/models/notificationData.ts, lib/notifications/db/detour.ex, lib/notifications/db/notification.ex, priv/repo/migrations/20240909134311_create_detour_notifications_table.exs, priv/repo/migrations/20240909134742_create_detour_notifications_index.exs, priv/repo/migrations/20240909200808_create_detour_notifications_reference.exs
Asana Ticket: https://app.asana.com/0/0/1208312289539633/f
Not sure if this PR is too small, but I'm fairly certain this will be the final shape of the table and that could be merged first.
This adds a field to the notifications table, because there were errors if it wasn't added, but it's intended that this table is entirely unused as of this PR, following PRs will use this table.
If this PR is too small I can roll this table creation into a PR that uses it.
=> feat: create detour notification table

lib/skate/detours/detours.ex
=> tweak: Preload author and retrieve detours in one query

assets/src/components/detourListPage.tsx, assets/src/components/detoursTable.tsx, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205718271156548/1208214740600735/f
Depends on:
- https://github.com/mbta/skate/pull/2777 (a git-conflict dependency - if needed, I can move things around so that this gets released first)
=> feat: Add properly-formatted headers to the detours list page

assets/css/_detour_list_page.scss, assets/src/components/detourListPage.tsx, assets/src/helpers/bsIcons.tsx, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205718271156548/1208226799631640/f
Depends on:
- https://github.com/mbta/skate/pull/2785
=> feat: Add icons and visibility descriptions to detour table headers

lib/notifications/db/block_waiver.ex, lib/notifications/db/bridge_movement.ex, lib/notifications/db/notification.ex, lib/notifications/db/notification_user.ex, lib/skate/detours/db/detour.ex, lib/skate/schema.ex, lib/skate/settings/db/route_tab.ex, lib/skate/settings/db/test_group.ex, lib/skate/settings/db/test_group_user.ex, lib/skate/settings/db/user.ex, lib/skate/settings/db/user_settings.ex, mix.exs
`mix docs` doesn't generate anything for these modules if `@moduledoc false` is set, but we're using `TypedEctoSchema` now which _does_ generate type information, which can be surfaced by `ExDoc`.
It's also impossible to link to modules in documentation if `@moduledoc false` is set.
I've also created a ExDoc group which is enabled via setting the option on `@moduledoc` `section: :ecto`, this should make it easier to find our database related code, and easier to navigate in the documentation.
---
It is possible to do this automatically for Ecto schemas, by setting this attribute in the shared `Skate.Schema` module. I do think this is neat, but I'm not really _certain_(i.e., let's discuss) this is a good decision?
```diff
diff --git a/lib/skate/schema.ex b/lib/skate/schema.ex
index …
```
=> feat:doc: stub doc headers for database tables

assets/src/components/detours/activateDetourModal.tsx, assets/src/components/detours/detourFinishedPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/hooks/useDetour.ts, assets/src/models/createDetourMachine.ts, assets/tests/components/detours/diversionPage.activate.test.tsx
https://github.com/user-attachments/assets/0d99035d-94e9-43d9-9293-a58a0405ef08
---
Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160230/f
=> feat: Activate detour flow

assets/css/bootstrap/_map_overrides.scss, assets/css/color/_definitions.scss, assets/src/components/detoursTable.tsx, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
---
Asana Ticket: https://app.asana.com/0/1205718271156548/1205857827225844/f
Depends on:
- https://github.com/mbta/skate/pull/2786
=> feat: Add cell borders and colors for active detour table

assets/src/components/detours/activeDetourPanel.tsx, assets/src/components/detours/deactivateDetourModal.tsx, assets/src/components/detours/diversionPage.tsx, assets/src/models/createDetourMachine.ts, assets/stories/skate-components/detours/activeDetourPanel.stories.tsx, assets/tests/components/detours/diversionPage.activate.test.tsx, assets/tests/components/detours/diversionPage.deactivate.test.tsx, lib/skate/detours/detours.ex, test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160255/f
Depends on:
- https://github.com/mbta/skate/pull/2793
=> feat: Deactivate detour flow

assets/src/components/detours/activateDetourModal.tsx
=> feat: Update confirm activate detour language

assets/src/components/detours/activeDetourPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/tests/components/detours/diversionPage.deactivate.test.tsx
No Asana Ticket, but I noticed this while playing around with detours, and didn't think it should be lumped in with https://github.com/mbta/skate/pull/2805.
Depends on:
- https://github.com/mbta/skate/pull/2805
- Not a real semantic conflict, but doing it in sequence avoids annoying git conflicts.
=> feat: Suppress "Return to regular route" button for non-dispatchers

lib/notifications/db/detour.ex, lib/notifications/db/notification.ex, lib/notifications/detour.ex, lib/notifications/notification.ex, test/notifications/db/detour_test.exs, test/notifications/db/notification_test.exs, test/notifications/notification_test.exs, test/support/factory.ex
Step 1 of adding detour notifications to Skate. To be able to send detour notifications, we first need to create the functions and setup for storing and retrieving this info from the database.
This will be used by `notification_server` in future PR's.
The entire feature can be seen in context on the branch https://github.com/mbta/skate/compare/main...kf/asn/detour-notifications
=>  feat: add detour notifications to notifications module

assets/src/components/detours/diversionPage.tsx, assets/src/components/detours/pastDetourPanel.tsx, assets/stories/skate-components/detours/pastDetourPanel.stories.tsx, assets/tests/components/detours/diversionPage.deactivate.test.tsx
---
This doesn't _exactly_ match the hi-fi designs, but I think it's still worth merging so that we don't have the obnoxious experience of having all the content disappear when a detour is deactivated.
The remaining things that I'm thinking of at the moment, which I think should be follow-up PR's are:
- Copy Details button in the header
- Created by and `Last used` in the header (kinda sorta blocked by https://github.com/mbta/skate/pull/2806, since that does this hi-fi task for the active detour panel)
Asana Ticket: https://app.asana.com/0/1205385723132845/1208391763317540/f
=> feat: Contents for past detour page

assets/css/_route_ladder.scss, assets/src/components/routeLadder.tsx, assets/src/helpers/bsIcons.tsx, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/minimalLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/routeLadder.test.tsx
Asana ticket: https://app.asana.com/0/1205385723132845/1208333281632131
~~Pushing up my current work. I'm again confused by tests; to be fixed when I get back from time off~~
=> feat: Update route ladder dropdown

lib/notifications/notification_server.ex, test/notifications/notification_server_test.exs
Step 2 of adding detour notifications to Skate. This creates the notification API for having the notification server create a new notification for a detour.
Asana Ticket: https://app.asana.com/0/0/1208393164852685/f
Depends on:
- #2813
=> feat: add detour notifications to notifications server 

assets/src/components/detours/activeDetourPanel.tsx, assets/src/components/detours/deactivateDetourModal.tsx, assets/src/components/detours/diversionPage.tsx, assets/tests/components/detours/diversionPage.deactivate.test.tsx
---
~One thing that's missing is that the button still has the wrong text (should say `Return to regular route` rather than `Confirm`). That can either be part of this PR or a follow-up.~
Asana Ticket: https://app.asana.com/0/1205526445275136/1208403460973162/f
=> feat: Make Deactivate Modal match Hi-Fi designs

priv/repo/migrations/20240924125339_fix_detour_delete.exs, priv/repo/migrations/20240930144411_fix_detour_delete_validate.exs, test/notifications/notification_test.exs
Turns out, you need to specify this explicitly so that you don't get fkey constraint errors.
I also added `on_update` in case for some reason we change a detour's primary key so that notifications don't get broken and have constraint errors.
=> fix(ex/db/notifications): update or delete notifications if detour is updated or deleted

lib/skate/detours/detours.ex, test/skate_web/controllers/detours_controller_test.exs, test/support/factory.ex
Asana Ticket: https://app.asana.com/0/0/1208393164852692/f
Depends on:
- #2815 
- #2820 
- #2830
=>  feat: send detour notification when detour is activated 

assets/src/components/notificationBellIcon.tsx, assets/src/components/notificationCard.tsx, assets/src/models/detoursList.ts, assets/src/models/notificationData.ts, assets/src/realtime.ts, assets/tests/components/__snapshots__/notificationBellIcon.test.tsx.snap, assets/tests/components/__snapshots__/notificationCard.test.tsx.snap, assets/tests/components/notificationBellIcon.test.tsx, assets/tests/components/notificationCard.test.tsx, assets/tests/factories/notification.ts, lib/notifications/db/detour.ex
Asana Ticket: https://app.asana.com/0/1203014709808707/1208393164852689/f
This creates the frontend part of notifications work, it's independent of other work because the parsing will not be triggered until the detour notification data is live and being sent.
Todo:
=> feat(ts/notifications): create notification card for detours

lib/notifications/db/detour.ex
just a little cleanup, I had originally created this function because that's what other notifications did. I think that was actually incorrect because we don't create detour notifications from external input, unlike bridge notifications or block waivers which get their data from external sources and need to validate the data.
To make it clear that detour notifications are not created from user input, I've removed the changeset function so we're not tempted to use it without question, and instead halve to think about it when/if we re-add the function
=> cleanup(ex/notifications/detour): remove changeset function

assets/css/_route_ladder.scss, assets/css/_route_pill.scss, assets/src/components/routeLadder.tsx, assets/src/components/routePill.tsx, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/minimalLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/ladderPage.test.tsx, assets/tests/components/routeLadder.test.tsx
Asana ticket: https://app.asana.com/0/1205385723132845/1208333281632130
Talked with Kathleen async and decided a few things that are not captured in the handoff doc (given that the doc was medium-fi):
1. Make the route pills dynamically sized for the route ladders. (Rationale: if the 32/33 route had an alert, that's very wide. If we made all the pills that wide, it would look funny. So instead, give all pills 1.5rem padding.)
2. Minimum margin around the routePill: .5rem.
3. Alert + route number can be centered in the pill.
=> tweak: Move alert icon to route pill

test/notifications/notification_server_test.exs, test/notifications/notification_test.exs
small fix that I noticed when doing the detour deactivated notifications
=> fix:test: assert that detour is activated in test

.github/workflows/deploy-base.yml
When deploying #2831 I was having difficulties with getting the deployment to succeed due to our database issues. It was getting pretty frustrating to have to build the docker container just to attempt a redeploy. I tried a few ways of parallelizing this, but so far this seems like the best option.
I was having trouble getting a deploy to work for testing this, so this also depends on #2841 
Depends on:
- #2841
=> fix: split up build and deploy steps

assets/src/components/detours/diversionPage.tsx
I found it mildly easier to read extracting the detourPanel logic out of the rest of the JSX tree, but this isn't expressly necessary if you prefer it the old way!
=> tweak: reorganize diversion page

assets/src/components/notificationCard.tsx, assets/src/models/notificationData.ts, assets/src/realtime.ts, assets/tests/components/__snapshots__/notificationBellIcon.test.tsx.snap, assets/tests/components/__snapshots__/notificationCard.test.tsx.snap, assets/tests/components/notificationBellIcon.test.tsx, assets/tests/components/notificationCard.test.tsx, assets/tests/factories/notification.ts, lib/notifications/db/detour.ex, lib/notifications/detour.ex, lib/notifications/notification.ex, lib/notifications/notification_server.ex, lib/skate/detours/detours.ex, test/notifications/notification_server_test.exs, test/notifications/notification_test.exs, test/skate_web/controllers/detours_controller_test.exs, test/support/factories/detour_factory.ex
Asana Ticket: https://app.asana.com/0/1203014709808707/1208409921049870/f
This implements deactivated notifications through the entire stack, from the notification internals, all the way to the deactivated card.
TODO:
- There's something up with `eslint` not properly detecting that all possible branches of the `switch` are handled. Maybe I did something wrong here and I'd love that pointed out, but if I add an explicit `break` to make `eslint` happy, typescript then complains that the break is "unreachable" and "unnecessary". Still looking into this.
Depends On:
- ~#2831~
- #2836
=> feat: add detour deactivated notifications 

config/runtime.exs, lib/realtime/server.ex
When we added distributed Elixir via `DNSCluster` in #2831, we started getting flickering data in our realtime sources. This was because we used a `Phoenix.PubSub` with the same name on both instances. Once instances were talking to eachother, those `PubSub`'s started getting messages from other instances but the messages referenced non-existent information, which caused them to send `null` or empty `[]` information to clients when they received those messages.
Switching to `broadcast_local` for our `Realtime.Server.broadcast/2` returns the code to it's previous assumptions where a message is only broadcasted to subscribers on the same node, which stopped instances from stepping on eachother.
=> fix(ex/Realtime.Server): use `broadcast_local` instead of `broadcast`

assets/src/components/detours/detourPanelComponents.tsx
Asana Ticket: https://app.asana.com/0/1205385723132845/1208153509160211
Brian noted that the Bootstrap default component is ok!
=> tweak: Make the missed stops count badge round

assets/src/components/detours/detourPanels/detourFinishedPanel.tsx, assets/src/components/detours/detourPanels/drawDetourPanel.tsx, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap, assets/tests/components/detours/detoursListPage.openDetour.test.tsx, assets/tests/components/detours/diversionPage.activate.test.tsx, assets/tests/components/detours/diversionPage.test.tsx, assets/tests/components/mapPage.test.tsx, assets/tests/components/notificationCard.openDetour.test.tsx, assets/tests/testHelpers/selectors/components/detours/diversionPage.tsx
Adhoc, but here's the [figma link](https://www.figma.com/design/XGmmwVROXdOvnWtJeUFC50/Skate-%7C-Unplanned-Detours-%7C-Handoff?node-id=3666-13075&t=dJLTPrFTZyzHvNWX-4)
=> tweak: Update detour panel titles / buttons to match hi-fi language

assets/src/components/detours/detourPanelComponents.tsx
Fix to follow: https://github.com/mbta/skate/pull/2857
=> tweak: Margin needed on missed stops badge, not padding

assets/css/_shuttle_map.scss
This _happens_ to override the vehicle marker because it's imported after the vehicle marker css, just so we don't stumble into that later, I decided to remove it.
Context: https://mbta.slack.com/archives/C024N3SKX33/p1729517468174199?thread_ts=1729517026.304969&cid=C024N3SKX33
=> cleanup(css/shuttle-map): remove selected label color override on shuttle map

assets/src/models/shuttle.ts
As part of #2860 I added some helpers to map shuttles, This refactors the current "prefix" to also use these new helpers.
Shares code with:
- #2860 (two shared commits, doesn't matter which branch merges first)
=> refactor(ts/models/shuttle) implement shuttle prefix using `shuttleVariantFromRunId`

assets/src/components/detours/detourMap.tsx
The 1 has two stops called Mass Ave & Albany! One in Cambridge, one in Boston. This suppresses some rowdy console errors
=> fix: Avoid using non-unique stop names as key

test/support/factory.ex
An upgrade in the name of good factory hygiene. Makes it so you must specify the values if you expect it to be a certain value, or to use the value in your assertions.
=> feat(ex/test/factory): make user factory dynamic

assets/src/components/detours/diversionPage.tsx
Hotfix following https://github.com/mbta/skate/pull/2872
=> fix: Don't show connectionPoints on draw panel until they exist

assets/src/components/detours/activateDetourModal.tsx, assets/src/components/detours/deactivateDetourModal.tsx, assets/src/components/detours/detourMap.tsx, assets/src/components/detours/detourPanelComponents.tsx, assets/src/components/detours/detourPanels/activeDetourPanel.tsx, assets/src/components/detours/detourPanels/detourFinishedPanel.tsx, assets/src/components/detours/detourPanels/detourRouteSelectionPanel.tsx, assets/src/components/detours/detourPanels/drawDetourPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
Asana Ticket: https://app.asana.com/0/1203014709808707/1208610656881565/f
---
Superceeds: #2870
=> feat(ts/detours): add `data-fs-element` properties to detours flow

test/support/conn_case.ex, test/support/data_case.ex, test/test_helper.exs
Reviewable by commit for more info.
=> cleanup(ex/test): general cleanup related to upgrading to the latest Phoenix version and Template

config/config.exs
Context: https://mbta.slack.com/archives/C024N3SKX33/p1730132093594659
=> fix: change `training_url` redirect

assets/src/hooks/useSwings.ts, assets/tests/factories/routeTab.ts, assets/tests/hooks/useSwings.test.tsx
Asana Ticket: https://app.asana.com/0/1203014709808707/1208181989823248/f
> [!NOTE]
> Recommend reviewing by commit
=>  feat: make swings apply to current route tab

assets/src/components/detours/detourPanels/activeDetourPanel.tsx, assets/src/components/detours/detourPanels/detourFinishedPanel.tsx, assets/src/components/detours/detourPanels/pastDetourPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/stories/skate-components/detours/activeDetourPanel.stories.tsx, assets/stories/skate-components/detours/detourFinishedPanel.stories.tsx, assets/stories/skate-components/detours/pastDetourPanel.stories.tsx, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
I renamed `detourText` to distinguish `editableDirections` from `copyableDetourText`, but splitting out into a separate PR to make review easier.
Builds off of
- https://github.com/mbta/skate/pull/2878
=> tweak: Rename detourText to copyableDetourText, fix typo

lib/skate/detours/detours.ex, lib/skate/detours/snapshot_serde.ex, lib/skate_web/controllers/detours_controller.ex, test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1203014709808707/1208675099752884/f
=> init(ex/skate/snapshot_serde): create deserialize function

test/support/conn_case.ex
#2874 
> There are a few tests which assume what user information they're going to get, but https://github.com/mbta/skate/pull/2864 "revealed" that we hardcode the user for ConnCase, but with https://github.com/mbta/skate/pull/2873 we can now generate dynamic users, so this fixes the tests so that we can dynamically create users.
Depends on:
- ~https://github.com/mbta/skate/pull/2864~
- #2873 
- #2874
=> feat(ex/test/conn-case): make default user dynamic from factory 

lib/skate/detours/detours.ex, lib/skate/detours/snapshot_serde.ex, lib/skate_web/controllers/detours_controller.ex, test/skate_web/controllers/detours_controller_test.exs
=>  refactor:test(ex/skate_web/detour_controller): use `:user` factory 

test/skate_web/controllers/detours_controller_test.exs, test/skate_web/controllers/page_controller_test.exs, test/support/conn_case.ex
There are a few tests which assume what user information they're going to get, but https://github.com/mbta/skate/pull/2864 "revealed" that we hardcode the user for `ConnCase`, but with https://github.com/mbta/skate/pull/2873 we can now generate dynamic users, so this fixes the tests so that we can dynamically create users.
=> fix(ex/test): make tests against user data dynamic

lib/skate_web/endpoint.ex
Aligns our implementation with the `phx.new` template
- https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/endpoint.ex#L7-L12
- https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/endpoint.ex#L51
=> chore(ex/skate_web/endpoint): pull `Plug.Session` options into compile time constant

Dockerfile
The AWS RDS Cert bundle updated again and builds have been failing due to that.
Turns out, there is now a [`Dockerfile` `--checksum` argument to the `ADD` command](https://docs.docker.com/reference/dockerfile/#add---checksum) which both pulls something from the internet (like `curl`) but _also_ can check the hash of the content at the same time. 
This will also give us better logs when builds fail, and tell us what the new checksum is.  
(Example log from when I initially added the `ADD` command, with a dummy checksum from the docs)
```
ERROR: failed to solve: digest mismatch sha256:390fdc813e2e58ec5a0def8ce6422b83d75032899167052ab981d8e1b3b14ff2: sha256:24454f830cdb571e2c4ad15481119c43b3cafd48dd869a9b2945d1036d1dc68d
```
Previously: #2746 
Asana Ticket: …
=> fix(Dockerfile): update checksum for aws cert bundle

lib/skate/open_route_service_api.ex, lib/skate/open_route_service_api/directions_formatter/MBTA/english.ex, test/skate/open_route_service_api_test.exs, test/skate_web/controllers/detour_route_controller_test.exs, test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1208502791134829/1208288732617333/f
=> feat(ex/skate/ors): format directions as "short directions"

assets/src/components/detours/detourPanels/detourFinishedPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/stories/skate-components/detours/detourFinishedPanel.stories.tsx, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap
Asana Ticket: https://app.asana.com/0/1205385723132845/1208672004049522/f
=> feat: add Affected Route to Finished Panel

lib/skate/detours/detours.ex, lib/skate_web/controllers/detours_admin_controller.ex
`user_id` is only needed in `db_detour_to_detour` for the sake of filtering out draft detours not created by the current user. That can and should be done in the parent function, not in `categorize_detour`. Refactored to simplify. Useful for the detours channel work
=> tweak: Move user filter for drafts

assets/src/models/createDetourMachine.ts, assets/src/models/detour.ts, lib/skate/detours/db/detour.ex, lib/skate/detours/detours.ex, lib/skate/detours/snapshot_serde.ex, priv/repo/async_migrations/20241218135700_backfill_detour_activated_at.exs, priv/repo/migrations/20241211183227_add_detour_activated_at_field.exs, test/skate_web/controllers/detours_controller_test.exs, test/support/factories/detour_factory.ex
To be able to show the activated at time in various places within Skate, as well as for sorting, we need to start recording the time of activation for a detour.
This PR
- adds the database column
- backfills the database column so that currently active detours are marked as having been active since the last modification time
- starts recording the activation time in the state machine when a detour is activated
---
Asana Ticket: https://app.asana.com/0/0/1208989312907929/f
=> feat(ex/skate/detours): add `activated_at` column

Dockerfile
Here we are again! Updating the checksum to unblock deploys
Prior work: https://github.com/mbta/skate/pull/2901
=> fix: update checksum for aws cert bundle

assets/src/components/detoursTable.tsx, assets/src/hooks/useCurrentTime.ts, assets/src/hooks/useDetours.ts, assets/src/models/detoursList.ts, assets/src/util/dateTime.ts, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap, assets/tests/components/detours/detourListPage.test.tsx, assets/tests/factories/detourListFactory.ts, assets/tests/hooks/useDetours.test.ts, lib/skate/detours/detour.ex, lib/skate/detours/detours.ex, lib/skate_web/channels/detours_channel.ex, test/skate_web/channels/detours_channel_test.exs, test/skate_web/controllers/detours_controller_test.exs
This uses the work in #2910 to fix the Activated At column to use the _real_ activated at time, in the Activated Detours table.
Asana Ticket: https://app.asana.com/0/0/1208989312907930/f
Depends on:
- #2910
=>  feat: add `activated-at` column to frontend detours list 

assets/src/components/detoursTable.tsx, assets/src/models/detoursList.ts, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap, assets/tests/components/detours/detourListPage.test.tsx, assets/tests/factories/detourListFactory.ts, lib/skate/detours/detour.ex, lib/skate/detours/detours.ex, test/support/factories/detour_factory.ex
This adds the estimated duration info from the detour to the Activated Detour structure and returns that to the frontend to display in the activated detour table.
Asana Ticket: https://app.asana.com/0/0/1208989312907931/f
Depends on:
- #2911 
- #2910
=> feat: add `estimated-duration` column to frontend detours list 

assets/css/_diversion_page.scss, assets/src/components/detours/detourPanels/activeDetourPanel.tsx, assets/src/components/detours/diversionPage.tsx, assets/stories/skate-components/detours/activeDetourPanel.stories.tsx, assets/tests/components/detours/diversionPage.activate.test.tsx
Asana Ticket: https://app.asana.com/0/0/1209181972308522
=> feat(ts/ActiveDetourPanel): add detour properties to activated panel

assets/src/util/dateTime.ts
turns out `valueOf()` doesn't do timezone conversions, so I've switched to `getTime()`
related to #2923
=> fix(ts/dateTime): compare dates in UTC

.formatter.exs, priv/repo/async_migrations/.formatter.exs, priv/repo/async_migrations/20230830202227_first_async_migration.exs, priv/repo/async_migrations/20241218135700_backfill_detour_activated_at.exs, priv/repo/migrations/.formatter.exs
This makes `.formatter.exs` match `phx.new` template, and moves formatter config for specific directories into local files in those directories, to match "new" phoenix conventions.make `.formatter.exs` match `phx.new` template
This also configures the async_migrations folder to be formatted, and formats those files.
=> feat(ex/formatter): configure migrations formatter in directory

lib/skate/detours/snapshot_serde.ex, test/skate_web/controllers/detours_controller_test.exs
I don't think this is a full solution, but I think this addresses the bug well enough that we can ship other things by tomorrow.
=> fix(ex/snapshot_serde): fix "activatedAt" not present in old snapshots at serialize time

config/prod.exs, lib/skate_web/endpoint.ex
This configuration has always confused me a little, mainly that we had to "implement" it ourselves.
So I tracked this down and confirmed that this can be configured via Application config
- https://hexdocs.pm/phoenix/1.7.11/Phoenix.Endpoint.html#socket/3-common-configuration
- > `:check_origin` - if the transport should check the origin of requests when the origin header is present. [...]. **_Defaults to `:check_origin` setting at endpoint configuration_**.
I do not know if this option was available at the time of https://github.com/mbta/skate/pull/36/ but now we can configure this via `SkateWeb.Endpoint`.
I loaded this up on dev-green and saw no changes or issues when loading the application.
This also seems to match other "modern" TID applications.
---
Depends on:
- #2894
=> chore(ex): configure check_origin for all transports on the `SkateWeb.Endpoint`

assets/src/components/detours/detourPanels/activeDetourPanel.tsx
The arguments were reversed 🙃 
related to #2923
=> fix(ts/activeDetourPanel): fix time ago label

assets/src/models/createDetourMachine.ts
Currently, the date is being created when the machine starts, _not_ when the action is fired 🤣 😭 whoops.
=> fix(ts/createDetourMachine): create `activatedAt` date when invoked

assets/src/components/routeLadder.tsx, assets/tests/components/__snapshots__/ladderPage.test.tsx.snap, assets/tests/components/__snapshots__/minimalLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadder.test.tsx.snap, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap
=> fix(ts/routeLadder): show dropdown on mobile breakpoint

assets/src/components/routeLadders.tsx, assets/tests/components/__snapshots__/routeLadders.test.tsx.snap, assets/tests/components/routeLadders.test.tsx
SL detours were not correctly appearing in the route ladders after we switched to useActiveDetours instead of useActiveDetoursByRoute because of trying to match route names and ids
=> [for launch] fix: Detour in ladder needs to match on route ids, not name

assets/src/components/routeLadders.tsx, assets/src/hooks/useDetours.ts, assets/src/userInTestGroup.ts
Production issue is possibly due to DB overload from every route ladder making a 6s+ query.
This makes it so it doesn't fire by default.
=> disable active detours on ladder

assets/src/components/detoursTable.tsx, assets/src/models/detoursList.ts, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap, assets/tests/components/detours/detourListPage.test.tsx, assets/tests/factories/detourListFactory.ts
Frontend needs to reflect that backend provides empty arrays for empty detour tables
=> [low priority] fix: Empty detour tables should be visible

lib/skate/detours/db/detour.ex, lib/skate/detours/detours.ex, priv/repo/migrations/20250131195636_add_detour_status_field.exs, priv/repo/migrations/20250204034128_create_detour_status_index.exs, test/skate/detours/db_test.exs, test/skate_web/controllers/detours_controller_test.exs, test/support/factories/detour_factory.ex
This adds a new database column and starts populating it from the changeset function.
Once we deploy this and have all instances become aware of the field. We'll then
deploy a data migration which adds this to previously made detours, so that there
are no running instances without this change to the changeset function.
---
Asana Ticket: https://app.asana.com/0/1203014709808707/1209213931559673
=> feat(ex/detours): add detour `:status` field, and populate from changeset

lib/skate/detours/trip_modification_publisher.ex, lib/skate_web/controllers/detours_controller.ex
Question: Is it valuable to log on trip mod publication success / failure? It seems that the skate-dev traffic to MQ is low or non-existent from infra's review, so I'd be curious to see logs to confirm messages are getting published properly.
=> tweak: Log on trip mod publication

assets/src/components/detours/diversionPage.tsx, assets/src/userInTestGroup.ts, assets/tests/components/detours/diversionPage.editDuration.test.tsx
`change-detour-duration` feature flag is in override mode on prod, so we can remove the conditionals and delete the group
=> tweak: remove change-detour-duration feature flag

.github/workflows/deploy-base.yml
getSentry action updated to reference a new action, which isn't allowed in our github config. [See here](https://github.com/getsentry/action-release/pull/255#issuecomment-2647646773).
=> tweak: pin earlier version step of getSentry action

lib/notifications/db/detour.ex, lib/notifications/db/notification.ex, lib/skate/detours/db/detour.ex, lib/skate/detours/detour.ex, lib/skate/detours/detours.ex, lib/skate_web/controllers/detours_admin_controller.ex, lib/skate_web/controllers/detours_admin_html/index.html.heex, test/skate/detours/db_test.exs, test/skate/telemetry_test.exs, test/skate_web/controllers/detours_controller_test.exs
Asana Ticket: https://app.asana.com/0/1203014709808707/1209252334767151/f
Depends on:
- #2954
=> fix: speed up Detour queries by returning subsets of JSON snapshot

assets/src/components/detours/diversionPage.tsx, assets/src/userInTestGroup.ts, assets/tests/components/detours/diversionPage.test.tsx
`backwards-detour-prevention` feature flag is in override mode on prod, so we can remove the conditionals and delete the group
=> tweak: remove backwards-detour-prevention feature flag

assets/src/helpers/bsIcons.tsx
Turns out, the data for the `ArrowDownLeftSquare` was actually the `ArrowUpRightSquare` data.
---
Asana Ticket: https://app.asana.com/0/1148853526253437/1209227790219716
=> fix: correct `ArrowDownLeftSquare` icon

README.md
small change to use `npm  --prefix assets` instead of `cd assets &`
The commands still work for me locally as expected.
=> docs: update README to use npm --prefix in place of cd

assets/src/components/detourListPage.tsx, assets/src/components/routeLadders.tsx, assets/src/hooks/useDetour.ts, assets/src/hooks/useDetours.ts, assets/tests/components/detours/__snapshots__/detourListPage.test.tsx.snap, assets/tests/components/detours/detourListPage.test.tsx, assets/tests/components/detours/detoursListPage.addDetour.test.tsx, assets/tests/components/detours/detoursListPage.openDetour.test.tsx, assets/tests/components/detours/diversionPage.delete.test.tsx, assets/tests/components/detours/diversionPage.editDuration.test.tsx, assets/tests/components/detours/diversionPage.saveDetour.test.tsx
Asana ticket: https://app.asana.com/0/1205385723132845/1208390246838825
In terms of tests, I'm not sure what else to cover? Ideally, I'd like to verify some integration flow -- like activating a detour triggers the channel to be affected -- but I struggled with that.
Known issue: preventing a drafted detour from appearing in the channel and passing through the `handleDrafted` function before it has all it's returned values (like nearestIntersection). To be discussed in subsequent PR.
Also: have confirmed with Brian that the spinner is great!
=> feat: Populate detours list with channels

assets/src/models/createDetourMachine.ts, assets/tests/components/detours/__snapshots__/detoursListPage.openDetour.test.tsx.snap, assets/tests/components/detours/diversionPage.saveDetour.test.tsx, assets/tests/components/detours/diversionPage.test.tsx
Asana Ticket: https://app.asana.com/0/1203014709808707/1209629085185045
=> feat(ts/createDetourMachine): default `fetchNearestIntersection` result to an Em Dash on error

lib/schedule/fetcher.ex
I noticed that we log the GTFS feed information and the last modified timestamp for the zip file. We don't log the hastus version information but there is an updated version of both returned from [fetch_remote_files](https://github.com/mbta/skate/blob/b8ae48a24306135c63d44962a87935152369df5c/lib/schedule/fetcher.ex#L231).
We could use the returned timestamps instead.
=> tweak: add gtfs and hastus versions to Schedule.Fetcher logging

.github/workflows/ci.yml
> it looks like mbta/actions/dialyzer is being affected by the scheduled brownout of the deprecated cache service today, meaning it will permanently stop working one week from today (April 15th) when the service is decommissioned for good. although it seems like only attempts to restore the cache are being affected, so re-running the relevant job once it fails does work, since the action does not attempt to restore the cache on re-runs.
> -- https://mbta.slack.com/archives/GP5QJM98A/p1744134926110489
> https://github.com/mbta/actions/pull/64
=> fix: update dialyzer action to v2

.github/pull_request_template.md
This adds the trigger phrase in the expected format for the Github -> Asana CI workflow to avoid issues with a missing or invalid trigger phrase. We could discuss adding more to this template in the future.
=> docs: add Pull Request Template

lib/skate/settings/test_group.ex
Asana Ticket: No ticket
I saw these errors in Splunk while looking at something else. I'm assuming it's code leftover from debugging during development, I don't see a reason to log it in production as an error.
=> fix: remove Logger.error call from a non-error state

lib/notifications/bridge.ex
In Splunk, the logfmt parser they have doesn't really handle this comma very well, and logfmt formatted logs should be key=value pairs with spaces between.
---
No Ticket.
=> fix(ex/notifications/bridge): remove comma in log

lib/realtime/timepoint_status.ex, test/realtime/timepoint_status_test.exs
No ticket. 
Related to an issue we saw yesterday:
https://mbta.slack.com/archives/C047ZT8ACP5/p1747546808098849
```
key :stop_times not found in: %Schedule.AsDirected{
kind: :rad,
}
```
=> fix: handle RAD/WAD activites in Timepoint Status

config/config.exs, lib/notifications/db/detour_expiration.ex, lib/notifications/db/notification.ex, lib/notifications/notification.ex, lib/skate/detours/db/detour.ex, lib/skate/postgrex_types.ex, priv/repo/migrations/20250522165450_create_detour_expiration_notifications.exs, priv/repo/migrations/20250522204236_fkey_notifications_detour_expiration_notification.exs, test/notifications/db/notification_test.exs, test/notifications/notification_test.exs
Asana Ticket: [Create New Notification Type on Backend](https://app.asana.com/1/15492006741476/task/1210418717846181)
This does just about everything to setup the database side of notifications, except for returning the new notifications from `unexpired_notifications_for_user`. 
If a `DetourExpiration` notification is returned to the frontend before the Superstruct definition is completed on the frontend, then all notifications will fail to work, so that has been left out of this to unblock this from being merged or needing any sort of rollback.
This also configures `PostgrexTypes` per the documentation, so that we can use `%Duration{}`(as per the ideas in the ADR[^adr-mistake]).
[^adr-mistake]: turns out, I also had a bit of a "typo" in the original ADR, which I've opened a [PR to …
=> feat: create detour expiration notification type

documentation/adr/0005-detour-reminder-toasts-architecture.md
I had intended when writing the ADR that `expires_at` would be a `Duration`, but it seems I missed that when originally writing this ADR.
The ticket for [Create New Notification Type on Backend](https://app.asana.com/1/15492006741476/project/1203014709808707/task/1209653841420226?focus=true) specifies `Duration`, and that's how I have currently implemented it, but if we need to discuss the path forward I understand, since I missed this.
Related-To: #3009
=> fix(amend/adr/5): use `Duration` where `DateTime` was accidentally used

assets/stories/skate-components/notifications/detourNotificationCard.stories.tsx, assets/tests/components/notificationCard.test.tsx, assets/tests/factories/notification.ts
Asana Ticket: [Mark Notification as Read when Clicked](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1210353029759140?focus=true)
I looked briefly at changing the role of these readable Cards to something other than button, like dialog (while keeping the buttons as buttons). That change affected a lot of other code paths and tests though, so I didn't pursue it further.
=> test: clicking a notification card marks it as read

lib/notifications/notification.ex, lib/notifications/notification_server.ex, test/notifications/notification_server_test.exs
Asana Ticket: [Add Detour Expiration Notification Creation Interface](https://app.asana.com/1/15492006741476/project/1203014709808707/task/1210353029759134?focus=true)
Depends-on:
- #3011 
---
This implements broadcasting Detour Expiration Notifications to the frontend.
This is a few things wrapped up together, but the work should make sense when viewed by commit
1. Implements a interface to get notifications[^ac-1]
1. Implements a interface to get database notifications as `Notifications.Notification{}` structs (expected to be removed with [Refactor: Move "Notifications Database Object => Notifications Frontend Object" conversion into own module](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1210323017373166?focus=true)) [^ac-1]
1. Broadcasts notifications when a …
=> feat: broadcast detour expiration notification to users

lib/notifications/db/detour_expiration.ex, lib/notifications/db/notification.ex, lib/notifications/db/notification_user.ex, test/notifications/notification_test.exs
Asana Ticket: [Add Detour Expiration Notification Creation Interface](https://app.asana.com/1/15492006741476/task/1210594450484913)
Fixes the behavior added in #3009 to create notifications for all users and adds tests for this behavior.
---
- https://app.asana.com/0/0/1210594450484913
=> fix:test(ex/notifications): assert all users get a detour expiration notification

config/config.exs, lib/notifications/bridge.ex, lib/notifications/db/bridge_movement.ex, lib/notifications/notification.ex, lib/notifications/notification_server.ex, lib/skate/bridge_status.ex, lib/skate/settings/user.ex, test/notifications/bridge_test.exs, test/notifications/notification_server_test.exs, test/notifications/notification_test.exs, test/skate/bridge_status_test.exs, test/support/factory.ex, test/support/helpers.ex
Asana Ticket: [Refactor: Move Bridge Movement and Block Waiver logic into own modules](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1210323017373160?focus=true)
This relies on commitsfunctionality also in PR https://github.com/mbta/skate/pull/3016
---
~Putting this up for review of the approach. Mainly I'm not sure where the interface should live.~
~This current implementation has two places that could create bridge notifications, `Notifications.Notification.new_bridge_movement_notification/2` and `Skate.BridgeStatus.maybe_record_bridge_status/2`~
~But another implementation could look like `new_bridge_movement_notification` being the only interface and having `new_bridge_movement_notification` call a module with the functionality in `maybe_record_bridge_status`.~ …
=> refactor: move bridge movement de-duplicate logic into own module

lib/skate/detours/detours.ex, lib/skate/detours/notification_scheduler.ex, test/skate/detours/notification_scheduler_test.exs
Asana Ticket: [Fix detour duration changed handling](https://app.asana.com/1/15492006741476/project/1205385723132845/task/1210768108127121?focus=true)
=> fix(detours): fix handling of detour duration changed

Dockerfile
https://github.com/mbta/skate/actions/runs/16524261697/job/46733429405
```
$ curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem | shasum -a 256
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  161k  100  161k    0     0   674k      0 --:--:-- --:--:-- --:--:--  675k
e5bb2084ccf45087bda1c9bffdea0eb15ee67f0b91646106e466714f9de3c7e3  -
```
=> fix: update aws cert file checksum since it updated again
